### ISSUE TITLE
Repo Setup Tasks

### ISSUE THREAD

**Issue by shellscape** [rollup/plugins#1]
Tasks that have been identified as required to make this repository functional.

- [x] Copy `.github` from rollup/rollup and customize
- [x] Copy CI from rollup/rollup
- [x] Configure CI to only build tests from changed paths (this will be tricky)
- [x] ~~Install [rush](https://rushjs.io) and configure. Rush is the prevailing favorite for monorepo management. We'd like to give it a shot. Use of pnpm under the covers is compelling.~~
- [x] Install and setup `pnpm` for monorepo management
- [x] Copy the TypeScript configuration from rollup/rollup
- [x] Create `@rollup/eslint-config` using [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config) and the tslint config from rollup/rollup
- [x] Pull in a good `.editorconfig`
- [x] Install `ava`, `nyc`, and create a demo plugin to demo tests. _(I would like to try out ava here. It's very solid, very fast, has wonderful snapshot support, and works well for libraryish projects)_
- [ ] Create configuration and CI script(s) to identify core-critical plugins that should align with and adhere to the Node versions in the `latest` version of Rollup. These should prevent publish if out-of-line, and will prevent a plugin from jumping core's supported node version(s).

_Note to maintainers: If you'd like to see a task listed here, please edit the OP and add it, and provide a followup comment with what was added, for visibility._

**Comment by lukastaegert** [comment]
Sounds good!

> Install ava

What is the upside of using ava vs. using Jest except trying it out?

**Comment by TrySound** [comment]
ava supports esm out of the box. Jest does not work with esm (loader) yet.

**Comment by lukastaegert** [comment]
Good point. Though this will probably only become relevant when the minimum supported Node version is 12, unless we want to transpile all our tests. Which could actually be a viable option, Rollup tends to be quite fast for small code bases...

**Comment by TrySound** [comment]
I mean ava uses [esm loader](https://github.com/standard-things/esm) out of the box. So you do not need setup them.

**Comment by lukastaegert** [comment]
Ah, I misunderstood. Now that is definitely useful!

**Comment by lukastaegert** [comment]
On the other hand a point for Jest would be that you can write your tests in TypeScript via ts-jest. Would this be possible with Ava as well?

**Comment by TrySound** [comment]
https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md

**Comment by shellscape** [comment]
I've been using ava on my projects for over a year now, and I have nothing but good things to say. I also like the snapshots _far better_ than what Jest produces. The result output after a run are cleaner imho, and more informative. Overall I find ava easier and quicker to work with. But that doesn't mean we _have_ to use it. I'd like to try it out and see how everyone likes it (or not). Sindre has done a really amazing job on this, and Ava doesn't get as much love as it should. If a big company picked it up and backed it, it would explode.

**Comment by wesleygrimes** [comment]
I'm good with giving it a shot, it wouldn't be that hard to migrate to Jest if we needed to.

**Comment by shellscape** [comment]
OK we're wrapped on this issue. Working in the `setup` branch at the moment. Going to break out the last task into a separate issue.
