### ISSUE TITLE
@rollup/plugin-typescript TS5023: Unknown compiler option 'extends'.

### ISSUE THREAD

**Issue by loynoir** [rollup/plugins#1001]
- Rollup Plugin Name:  @rollup/plugin-typescript
- Rollup Plugin Version: ^8.2.5
- Rollup Version: 2.56.3
- Operating System (or Browser):
- Node Version: 14.17.4
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
No error.

### Actual Behavior
```txt
(!) Plugin typescript: @rollup/plugin-typescript TS5023: Unknown compiler option 'extends'.
[!] (plugin typescript) Error: @rollup/plugin-typescript: Couldn't process compiler options
Error: @rollup/plugin-typescript: Couldn't process compiler options
```

### Additional Information
Minimal config
```
            rollupTypescript({
              "extends": "@tsconfig/node14/tsconfig.json"
            }),
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by loynoir** [comment]
@shellscape

https://github.com/loynoir/reproduce-rollup-1001

**Comment by loynoir** [comment]
@shellscape 
Sorry for missing a reproduce. 
Just think it's one line in config, and not related to `src/**/*`, thus no need a reproduce repo.
