### ISSUE TITLE
[plugin-commonjs] incorrect default value for `ignoreTryCatch` option

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#1004]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 20

### Expected Behavior

[The docs for the `ignoreTryCatch` option](https://github.com/rollup/plugins/tree/master/packages/commonjs#ignoretrycatch) say:
>In most cases, where require calls are inside a try-catch clause, they should be left unconverted as it requires an optional dependency that may or may not be installed beside the rolled up package.

Thus, I would would expect the default value to be `true` since it is the value which exhibits this behavior

### Actual Behavior

The default is `false`. The imported code gets hoisted out of the `try/catch` and fails at runtime as a result

### Additional Information

This is the root cause of https://github.com/node-fetch/fetch-blob/issues/117

**Comment by jimmywarting** [comment]
maybe this can be closed now when #1005 is merged?
