### ISSUE TITLE
Rollup bundle issue: Cannot read properties of undefined (reading 'withStyles')

### ISSUE THREAD

**Issue by mathura333** [rollup/plugins#1006]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: @rollup/plugin-commonjs - ^20.0.0
- Rollup Version: ^2.57.0
- Operating System (or Browser): All browsers
- Node Version: 14.17.5
- Link to reproduction _(⚠️ read below)_: Use of pacakges that use material ui in it like react-material-ui-carousel and doing the bundling is causing this issue

### Expected Behavior
For materail-ui/core/styles default import should not happen

### Actual Behavior
In the bundled file import is happening like this. 
`import require$$4, { makeStyles, createStyles, withStyles, useTheme, fade as fade$1 } from '@material-ui/core/styles';`
There is no default export in '@material-ui/core/styles' even then it is doing default import

### Additional Information

**rollup.config.js**
```
import typescript from 'rollup-plugin-typescript2';
import commonjs from '@rollup/plugin-commonjs';
import external from 'rollup-plugin-peer-deps-external';
import resolve from '@rollup/plugin-node-resolve';
import json from '@rollup/plugin-json';
import pkg from './package.json';

/**
 * @type {import('rollup').RollupOptions}
 */
const config = {
  input: 'src/index.ts',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      exports: 'named',
      sourcemap: true,
    },
    {
      file: pkg.module,
      format: 'es',
      exports: 'named',
      sourcemap: true,
    },
  ],
  plugins: [
    external(),
    resolve(),
    commonjs({
      include: ['node_modules/**'],
    }),
    typescript({
      rollupCommonJSResolveHack: true,
      exclude: ['**/__tests__/**'],
      clean: true,
    }),
    json(),
  ],
  external: ['@material-ui/core/styles'],
};

export default config;

```
**Versions of plugins**

- "@rollup/plugin-commonjs": "^20.0.0",
- "@rollup/plugin-json": "^4.1.0",
- "@rollup/plugin-node-resolve": "^13.0.5",
- "rollup": "^2.57.0","
- "rollup-plugin-alias": "^2.2.0",
- "rollup-plugin-peer-deps-external": "^2.2.0",
- "rollup-plugin-typescript2": "^0.30.0",

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
