### ISSUE TITLE
[@rollup/plugin-alias] -  export types   report  "Error: 'Ixxxx' is not exported"

### ISSUE THREAD

**Issue by CharlieLau** [rollup/plugins#1007]
Rollup Plugin Name: @rollup/plugin-alias
Rollup Plugin Version: 3.1.5
Rollup Version:2.56.3

**Expected Behavior**

When use alias, types should correctly export types whatever is imported.

**Actual Behavior**

rollup.config.js
```javascript
...
alias({
                'entries': {
                    '@': '.'
                }
}),
...
```
tsconfig.ts
```javascript
...
"paths":{
    
    "@/*":["src/*"]
}
...

```

src/login.ts
```javascript
export const hello = 12333;

export interface Ilogin {
    name: string;
}

```
src/index.ts
```javascript
export { hello, Ilogin } from '@/login/index';

```

**But, when compiler , report  a error** :

[!] Error: 'Ilogin' is not exported by  packages/**/src/login/index.ts, imported by packages/**/src/index.ts

**When  not use alias**
src/index.ts
```javascript
export { hello, Ilogin } from './login/index';
```
was  working.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
