### ISSUE TITLE
[plugin-commonjs] 'default' is not exported error while using monorepo tools, yarn,pnpm...

### ISSUE THREAD

**Issue by Kilims** [rollup/plugins#1008]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version:^17.0.0
- Rollup Version:^2.23.1
- Operating System (or Browser):MacOS Catalina 10.15.7 Chrome v93.0.4577.82
- Node Version:v14.17.6
- Link to reproduction _(⚠️ read below)_: 
[ui lib](https://github.com/Kilims/kilims-react-lib.git);
[monorepo workspace, pnpm example here, it can reproduce by using yarn workspace as well](https://github.com/Kilims/kilims-pnpm-workspace.git)

### Actual Behavior
```
./components/index.ts → lib/index.main.js, lib/index.module.js...
[!] Error: 'default' is not exported by ../../node_modules/classnames/index.js, imported by ../../node_modules/antd/es/empty/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
../../node_modules/antd/es/empty/index.js (18:7)
16: 
17: import * as React from 'react';
18: import classNames from 'classnames';
           ^
19: import { ConfigContext } from '../config-provider';
20: import LocaleReceiver from '../locale-provider/LocaleReceiver';
Error: 'default' is not exported by ../../node_modules/classnames/index.js, imported by ../../node_modules/antd/es/empty/index.js
    at error (/Users/kilims/Documents/playground/personal/lerna_projects/node_modules/rollup/dist/shared/rollup.js:158:30)
    at Module.error 

error Command failed with exit code 1.
```

### Additional Information

- the ui-lib repo could work and build the dist perfectly without monorepo structure. (could just clone and try)
- but once integrated into monorepo stucture, ex, yarn workspace (just simply tried), pnpm workspace, it just unfortunately pop up the 'default' is not exported error

looks like commonjs standard import issue, but no idea how to locate the root cause, seeking help eagerly !!

tons of thanks

**Comment by Kilims** [comment]
[](https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module)already tried this page,namedExports option has been removed and could not work

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template on reproductions:

>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/

Those are the options. If you're going to provide a repo, it _must_ be minimal. It's not reasonable to ask the maintainers here to understand your monorepo to triage your bug. Please provide a valid repo or REPL for this bug report.

**Comment by Kilims** [comment]
This is the repo to reproduce: https://github.com/Kilims/kilims-pnpm-workspace

**Comment by shellscape** [comment]
That's not a minimal reproduction. See the links provided for more info. We'll reopen when that's provided.
