### ISSUE TITLE
Remove the `imports must end with a file extension` limitation

### ISSUE THREAD

**Issue by UltraCakeBakery** [rollup/plugins#1009]
- Rollup Plugin Name: plugin-dynamic-import-vars
- Rollup Plugin Version: latest

### Expected Behavior / Situation
[This ](https://github.com/sveltejs/kit/issues/2499) issue explains it briefly. 

Basically: I have an array of paths pointing to different kinds of paths (.png, .svg, and more). I want to import all the files in the array dynamically, like this for example:
```javascript 
const client = 'some-local-company'
const filePath = 'foo/bar/image.png'
const file = await import(`/assets/${client}/${filePath}`)
```

This does not work right now.

### Actual Behavior / Situation
The plugin has a limitation that requires the import string must end with a file extension [(docs)](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#imports-must-end-with-a-file-extension) 

### Modification Proposal
1. Include all potential files and simply don't require a file extension
2. Allow a wildcard `*` as the extension, indicating everything should be included.
```javascript 
const filePath = 'foo/bar/image.png'
const file = await import(`/assets/${filePath}.*`)
```
3. Allow a short regex like string as the extension, indicating what file extensions to include.
```javascript 
const filePath = 'foo/bar/image.png'
const file = await import(`/assets/${filePath}.(jpg|JPG|gif|GIF|doc|DOC|pdf|PDF)`)
```

**Comment by m430** [comment]
why close this issue, I have same problem.

**Comment by shellscape** [comment]
@m430 https://github.com/rollup/plugins/issues/1009#issuecomment-984240272 read the bot's reply please.

**Comment by RafidMuhymin** [comment]
I agree with the author. There should be a way to do this. Because it's necessary for many cases. Otherwise, we have to duplicate the same code again and again.

**Comment by UltraCakeBakery** [comment]
> @m430 [#1009 (comment)](https://github.com/rollup/plugins/issues/1009#issuecomment-984240272) read the bot's reply please.

In the reply it clearly says:
> Further discussion is always welcome even with the issue closed.

Learn how to properly manage a opensource project please.
