### ISSUE TITLE
@rollup/plugin-eslint checks files after compiled them by @rollup/plugin-typescript, i.e. it checks not sources

### ISSUE THREAD

**Issue by rosinfotech** [rollup/plugins#1010]
- Rollup Plugin Name: @rollup/plugin-eslint 
- Rollup Plugin Version: 8.0.1
- Rollup Version: 2.57.0
- Operating System (or Browser): MacOS, 11.4
- Node Version:  v16.10.0
- Link to reproduction _(⚠️ read below)_: https://github.com/rosinfotech/issue_300921_rollup_plugin_eslint

### Expected Behavior

1) Plugin checks files before compiled them by @rollup/plugin-typescript;
2) The plugin checks all files of the project and then stop the Rollup's packing;

### Actual Behavior

1) When we use the "fix" option, the plugin checks files after compiled them by @rollup/plugin-typescript, i.e. it checks not sources!
2) Plugin stops checking after checked the first file with founded error or warning – it is don't check all project's files.

**Comment by Marcus-Rise** [comment]
issue is still actual, it's checks compiled files and throws on first error

**Comment by Brainshaker95** [comment]
I am encountering the same issue

**Comment by luy19** [comment]
I ran into the same problem and tried [this method](https://github.com/rollup/plugins/issues/1231#issuecomment-1202082659) but it didn't help.
