### ISSUE TITLE
[@rollup/plugin-commonjs] MISSING_EXPORT when cjs re-export an other file

### ISSUE THREAD

**Issue by dmail** [rollup/plugins#1011]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 20.0.0
- Rollup Version: 2.57.0
- Operating System (or Browser): Mac
- Node Version: 14.17
- Link to reproduction _(⚠️ read below)_: https://github.com/dmail/rollup-issue-named-export-cjs

Some of my dependencies are using commonjs re-exporting exports from an other file

_main.cjs:_
```js
module.exports = require("./helper.cjs");
```

_helper.cjs:_
```js
exports.answer = 42
```

When using `@rollup/plugin-commonjs` to convert these files to esm, the named exports are lost. 
It practice `answer` is `undefined` in the following code where `./dist/main.cjs` is generated by rollup.

```js
import { answer } from './dist/main.mjs'
```

### Expected Behavior

`@rollup/plugin-commonjs` generate code re-exporting the named exports.

```js
export const answer = 42;
```

### Actual Behavior

`@rollup/plugin-commonjs` is writing all named exports on a default export

```js
var helper = {};

helper.answer = 42;

var main = helper;

export { main as default };
```

### Additional Information

This issue replicates a pattern used by packages like react or react-is.

**Comment by dmail** [comment]
I assumed `@rollup/plugin-commonjs` was capable of handling that but it seems to be in the scope of other tools like [cjs-module-lexer](https://www.npmjs.com/package/cjs-module-lexer)

I just discovered [esinstall](https://github.com/snowpackjs/snowpack/tree/main/esinstall#esinstall) which is marvelous. They are doing a mix of static analysis + runtime analysis. Link to the code where they combine `@rollup/plugin-commonjs` with `cjs-module-lexer`:

https://github.com/snowpackjs/snowpack/blob/d004e827e0781144cc84c5d935c64996e4723116/esinstall/src/index.ts#L337-L344

Unfortunately I cannot reuse `esinstall` as it is because my use case is a bit different but I can borrow the concepts.

**Comment by dmnsgn** [comment]
@dmail it might be useful to you: I have just published [rollup-plugin-commonjs-named-exports](https://github.com/dmnsgn/rollup-plugin-commonjs-named-exports) which takes the [cjs-module-lexer](https://github.com/nodejs/cjs-module-lexer) approach at exporting named re-exports.

**Comment by lukastaegert** [comment]
Nice one. I keep wondering if we should not add cjs-module-lexer to the commonjs plugin itself but cannot seem to find time for it as it would not be 100% trivial.

**Comment by dmail** [comment]
On my side I took the time to create something inspired from esinstall that is using cjs-module-lexer + many other rollup plugins to convert commonjs to esm. It works like a charm until now but it's not open source as it contains some specificities.
