### ISSUE TITLE
transformMixedEsModules shouldn't replace typeof exports

### ISSUE THREAD

**Issue by gluck** [rollup/plugins#1014]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 21.0.0

### Expected Behavior / Situation

If an ESM file is transformed with `transformMixedEsModules=true` (for require support), it shouldn't replace `typeof exports` by `'object'` and leave it as-is (or replace by `'undefined'` ?)

### Actual Behavior / Situation

Right now the bundle fails with `exports is not defined` because of code in ESM such as lodash-es:
https://github.com/lodash/lodash/blob/es/isBuffer.js#L5

```js
var freeExports = typeof exports == 'object' && exports && !exports.nodeType && exports;
// becomes:
var freeExports = exports && !exports.nodeType && exports;
```

(lodash-es itself doesn't require transformMixedEsModules, but other parts of the bundle do)

### Modification Proposal

If `esModule=true` do not transform typeof module/exports/module.exports into `'object'`, as they'll likely open invalid code paths in an ESM.

(I can PR with tests if agreed)

**Comment by fi3ework** [comment]
same issue

**Comment by theprimone** [comment]
Any progress? lodash-es cause the same error, when I use Vite with `transformMixedEsModules=true`.

**Comment by lukastaegert** [comment]
I added a fix to #1038

**Comment by theprimone** [comment]
> I added a fix to #1038

Hello, when will it be released?

**Comment by shellscape** [comment]
@theprimone we don't have a release schedule. please exercise patience.

**Comment by theprimone** [comment]
> @theprimone we don't have a release schedule. please exercise patience.

Well，how can I make a workaround？It casuses error after bundled, though I try to configure `exclude`.

**Comment by theprimone** [comment]
It looks like version `@rollup/plugin-commonjs@22.0.0-4` fixes the problem for now, detail: https://unpkg.com/browse/@rollup/plugin-commonjs@22.0.0-4/dist/index.es.js

**Comment by webhao** [comment]
@yunsii  I didn't solve it.update`@rollup/plugin-commonjs@22.0.0-9`,use `commonjsOptions: { transformMixedEsModules: true, strictRequires: true, }`

**Comment by yunsii** [comment]
> @yunsii I didn't solve it.update`@rollup/plugin-commonjs@22.0.0-9`,use `commonjsOptions: { transformMixedEsModules: true, strictRequires: true, }`

The same error: `exports is not defined`? I replace `require` with `import ... from ...` and remove commonjs plugin finnally 😂

**Comment by webhao** [comment]
咱直接说中文吧，就是https://github.com/rollup/plugins/issues/1014提出的lodash-es和vite的transformMixedEsModules使用问题，能方便给个wx吗
| |
孙昊男
|
|
***@***.***
|
签名由网易邮箱大师定制


On 02/10/2022 ***@***.***> wrote：

@yunsii I didn't solve ***@***.******@***.***,use commonjsOptions: { transformMixedEsModules: true, strictRequires: true, }

The same error: exports is not defined? I replace require with import ... from ... and remove commonjs plugin finnally 😂

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mccxiv** [comment]
Workaround while waiting for the fix to release:

Add `window.exports = undefined` before anything else executes.   
For me, I had to do it in a separate script tag above the main file:
```
<script>
  // Workaround for https://github.com/rollup/plugins/issues/1014
  window.exports = undefined
</script>
```

**Comment by superchangme** [comment]
help me vite 2.6.8 still has this problem Uncaught ReferenceError: exports is not defined
