### ISSUE TITLE
The Result of `unwrapExports` is Never Assigned

### ISSUE THREAD

**Issue by ryanfitzer** [rollup/plugins#102]
_This issue was transferred from rollup/rollup-plugin-commonjs, which had no issue templates_

I'm trying to bundle [`styled-jsx`](https://github.com/zeit/styled-jsx) with my React comment and getting errors resulting from the `unwrapExports` function being called but never assigned. Here is the abbreviated output:

```js
/* ... */

function createCommonjsModule(fn, module) {
    return module = {
        exports: {}
    }, fn(module, module.exports), module.exports;
}

/* ... */

var style = createCommonjsModule(function(module, exports) {

    Object.defineProperty(exports, "__esModule", {
        value: true
    });
    exports.flush = flush;
    exports.default = void 0;
    
    /* ... */
    
    var JSXStyle =
        /*#__PURE__*/
        function(_Component) {/* ... */}(React.Component);

    exports.default = JSXStyle;

    function flush() {/* ... */}
});

unwrapExports(style);
var style_1 = style.flush;

var style$1 = style;
```

As you can see, `unwrapExports(style);` is called, but never assigned to `style$1`.  This results in errors when any methods of `style$1` are used since its value is `module.exports` (via `createCommonjsModule`)  instead of `module.exports.default`.

If I alter the last line to be the following, everything works as expected:

```js
var style$1 = unwrapExports(style);
```

Am I possibly misconfiguring the plugin? Any pointers will be much appreciated.

**Comment by shellscape** [comment]
Just sat down to look into this issue. Within the commonjs plugin codebase, I can't find anything that would prevent the assignment that everyone is talking about. This looks like it might be a problem with Rollup core with transforms to cjs. I'll have to investigate further.

**Comment by shellscape** [comment]
Hey folks, this one has gone quite stale. We're going to close for housekeeping but we'd happily review any PRs that pop up to resolve this issue.
