### ISSUE TITLE
[@rollup/plugin-wasm] filename is renamed to hash for copy creates 404

### ISSUE THREAD

**Issue by hey24sheep** [rollup/plugins#1025]
- Rollup Plugin Name: plugin-wasm
- Rollup Plugin Version: 5.1.2
- Rollup Version: 2.58.0
- Operating System (or Browser): Chrome browser on Windows 10
- Node Version: 16.3.0
- Link to reproduction _(⚠️ read below)_:
- To reproduce this error, I am using a library argon2-browser in my own library. [Argon2-browser](https://github.com/antelle/argon2-browser) uses a "argon2.wasm" file. 
-when I try to build using `rollup -c` this "argon2.wasm" file gets copied to my "dist/{hash}.wasm" 
- now the issue is while the file gets copied with a new name, but that same file is used by "argon2-browser" multiple times in their code by the name "argon2.wasm" which is alwasy 404 if I serve it.

```js
export default {
    input: "src/index.js",
    output: [
        {
            format: "cjs",
            name: "dummy",
            file: "dist/dummy.cjs.js",
            globals: {
                "argon2-browser": "argon2",
                "path": "path",
                "fs": "fs",
            }
        },
        {
            format: "cjs",
            name: "dummy",
            file: "dist/dummy.cjs.min.js",
            plugins: [terser()],
            globals: {
                "argon2-browser": "argon2",
                "path": "path",
                "fs": "fs",
            }
        },
        {
            format: "umd",
            name: "dummy",
            file: "dist/dummy.umd.js",
            globals: {
                "argon2-browser": "argon2",
                "path": "path",
                "fs": "fs",
            }
        },
        {
            format: "umd",
            name: "dummy",
            file: "dist/dummy.umd.min.js",
            plugins: [terser()],
            globals: {
                "argon2-browser": "argon2",
                "path": "path",
                "fs": "fs",
            }
        },
        {
            format: "iife",
            name: "dummy",
            file: "dist/dummy.iife.js",
            globals: {
                "argon2-browser": "argon2",
                "path": "path",
                "fs": "fs",
            }
        },
        {
            format: "iife",
            name: "dummy",
            file: "dist/dummy.iife.min.js",
            plugins: [terser()],
            globals: {
                "argon2-browser": "argon2",
                "path": "path",
                "fs": "fs",
            }
        },
        {
            format: "es",
            name: "dummy",
            file: "dist/dummy.esm.js",
            globals: {
                "argon2-browser": "argon2",
                "path": "path",
                "fs": "fs",
            }
        },
        {
            format: "es",
            name: "dummy",
            file: "dist/dummy.esm.min.js",
            plugins: [terser()],
            globals: {
                "argon2-browser": "argon2",
                "path": "path",
                "fs": "fs",
            }
        },
    ],
    plugins: [
        commonjs(),
        nodePolyfills(),
        nodeResolve({
            preferBuiltins: true,
            browser: true,
            dedupe: [
                "node_modules",
            ],
            // pass custom options to the resolve plugin
            moduleDirectories: [
                "node_modules"
            ],
            extensions: [".js", ".ts", ".wasm"]
        }),
        wasm(),
    ],
};
```

### Expected Behavior
- File should be copied with the original name instead of a "{hash}.wasm" to keep imports/filename uses within packages intact

### Actual Behavior
- File get copied with a new filename like "{hash}.wasm"

### Additional Information
- This [code line](https://github.com/rollup/plugins/blob/6eb661692f5b8d8fc4e3b61ff748f49fab1e82ec/packages/wasm/src/index.ts#L40) should not exist.

**Comment by hey24sheep** [comment]
This issue still exists, I added a repro repository and steps. Any update regarding this?

**Comment by riskers** [comment]
I meet the same question.

The plugin provide [publicPath](https://github.com/rollup/plugins/blob/master/packages/wasm/README.md#publicpath) actually.
But I don't think it's reasonable. Because I develop a lib , users serve on browser, I have no idea what is `publicPath`!

So, I set targetEnv: 'auto-inline' that will bundle wasm file in js through it's ugly.

**Comment by hey24sheep** [comment]
@riskers do you set the targetEnv in wasm() or somewhere else?
