### ISSUE TITLE
[plugin-graphql] Allow .graphqls file extension

### ISSUE THREAD

**Issue by IanVS** [rollup/plugins#1027]
- Rollup Plugin Name: @rollup/plugin-graphql
- Rollup Plugin Version: 1.0.0

### Feature Use Case
My graphql schema is named `schema.graphqls`, which is the default from gqlgen (https://gqlgen.com/)

### Feature Proposal
I think the plugin should include `.graphqls` alongside `.gql` and `.graphql`, or even make it configurable.

**Comment by fmatosqg** [comment]
Adding my 2 cents, android apollo uses `.sdl` for schemas but also support `.json`. So far I'm not aware/able to have apollo handle schemas in `.graphql` file extension.

https://github.com/apollographql/apollo-tooling/issues/1408
