### ISSUE TITLE
Crash on new typescript file pattern `.d.mts` `.d.cts`

### ISSUE THREAD

**Issue by loynoir** [rollup/plugins#1032]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: ^8.3.0
- Rollup Version: ^2.59.0
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_: https://github.com/loynoir/reproduce-rollup-plugins-1032.mjs

### Expected Behavior
No error

### Actual Behavior
```sh
$ rollup -c
./index.mjs → stdout...                                                                                          
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)                 
lib/a.d.mts (1:7)
1: export declare const value = "a";
          ^
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

### Additional Information
Typescript have new file pattern `.d.mts` `.d.cts`

**Comment by shellscape** [comment]
Do you have a link for a spec defining these file extensions?

**Comment by loynoir** [comment]
I think main pull is
https://github.com/microsoft/TypeScript/pull/45884

And entry file `index.mjs` reference to `lib/a.mjs` `lib/a.d.mts`, are generated by official `tsc` command.

**Comment by shellscape** [comment]
Thanks, but that PR has 569 files that we're definitely not going to sift through. To consider this a bug, we'll need a link to spec or docs showing that TS officially supports these  lnew extensions.

**Comment by NotWoods** [comment]
I can confirm these will be supported by TypeScript 4.5, [see announcement blog](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#new-file-extensions)

**Comment by Septh** [comment]
The new extensions were announced with the 4.5 beta : https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#new-file-extensions

Not sure what the status is right now since many module-related things have been officially delayed and are only available as an experimental flag in nightly releases. : https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#whats-new-since-the-beta-and-rc
