### ISSUE TITLE
[commonjs] not transform when extension has a query

### ISSUE THREAD

**Issue by mater1996** [rollup/plugins#1034]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version:  21.0.1
- Rollup Version: 2.58.3
- Operating System (or Browser): nodejs
- Node Version: v15.2.0
- Link to reproduction _(⚠️ read below)_: https://github.com/mater1996/rollup-commonjs-bug

### Expected Behavior

transform test2.js

### Actual Behavior

`require('./test2.js?query=1')`. not transform test2.js

### Additional Information

- npm install 
- npm run build
- see dist index js

**Comment by dnalborczyk** [comment]
I don't think commonjs supports query strings or fragments?

**Comment by mater1996** [comment]
I'm working on a rollup plugin when resolve a id with query, commonjs will not transform code

souce 
```js
require('***')
```

``` js
export default function plugin(){
  return {
    resolveId(source){  
      if(filter(soure))  return  souce + '?query=1'
    } 
  }
}
```

**Comment by dnalborczyk** [comment]
I don't think it should be supported, as it's not possible to run that anywhere without transpiling or bundling. that said, I agree you could take that argument and apply it to any non-standard way of importing anything else which is not on the standards track.

@mater1996  curious why you don't use `esm` instead?

**Comment by mater1996** [comment]
I tried using esM, but the effect was the same.
The reason I use `require` is because this plugin was previously a plugin for `webpack`, which supports handling require and converting it to import.
I think the error here is because 'extName' is `.js?query=1` in the code below.

```js
transform(){
   const extName = path$t.extname(id);
   if (!filter(id) || !extensions.includes(extName)) return null
}
```

**Comment by lukastaegert** [comment]
I think the extension logic is not exactly critical so extending it to support queries should not bring too many problems. Still I would like to explore your problem a little more first:
* Do you want to attach "meta-information" to a module via the query string (that would be respected by a loader/transformer downstream), but essentially the module would still exist only once, or
* do you want to be able to have "different flavors" of a module in the same tree with different query strings?

If it is the second, then you need different ids and query strings are definitely a way forward. If it is the first, then I would recommend to use [custom module meta data](https://rollupjs.org/guide/en/#custom-module-meta-data) instead, which is an invisible way of attaching arbitrary information to modules.

**Comment by mater1996** [comment]
Different ids and query strings is?

**Comment by mater1996** [comment]
I found this problem when in vite, vite under the mode of development will convert the import to ` node_modules/lodash/flatten.js?v=1149f538, extension is '.js'?v=1149f538 ', I tried using viteCommonjs and this did not appear.
