### ISSUE TITLE
[plugin-alias] Alias not resolved in dynamic import including variables

### ISSUE THREAD

**Issue by pmrotule** [rollup/plugins#1035]
- Rollup Plugin Name: plugin-alias
- Rollup Plugin Version: 3.1.2
- Rollup Version: 2.58.0
- Operating System (or Browser): MacOS 
- Node Version: 14.16.1
- Link to reproduction _(⚠️ read below)_: https://github.com/pmrotule/rollup-alias-bug-import-with-vars

### Expected Behavior

I expect the alias in dynamic imports including a variable to be resolved.

```js
import(`@/files/${letter}.js`)

// expected output
import(`../../files/${letter}.js`) // the resolved path
```

### Actual Behavior

```js
import(`@/files/${letter}.js`)

// actual output
import(`@/files/${letter}.js`) // no change
```

### Additional Information

I understand [`@rollup/plugin-dynamic-import-vars`](https://www.npmjs.com/package/@rollup/plugin-dynamic-import-vars) needs to be used in order to include the possible files to import in the bundle, but it only accepts relative paths and it's not its responsibility to resolve aliases. If `@rollup/plugin-alias` would resolve the alias as expected, it would generate a relative path ready to be processed by `@rollup/plugin-dynamic-import-vars`.

**Comment by balboFK** [comment]
Any news on this?

**Comment by claudio-darkkenergy** [comment]
I'm experiencing the same issue. Does anyone know why the plugin-alias doesn't work in dynamic imports?
