### ISSUE TITLE
[typescript]: Add ts error location to logged message

### ISSUE THREAD

**Issue by YonatanKra** [rollup/plugins#1041]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 8.3.0

### Expected Behavior / Situation

I expect that on TS error I'll also get the location of the error in the code like this:
```
Error: @rollup/plugin-typescript TS6133: 'test' is declared but its value is never read.
        In /Users/me/projects/project1/src/components/button/button.ts:8:7
```

### Actual Behavior / Situation

We just get the error message, without a location line:
```
Error: @rollup/plugin-typescript TS6133: 'test' is declared but its value is never read.
```

### Modification Proposal
I suggest to change the message and add the location line like in the expected behavior above.

**Comment by YonatanKra** [comment]
@shellscape - do you think this can go through?
I'm currently running with my own version of the plugin but would love to use the original :)

**Comment by shellscape** [comment]
Pending PR
