### ISSUE TITLE
external files are being bundled for commonjs

### ISSUE THREAD

**Issue by dnalborczyk** [rollup/plugins#1044]
- Rollup Plugin Name: 
- Rollup Plugin Version:
- Rollup Version:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
**foo.js**
```js
const js = require("./foo.js");

console.log(js);
```

**foo.js**
```js
export default "foo";
```

### Actual Behavior
```js
import './foo.js';

var rollupCreateRequireTest = {};

var require$$0 = "foo";

const foo = require$$0;

console.log(foo);

export { rollupCreateRequireTest as default };
```

### Additional Information
works for esm.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by dnalborczyk** [comment]
🤣  hold your horses, still filing things out

**Comment by dnalborczyk** [comment]
@shellscape I'm sorry, but I believe you are alienating people with auto closing issues. this is a bug which does not affect me, I noticed it while trying some things out.  I thought I'd be filing it anyways as it appears to be a bug.

**Comment by shellscape** [comment]
Thanks for your input. The issue policy here has been very effective.
