### ISSUE TITLE
CommonJS plugin ignores __esModule field of minified webpack4 bundles

### ISSUE THREAD

**Issue by fabianonunes** [rollup/plugins#1046]
## Rollup Plugin Reproduction REPL

- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 21.0.1
- Rollup Version: 2.60.0
- Operating System (or Browser): Ubuntu 21.10, Chrome 96.0.4664.45, Firefox 94.0
- Node Version: v16.13.0, v12.22.6 (repl.it)
- Link to reproduction: <https://replit.com/@fabianonunes/rollup-plugin-repro>

### Expected Behavior

Both imports from minified and unminified webpack4 bundles should return `.default` field, because they both contain the `__esModule` field.

### Actual Behavior

Minified webpack4 bundles returns a `Object [Module] { default: { foo: 'bar' } }` instead of ` { foo: 'bar' }`.

**Comment by morlay** [comment]
Now just do check exports from AST https://github.com/rollup/plugins/blob/master/packages/commonjs/src/index.js#L112

If need to fix this, may add check exports in runtime.

**Comment by morlay** [comment]
`module.exports` with `IIFE` will case this issue.

```js
module.exports = (() => { default, __esModule:true })()
```

`babel/esbuild/swc/typescript/rollup` should not generated `IIFE` code like this.
 I don't think need to deep walk AST to handle this case, 
 so just add a PR to make `defaultIsModuleExports` as an function to ignore the this case.
