### ISSUE TITLE
[typescript] declarationDir not working as expected

### ISSUE THREAD

**Issue by jpoehnelt** [rollup/plugins#1049]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 8.3.0
- Rollup Version: 2.60.0
- Operating System (or Browser): MacOS
- Node Version: v17.0.1
- Link to reproduction: https://replit.com/join/chxcoykjaf-jpoehnelt

### Expected Behavior
The typescript plugin places the typings in the same path as running tsc without rollup.

### Actual Behavior

The typings are nested incorrectly where `outDir` and `declaratationDir` are joined. These options are exclusive of one another.

```json
{
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "./dist",
    "outDir": "./dist",
  },
  "include": ["src/**/*"]
}
```

`./dist/dist/index.ts` instead of `/dist/index.d.ts`

### Additional Information

Attempting to bypass with `declarataionDir: '.'` doesn't work because `.` is then excluded.

Copied from #978 
```
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "./lib",
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "allowJs": false,
    "strict": true,
    "noUnusedLocals": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "declaration": true,
    "declarationDir": "./lib",
    "declarationMap": false,
    "lib": [
      "esnext",
      "dom"
    ],
    "types": [
      "node",
    ]
  },
  "include": [
    "src/*"
  ]
}
```

```
// rollup.config.ts
export default {
  input: 'src/index.ts',
  output: [
    {
      file: 'lib/index.js',
      format: 'cjs',
    },
    {
      file: 'lib/index.esm.js',
      format: 'esm',
    },
    {
      file: 'lib/index.umd.js',
      format: 'umd',
      name: 'ShawUtil',
    },
  ],
  plugins: [
    nodeResolve(),
    commonjs(),
    babel({
      babelHelpers: 'bundled',
      exclude: 'node_modules/**',
    }),
    typescript({
      tsconfig: './tsconfig.json'
    }),
    eslint({
      include: ['src/**'],
      exclude: 'node_modules/**',
    })
  ]
};
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

--

_Side note: I see you gave my comment closing #978 a thumbs down. That's a bad look for someone seeking maintainer action. The author of that issue chose not to follow the instructions in our issue templates. You've chosen to disregard the warnings in our template, and that's why this issue is being closed. Play by the rules of a repo, or don't be salty if the maintainers don't like that you're not. Update your issue to abide by the instructions and we'll reopen it._

**Comment by jpoehnelt** [comment]
Reproducible example https://replit.com/join/chxcoykjaf-jpoehnelt.

**Comment by jpoehnelt** [comment]
![image](https://user-images.githubusercontent.com/3392975/142926077-d77b9a6f-9118-430c-b4b9-a015dbad88ba.png)

but when calling `tsc` directly you get:

![image](https://user-images.githubusercontent.com/3392975/142926158-2a02e11d-579c-43f1-8c99-379624cb68f3.png)

**Comment by rafifos** [comment]
https://github.com/rollup/plugins/tree/master/packages/typescript#declaration-output-with-outputfile

**Comment by jpoehnelt** [comment]
That workaround seems fragile and unnecessary.

**Comment by fengxinming** [comment]
I got the same situation

**Comment by fengxinming** [comment]
it doesn't generate declaration files, I think #1112 is not duplicate

```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "dist",
    "declaration": true,
    "sourceMap": false,
    "target": "es5",
    "useDefineForClassFields": false,
    "module": "esnext",
    "moduleResolution": "node",
    "allowJs": false,
    "strict": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "removeComments": false,
    "composite": true,
    "jsx": "preserve",
    "lib": ["esnext", "dom"],
    "rootDir": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ],
      "~/*": [
        "./*"
      ]
    }
  },
  "include": [
    "./src",
    "./types"
  ]
}
```

**Comment by gnoyixiang** [comment]
not stale?

**Comment by DominicTobias** [comment]
I think this is strange/unexpected behaviour but I solved it like this: `"declarationDir": "../dist",`
I remember working around it another way before but can't find the thread now.

**Comment by shellscape** [comment]
#1378 has been merged and should address this issue
