### ISSUE TITLE
import with relative and absolute path -> same variable in <script context="module"> is DIFFERENT!

### ISSUE THREAD

**Issue by masrlinu** [rollup/plugins#1051]
- Rollup Plugin Name: plugin-alias
- Rollup Plugin Version: 3.1.8
- Rollup Version: 2.60.1
- Operating System (or Browser): MacOSX / Chrome
- Node Version: 7.24.0
- Link to reproduction _(⚠️ read below)_: https://github.com/masrlinu/rollup-test.git

### Expected Behavior
The website should output:
same variable:3!
same variable:3!
same variable:3!

...because I import the exact same component three times and increment it three times (one time with an absolute path and two times with a relative path)!

### Actual Behavior
The output is:
same variable:1!
same variable:2!
same variable:2!

### Additional Information
The reason is that the component included with an absolute path is compiled as another component as the two components, which are included with a relative path! So the one included with an absolute path is incremented one time, while the two components, which are included with a relative path are incremented two times.

It is the same bug, which I created here:
https://github.com/rollup/plugins/issues/296

This is just now an example, that this bug has a direct effect on projects and the bug cannot be ignored!

**Comment by masrlinu** [comment]
I think, it's better to not use this plugin, if such a big bug, which creates pain for developers, is now closed without even looking at it!

**Comment by shellscape** [comment]
@masrlinu I must be missing your contribution to resolve this issue. Please let us know where your PR is to fix, and we'll be happy to reopen the issue.

You may also find this interesting: http://liberamanifesto.com. Please don't comment on repo management in bug issues.

**Comment by masrlinu** [comment]
Yes, sorry! I completely read the manifesto and know that you don't owe me anything. You don't need to fix the bug, but could you please let this bug open, so that everybody, who uses relative and absolute include paths is informed that this is not supported by this plugin and that he should either just use relative or just use absolute paths, but not a combination? Because if he uses a combination, this leads to bugs, whose origin is VERY hard to detect!
