### ISSUE TITLE
Documentation for how to add typescript to multi entry

### ISSUE THREAD

**Issue by jacktan165** [rollup/plugins#1056]
- Rollup Plugin Name: 
- Rollup Plugin Version:

Documentation Is:

- [ x ] Missing
- [ x ] Needed
- [ x ] Confusing
- [ x ] Not Sure?

### Please Explain in Detail...
rollup.config.js
```
  import multi from "@rollup/plugin-multi-entry";

  plugins: [
    svgr(),
    peerDepsExternal(),
    resolve(),
    multi({ entryFileName: "index.js" }),
    babel({ 
      babelHelpers: 'runtime',
      exclude: '**/node_modules/**',
      skipPreflightCheck: true,
      presets: ['@babel/env', '@babel/preset-react']
    }),
    commonjs(),
    typescript({ useTsconfigDeclarationDir: true, tsconfig: "tsconfig.json" })
```
The plugin multi entry creates an entry file called index.js which is the encapsulation of all files, but it does not emit a index.d.ts. Is there a documentation on how to do so?

### Your Proposal for Changes
Please write a documentation on how to create a index.d.ts to a newly created multi entry file.

**Comment by ankeetmaini** [comment]
Does the tsconfig.json has "declarations: true"?

**Comment by jacktan165** [comment]
Yes. It emits `.d.ts` for all existing files. The problem I think is Typescript does not run through `index.js` because it is generated when you run `yarn build` or whatever, Typescript ignores that generated file...
