### ISSUE TITLE
`Array` is inconsistent in plugin READMEs

### ISSUE THREAD

**Issue by NotWoods** [rollup/plugins#106]
- Rollup Plugin Name: most of them :)

Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
We currently represent an array of items in different formats in our markdown docs. 
- `Array(String)`
- `Array[String]`
- `Array[...String]`

### Your Proposal for Changes
Let's pick one of these and replace the rest.

**Comment by shellscape** [comment]
Let's go with `Array[...String]`.
