### ISSUE TITLE
node-resolve wipes out other plugins' meta data

### ISSUE THREAD

**Issue by Septh** [rollup/plugins#1060]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 13.0.6
- Rollup Version: 2.60.1
- Operating System (or Browser): Windows 10
- Node Version: 14.17.6
- Link to reproduction _(⚠️ read below)_: https://replit.com/@Septh/node-resolve-meta-issue-repro

### Expected Behavior
Meta data added by other plugins is respected.

### Actual Behavior
Meta data is removed.

### Additional Information
It all depends on plugins order - run REPL for a demo.

**Comment by lukastaegert** [comment]
I will have a look.

**Comment by lukastaegert** [comment]
Fix at #1062.

**Comment by Septh** [comment]
Thanks!
