### ISSUE TITLE
`(plugin commonjs) SyntaxError: Unexpected token typeof`

### ISSUE THREAD

**Issue by kamleshchandnani** [rollup/plugins#1065]
- Rollup Plugin Name: `commonjs`
- Rollup Plugin Version: `21.0.1`
- Rollup Version: `2.61.1`
- Operating System (or Browser): MacOS 11.6
- Node Version: `16.13.0`
- Link to reproduction _(⚠️ read below)_: https://github.com/razorpay/blade/pull/391

Steps to reproduce:
1. Clone the repository
2. Checkout [this branch](https://github.com/razorpay/blade/tree/add-storybook)
3. Run `yarn` at the repo root

### Expected Behavior
After I upgraded the babel packages from versions `7.14.x` to `7.16.x` my rollup builds starts failing. Specifically the `@rollup/plugin-commonjs`. It starts throwing below error 
```
[!] (plugin commonjs) SyntaxError: Unexpected token (14:7) in /home/runner/work/blade/blade/packages/blade/node_modules/react-native/index.js
node_modules/react-native/index.js (14:7)
12: 
13: // Components
14: import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
```
Here's the [github action link](https://github.com/razorpay/blade/runs/4535789378?check_suite_focus=true#step:4:77) to see the exact error details

While upgrading I also upgraded the commons plugin version to `21.x` and then again tried reverting that but seems like there's something which commonjs plugin is not liking and it's difficult to identify from the logs what exactly is going wrong.

Although the project is running absolutely fine, the tests are passing too which means it's not necessarily the problem with babel?

### Actual Behavior

The plugin shall transform and build successfully.

### Additional Information

Here's my [`rollup.config.js`](https://github.com/razorpay/blade/blob/add-storybook/packages/blade/rollup.config.js). There's no change in the rollup config, just the packages have been upgraded.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by kamleshchandnani** [comment]
Hey @shellscape I linked to a repro branch in the description with steps to run to reproduce the issue as well. 🤔  

Putting the branch here again - https://github.com/razorpay/blade/tree/add-storybook

**Comment by shellscape** [comment]
@kamleshchandnani we have three options for a _valid reproduction_. See my reply above. What you've provided doesn't match any of our accepted options. It's not the maintainer's job here to wade through complex problems. Please choose one of the options we accept so that your issue is isolated, and we'll be happy to reopen the issue for triage.

**Comment by SixiCat** [comment]
@kamleshchandnani Did you fix that? I have a same problem in my project.

**Comment by Stevemoretz** [comment]
Same issue on ubuntu

**Comment by shellscape** [comment]
Please do not reply with "same," "me too," or +1. Please use the reaction buttons on the issue instead.

**Comment by shellscape** [comment]
OK thanks for clarifying
