### ISSUE TITLE
no beep in vite :(

### ISSUE THREAD

**Issue by RaafatTurki** [rollup/plugins#1067]
I used to use this all the time in rollup, but now that I've switched over to vite my beeps were gone!

ok `vite build` does beep however `vite dev` doesn't.
the beep is happening on the [`buildEnd()`](https://github.com/rollup/plugins/blob/8c6ae32f96ab299ca0b1207857e242bac89b9ca7/packages/beep/lib/index.js#L9) callback which I guess isn't called in `vite dev`.
I'm currently eyeing this [`handleHotUpdate()`](https://vitejs.dev/guide/api-plugin.html#handlehotupdate) vite specific hook.

I just want my beep back, where's the beep lebowski!

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by RaafatTurki** [comment]
but ... beep can't work in a repl.
also this is a vite related issue, that is a rollup template.

**Comment by shellscape** [comment]
If this is a vite issue, please post in the vite repo. We cannot be any clearer about requirements for bug issues. I'm sorry that you chose to ignore our warnings in the issue template, but it looks like we won't be able to help you with your issue. If you decide to open a new issue, please make sure you follow the instructions in our templates.
