### ISSUE TITLE
`node-resolve` plugin hoisting dependency libraries' unused `path` module and importing it in the final bundle

### ISSUE THREAD

**Issue by batjaa** [rollup/plugins#1068]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: I'm using ^13.1.1
- Rollup Version: "rollup": "^2.61.1"
- Operating System (or Browser): macOS 10.15.7 Catalina
- Node Version: v12.18.0
- Link to reproduction _(⚠️ read below)_: https://github.com/batjaa/test-rollup

### Expected Behavior

Not hoist `path` and import it.
```
function joinNormal(...rest) {
  return rest.join('/');
}

console.log(joinNormal('a', 'b'));
```

### Actual Behavior

`path` (and other nodejs modules) gets hoisted and imported into the final bundle when `node-resolve` plugin is used.

```
import 'path';

function joinNormal(...rest) {
  return rest.join('/');
}

console.log(joinNormal('a', 'b'));
```

### Additional Information

rollup was supposed to tree shake and not import nodejs modules (`fs`, `path` etc) which it does when `node-resolve` plugin is not used. When using `node-resolve` plugin, though the imported `path` is not being used it gets hoisted and imported in the final bundle.

**Comment by dnalborczyk** [comment]
> which it does when node-resolve plugin is not used.

@batjaa   how did you get it working with `rollup` only? I'm not able to. might be a `rollup` bug rather?

```js
// index.js
import { foo } from "./foo.js";

console.log(foo);
```

```js
// foo.js
export { versions } from "process";

export const foo = "foo";
```

```js
// dist.esm.js
import 'process';

const foo = "foo";

console.log(foo);
```

**Comment by dnalborczyk** [comment]
I'm guessing rollup does not know about `node.js` globals 🤔 

```js
// rollup.config.js
export default {
  input: "index.js",
  output: [
    {
      file: "dist.esm.js",
    },
  ],
};
```

```js
// index.js
import { foo } from "./foo.js";

console.log(foo);
```

```js
// foo.js
export const { versions } = process;

export const foo = "foo";
```

```js
// dist.esm.js
process;

const foo = "foo";

console.log(foo);
```

**Comment by batjaa** [comment]
I couldn't get your example working. Maybe there're some inconsistencies there — because I think I've seen it not importing modules that were not consumed in other use cases. Are there some clear explanation on when an import gets hoisted? Or why it is there when nothing that consumes it was referenced?

**Comment by batjaa** [comment]
Digging into rollup issues, I found [this ticket](https://github.com/rollup/rollup/issues/4143).  Related option: [treeshake](https://rollupjs.org/guide/en/#treeshake).

**Comment by dnalborczyk** [comment]
> I couldn't get your example working. 

in which way? like "at all", or you didn't see the expected outcome I described, or the outcome you described?

> Maybe there're some inconsistencies there — because I think I've seen it not importing modules that were not consumed in other use cases. 

yeah, that's the whole point of rollup. 😉

**Comment by dnalborczyk** [comment]
> Digging into rollup issues, I found [this ticket](https://github.com/rollup/rollup/issues/4143). Related option: [treeshake](https://rollupjs.org/guide/en/#treeshake).

good find! 

I think `rollup` could safely expect node built-in modules to be side effect free? 🤔  presumably thru an `input option` specifying that the target is indeed `node.js`, because e.g. `import {buffer} from 'buffer'` could mean multiple things: the node.js built-in as well as an external module, depending if it is a build for node.js or browsers. although this could be possibly also ruled out if we look at the `node:` prefixed module imports: `import {buffer} from 'node:buffer'` is definitely(?) the node.js built-in module.

as for the globals (`process`, `Buffer`, etc.): it seems those are missing and not defined in `rollup`. I'll have a PR in the works.

**Comment by dnalborczyk** [comment]
I think this issue can be (should be) moved to the `rollup` repo?
