### ISSUE TITLE
add updated node-builtins

### ISSUE THREAD

**Issue by yawetse** [rollup/plugins#1078]
- Rollup Plugin Name: rollup-plugin-node-builtins
- Rollup Plugin Version:

### Modification Proposal
please add https://github.com/crokita/rollup-plugin-node-builtins as an official plugin. It's the updated version of the original plug with the security vulnerabilities fixed.

**Comment by shellscape** [comment]
Sorry, this isn't up to us. Please contact that project, only they can make the request.
