### ISSUE TITLE
Image-plugin: Preserve module resolution and provide Base64 alternative

### ISSUE THREAD

**Issue by advename** [rollup/plugins#1087]
- Rollup Plugin Name: **[@rollup/plugin-image](https://github.com/rollup/plugins/tree/master/packages/image)**
- Rollup Plugin Version: 2.1.1

There are many rollup image plugins out there, even two official ones:

**[@rollup/plugin-image](https://github.com/rollup/plugins/tree/master/packages/image)**
While this plugin works, its a "cheap" solution increasing file sizes by 33%. Building an icon library like font awesome would be at a disadvantage bundling with rollup and this plugin.

**[@rollup/plugin-url](https://github.com/rollup/plugins/blob/master/packages/url)**
If i correctly understand this plugin, it does a similar job as the above, while using images as the examples.

With the first one having 230k weekly downloads shows that resolving images is quite common in bundles.

However, it can become quite heavy when adding multiple SVG/JPG files to a project, always leading to an increased disk size of 33%.

### Feature Use Case
Having the following component with an image
```jsx
import React from "react";
import dog from "./../assets/dog.jpg";

export function Dog() {
  return (
    <div>
      <img src={dog} alt="Logo" />
    </div>
  );
}
```
The bundle should copy the file to a specific directory (e.g. `/dest/assets`) and link to the file with the appropriate import statement.
This would be of an advantage for libraries, where a consuming application should handle images, and not the library itself.
It seems like most people gave up on this idea since everybody just ignorantly started using Base64 approach.

### Feature Proposal
Add a feature to copy&paste the files to a destination folder and import the accordingly in the build files.

Generating a similar output from above's component:
```jsx
import 'react';
import dog from '../assets/dog.jpg';
import { jsxs, jsx } from 'react/jsx-runtime';

function Button(props) {
  return /*#__PURE__*/jsxs("div", {
    children: [/*#__PURE__*/jsx("img", {
      src: dog,
      alt: "Logo"
    })]
  });
}
export { Button };
```

Some similar (but incomplete, bugged, or not anymore working) plugins for reference:
- https://github.com/alwaysonlinetxm/rollup-plugin-img
- https://stackoverflow.com/a/70352910
- https://rollupjs.org/guide/en/#file-urls

**Comment by TaylorBeeston** [comment]
To anyone landing on this issue looking for how to implement this like I did, [rollup-plugin-smart-asset](https://github.com/sormy/rollup-plugin-smart-asset) seemed to be exactly what I was looking for!
