### ISSUE TITLE
[plugin-babel] Unexpected situation when using with babel-preset-react-app on Windows

### ISSUE THREAD

**Issue by atti187** [rollup/plugins#1089]
- Rollup Plugin Name: plugin-babel
- Rollup Plugin Version: 5.3.0
- Rollup Version: 2.63
- Operating System (or Browser): Windows
- Node Version: v14.15.5
- Link to reproduction: https://regex101.com/r/y6BLj8/2

### Expected Behavior
PreflightChecks are passed

### Actual Behavior
Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/plugins/issues. Thanks!

### Additional Information
https://github.com/facebook/create-react-app/blob/a422bf227cf5294a34d68696664e9568a152fd8f/packages/babel-preset-react-app/create.js#L194 is using 

```
absoluteRuntimePath = path.dirname(
      require.resolve('@babel/runtime/package.json')
    );
```

which on Windows evaluates to ```<my-source-path>\\rollup-babel-bug\\node_modules\\@babel\\runtime```. This breaks the preflightCheck at https://github.com/rollup/plugins/blob/9874740ca685b1600e4319365c21e8c1131e9d95/packages/babel/src/preflightCheck.js#L48, as the regex is not considering backslashes.

https://github.com/rollup/plugins/blob/9874740ca685b1600e4319365c21e8c1131e9d95/packages/babel/src/preflightCheck.js#L37 should be changed to:

```
const inheritsHelperRe = /[\\\/]+helpers[\\\/]+(esm[\\\/]+)?inherits/;
```

If possible to verify on Windows I can provide a reproduction repo.

No matter what, I'll create a PR for the change.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by atti187** [comment]
Thought you might be ok with the regex reproduction link, as it's simple as that. But here's the repo I promised (if needed): https://github.com/atti187/rollup-babel-bug
