### ISSUE TITLE
`@types/resolve` is a regular dependency of `@rollup/plugin-node-resolve`

### ISSUE THREAD

**Issue by samualtnorman** [rollup/plugins#1091]
- Rollup Plugin Name: `@rollup/plugin-node-resolve`
- Rollup Plugin Version: `13.1.13`

### Expected Behavior / Situation
`@types/resolve` is a dev dependency of `@rollup/plugin-node-resolve`

### Actual Behavior / Situation
`@types/resolve` is a regular dependency of `@rollup/plugin-node-resolve`

I have a project that lets me import node modules, but the code doesn't actually run in node.
having this plugin installed causes typescript to think that array likes have an `.at()` method due to `@types/node@"*"` being a dependency of `@types/resolve@1.17.1`

I tried searching in issues first, so sorry if the `package.json` is configured this way on purpose

### Modification Proposal
make `@types/resolve` a dev dependency of `@rollup/plugin-node-resolve`

**Comment by frank-dspeed** [comment]
i like the issue a lot so you want to avoid having @types/resolve in your production build because of typechecking is that correct?

**Comment by frank-dspeed** [comment]
you can give this a try if that fails for any reason there can be many 

```
"skipLibCheck": true
```

you need to use

```
{
  "compilerOptions": {
    ...,
    "types": []
  }
}
```
that disables automatic type inclusion and will only include the "@types/yourname" that you reference in that array.
