### ISSUE TITLE
Relative imports are made absolute before other plugin sees them

### ISSUE THREAD

**Issue by Hexxeh** [rollup/plugins#1092]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 13.1.3
- Rollup Version: 2.64.0
- Operating System (or Browser): OSX 12.1
- Node Version: 16.13.1
- Link to reproduction _(⚠️ read below)_: https://replit.com/@LiamMcLoughlin1/rollup-repro#rollup.config.js

### Expected Behavior

Relative imports are not made absolute before other plugins can see them.

### Actual Behavior

Relative imports are made absolute before my other plugin can see it.

### Additional Information

Upgrading from 11.2.1 where this behaviour was not observed. I know there's a couple major bumps, but looking through the changelog I don't see anything relevant. Sorry if it's there and I missed it!

**Comment by Hexxeh** [comment]
I'm happy to submit a pull request (once I figure out where the change happened), but I'm not sure if this change was intentional or not.

**Comment by shellscape** [comment]
@guybedford any input here? 

At the very least, putting a change in function behind a flag seems reasonable to me.
