### ISSUE TITLE
plugins commonjs lets make it type save

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/plugins#1093]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: *

### Expected Behavior / Situation
the commonjsHelper should not make my typescript that does check js types unhappy

### Actual Behavior / Situation
It makes it unhappy

### Modification Proposal
lets add a small line with big impact

```
/** @param {{ [x: string]: any; }} x */
```

then typescript is happy!

**Comment by shellscape** [comment]
This looks like a bug report. Please use the bug report template and provide a reproduction so we can see the unhappy compiler you're describing.

**Comment by frank-dspeed** [comment]
Will Create Minimal Reproducer Repo

**Comment by frank-dspeed** [comment]
closed in favor of permernent fork will support more complet PR's later from my backport org
