### ISSUE TITLE
Support module overrides in the browser field in package.json

### ISSUE THREAD

**Issue by DimaLapshyn** [rollup/plugins#1098]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: 13.1.1

### Expected Behavior / Situation

If a package specifies module overrides in its "browser" field in package.json, e.g.

```
"browser": {
    "util": false,
    "worker_threads": false,
    "./errors": "./errors-browser.js",
    "./readable.js": "./readable-browser.js",
    "./lib/internal/streams/from.js": "./lib/internal/streams/from-browser.js",
    "./lib/internal/streams/stream.js": "./lib/internal/streams/stream-browser.js"
  }
```
the plugin import logic shall respect these overrides if `{ brower: true }` has been supplied in the config (or if the browser field has been specified as the first priority via the `mainFields` option)

### Actual Behavior / Situation

the plugin import logic seems to ignore such overrides, so they have to be monkey-patched with @rollup/plugin-replace.

### Modification Proposal

Implement full support for the `browser` field, including support for module import overrides.

**Comment by guybedford** [comment]
Browser field support is already implemented, so the question would be why this is not applying.

Do you have an exact replication here to share?

**Comment by frank-dspeed** [comment]
@guybedford i think improving the support for imports and exports should be more well defined so that when this filds are supplyed we take the browser fild from there we maybe should drop browser fild support in favor of that. typescript also introduced 2 new resolve algos to address that they call it node12 and nodenext if this is used the imports and exports get strict used.

**Comment by DimaLapshyn** [comment]
@guybedford For example, given the overrides in the "browser" field here:
https://github.com/nodejs/readable-stream/blob/main/package.json#L56

The following `require` call does not seem to apply the overrides:
https://github.com/nodejs/readable-stream/blob/97fd94f404709542a7d69b271eddfcc34345916e/lib/_stream_readable.js#L1111

**Comment by frank-dspeed** [comment]
just my 5cent and a guide for people who come to this

## Guide Browser & NodeJS & Everything Packaging
Create indipendent package.json files reference them as workspace in your package.json (root one) then install only the root one your done.

**Comment by shinichy** [comment]
I think this is still an issue.
