### ISSUE TITLE
Can't import dependencies as external and setting global with @rollup/plugin-virtual

### ISSUE THREAD

**Issue by sumitsaha** [rollup/plugins#1103]
I want to use the Rollup JavaScript API to bundle my codes. I don't have any file system so I want to do it on the fly and @rollup/plugin-virtual is a perfect option for me. I was able to bundle internal modules but failed to import external modules like react, react-dom etc. Also I don't want to resolve dependencies from node_modules folder, and I want to resolve them in the front end using import maps. I tried the below code, but getting below error response. Can anyone help me figure this out?

```js
import { babel } from "@rollup/plugin-babel";
import virtual from "@rollup/plugin-virtual";
import express from "express";
import { rollup } from "rollup";
const app = express();
const port = 3300;

app.get("/", (req, res) => {
    const inputOptions = {
        external: ["react", "react-dom"],
        input: "entry",
        plugins: [
            virtual({
                entry: `import React from 'react';
                import ReactDOM from 'react-dom';

                ReactDOM.render(
                  <h1>Hello, world!</h1>,
                  document.getElementById('root')
                );`,
            }),
            babel({
                presets: ["react"],
                babelHelpers: "runtime",
            }),
        ],
    };

    const outputOptions = {
        format: "iife",
        globals: {
            react: "React",
            "react-dom": "ReactDOM",
        },
    };

    async function build() {
        let bundle;
        let buildFailed = false;
        try {
            // create a bundle
            const bundle = await rollup(inputOptions);

            await generateOutputs(bundle);
        } catch (error) {
            buildFailed = true;
            // do some error reporting
            console.error(error);
        }
        if (bundle) {
            // closes the bundle
            await bundle.close();
        }
    }

    async function generateOutputs(bundle) {
        const { output } = await bundle.generate(outputOptions);
        console.log(output[0].code);
    }

    build();
    res.send("hello");
});

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`);
});

```

I am getting the below error when I run -

<img width="1070" alt="Screenshot 2022-02-05 at 3 35 29 PM" src="https://user-images.githubusercontent.com/1416832/152636468-6ab56f68-703b-479e-92bb-8e42d26610b7.png">

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
