### ISSUE TITLE
[@rollup/plugin-typescript]: Breaks pragma adding from another plugin

### ISSUE THREAD

**Issue by RoyalHunt** [rollup/plugins#1106]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: "^8.3.0",
- Rollup Version: "vite": "^2.8.1"
- Operating System (or Browser): MacOS Monterey, Chrome  98.0.4758.80
- Node Version: v16.13.2
- Link to reproduction _(⚠️ read below)_:  https://github.com/RoyalHunt/themeUI-storybook

### Expected Behavior

Create d.ts files without breaking code.

### Actual Behavior

Create d.ts files, but prevent another plugin work.  

### Additional Information
With plugin:
<img width="727" alt="Screenshot 2022-02-14 at 22 20 09" src="https://user-images.githubusercontent.com/22590130/153940114-6da3d9f1-42cd-4926-bbdc-bb0891461324.png">

Without:
<img width="695" alt="Screenshot 2022-02-14 at 22 21 00" src="https://user-images.githubusercontent.com/22590130/153940226-9ea7a565-141c-4b37-9db5-c962bb410451.png">

Steps to reproduce:
1. Run lerna bootstrap
2. In file viteconfig.base.ts remove comments from typescript pluguin
3.  run yarn build

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

Please re-read https://git.io/fNzHA for instructions and guidance as to what an acceptable, minimal repository reproduction is.

**Comment by RoyalHunt** [comment]
> Thanks for opening an issue. Citing the issue template:
> 
> > 🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> > Please provide one by:
> > 
> > 1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
> > 2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
> >    Please use NPM for installing dependencies!
> >    These may take more time to triage than the other options.
> > 3. Using the Rollup REPL at https://rollupjs.org/repl/
> > 
> > ⚠️ ZIP Files are unsafe and maintainers will NOT download them.
> 
> Please re-read https://git.io/fNzHA for instructions and guidance as to what an acceptable, minimal repository reproduction is.

Can you help me to understand what I've missed, please! Should I add the issue in the README file of the repo to make it valid?

**Comment by shellscape** [comment]
> How to create a minimal reproduction

there is an entire section at that URL which tells you exactly how to create a minimal repository. The second bullet point talks about removing things that are unrelated.

**Comment by RoyalHunt** [comment]
> > How to create a minimal reproduction
> 
> there is an entire section at that URL which tells you exactly how to create a minimal repository. The second bullet point talks about removing things that are unrelated.

Thank you for the explanation.
