### ISSUE TITLE
[@rollup/plugin-url] request URL path via query param in import line

### ISSUE THREAD

**Issue by lazka** [rollup/plugins#1108]
- Rollup Plugin Name: @rollup/plugin-url
- Rollup Plugin Version: 6.1.0

### Feature Use Case

Inspired by https://vitejs.dev/guide/assets.html#explicit-url-imports it would be nice if I could request an URL path for a file in the import line instead of the rollup config.

I have various sub-packages that use the url() plugin and every reverse dependency has to mirror the url plugin config includes/excludes. If it was configured in via the import then things would just work.

### Feature Proposal

```js
import myPath from 'select2/dist/css/select2.min.css?url';
```

**Comment by gadingnst** [comment]
is this issue stil relevant?

**Comment by lazka** [comment]
My stance on it hasn't changed at least, not that that helps much.

**Comment by visuallization** [comment]
Also looking for a way to rollup a vite project which utilizes explicit url imports. Currently I do get the error: `ENOENT: no such file or directory` as rollup doesn't know how to interpret files imported with `?url` postfixed.
