### ISSUE TITLE
"name-is-not-exported-by-module" for default export #206

### ISSUE THREAD

**Issue by dman777** [rollup/plugins#112]
from https://github.com/rollup/rollup-plugin-commonjs/issues/206

> Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. beer

@shellscape  I am hitting this issue with Google's material-components-web https://github.com/material-components/material-components-web

**Comment by dman777** [comment]
Oh wait, closing because I am not using common.js but plugin-node-resolve instead. Not sure if that matters, though, as I am still hitting this issue.

**Comment by shellscape** [comment]
_(Please do fill out the issue template if you're migrating an issue over this way)_
