### ISSUE TITLE
[@rollup/plugin-commonjs] plugin can't work with a file with both import and module.exports syntax

### ISSUE THREAD

**Issue by musicq** [rollup/plugins#1121]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: latest
- Rollup Version: latest
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_: https://replit.com/@musicq/rollup-commonjs-repl#rollup.config.js

### Expected Behavior

Build successfully.

### Actual Behavior

It reports the below errors.

```
[!] Error: 'default' is not exported by src/commonjs/lib.ios.js, imported by src/commonjs/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/commonjs/index.js (2:7)
1: // const add = require('./lib');
2: import add from './lib';
```

### Additional Information

When including a file with both `import` and `module.exports`, commonjs plugin will take it as an ESmodule and won't transform the `module.exports` statement which will make Rollup reports error.

```js
import path from 'path'

module.exports = 1
```

https://github.com/rollup/plugins/blob/4c5e8fd582d7f2e173bfacd7c8cb066af4edd916/packages/commonjs/src/transform-commonjs.js#L502-L520

Is there any solution that can solve the problem?

**Comment by musicq** [comment]
Seems like no one wants to solve this issue, or maybe it's not an issue? 🤔

**Comment by dantman** [comment]
> Seems like no one wants to solve this issue, or maybe it's not an issue?

I'm not sure it's an issue. As this is not valid CommonJS nor ESM. `module` doesn't exist in ESM and so that code will error. `import` statements are not valid in CommonJS, only ESM modules can use them.

**Comment by musicq** [comment]
@dantman agree. The syntax seems not standard, but it is actually widely used in `react-native` source code. For example

https://github.com/facebook/react-native/blob/main/Libraries/ReactNative/UIManager.js#L11-L39

Will you consider supporting such syntax?

**Comment by dantman** [comment]
> @dantman agree. The syntax seems not standard, but it is actually widely used in `react-native` source code. For example

That's not actually JS. If you look closer the only uses of `import` and `export` are `import type` and `export interface`. That's not actually ESM. It's flow types. The RN code appears to be flow types in CommonJS code.

plugin-commonjs doesn't support flow, so the correct way to handle RN would be to have a flow plugin transpile the flow typed code to standard CommonJS before letting plugin-commonjs see it. In which case because the `import` and `export` are just for types, they wouldn't be present in the CommonJS code.

**Comment by musicq** [comment]
@dantman that seems not a good example. But other files contain such syntax. Like this one

https://github.com/facebook/react-native/blob/main/Libraries/ReactNative/AppContainer.js

No need to consider flow syntax, because it will be handled by `remove-flow-type` first and produce the normal JS code.
The syntax is actually used in some codebase I think.

**Comment by ppalmeida-vakt** [comment]
Hi.
First of all, thank you for your plugin and efforts. Really appreciate it.

Although I understand your point, I also see that lots of very common scripts adopt this "invalid" approach. One of the most famous is [classnames](https://github.com/JedWatson/classnames/blob/master/index.js#L47)

I tried to include it in my bundle in many different ways, but I couldn't avoid the following error:

```sh
src/index.tsx → ./dist...
[!] Error: 'default' is not exported by node_modules/classnames/index.js, imported by src/shared/components/my-component.tsx
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/shared/components/my-component.tsx (3:7)
1: import React from 'react';
2: import { mergeStyleSets } from '@fluentui/react';
3: import classNames from 'classnames';
          ^
4: const contentStyles = mergeStyleSets({
5:     status: {
Error: 'default' is not exported by node_modules/classnames/index.js, imported by src/shared/components/my-component.tsx
```

So, as far as I can see, there is no way to include it for now, right?

**Comment by dantman** [comment]
@ppalmeida-vakt I'm not the author of the plugin, none of the maintainers have commented so far.

Your issue appears to be separate. The classnames code you link to looks like UMD code. There is no `import` in it so it is not invalid in the way being discussed in this issue (containing both ESM imports and CommonJS exports).

Your issue appears to be with the plugin not being able to detect the export properly.

**Comment by lukastaegert** [comment]
One could probably implement a logic: If there is an export statement in the file, then we ignore module.exports, otherwise we do not ignore it. The only thing that feels like complete chaos to me would be trying to merge both.
