### ISSUE TITLE
[@rollup/plugin-node-resolve] Missing dependency should stop the build

### ISSUE THREAD

**Issue by hellos3b** [rollup/plugins#1125]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 13.1.3

### Expected Behavior / Situation

When building a project, if I forget to install a dependency the build should break and let me know so I can quickly fix it.

### Actual Behavior / Situation

A missing dependency gets assumed to be external and build finishes with broken code

```
'somelibrary' is imported by some-file.js, but could not be resolved – treating it as an external dependency
```

### Modification Proposal

Add an option to the config to not treat missing dependencies as external

**Comment by eddiemonge** [comment]
Was an option added?

**Comment by SunStupic** [comment]
@hellos3b How did you solve this issue?
