### ISSUE TITLE
plugin-node-resolve - new option "paths", manual resolution similar to tyepscript "paths" option.

### ISSUE THREAD

**Issue by craigphicks** [rollup/plugins#1127]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: currently 13.1.3

### Feature Use Case

When links beneath node_modules conflict with
links that are required for correct resolution with  "plugin-node-resolve".
This can happen when using dual dev/release environments,
where the required links differ for each.
Fundamentally this is do to the node_module link functionality being overloaded - 
it is is used to satisfy both node runtime requirements and rollup build time requirements.

Notice that typescript config files enable explicit "paths" that enable manually specifying module lookup,
thus avoiding this issue.  Rollup needs something similar.

### Feature Proposal

Add a "paths" options to plugin-node-resolve
```
type Paths = { 
   [path: string]:string
}
```
Examples:
```
paths: { 
   "mypackage1": "../mypackage1/dist-rls/release",
   "@myscope/mypackage2": "../mypackage2/dist-rls/release"
}
```
Of course "../mypackage1/dist-rls/release" is expected to contain a `package,json` with
```
  "name":"mypackage1",
```  
and "../mypackage2/dist-rls/release" is expected to contain a `package,json` with
```
  "name":"@myscope/mypackage2",
```  
"paths" would be used as a lookup to preempt any node resolution.

**Comment by craigphicks** [comment]
This quick solution seems to work - 
```
function rollupModuleMapPlugin(moduleMap) {
  return {
    name: "rollup-module-map-plugin", // this name will show up in warnings and errors
    resolveId(source) {
      if (moduleMap[source]) {
        return {
          id: path.resolve(moduleMap[source]),
          moduleSideEffects: false,
          meta: {},
        }; // this signals that rollup should not ask other plugins or check the file system to find this id
      }
      return null; // other ids should be handled as usually
    },
    load(id) {
      return null; // other ids should be handled as usually
    },
  };
}
``` 
and then just add 
```
  plugins:[rollupModuleMapPlugin({"mypackage1": "../mypackage1/dist-rls/release"})],
```
without the need for modification of `rollup-plugin-resolve`.

However, I do believe it would be helpful to have that functionality in `rollup-plugin-resolve`.

**Comment by shellscape** [comment]
I think if there were a larger call for the functionality, it would be justified to add that kind of feature to node-resolve. Given that the use case is fairly niche (but certainly valid, not commenting otherwise) I think the workaround is probably good for now. If you'd like to add a "recipe" to the repo that demonstrates how to use this workaround and the scenario it's for, we'd be happy to include that and update the readme with a link.

**Comment by craigphicks** [comment]
@shellscape  - Anyway, I have already forked and begun modifying because that's easier than bringing that workaround up to (reliable & reusable) par anyway.  Once that is rock solid with node-resolve tests and external usage in a build environment, I'll make a pull and discuss how it is being used.  I will close this issue in the meantime..

**Comment by craigphicks** [comment]
So it turns out the necessary functionality can be achieved using *plugin-node-resolve*'s existing `moduleDirectories` option and creating some extra directories and links.  No absolute need for modification.

**Comment by craigphicks** [comment]
Closing again.

**Comment by YonatanKra** [comment]
@craigphicks can you please give an example on how this can be achieved using `moduleDirectories`?
I'm unable to achieve that by using:
```
nodeResolve({
    moduleDirectories: ['node_modules', 'dist']
  })
```
This makes no difference. I still get:
`could not be resolved – treating it as an external dependency`
