### ISSUE TITLE
Update package dependencies of @rollup/plugin-eslint

### ISSUE THREAD

**Issue by haasz** [rollup/plugins#1128]
- Rollup Plugin Name: @rollup/plugin-eslint
- Rollup Plugin Version: 8.0.1

### Feature Use Case

Please update the package dependencies, especially eslint to at least v8.9.0.

https://github.com/rollup/plugins/blob/4c5e8fd582d7f2e173bfacd7c8cb066af4edd916/packages/eslint/package.json#L55

### Feature Proposal

To use the es2022 environment setting and other new features.

https://github.com/eslint/eslint/releases

Thanks.

**Comment by shellscape** [comment]
We'll welcome community contribution to resolve this. You can reference this abandoned PR for guidance https://github.com/rollup/plugins/pull/663
