### ISSUE TITLE
[@rollup/plugin-wasm] allow omitting node.js specific modules from output with targeted environment

### ISSUE THREAD

**Issue by nickbabcock** [rollup/plugins#1129]
- Rollup Plugin Name: @rollup/plugin-wasm
- Rollup Plugin Version: v5.1.2 (latest)

### Feature Use Case

I am using rollup and the rollup wasm plugin to create libraries that leverage wasm.

When a downstream developer imports this library using default webpack config, the build will fail due to helper module requiring Node.js modules:

https://github.com/rollup/plugins/blob/4c5e8fd582d7f2e173bfacd7c8cb066af4edd916/packages/wasm/src/helper.ts#L20-L21

webpack will error with "Error: Can't resolve 'fs' in ..."

### Feature Proposal

I'm proposing that the rollup wasm plugin exposes an additional configuration value where the library author can dictate if node.js specific modules can be used to initialize the wasm. This way the library author can use package.json conditional exports to properly expose wasm initialization depending on the environment.

```js
import { wasm } from "@rollup/plugin-wasm";
export default {
  plugins: [
    wasm({
      targetEnv: "browser" | "node" | "auto"
    })
  ]
}
```

- "auto" is the default and doesn't change the behavior
- "browser" removes the `isNode` conditional and associated branches
- "node" can assume the `isNode` conditional is true and remove `fetch`

**Comment by shellscape** [comment]
Seems reasonable. Please feel free to submit a PR
