### ISSUE TITLE
`[@rollup/plugin-multi-entry]` Exported Classes Not Bundling

### ISSUE THREAD

**Issue by ErrorBot1122** [rollup/plugins#1146]
- Rollup Plugin Name: **`@rollup/plugin-multi-entry`**
- Rollup Plugin Version: **`4.1.0`**
- Rollup Version: **`2.70.0`**
- Operating System (or Browser): ***Whatever Replit's OS is...***
- Node Version: **`14.17.1`**
- Link to reproduction _(⚠️ read below)_: https://replit.com/@ErrorbotTHE2nd/rollup-plugin-repro#rollup.config.js

### Expected Behavior

All files to bundle to bundle

### Actual Behavior

Only the Enums *(Exported Contents)* get bundled

### Additional Information

https://replit.com/@ErrorbotTHE2nd/Roblox-File-Handler-1 (I'm working on the **`unstable`** branch currently so go to that..)

**Comment by JFGHT** [comment]
It does not work with `export default`, but as a workaround you can use `export class ClassName`, which works fine.

**Comment by JFGHT** [comment]
A workaround for this is `export class ClassName` instead of `export default`.

**Comment by JFGHT** [comment]
Why is this closed?

**Comment by ErrorBot1122** [comment]
oh okay, I closed it as it was a fix to my problem, ill re-open it...
