### ISSUE TITLE
[@rollup/pluginutils] missing estree in dependencies

### ISSUE THREAD

**Issue by sionzee** [rollup/plugins#1156]
- Rollup Plugin Name: @rollup/pluginutils
- Rollup Plugin Version: 4.2.0
- Rollup Version: *
- Operating System (or Browser): Brave
- Node Version: 17.4.0
- Link to reproduction _(⚠️ read below)_:
 

### Expected Behavior
All imported modules must be listed in package.json

### Actual Behavior
Because of missing `estree` in package.json, the pnpm manager fails on resolution + typescript is unable to build.

ts-log:
```
error TS2307: Cannot find module 'estree' or its corresponding type declarations.

2 import { BaseNode } from 'estree';
                           ~~~~~~~~
Found 1 error in node_modules/.pnpm/@rollup+pluginutils@4.2.0/node_modules/@rollup/pluginutils/types/index.d.ts:2
```

code:
https://github.com/rollup/plugins/blob/master/packages/pluginutils/src/attachScopes.ts#L2

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by sionzee** [comment]
Do not get me wrong, but do you really need a reproduction for a straightforward issue?

I have linked the file what is using the 'estree' module and you can easily see that the module is missing in package.json file.

Doing a reproduction case will take an hour and will show you literally nothing.

**Comment by nogic1008** [comment]
Please move `@types/estree` package from `devDependencies` to `dependencies` on [/packages/pluginutils/package.json](https://github.com/rollup/plugins/blob/master/packages/pluginutils/package.json).

ex. https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

**Comment by nogic1008** [comment]
@sionzee Set [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) to `true` on your `tsconfig.json` as workaround.
