### ISSUE TITLE
CommonJS plugin v21 ignores leaves out ESM import for `try { require("dep") }`

### ISSUE THREAD

**Issue by aapoalas** [rollup/plugins#1162]
- Rollup Plugin Name: plugin-commonjs
- Rollup Plugin Version: ^21.0.0
- Rollup Version: 2.47.0 - 2.70.1
- Operating System (or Browser): Linux
- Node Version: 12.22.3
- Link to reproduction _(⚠️ read below)_: 

In plugin-commonjs v20 and before, building backbone.js as ESM with underscore and jquery set as external would create both underscore and jquery imports for the given external paths. In v21 jquery gets left out as its require call is inside a try-catch. This is a bit right and a bit wrong, as the try-catch does allow failing imports which a static import does not, but on the other hand leaving the import out doesn't feel quite ESM-correct either.

### Expected Behavior
The static import for jquery should probably still be generated.

### Actual Behavior
jquery static import is left out of build output.

### Additional Information
Replit: https://replit.com/@aapoalas/rollup-plugin-commonjs-21-backbone?v=1
* Pre-v21 output: https://replit.com/@aapoalas/rollup-plugin-commonjs-21-backbone?v=1#output/bundle-commonjs-20.js
* Post-v21 output: https://replit.com/@aapoalas/rollup-plugin-commonjs-21-backbone?v=1#output/bundle-commonjs-21.js

Let me know if the Replit doesn't work for some reason.

**Comment by lukastaegert** [comment]
Set the [`ignoreTryCatch`](https://github.com/rollup/plugins/tree/master/packages/commonjs#ignoretrycatch) option explicitly to `false`.
