### ISSUE TITLE
Commonjs plugin processes ids already resolved by other plugins

### ISSUE THREAD

**Issue by sagargurtu** [rollup/plugins#1175]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 22.0.0
- Rollup Version: 2.70.2
- Operating System (or Browser): MacOS
- Node Version: 16.14.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@sagargurtu/rollup-plugin-repro#rollup.config.js

### Expected Behavior
Commonjs plugin should not attempt to resolve ids which have already been resolved and marked external by other plugins. In the above example, `externals/object-assign` should not have been processed by commonjs plugin.

```
// Expected console log
Externals: object-assign
```

### Actual Behavior
Commonjs plugin attempts to import `externals/object-assign` from `externals/object-assign?commonjs-external`.
```
// Actual console log
Externals: object-assign,object-assign,externals/object-assign
```

### Additional Information

I'm trying to create a "catch-all-resolver" that collects all external dependencies (hence the reason for not using node-resolver plugin).

**Comment by lukastaegert** [comment]
That is unfortunately necessary for the commonjs plugin to correctly convert `require('external')` to an import. The actual external import is then located in `externals/object-assign?commonjs-external`.

**Comment by sagargurtu** [comment]
Based on that, I implemented this logic https://replit.com/@sagargurtu/rollup-plugin-repro-1#rollup.config.js which might work but
- It ties my plugin to the internal implementation of `commonjs` plugin.
- `?commonjs-external` query may change or be removed in future versions of `commonjs` plugin.

Is depending on `?commonjs-external` something that should be done? Is there an alternative for collecting external imports?

Based on rollup documentation, I thought that if a plugin's `resolveId()` returns an object, other plugins should not process the same id.

**Comment by lukastaegert** [comment]
Other plugins can do `this.resolve` to get this object, and then they can do any processing they like. But yes, you should not depend on the commonjs plugin that way. Not sure if you can easily get the externals in a reliable way during build, though you should be able to get them e.g. from `generateBundle` by inspecting the generated chunks reliably.
