### ISSUE TITLE
[@rollup/plugin-alias] don't support scss alias import in vue

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [rollup/plugins#1186]
- Rollup Plugin Name: @rollup/plugin-alias
- Rollup Plugin Version:3.1.9
- Rollup Version:2.70.2
- Operating System (or Browser): mac
- Node Version: 14.x
- Link to reproduction _(⚠️ read below)_: https://codesandbox.io/s/festive-northcutt-gbqnr4?file=/rollup.config.js

### Expected Behavior

success

### Actual Behavior

<img width="775" alt="image" src="https://user-images.githubusercontent.com/32830366/168551411-737fd28a-df13-41ba-8b51-21f4d7e5d043.png">

### Additional Information

how can I do

**Comment by shellscape** [comment]
Thanks for the issue. Unfortunately the issues here aren't for support. If you have an actionable bug report, rather than a "how to" request, please edit your issue.

**Comment by zjjjjjjjjjjd** [comment]
> Thanks for the issue. Unfortunately the issues here aren't for support. If you have an actionable bug report, rather than a "how to" request, please edit your issue.

ok, I think this is bug
