### ISSUE TITLE
commonjs plugin add extra query to chunk facadeModuleId in renderChunk hook without removing

### ISSUE THREAD

**Issue by huozhi** [rollup/plugins#1195]
- Rollup Plugin Name: `@rollup/plugin-commonjs` 
- Rollup Plugin Version: 22.0.0
- Rollup Version: 2.74.1
- Operating System (or Browser): macOS 12.0.1
- Node Version: v14.19.1
- Link to reproduction _(⚠️ read below)_: https://github.com/beeebox/rollup-missing-shebang-repro

### Expected Behavior

The input ts file with shebang will be preserved

### Actual Behavior

The input ts file with shebang is omitted

### Additional Information

The reproduction is using ts plugin, commonjs plugin and preserve shebang plugin (non official one), and when bumping commonjs plugin to v0.22, it will break the shebang preseving logic. I digged a little bit deep found that the `facadeModuleId` in `renderChunk` hook of shebang plugin is always having a `?commonjs-entry` query. It works well when I downgrade commonjs plugin to v0.21

**Comment by lukastaegert** [comment]
I fear the shebang plugin will need to be adjusted as it relies on the brittle assumption that an entry module will automatically become the facade module of a chunk while it has always been possible that another plugin injects a proxy module, just like the commonjs plugin needs to do it now. See https://github.com/rollup/plugins/issues/1169#issuecomment-1111753670 for a possible solution and more detailed reasoning.
