### ISSUE TITLE
use external

### ISSUE THREAD

**Issue by guaijie** [rollup/plugins#12]
_This issue was transferred from rollup-plugin-alias, which lacked an issue template_

---

![image](https://user-images.githubusercontent.com/30885718/67730239-6962cb80-fa2f-11e9-943e-d34ed13e8b3b.png)

expected:
```
import a from "../../src/utils/a"
```
actual:
```
import a from "win-plus/src/uitls/a
```

**Comment by shellscape** [comment]
Closed by #34
