### ISSUE TITLE
minify output html

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/plugins#120]
- Rollup Plugin Name: @rollup/plugin-html
- Rollup Plugin Version: 0.1.0

### Feature Use Case
Minified HTML makes for less bytes sent over the write.

### Feature Proposal
Add a configuration option to allow minifying the HTML output, [html-minifier](https://www.npmjs.com/package/html-minifier) is a good choice.

Alternative can be documenting how to implement your own minification like here: https://github.com/styleguidist/mini-html-webpack-plugin#html-minification but that's less convenient in my opinion.

**Comment by shellscape** [comment]
I'd like to know more about the scenario in which you're using the plugin. On the surface it seems like any gain here would be negligible, and wouldn't justify the added complexity. The primary use-case for the `html` plugin right now is a development environment, and it wouldn't make a whole lot of sense to minify for that.

**Comment by LarsDenBakker** [comment]
When you're building a modern webpapp you don't need all the complexities of webpack to handle legacy module syntaxes, rollup is a much more developer friendly tool which we generally recommend to developers. 

You can definitely use it during development, but you can use the same for deploying your application to production.

I think generally it's a good practice to minify your index.html, if people are inlining CSS or have a prerendered HTML it can add up quite a bit. It could be in a separate plugin if you'd like to keep the `html` plugin minimal.

**Comment by shellscape** [comment]
I honestly hadn't considered that this would be used to deploy html files. That's interesting. I'd like to look into a new plugin for minifying html. Let's enumerate the various tools that can handle it and go from there.

**Comment by shellscape** [comment]
This looks promising https://github.com/DanielRuf/html-minifier-terser.

Seeing this https://github.com/gucong3000/postcss-html also piques my interest. I have a few projects leveraging PostCSS and an HTML syntax for it is fascinating, and might allow to me construct an HTML minifier on par with html-minifier.

**Comment by LarsDenBakker** [comment]
I'm using https://github.com/DanielRuf/html-minifier-terser right now as well, and it's used by [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) as well.

**Comment by shellscape** [comment]
After letting this marinate for a while, I think the right course of action would be to write this as a separate plugin, similar to how there's a separate terser plugin for minifying script. html-webpack-plugin has long been known as the "kitchen sink" in terms of a plugin, trying to pack every feasible feature into the plugin. That's caused them a lot of headache in the past and the plugin isn't very nimble in terms of maintenance. Our html plugin is more based off of mini-html-webpack-plugin and keeping things small.

A plugin to leverage html-minifier-terser could be written relatively easily to handle assets which match https://github.com/rollup/plugins/blob/70780a0e903f7d325e5e95360c9249b4f6edaaf8/packages/html/lib/index.js#L106-L111 and you'd get the benefit of that happening in the build pipeline. Stacking plugins here is preferable to adding a hefty dependency to the html plugin I think. If you'd like to collab on adding a new plugin to the repo, I wouldn't be opposed to it and happy to add you as a maintainer.

**Comment by ruddenchaux** [comment]
Hi, I used `@rollup/plugin-html` with `rollup-plugin-html-minifier` ([html-minifier](https://www.npmjs.com/package/html-minifier) plugin wrapper) and work well. See the https://github.com/juliendargelos/rollup-plugin-html-minifier/issues/5#issuecomment-863763901
