### ISSUE TITLE
How to inline core-js code into the bundle.js instead of generating an import/require

### ISSUE THREAD

**Issue by roadupcc** [rollup/plugins#1202]
I want to get a complete code that can be executed in the browser without loading some dependencies.
Like WebPack.

![image](https://user-images.githubusercontent.com/18000037/173038568-b9784ca0-4926-41d2-b209-770caeb92635.png)

Hey there! If you need help or tech support then this is not the place to
ask. Please head to the [Rollup Discord](https://is.gd/rollup_chat)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

If you arrived here because you think Rollup's documentation is unclear,
insufficient or wrong, please consider creating an issue for the documentation
instead.

**Comment by roadupcc** [comment]
@shellscape 
Why close my issue without any reply ?

**Comment by shellscape** [comment]
> 
>   🚨 Your issue will be CLOSED if:
>      - This template is removed
>      - Parts of this template are removed
> 
>   👉🏽 Need help or tech support? Please don't open an issue!
>   Head to https://is.gd/rollup_chat or https://stackoverflow.com/questions/tagged/rollupjs

Ignore issue templates at your own peril.
