### ISSUE TITLE
[@rollup/plugin-inject] Support .vue files

### ISSUE THREAD

**Issue by last-partizan** [rollup/plugins#1216]
- Rollup Plugin Name: @rollup/plugin-inject
- Rollup Plugin Version: 4.0.4

### Feature Use Case
Please, add support for injecting imports into vue <script> tags.

### Feature Proposal
It should work the same as with normal js files.

Right now it says:

```
[vite] warning: rollup-plugin-inject: failed to parse /app/View.vue. Consider restricting the plugin to particular files via options.include
```

**Comment by shellscape** [comment]
That would be the job of a vue file parser to transform the file into a module that inject can operate on. The vite warning is correct, please consider asking vite how to accomplish what you're attempting.

**Comment by last-partizan** [comment]
Turns out it was already supported, but `vue()` plugin should be before `inject()`.

Thanks for great work!
