### ISSUE TITLE
[@rollup/plugin-run] HTTP server not stopped when rollup.config.js is updated

### ISSUE THREAD

**Issue by aminnairi** [rollup/plugins#1217]
- Rollup Plugin Name: @rollup/plugin-run
- Rollup Plugin Version:2.1.0
- Rollup Version: 2.75.0
- Operating System (or Browser): Arch Linux
- Node Version: 18.3.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@amin_nairi/PlayfulHappyJavascript#rollup.config.js

### Expected Behavior

Plugin should stop the server on new bundles.

### Actual Behavior

The server is still listening even though the rollup configuration has been changed and reloaded the bundle.

### Additional Information

None.

**Comment by shellscape** [comment]
What you're expecting isn't a function of the `run` plugin. The plugin simply runs the bundled code after a build, it doesn't monitor the process or manipulate the process. If that's a feature you would like to see, I would suggest opening a new issue to discuss that feature, or submitting a pull request for that.
