### ISSUE TITLE
[@rollup/plugin-multi-entry] Multiple outputs

### ISSUE THREAD

**Issue by DalderupMaurice** [rollup/plugins#1220]
- Rollup Plugin Name: @rollup/plugin-multi-entry
- Rollup Plugin Version: latest

### Expected Behavior / Situation
Defining multiple inputs result in multiple outputs

### Actual Behavior / Situation
Defining multiple inputs result in 1 file "multi-entry"

### Modification Proposal
I'd like to have multiple output files.

I'm building web-components and would like to have a separate output file for each input file.
Having 1 output file would mean that if I'd like to use 1 web component from a big component library, I would have to import ALL of them through this 1 multi-entry file

**Comment by bckthomas** [comment]
Hi @DalderupMaurice 
Did you find a way to output multiple files ? I would like to do the same as you wanted
Thanks

**Comment by DalderupMaurice** [comment]
> Hi @DalderupMaurice Did you find a way to output multiple files ? I would like to do the same as you wanted Thanks

You can simply have multiple input/ouputs in your array.

I ended up making something like this:

```
import merge from 'deepmerge';

import baseConfig from '../../rollup.config.js';

const addConfig = componentName => ({
  ...merge(baseConfig, {
    input: `./src/${componentName}/${componentName}.ts`,
    output: {
      file: `../../dist/${componentName}.js`,
      format: 'esm',
    },
  }),
});

export default [
  addConfig('x'),
  addConfig('y'),
  addConfig('z')
];
```

Where the base config is:
```
export default {
  external: [
    './xxx.js'
  ],
  preserveEntrySignatures: 'strict',
  plugins: [
    // Enable TS
    typescript(),
    // Resolve bare module specifiers to relative paths
    resolve(),
    // Minify HTML Template literals
    minifyHTML(),
    // Minify JS
    terser({
      ecma: 2021,
      module: true,
      warnings: true,
    }),
    // Support Image imports
    image(),
    // Output summary
    summary(),
  ],
  onwarn(warning) {
    if (warning.code !== 'THIS_IS_UNDEFINED') {
      // eslint-disable-next-line no-console
      console.error(`(!) ${warning.message}`);
    }
  },
};
```
