### ISSUE TITLE
rollup fails when importing a package in node_modules whose main field is a ts file

### ISSUE THREAD

**Issue by lcwlucky** [rollup/plugins#1223]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 
- Rollup Version: 8.3.3
- Operating System (or Browser): macOS
- Node Version: 14.19.0

### Expected Behavior
rollup can bundle ts files in node_modules normally

### Actual Behavior
The bundle failed with the following error message

![image](https://user-images.githubusercontent.com/39229436/178694784-db82db78-8a82-464d-90f3-9eaf44ea770d.png)

### Additional Information
my entry file
```js
// src/index.ts
import isArray from '@test/isarray';

console.log(isArray([]));
```

@test/isarray
```js
// index.ts
export default (o: any) => Array.isArray(o);
```

my rollup config
```js
const config: RollupOptions = {
    input: 'src/index.ts',
    output: '
      file: 'lib/bundle.js',
      format: 'cjs',
      exports: 'auto',
    },
    plugins: [
      json(),
      tsPlugin({
        typescript,
        tslib: require.resolve('tslib'),
        compilerOptions,
      }),
      nodeResolve(),
      commonjs(),
    ],
  };
```

When I add these codes in `@rollup/plugin-typescript/dist/index.js`, I can bundle successfully

![image](https://user-images.githubusercontent.com/39229436/178695332-2a1a2a03-a319-4755-a05b-af74d0f908dd.png)

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
