### ISSUE TITLE
@rollup/plugin-typescript does not resolve modules that use conditional exports when moduleResolution is set to node16

### ISSUE THREAD

**Issue by apottere** [rollup/plugins#1224]
- Rollup Plugin Name: `typescript`
- Rollup Plugin Version: `8.3.3`
- Rollup Version: `2.77.0`
- Operating System (or Browser): MacOS 12.4 (21F79)
- Node Version: `16.14.0`
- Link to reproduction _(⚠️ read below)_: https://github.com/apottere/rollup-typescript-reproduction

### Expected Behavior
Both `tsc` and `rollup -c` successfully find typescript declarations.

### Actual Behavior
`tsc` compiles successfully, but `rollup -c` does not - it fails to find the type declarations for the `dependency` dependency.

### Additional Information

The `package.json` in the included dependency uses [Conditional Exports](https://nodejs.org/api/packages.html#conditional-exports) to specify the location of type declaration files for the module: https://github.com/apottere/rollup-typescript-reproduction/blob/main/dependency/package.json#L4-L10

In the main package, `tsconfig.compilerOptions.moduleResolution` is set to `node16`: https://github.com/apottere/rollup-typescript-reproduction/blob/main/tsconfig.json#L9

This is correct AFAICT according to the [Typescript 4.7 release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing), and `tsc` can find the declarations and compile the script just fine.  For some reason `rollup -c` cannot, and throws the following error:
```
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2307: Cannot find module 'dependency' or its corresponding type declarations.
src/index.ts (1:19)
```

I did a little digging in the module resolution code in the rollup plugin, and it seems like adding `"main": "./build/types/",` to the dependency's `package.json` allows rollup to successfully build the bundle, but that's obviously not a great solution.  I wasn't able to figure out anything more than that though.

**Comment by apottere** [comment]
Note that this could be caused by `@rollup/plugin-node-resolve` as well.

**Comment by oxc** [comment]
I don't think this problem is related to conditional exports. If I change the package.json in the provided demo to contain the following exports property, I get the same error:
```
      "exports": {
          ".": "./build/esm/index.js"
      }
```

I'm experiencing a similar (or the same?) problem in my project. `tsc` compiles, but `rollup -c` does not.

I've added some console logs to `createModuleResolver` (in 'node_modules/@rollup/plugin-typescript/dist/index.js', see below) and the module in question always resolves to undefined, of course. 
This leads me to believe that the problem is in @rollup/plugin-typescript, not @rollup/plugin-node-resolve.

It seems to finds the package.json, but does not seem to be able to use the information to resolve the location of the type information. I've tried with `typescript@4.8.2`.

```js
 69 function createModuleResolver(ts, host) {
 70     const compilerOptions = host.getCompilationSettings();
 71     const cache = ts.createModuleResolutionCache(process.cwd(), host.getCanonicalFileName, compilerOptions);
 72     const moduleHost = Object.assign(Object.assign({}, ts.sys), host);
 73     return (moduleName, containingFile) => {
 74         const resolved = ts.nodeModuleNameResolver(moduleName, containingFile, compilerOptions, moduleHost, cache);
 75         if (moduleName.startsWith('dependency')) {
 76             console.log({moduleName, containingFile, resolved});
 77         }
 78         return resolved.resolvedModule;
 79     };
 80 }
```

**Comment by apottere** [comment]
That's definitely the same issue - the `exports` field in package.json is what defines [conditional exports](https://nodejs.org/api/packages.html#conditional-exports)

**Comment by oxc** [comment]
Ah, my bad, I thought it's only called Conditional Exports when it contains different exports for import/require.

**Comment by oxc** [comment]
Typescript also exports a function [resolveModuleName](https://github.com/microsoft/TypeScript/blob/c89f355a41b18c96eccb67dade04fce8c330068b/src/compiler/moduleNameResolver.ts#L962). It has the same signature as `nodeModuleNameResolver`. However, it only delegates to this function if moduleResolution is set to NodeJs. For Node16, NodeNext and Classic, it delegates to the respective resolver function.

If I replace (https://github.com/rollup/plugins/blob/0bbb4fde7ea52f29769d630269982524e73a7ee9/packages/typescript/src/moduleResolution.ts#L30)[ts.nodeModuleNameResolver()] with `ts.resolveModuleName()`, my project compiles as expected.

**Comment by oxc** [comment]
And here seems to be a PR that fixes this: https://github.com/rollup/plugins/pull/1194 :)

**Comment by qiu8310** [comment]
Is this fixed?  the problem seem still in there.

use the repo [apottere/rollup-typescript-reproduction](https://github.com/apottere/rollup-typescript-reproduction), change all dependences to latest and change tsconfig module property to `NodeNext`, problem still there
