### ISSUE TITLE
typescript: Undocumented outputToFilesystem option emits warning if not present

### ISSUE THREAD

**Issue by danopia** [rollup/plugins#1227]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.3.3

Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

When configured minimally (so, using defaults), the plugin is printing a warning:

```
(!) Plugin typescript: @rollup/plugin-typescript: outputToFilesystem option is defaulting to true.
```

This option is not documented on the README and the message doesn't have any further information. It's not clear what the options are to remove the warning.

### Your Proposal for Changes

1. The message could be more detailed: What did I do to introduce this warning? Is it related to a tsconfig.json option? Is there documentation it can link to, or a recommended action to take?
1. The option should be added to the other options in the plugin documentation. When is it needed? What are the reasons to use either false or true here? Are there other possible values? Since what version has this flag been soft-required?

### References

* #1099

**Comment by shellscape** [comment]
Happy to review a PR with the changes you'd like to see.

**Comment by ctretyak** [comment]
I think it should be reopened

**Comment by Bloodsucker** [comment]
This ticket should be reopen and I believe it is related to Typescript Project References.

**Comment by ericmasiello** [comment]
➕ Can this be reopened? This is still a problem

**Comment by shellscape** [comment]
people, please read the bot message. it will be reopened when the community steps up to help.

**Comment by vpalos** [comment]
As a workaround, if you don't really need incremental compiling for TypeScript, just set `incremental` to `false` in your `tsconfig.json`. This did the trick for me. Thanks @vividlearningsystems for pointing that out.

**Comment by CharlesStover** [comment]
For reference, here is the IntelliSense for the property:
```
When set to false, force non-cached files to always be emitted in the output directory.output If not set, will default to true with a warning.
```

**Comment by segevfiner** [comment]
Generally the behavior without this option set is technically correct despite the warning. The file outputted outside the bundle, the `tsbuildinfo` is not really part of the output, and as such, writing it using Rollup's `emitFile` doesn't matter and it can be written to the disk directly. But, this presents a warning to the user. On the other hand, enabling `outputToFilesystem` will write all output directly to the filesystem, bypassing Rollup, which is not desired. So maybe we just need an option to disable the warning, or otherwise not output it for files that are safe to write directly to the filesystem?

**Comment by NotYoojun** [comment]
Please reopen this issue. I really need incremental to be true for my project since it takes a really long time when building.

**Comment by xiaoxiyao** [comment]
So, how can this warning be removed? How should `outputToFilesystem` be set, and what is the difference?
