### ISSUE TITLE
[@rollup/plugin-typescript] tsconfig declarationDir is ignored when using single file output

### ISSUE THREAD

**Issue by CarrotB** [rollup/plugins#1230]
- Rollup Plugin Name: plugin-typescript
- Rollup Plugin Version: 8.3.4
- Rollup Version: 2.77.2
- Operating System (or Browser): Windows
- Node Version: v14.19.1
- Link to reproduction _(⚠️ read below)_: https://replit.com/@BobCarrot/rollup-plugin-typescript-declarationDir-error

### Expected Behavior
Declarations generated at the specified location

### Actual Behavior
Declarations generated at the same directory as the output file.

### Additional Information
I'm using api-extractor to rollup d.ts files into a single one, so the declarations are output at a place that will be removed after 
 processing.
This works at version 8.3.1 with a problem that it generates file at relative location under output directory, that is when `declarationDir` is `types` and output.file is `dist/index.js`, declarations will be under `dist/types`. But after my collegue updated to 8.3.4 (by using ^8.3.1 in package.json), the behavior changes to that declarations generated at `dist/`, and the build progress breaks since api-extractor can't find the desired entry for d.ts rollup.

**Comment by dominikbulaj** [comment]
Also confirmed. 

In `tsconfig.json` I have: `"declaration": false` and in `rollup.config.js` I got 
```
    typescript({
      compilerOptions: { declaration: true, declarationDir: './types' }
    }),
 ```
 
 When rollup runs declaration file(s) are placed in the output directory and not specified (`'./types'`)

**Comment by himanshuchawla009** [comment]
+1

**Comment by shellscape** [comment]
@himanshuchawla009 please do not post "me too," "+1" type replies. They spam anyone who has notifications on for issues (e.g. all maintainers). Please use the reaction buttons on the original post in the issue instead.

**Comment by Alpha0723** [comment]
I got the same issue with 8.3.4.  Now I have to create new tsconfig.types.json with declaration config
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "./dist/types",
    "emitDeclarationOnly": true,
  }
then use tsc command to generate d.ts to specific folder.
It works but it's ugly. Hope it could be fixed asap.

**Comment by Basssiiie** [comment]
I got the issue as well. Reverting back to version 8.3.3 fixes the issue, so it seems it was introduced in the 8.3.4 release. The only change in that release is this; #1201, which may very well be the cause (also there's other people talking about problems there as well).

### Easiest temporary fix for now: revert back to 8.3.3 and pin this version in your package.json.

**Comment by IronGeek** [comment]
I'm also having this problem with the latest version. And I think I found the problem with the recently merged PR #1201. 
Please correct me if my analysis is wrong.

https://github.com/rollup/plugins/blob/0bbb4fde7ea52f29769d630269982524e73a7ee9/packages/typescript/src/index.ts#L141-L155

Asumming the `parsedOptions.options.declaration` is true and we're using single file output.
The `outputOptions.dir` will be `undefined`, and the `baseDir` will be set to the `parsedOptions.options.declarationDir` value or fallback to `parsedOptions.options.outDir` if its not set (line 141). 
And since `baseDir` is now defined, the code generation will not be skipped and output files will be generated (line 149).
This seems to a solid logic, however on line 153 the filename for the file being generated is normalized and make relative to the `baseDir`.

https://github.com/rollup/plugins/blob/0bbb4fde7ea52f29769d630269982524e73a7ee9/packages/typescript/src/index.ts#L153

So for example, if user set declarationDir to `types`, and `foo/bar.d.ts` is to be generated then:
the expected filename relative to the output will be `types/foo/bar.d.ts`
but the actual filename instead `foo/bar.d.ts` this is because:
```js
baseDir = '/some/absolute/path/to/output/types'
id = '/some/absolute/path/to/output/types/foo/bar.d.ts'
filename = relative(baseDir, id) => 'foo/bar.d.ts'
```
we can see, that whatever value the `declarationDir` holds will be useless in single file output since the final filename will always be made relative to the `declarationDir` itself.

**Comment by rpearce** [comment]
This appears to still be an issue as of the latest version, `v9.0.0`. Locking the version to `8.3.3` seems to be the only way to keep the original behavior working.

**Comment by rpearce** [comment]
I'm sticking with the old one at present. I don't believe I saw anything about this getting fixed...

**Comment by yangliguo7** [comment]
> Did this ever get fixed? Or still just sticking with old rollup version for now?

I use a a hack way to avoid error . use ts to generate .d.ts . use rollup to build ......

**Comment by deansimcox** [comment]
After some debugging, I've noticed that this issue comes up if you have a subfolder for the `dir` property.

E.g this is the config we had
```
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      exports: 'named',
      sourcemap: true,
    },
    {
      dir: 'build/esm',
      format: 'esm',
      exports: 'named',
      sourcemap: true,
      preserveModules: true,
      preserveModulesRoot: 'src',
    },
  ],
```

The error went away when I changed `build/esm` to just `build`

**Comment by soeasyjx** [comment]
Has this problem been solved yet

**Comment by cristian-eriomenco** [comment]
Can we re-open this? Its clearly not fixed and an outstanding issue.

**Comment by shellscape** [comment]
@cristian-eriomenco read this in its entirety and you'll have your answer: https://github.com/rollup/plugins/issues/1230#issuecomment-1413173834

**Comment by cristian-eriomenco** [comment]
> @cristian-eriomenco read this in its entirety and you'll have your answer: [#1230 (comment)](https://github.com/rollup/plugins/issues/1230#issuecomment-1413173834)

Understood. Not going to fix it. Thanks for clarification.

**Comment by shellscape** [comment]
I'm not sure how you managed to misunderstand the very clear language in the message that the bot posted. but good luck to you.

for onlookers and people who run across this issue in the future, we openly welcome community help to resolve this. the team of maintainers for roll-up is extremely small, and we are stretched extremely thin. we all have jobs and families.

**Comment by jeremiegermond** [comment]
Still not fixed yet ?

**Comment by eimenanacreado** [comment]
Having the same problem with the latest versions : @rollup/plugin-typescript: Path of Typescript compiler option 'declarationDir' must be located inside the same directory as the Rollup 'file' option.

I have back to those version and everything worked well :

"@rollup/plugin-commonjs": "^25.0.3",
"@rollup/plugin-json": "^6.1.0",
"@rollup/plugin-node-resolve": "^15.1.0",
"@rollup/plugin-terser": "^0.4.4",
"@rollup/plugin-typescript": "^11.1.2",

**Comment by steebtom** [comment]
Encountered the same error `RollupError: [plugin typescript] @rollup/plugin-typescript: Path of Typescript compiler option 'declarationDir' must be located inside the same directory as the Rollup 'file' option.`

**Fix:**
Just updated `"declarationDir": "types"` to `"declarationDir": "dist/types"` in tsconfig.json and this fixed it. Hope this helps someone.

**package.json**

`"@rollup/plugin-babel": "6.0.4",`
`"@rollup/plugin-commonjs": "28.0.3",`
`"@rollup/plugin-node-resolve": "16.0.1",`
`"@rollup/plugin-terser": "0.4.4",`
`"@rollup/plugin-typescript": "12.1.2",`
`"@types/react": "19.0.10",`
`"react": "19.0.0",`
`"react-dom": "19.0.0",`
`"rollup": "4.35.0",`
`"rollup-plugin-peer-deps-external": "2.2.4",`
`"rollup-plugin-postcss": "4.0.2",`
`"typescript": "5.8.2"`

**tsconfig.json**
`{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "jsx": "react",
    "declaration": true,
    "declarationDir": "dist/types",
    "outDir": "dist",
    "strict": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src"]
}`

**Comment by eakarpov** [comment]
12.* version still has the error (11.* is ok)

**Comment by RahulCh010** [comment]
> I found that there will be similar problems in the case of multi-file output
> 
> ```
> rollup.config.js
> 
>   output: [
>     {
>       dir: 'dist/cjs',
>       format: 'cjs'
>     },
>     {
>       dir: 'dist/es',
>       format: 'es'
>     },
>   ],
> ```
> 
> ```
> tsconfig.json
> 
>  compilerOptions: {
>     declaration: true,
>     declarationDir: "dist/types"
>   },
> ```
> 
> the error log
> 
> ```
> @rollup/plugin-typescript: Path of Typescript compiler option 'declarationDir' must be located inside Rollup 'dir' option.
> ```
> 
> Is this caused by the same problem?

Any idea how to resolve this for multi-file output? Even reverting to v11 didn't help for me

**Comment by ychavoya** [comment]
Hello! Regarding the multi-file output.

Checking the plugin's implementation, it looks like the `declarationDir` *must* be inside a directory controlled by rollup, in case a different plugin wants to do something with the declaration files. So having the types outside of an output dir (such as `dist/types` when the output is on `dist/cjs`), would not respect that. See [here](https://github.com/rollup/plugins/pull/217#issue-568520709):

> When generating declaration files, the outDir must be set and be pointed to Rollup's output dir (or some subfolder). This allows us to use Rollup's asset emit API, and other plugins can then intercept these assets to potentially bundle the declaration files later. 

However, there is a workaround, such as [this one found by zeakd](https://github.com/rollup/plugins/issues/61#issuecomment-597090769). Basically there are two different rollup configs: 

- In one, the typescript is compiled into `cjs` and the types are generated. This one uses the `dist` dir as output dir, but renames the index to be in a `cjs` subfolder. This allows the usage of `dist/types` as an output dir for the declaration files.
- In the other, the typescript is compiled into `es` but without emitting declaration files. This config is as usual. 

The main disadvantage of this approach is that now you have to maintain two configs, though you can probably have a common config object and spread the common configuration between them.

Here's an example I managed to make:

`rollup.config.js`
```js
const typescript = require("@rollup/plugin-typescript");

module.exports = [
  {
    input: "src/index.ts",
    output: {
      dir: "dist",
      entryFileNames: "cjs/index.js",
      format: "cjs",
    },
    plugins: [
      typescript({
        tsconfig: "./tsconfig.json",
        declaration: true,
        declarationDir: "dist/types",
      }),
    ],
  },
  {
    input: "src/index.ts",
    output: {
      dir: "dist/es",
      format: "es",
    },
    plugins: [
      typescript({
        tsconfig: "./tsconfig.json",
      }),
    ],
  },
];
```

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": true,
    "inlineSources": true,
  },
  "exclude": [
    "node_modules"
  ]
}
```

This provides the following result:

```
dist
├── cjs
│   └── index.js
├── es
│   └── index.js
└── types
    └── index.d.ts
```

Hope this helps!
