### ISSUE TITLE
[@rollup/plugin-eslint] There is a conflict between @rollup/plugin-typescript and @rollup/plugin-eslint

### ISSUE THREAD

**Issue by aiden271828** [rollup/plugins#1231]
- Rollup Plugin Name: @rollup/plugin-eslint
- Rollup Plugin Version: 8.0.2
- Rollup Version: 2.77.2
- Operating System (or Browser): Windows
- Node Version: 14.19.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@aiden271828/rollup?v=1

### Expected Behavior

Resolve the conflict between `@rollup/plugin-typescript` and `@rollup/plugin-eslint`

### Actual Behavior

`@rollup/plugin-eslint` uses the file compiled by `@rollup/plugin-typescript` for verification.

### Additional Information

According to my [example](https://replit.com/@aiden271828/rollup?v=1), there is no error when running `npm run eslint`, but there is an error when running `npx rollup -c`. The reason is that `@rollup/plugin-eslint` uses the file compiled by `@rollup/plugin-typescript` for verification.

I found a library to solve this problem. You can refer to it. https://www.npmjs.com/package/rollup-plugin-eslint2.

**Comment by shellscape** [comment]
Place the eslint plugin before the typescript plugin. This isn't an error with the eslint plugin, working as designed.

**Comment by aiden271828** [comment]
@shellscape `Place the eslint plugin before the typescript plugin.` What should I do with it ?
