### ISSUE TITLE
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by khteh** [rollup/plugins#1238]
`tsc --project tsconfig.build.json && npm run rollup`:
```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
../core/greetings.ts (7:11)
5: import url from 'url'
6: export class Greetings {
7:     public greetings(req: Request, res: Response, next: NextFunction) {
              ^
8:         var url_parts = url.parse(req.url, true);
9:         var query = url_parts.query;
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:12543:16)
    at Module.tryParse (/usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:12920:25)
    at Module.setSource (/usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:12825:24)
    at ModuleLoader.addModuleSource (/usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:22267:20)

npm ERR! Lifecycle script `rollup` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: webapi@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/webapi 
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: webapi@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/webapi 
```
- Rollup Plugin Name: @rollup/plugin-typescript, 
- Rollup Plugin Version: 8.3.3
- Rollup Version: rollup v2.70.1
- Operating System (or Browser): Ubuntu 22.04, Chrome
- Node Version: v18.7.0
- Link to reproduction _(⚠️ read below)_: https://github.com/khteh/Node.JSRestAPI

### Expected Behavior
No error.

### Actual Behavior
Error.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
