### ISSUE TITLE
Package name wrong in update suggestion

### ISSUE THREAD

**Issue by LukasBombach** [rollup/plugins#124]
- Rollup Plugin Name: `rollup-plugin-commonjs` / `@rollup/plugin-commonjs`
- Rollup Plugin Version: `rollup-plugin-commonjs@10.1.0`
- Rollup Version: `1.27.14`
- Operating System (or Browser): macOS 10.14.5
- Node Version: `12.12.0`

### How Do We Reproduce?

```bash
npm i rollup-plugin-commonjs
# or yarn add rollup-plugin-commonjs
```

will echo the following warning:

> `warning rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commons.`

The error is correct, but there is a typo. Instead of `@rollup/plugin-commonjs` it says `@rollup/plugin-commons`, missing the `j` at the end and the installation of `@rollup/plugin-commons` will fail

> `error An unexpected error occurred: "https://registry.yarnpkg.com/@rollup%2fplugin-commons: Not found".`

### Expected Behavior

Copying the package name from the warning and installing it should "just work"

### Actual Behavior

You will get an error telling you the package does not exist

**Comment by shellscape** [comment]
Thanks for letting us know, I've updated the message just now to be correct. The "J" key on my keyboard sometimes doesn't work very well and it's been acting up lately.

**Comment by LukasBombach** [comment]
No worries. Thank you so much! Rollup is super awesome, thank you for this amazing library!
