### ISSUE TITLE
GraphQL Plugin type not compatible with rollup 2.78.0+

### ISSUE THREAD

**Issue by art-boer** [rollup/plugins#1243]
- Rollup Plugin Name: @rollup/plugin-graphql
- Rollup Plugin Version: 1.1.0
- Rollup Version: 2.78.0
- Operating System (or Browser): Mac OS
- Node Version: v16.15.0
- Link to reproduction: https://stackblitz.com/edit/nuxt-starter-ohu5c6?file=nuxt.config.ts (hover the graphql plugin in the config)

### Expected Behavior
Compatible Plugin type

### Actual Behavior
Type 'Plugin' is not assignable to type 'PluginOption'.
  Type 'Plugin' is not assignable to type 'Plugin_2'.
    Types of property 'resolveId' are incompatible.

**Comment by liqueflies** [comment]
Same here.

**Comment by shellscape** [comment]
@liqueflies please do not comment with "me too" type replies. instead, use the reaction buttons to indicate support.

**Comment by liqueflies** [comment]
@shellscape 🙏 got-it you're right.
Sorry!

**Comment by leonheess** [comment]
This happens with all rollup plugins inside vite configs

**Comment by mbcombes** [comment]
Was there ever a solution to this or is this an error that should just be ignored as long as everything is working correctly?

**Comment by jorisw** [comment]
I believe your answer is here: https://github.com/vitejs/vite/issues/10081#issuecomment-1243472115
