### ISSUE TITLE
[@rollup/plugin-commonjs] Plugin `commonjs--resolver` is attempting to read `package.json` of `jsdom`

### ISSUE THREAD

**Issue by tommy-mitchell** [rollup/plugins#1247]
- Rollup Plugin Name: `@rollup/plugin-node-resolve`
- Rollup Plugin Version: `22.0.2`
- Rollup Version: `2.78.1`
- Operating System (or Browser): `Windows 10`
- Node Version: `17.4.0`
- Link to reproduction: [REPL.it](https://replit.com/@tommy-mitchell/rollup-plugin-repro-commonjs?v=1), [repo](https://github.com/tommy-mitchell/rollup-jsdom)

### Expected Behavior

The plugin should bundle `jsdom` when imported in a module.

### Actual Behavior

Exports in `jsdom` are named exports (e.g. for a class: `exports.JSDOM = JSDOM`). When importing and bundling through Rollup with `@rollup/plugin-commonjs`, the build fails because the plugin tries reading `jsdom/package.json`:

```
[!] (plugin commonjs--resolver) Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/jsdom/package.json (2:8)
1: {
2:   "name": "jsdom",
           ^
3:   "version": "20.0.0",
4:   "description": "A JavaScript implementation of many web standards",
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (~\node_modules\rollup\dist\shared\rollup.js:198:30)
    at Module.error (~\node_modules\rollup\dist\shared\rollup.js:12560:16)
    at Module.tryParse (~\node_modules\rollup\dist\shared\rollup.js:12937:25)
    at Module.setSource (~\node_modules\rollup\dist\shared\rollup.js:12842:24)
    at ModuleLoader.addModuleSource (~\node_modules\rollup\dist\shared\rollup.js:22284:20)
```

### Additional Information

This [StackOverflow question](https://stackoverflow.com/questions/72585998/rollup-plugin-rollup-plugin-commonjs-parsing-package-json-and-throwing-unexpe) shows a similar issue of reading a `package.json` file.

The reproduction has a control test case that shows Rollup compiles when `jsdom` is not resolved. In addition, the REPL.it link displays a slightly different error message than the one above; however, in both cases the plugin attempts to read `jsdom/package.json`.

For ease of access, the following sample code is a reduced example without the control case.

`index.js`:

```js
// import a class, exported as "exports.JSDOM = JSDOM"
import { JSDOM } from "jsdom";

// should output "<html><head></head><body><p>Hello, World!</p></body></html>"
JSDOM.fromFile("./index.html").then(doc => console.log(doc.serialize()));
```

`index.html`:

```html
<p>Hello, World!</p>
```

`rollup.config.ts`:

```js
import commonjs from "@rollup/plugin-commonjs";
import resolve from "@rollup/plugin-node-resolve";

export default {
    input: "src/index.js",
    output: {
        file: 'dist/index.mjs',
        format: 'es',
    },
    plugins: [
        commonjs(),
        resolve(),
    ],
};
```

**Comment by shellscape** [comment]
Have you tried to use another plugin to allow JSON to be imported?

**Comment by tommy-mitchell** [comment]
Yes, but it takes nearly 15 seconds and results in a huge bundle ([REPL.it](https://replit.com/@tommy-mitchell/rollup-plugin-repro-commonjs?v=2#rollup.config.js)). And as mentioned in the StackOverflow question, why would I need another plugin for this?

**Comment by shellscape** [comment]
Rollup only handles js files natively. Any other kind of import requires a plugin. If documentation doesn't explicitly say it supports a thing (like ESBuild explicitly states it supports JSON by default with a loader) it's best not to assume it does. If jsdom is importing JSON, you'll need a plugin to support it.

**Comment by tommy-mitchell** [comment]
Ah, turns out `jsdom` imports its `package.json` to [read its version number](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/resources/resource-loader.js#L6). Didn't realize it was, go figure. Closing.
