### ISSUE TITLE
@rollup/plugin-typescript  Incorrect DTS path

### ISSUE THREAD

**Issue by CroatiaParanoia** [rollup/plugins#1253]
- Rollup Plugin Name:  @Rollup/plugin-typescript
- Rollup Plugin Version: 8.4.0
- Rollup Version: 2.79.0
- Operating System (or Browser): macos
- Node Version: v16.16.0
- Link to reproduction _(⚠️ read below)_:

When I set the `declarationDir` value to `./types`, but the output path of the type file is still in `dist`

### Expected Behavior
Type files should be generated in `types`

### Actual Behavior
Type files are generated in `dist`

**Comment by CroatiaParanoia** [comment]
https://github.com/rollup/plugins/pull/1252

**Comment by danieleds** [comment]
As a temporary workaround, you can pin @rollup/plugin-typescript to v8.3.3

**Comment by CroatiaParanoia** [comment]
> 作为临时解决方法，您可以将@rollup/plugin-typescript 固定到v8.3.3

**Comment by CroatiaParanoia** [comment]
> As a temporary workaround, you can pin @rollup/plugin-typescript to v8.3.3

Thank you for your idea. I tried it, but it didn't work. now I plan to use tsc to build type files

**Comment by danieleds** [comment]
Can we reopen this issue? The plugin is still broken.

**Comment by CroatiaParanoia** [comment]
> Can we reopen this issue? The plugin is still broken.

Sorry, yes, I may have misoperated...

**Comment by daiyam** [comment]
I'm having the issue with either `8.5.0` or `9.0.2`. `8.3.3` is working as expected.

**Comment by susnux** [comment]
The workaround mentioned here does not work either:
https://github.com/rollup/plugins/tree/master/packages/typescript#declaration-output-with-outputfile

If using `.` then no declarations are generated at all.

**Comment by susnux** [comment]
@CroatiaParanoia BTW if you plan to do something like this:
```
/dist/main.js
/types/main.d.ts
/src/main.ts
```

Meaning the output types are not within the same base directory as the js output, than this is **not** possible.
This is not a typescript plugin issue but a rollup limitation, [see this comment](https://github.com/rollup/plugins/pull/1378#discussion_r1131770253).

**Comment by shellscape** [comment]
#1378 has been merged and should address this issue
