### ISSUE TITLE
rollup-pluginutils: update deprecation message

### ISSUE THREAD

**Issue by mindrones** [rollup/plugins#126]
At https://github.com/rollup/rollup-pluginutils we can still read:

```
We're moving this repository into the monorepo at rollup/plugin. Please stand by...
```

while most of the other `rollup-plugin-*` repos have a proper deprecation message. It would be nice to conform that repo too to help the reader (I tried opening a PR there but it's in read mode). Thanks!

**Comment by shellscape** [comment]
Thanks for letting us know. I'll try to update that soon.

**Comment by shellscape** [comment]
Done
