### ISSUE TITLE
browser: true ignored when plugin-node-resolve 14 is used with plugin-typescript

### ISSUE THREAD

**Issue by FranklinWhale** [rollup/plugins#1267]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: 14.1.0
- Rollup Version: 2.79.0
- Operating System (or Browser): Windows 10 Professional 21H2 19044.2006
- Node Version: 16.17.0
- Link to reproduction: https://replit.com/@FranklinWhale/NodeResolve14-TypeScript, https://replit.com/@FranklinWhale/NodeResolve13-TypeScript

### Expected Behavior
The `diff` returns no result

### Actual Behavior
In NodeResolve14-TypeScript, TS and JS output are not the same. The outputs are the same in NodeResolve13-TypeScript.

### Additional Information

This is probably caused by the use of `order: "post"` as part of #1245. Both plugin-typescript and [plugin-typescript2 require plugin-node-resolve be run before themselves](https://github.com/ezolenko/rollup-plugin-typescript2#rollupplugin-node-resolve).

**Comment by pedrotorchio** [comment]
This could finally explain the issues I'm having. +1

**Comment by FranklinWhale** [comment]
[rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2) has just released [a version](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.34.1) that works properly with plugin-node-resolve 14

**Comment by dkuhnert** [comment]
Same issue here. My workaround is to disable `@rollup/plugin-typescript`'s `resolveId` and add `.ts` to `@rollup/plugin-node-resolve` extensions:

```typescript
import typescriptPlugin from "@rollup/plugin-typescript";
import {nodeResolve as nodeResolvePlugin} from "@rollup/plugin-node-resolve";

const typescript = {
  ...typescriptPlugin(/* ... */),
  // do not resolve anything instead leave this to `@rollup/plugin-node-resolve`!
  // see also: https://github.com/rollup/plugins/issues/1267
  resolveId: undefined,
};
const nodeResolve = nodeResolvePlugin({
  extensions: [".mts", ".ts", ".cts", ".mjs", ".js", ".cjs", ".json", ".node"],
  mainFields: ["browser", "module", "jsnext:main", "main"],
});

// ...
```
