### ISSUE TITLE
moduleDirectories vs modulePaths

### ISSUE THREAD

**Issue by andrewbaxter** [rollup/plugins#1268]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The descriptions for the two are not meaningfully different, in addition the link to `NODE_PATH` doesn't work and (assuming I found the current documentation) says roughly the same thing as the other two.

I looked at the code and AFAICT `moduleDirectories` identifies stopping directories when trying to find the `package.json` for a specific json file (i.e. it stops going up looking for further directories at that point).  This surprises me because it seems to have nothing to do with the current description in the documentation, but somewhat explains why `/` is forbidden (it would also be helpful if the error message mentioned `/` explicitly since "name" does not always imply a single path segment).

Having read the code, I'd guess that if you specify `a/b/c` as a `modulePaths` element, `moduleDirectories` should include `c` for the same reason it by default includes `node_modules`.

**Comment by davidhellmann** [comment]
Same error here. 
My config looks like this:
```ts
...
nodeResolve({
  moduleDirectories: [path.resolve('./node_modules')],
}),
```

works until I update to the latest version.

**Comment by jorenbroekema** [comment]
Yeah this was quite confusing to me as well. Seems like I could just drop-in replace moduleDirectories with modulePaths, but is very unclear on what the difference is exactly and when to use what.

**Comment by jorenbroekema** [comment]
https://github.com/rollup/plugins/pull/1104#pullrequestreview-943374801 here's a bit more info, I believe it was completely missed in this PR that this change was a breaking change. Users of this plugin may have relied on moduleDirectories being paths with '/'s, I certainly did, so breaking that by throwing an error and forcing users to use the new option is definitely a breaking change.
