### ISSUE TITLE
define entries by function

### ISSUE THREAD

**Issue by hikaruna** [rollup/plugins#13]
_This issue was transferred from rollup-plugin-alias, which lacked an issue template_

---

# future idea

```javascript
      alias({
        entries: [
          (id) => `replaced_${id}`
        ]
      })
```

## expect

same work 

```javascript
      alias({
        entries: [
          { find: /^.*$/, replacement: $0 }
        ]
      })
```

**Comment by shellscape** [comment]
Thanks for the issue :beer: I'm afraid that we're going to need a better use-case to explain why this feature would be necessary or useful for other users.

**Comment by Acionyx** [comment]
Hi. You may check https://github.com/Acionyx/rollup-plugin-module-replacement, it provides such mechanism.

**Comment by hikaruna** [comment]
@Acionyx oh... It seems good. Thanks.
