### ISSUE TITLE
Browser Main Fields override Export Conditions

### ISSUE THREAD

**Issue by ryansolid** [rollup/plugins#1307]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: 13.3
- Rollup Version: 2.79.0
- Operating System (or Browser): MacOS
- Node Version: 16.16
- Link to reproduction _(⚠️ read below)_: https://github.com/solidjs/solid-start/issues/263

### Expected Behavior
When an export condition matches it doesn't use the "browser" main field to remap it just because "browser" was set.

### Actual Behavior
In our case it matches on "worker" and then gets upgraded to the "browser" version unexpectedly.

### Additional Information

https://github.com/solidjs/solid-start/issues/263 Lays out the issue. It is talking about Vite. And I will take it up with them as well but it seems like this behavior originated by decisions taken by rollup.

This issue isn't only unexpected but it makes things very difficult. We have 3 things trying to balance:

1. Server vs Browser runtimes are different for SolidJS
2. Cloudflare Worker environments are Server environments for us but most tools call them browser, understandably because of Service/Web Workers. That's ok we can control this with export conditions.
3. Browser mainfield support is necessary for legacy tooling support. But its existence causes the work we do to map workers to be undone.

All these seem unmoveable. But perhaps main field overriding export conditions is not.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
