### ISSUE TITLE
Bad paths to dist in @rollup/plugin-eslint@8.0.4

### ISSUE THREAD

**Issue by pvljz** [rollup/plugins#1319]
- Rollup Plugin Name: eslint
- Rollup Plugin Version: 8.0.4
- Rollup Version: -
- Operating System (or Browser): MacOS
- Node Version: 16.14.2
- Link to reproduction _(⚠️ read below)_:
Just install plugin: npm i @rollup/plugin-eslint@8.0.4
node_modules/@rollup/plugin-eslint/package.json contains filepaths which not exists in "/dist" folder.

### Expected Behavior
node_modules/@rollup/plugin-eslint/package.json contains:
  "main": "./dist/cjs/index.js",
  "module": "./dist/es/index.js",

### Actual Behavior
node_modules/@rollup/plugin-eslint/package.json contains:
  "main": "dist/index.js",
  "module": "dist/index.es.js",

**Comment by lukastaegert** [comment]
`@rollup/plugin-eslint@9.0.0` is the current version that should also fix this

**Comment by lukastaegert** [comment]
But I se what you mean, I will try to re-deploy the actual 8.0.2 as 8.0 5

**Comment by lukastaegert** [comment]
Done
