### ISSUE TITLE
[typescript]: Default export type not being picked up with module: "nodenext"

### ISSUE THREAD

**Issue by wight554** [rollup/plugins#1328]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: ^9.0.2
- Rollup Version: 2.78.1 (vite ^3.1.4)
- Operating System (or Browser): macOS 12.6
- Node Version: 16
- Link to reproduction _(⚠️ read below)_:

Steps: (will try to make link if needed):

1. Add these settings to tsconfig:
```
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
```
2. Import and use typescript plugin
3. See the error

### Expected Behavior

Typing should be picked-up

### Actual Behavior
```
This expression is not callable.
  Type 'typeof import("/Users/Volodymyr_Zhdanov/playground/blog-template/node_modules/@rollup/plugin-typescript/types/index")' has no call signatures.
  ```

### Additional Information
3 possible fixes:

1. Add named export for plugin
2. Use CJS styled export in typings: `export default function typescript` => `export = typescript`;
3. Use declaration merging to make default export namespace and function simultaneously, example here: https://github.com/fastify/fastify-cookie/pull/184

I've used this thin wrapper for fixing typings before, might be helpful: https://github.com/wight554/vite-plugin-typescript/blob/main/index.d.ts

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
