### ISSUE TITLE
[@rollup/plugin-node-resolve] does not include fonts that are imported from css file.

### ISSUE THREAD

**Issue by DamianPereira** [rollup/plugins#1330]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 15.0.1
- Rollup Version: 3.2.3
- Operating System (or Browser): Mac OS Monterey
- Node Version: 14.19.3
- Link to reproduction _(⚠️ read below)_: https://github.com/DamianPereira/rollup-typeface-repro

### Expected Behavior

Running `npx rollup -c` inside that repository should package font files for package typeface-roboto, which includes a css file which imports several font files. 

### Actual Behavior

The folder dist/node_modules/typeface-roboto only contains the css, converted to inline and moved into a js file. The font files are nowhere to be found.

### Additional Information

This might be related to https://github.com/rollup/rollup/issues/2872, as I think I'm trying to have postcss plugin handle the font file imports.

**Comment by hanifmhd** [comment]
any update on this?
