### ISSUE TITLE
Error: "[name] is not exported by [module]"

### ISSUE THREAD

**Issue by shezhangzhang** [rollup/plugins#1331]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/26793777/197749522-349a1637-55b1-4c7a-b24b-af5ca8fd31d1.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/26793777/197749015-6a949151-98ba-4b05-97c9-10814f572fa6.png">

But I can not find the `namedExports option` is this link: https://github.com/rollup/plugins/tree/master/packages/commonjs#custom-named-exports

- Rollup Plugin Name: commonjs
- Rollup Version: latest
- Operating System (or Browser): mac
- Node Version: 16
- Link to reproduction _(⚠️ read below)_:

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction, and please fill our template out properly, and we'll be happy to triage further.
