### ISSUE TITLE
Rollup ignores imported library "main" and fails to import TypeScript files when present

### ISSUE THREAD

**Issue by smallstepstoday** [rollup/plugins#1333]
- **Rollup Plugin Name:** TypeScript/Node-Resolve
- **Rollup Plugin Version:** Typescript 9.0.2/Node-Resolve 15.0.1
- **Rollup Version:** 3.2.5
- **Operating System (or Browser):** Not Specific
- **Node Version:** v18.0.2
- **Link to reproduction:** [https://replit.com/@smallstepstoday/rollup-import-issue-repro?v=1](https://replit.com/@smallstepstoday/rollup-import-issue-repro?v=1)

### Expected Behavior

One or both of the following:
- rollup should import starting with the package "main" entry.
- The TypeScript plugin should ignore TypeScript files that are "riding along" in an imported library and not imported via the "main" entry. Obviously if a package main is "index.ts", then it should process the files that are needed. Otherwise, they should not be processed.

### Actual Behavior

The build fails, producing output similar to the following:

```bash
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/@josephg/resolvable/index.ts (1:7)
1: export type Resolvable<T> = Promise<T> & {
          ^
2:   resolve: (t: T) => void,
3:   reject: (e: any) => void,
RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:206:30)
    at Module.error (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:13310:16)
    at Module.tryParse (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:13684:25)
    at Module.setSource (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:13594:24)
    at ModuleLoader.addModuleSource (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:22913:20)
```

### Additional Information

I was digging into the issue and found the following:

- The `@josephg/resolvable` correctly resolves to `".../node_modules/@josephg/resolvable/index.js"` on the first pass.
- It then goes through another pass through `resolveIdViaPlugins` with `".../node_modules/@josephg/resolvable/index.js"` as source. It is during this pass that it is switched to index.ts. Here is the call stack at the point where the switch is made:

```bash
nodeModuleNameResolverWorker (.../typescript@4.8.4/node_modules/typescript/lib/typescript.js:44034)
nodeModuleNameResolver (.../typescript@4.8.4/node_modules/typescript/lib/typescript.js:44006)
resolveModuleName (.../typescript@4.8.4/node_modules/typescript/lib/typescript.js:43733)
<anonymous> (.../@rollup+plugin-typescript@9.0.2.../node_modules/@rollup/plugin-typescript/dist/es/index.js:48)
resolveId (.../@rollup+plugin-typescript@9.0.2.../node_modules/@rollup/plugin-typescript/dist/es/index.js:803)
<anonymous> (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23664)
processTicksAndRejections (internal/process/task_queues:95)
Promise.then (Unknown Source:0)
runHook (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23659)
<anonymous> (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23565)
processTicksAndRejections (internal/process/task_queues:95)
Promise.then (Unknown Source:0)
hookFirst (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23562)
resolveIdViaPlugins (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:22541)
resolveId (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:22545)
ModuleLoader.resolveId (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:22795)
resolve (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23490)
handler (.../@rollup+plugin-node-resolve@15.0.1_rollup@3.2.3/node_modules/@rollup/plugin-node-resolve/dist/es/index.js:1235)
processTicksAndRejections (internal/process/task_queues:95)
```

Hopefully this helps identify the logic that results in making the switch. Thanks for all the hard work! This is such a great toolset.

Referred here by @lukastaegert. See [his response](https://github.com/rollup/rollup/issues/4695#issuecomment-1298039396) to this issue.

See `README.md` in repository

**Comment by hperrin** [comment]
Running into this same issue. It started with `@rollup/plugin-node-resolve` v14.0.0.

My error output:

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/@smui/common/src/internal/forwardEventsBuilder.ts (1:12)
1: import type { SvelteComponent } from 'svelte';
               ^
2: import {
3:   bubble,
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/hperrin/repos/quickdav/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/home/hperrin/repos/quickdav/node_modules/rollup/dist/shared/rollup.js:12560:16)
    at Module.tryParse (/home/hperrin/repos/quickdav/node_modules/rollup/dist/shared/rollup.js:12937:25)
    at Module.setSource (/home/hperrin/repos/quickdav/node_modules/rollup/dist/shared/rollup.js:12842:24)
    at ModuleLoader.addModuleSource (/home/hperrin/repos/quickdav/node_modules/rollup/dist/shared/rollup.js:22090:20)
```

Nothing is importing `@smui/common/src/internal/forwardEventsBuilder.ts`. It's not included in the `package.json`'s `export`. It is included in the source map for the built file though.

So it seems like Rollup is trying to add it as a source file, which apparently tries to parse the file and results in the error.

**Comment by hperrin** [comment]
My solution for now is to just stay on `13.3.0`.

**Comment by betabandido** [comment]
This issue also prevents using Rollup v3, as the current solution (downgrading node-resolve to v13) requires Rollup v2.

**Comment by hperrin** [comment]
Yeah, this is also blocking me from upgrading to Rollup 3.
