### ISSUE TITLE
[@rollup/plugin-terser] Increase performance by running in parallel workers

### ISSUE THREAD

**Issue by dasa** [rollup/plugins#1334]
- Rollup Plugin Name: @rollup/plugin-terser
- Rollup Plugin Version: 0.1.0

### Feature Use Case

This is missing compared to the `rollup-plugin-terser` [implementation](https://github.com/TrySound/rollup-plugin-terser/blob/master/rollup-plugin-terser.js). This was noted at: https://github.com/rollup/plugins/pull/1323#issuecomment-1285935612

I'm seeing a four minute slowdown as compared to using the `rollup-plugin-terser` plugin when building about 3,500 files.

### Feature Proposal

This would be automatic as it was in the `rollup-plugin-terser` plugin. `rollup-plugin-terser` relied on [jest-worker](https://github.com/facebook/jest/tree/main/packages/jest-worker), but maybe https://nodejs.org/api/worker_threads.html could now be used instead.

**Comment by tada5hi** [comment]
I will devote myself to that :v: :relaxed:

**Comment by tada5hi** [comment]
Sorry for the delay guys.
But i was busy working on a online- & federated-learning architecture at my University :sweat_smile: .

Besides that i "wasted" my time on [routup](https://github.com/tada5hi/routup)  lightweight and extendable http interface based routing framework (alternative to express) :grin: .
I would be very happy if you would try it out, leave feedback or contribute to it :heart: 

https://github.com/rollup/plugins/pull/1341

**Comment by tada5hi** [comment]
This issue should be solved soon and closed soon ✌️😊. Waiting fo shellscape to merge the pr.

**Comment by tada5hi** [comment]
i would not call it work, rather suggestions from @dasa.

**Comment by michaelfaith** [comment]
Fair enough.  I just meant it was still WIP and not simply waiting on merge.  Appreciate your work on it. 🍻
