### ISSUE TITLE
Image import not working in production

### ISSUE THREAD

**Issue by Zain-ul-din** [rollup/plugins#1336]
Hey, I'm trying to deploy my app on `Vercel`  and `Heroku` but I'm getting this error

![image](https://user-images.githubusercontent.com/78583049/200133427-c4555dc7-e1ea-4f00-bfd5-07fd602e7d95.png)

**Note! Image import is working perfectly on my local machine**

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
