### ISSUE TITLE
commonjs: don't emit modules with side effects - or warn about it

### ISSUE THREAD

**Issue by frehner** [rollup/plugins#1342]
- Rollup Plugin Name: commonjs & node-resolve 
- Rollup Plugin Version: commonjs: 23.0.2. node-resolve: 15.0.1

I looked around, and found https://github.com/rollup/plugins/issues/1177 that may be somewhat similar, but it doesn't seem to quite be the same thing. 

### Feature Use Case
When commonjs emits code, in some situations it creates a module that has side effects. This can be problematic for library authors who have the `sideEffects` field in package.json, as they then are required to figure out which emitted modules have side effects, track them down, and then add them to the `sideEffects` array. 

For more context, this issue was originally raised in the Vite repo here: https://github.com/vitejs/vite/issues/10866#issuecomment-1311283625 but was eventually found to be an issue with (probably?) the commonjs plugin. 

Here's a StackBlitz example of the emitted code that has a side effect:

https://stackblitz.com/edit/rollup-template-1kqybv?file=dist%2Fnode_modules%2Fuse-sync-external-store%2Fshim%2Fwith-selector.js,rollup.config.js

The file `dist/node_modules/@xstate/react/es/fsm.js` has two imports:

```js
import '../../../use-sync-external-store/shim/with-selector.js';
...
import { w as withSelector } from '../../../../_virtual/with-selector.js';
```

The first import must not be treeshaked/removed, as it has the side effect of making the second import work. However, as a library author, it was very difficult for me to find this out as the side effect doesn't exist in my library and was the result of a transformation of a transitive dep. 

### Feature Proposal
Is it possible to change the emitted code to be self contained and not side-effect-y? 

If not, is it somehow possible to notify the dev that modules with side effects were created, so that I could be aware of it and add it to my package.json's `sideEffect` array?

Thanks!

**Comment by Danji-ya** [comment]
I faced this problem too.

```js
import './isBuffer.js';
import { i as isBuffer$1 } from '../../_virtual/isBuffer.js';
```

**Comment by thipokch** [comment]
I'm having this issue too
