### ISSUE TITLE
Ability to bundle the output inline

### ISSUE THREAD

**Issue by andrei-inc** [rollup/plugins#1343]
- Rollup Plugin Name: @rollup/plugin-html 
- Rollup Plugin Version: [v1.0.1](https://github.com/rollup/plugins/commit/7a8eb25a4546e8f4ef0ba51a0420f220da3532b6)

### Feature Use Case
Figma plugin API, supports only html files, without modules or external modules, so placing everything in the html is one convenient option.

### Feature Proposal
I would have expected to have the ability to config the plugin to bundle the output inline in the html file.
I'm referring to scripts, styles, and html part to be inline in the file, instead of being modules, external links.

**Comment by shellscape** [comment]
you could use a postprocessing script with cheerio and fs to accomplish that. it's not something I'll likely add to the plugin unless there's a large demand for it.
