### ISSUE TITLE
vite HMR breaks with "@rollup/plugin-typescript"

### ISSUE THREAD

**Issue by WelcomeDev** [rollup/plugins#1347]
- Rollup Plugin Name: "**@rollup/plugin-typescript**"
- Rollup Plugin Version: **9.0.2**
- Rollup Version: **3.3.0** (same as used in vite)
- Node Version: **18.12.0**
- Link to reproduction: [Stackblitz](https://stackblitz.com/edit/vitejs-vite-phea3a?file=src%2FApp.tsx)

## The issue

Was setting up runtime validation for ReactTs project on `vite`. It kind of works... But HRM is broken. It's always "one reload before actual" (just try smth to change at sandbox). Figured out that adding typescript plugin breaks HRM (even without custom TS implementation). Any ideas how to fix this? 

I stumbled across all the internet to find a workaround. But no result for now

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction, use our full bug template, and we'll be happy to triage further.
