### ISSUE TITLE
Bug: type issue in ts@4.8+ with esm

### ISSUE THREAD

**Issue by Mister-Hope** [rollup/plugins#1348]
A lot of plugins are exporting esm version

In a recent change in ts4.8, this leaves to type failue. as typescript@4.8+ will assume users are importing a commonjs module.

Here is a example:

TS will report issues with:

```ts
import commonjs from "@rollup/plugin-commonjs";

commonjs()
```

Saying the expression is not callable.

That's because a cjs module will have it's module.exports on `default` key, so:

```ts
import commonjs from "@rollup/plugin-commonjs";

commonjs.default()
```

is fine to typescript, but it's not acually working (because we do have esm modules using `export default`)

This happens under

- esm package (with `type: module` in pacakge.json) and of course `target: ESxxx` in ts.config.json
-  together with `moduleResolution: NodeNext` is in ts.config.json

**Comment by Mister-Hope** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/33315834/202837137-f1909d6b-4d79-40d7-b420-b554e4bd93ee.png">

**Comment by Mister-Hope** [comment]
I belived this issue is releated to https://github.com/microsoft/TypeScript/issues/50690

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
