### ISSUE TITLE
Build hangs indefinitely after updating TypeScript to 4.9.3

### ISSUE THREAD

**Issue by romainmenke** [rollup/plugins#1349]
- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: `9.0.2`
- Rollup Version: `2.79.1` (but also happens in `3.x` because it isn't related to rollup itself)
- Operating System (or Browser): macos 
- Node Version: `16.x`
- Link to reproduction _(⚠️ read below)_: https://github.com/csstools/postcss-plugins/pull/714

### Expected Behavior

Build does not hang

### Actual Behavior

Build hangs

### Additional Information

https://github.com/microsoft/TypeScript/issues/51592

I've first updated an issue upstream at TypeScript because I am 99% sure that something changed when updating to `4.9.3`.

But there is a non-zero change that `@rollup/plugin-typescript` is using an API that subtly changed and is causing the issue.

Something that seemed harmless to change in TypeScript.

Cross linking here to so that you are aware of the issue.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by romainmenke** [comment]
> We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

yeah.... this is not helping anyone @shellscape 
This is a complex issue which happens in a large project.

I've made it clear that I do not expect you to spend time on this and that I am simply cross linking because I was asked to by the maintainers of TypeScript.

Being aware of issues is important.

Having a template that isn't always possible to be followed doesn't help anyone in getting anything resolved.

-----

The reproduction is very simple though:
- clone https://github.com/csstools/postcss-plugins on a macos intel machine (I can't reproduce on M1/M2)
- checkout branch : `revert-713-typescript-4.8--intuitive-labradoodle-bd363b90e9`
- `npm ci`
- `npm run build`

This CAN NOT be reproduced out of context.

**Comment by romainmenke** [comment]
@shellscape can you re-open this issue?
The template was followed and there are reproduction steps in my last comment.

**Comment by shellscape** [comment]
>

**Comment by romainmenke** [comment]
I am not asking you to fix it.
I am asking you to acknowledge the issue.

**Comment by nicholas-ochoa** [comment]
@romainmenke I'm also having the same problem, though it happens intermittently and locally and with different packages within my monorepo (tiny packages, though). Do you by chance use pnpm?
