### ISSUE TITLE
[@rollup/plugin-typescript] breaks tree-shaking

### ISSUE THREAD

**Issue by ivands** [rollup/plugins#1351]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 9.0.2
- Rollup Version: 3.2.5
- Operating System (or Browser): node
- Node Version: v18.3.0

At the moment I'm trying to bundle the ```v5``` export from the ```uuid``` package.
The code is simple:
```js
import { v5 } from 'uuid'

export default () => {
  return v5()
}
```

Rollup won't bundle it automatically.
I have to include ```@rollup/plugin-node-resolve``` in order to bundle ```uuid```.
This works perfectly and only bundles the code required for the ```v5``` function.

My project also requires typescript support.
However as soon as you add the ```@rollup/plugin-typescript``` plugin, rollup will throw the following error: ```RollupError: "v5" is not exported```
I got the error to go away by adding the ```@rollup/plugin-commonjs``` plugin.
The end result is that combining these 3 plugins will break tree-shaking and bundle all the code inside the ```uuid``` package.

### Expected Behavior
I would expect the typescript plugin to only transform the typescript code in my project and not break treeshaking for other packages / code.

### Actual Behavior
Combining the following plugins will break treeshaking.
- @rollup/plugin-typescript
- @rollup/plugin-commonjs
- @rollup/plugin-node-resolve

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by ivands** [comment]
I cant get the repl working with rollup 3.

**Comment by ivands** [comment]
I tried to make a repl. But I can't get it to work:
https://replit.com/@ivands/rollup-tree-shaking-not-working?v=1
