### ISSUE TITLE
[@rollup/plugin-typescript] breaks tree-shaking

### ISSUE THREAD

**Issue by ivands** [rollup/plugins#1352]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 9.0.2
- Rollup Version: 3.2.5
- Operating System (or Browser): node
- Node Version: v18.3.0
- Link to reproduction: https://replit.com/@ivands/rollup-tree-shaking-not-working?v=1

At the moment I'm trying to bundle the ```v5``` export from the ```uuid``` package.
The code is simple:
```js
import { v5 } from 'uuid'

export default () => {
  return v5()
}
```

Rollup won't bundle it automatically.
I have to include ```@rollup/plugin-node-resolve``` in order to bundle ```uuid```.
This works perfectly and only bundles the code required for the ```v5``` function.

My project also requires typescript support.
However as soon as you add the ```@rollup/plugin-typescript``` plugin, rollup will throw the following error: ```RollupError: "v5" is not exported```
I got the error to go away by adding the ```@rollup/plugin-commonjs``` plugin.
The end result is that combining these 3 plugins will break tree-shaking and bundle all the code inside the ```uuid``` package.

### Expected Behavior
I would expect the typescript plugin to only transform the typescript code in my project and not break treeshaking for other packages / code.

### Actual Behavior
Combining the following plugins will break treeshaking.
- @rollup/plugin-typescript
- @rollup/plugin-commonjs
- @rollup/plugin-node-resolve

### Additional Information

The reproduction I made isn't working because I can't get the typescript plugin to work inside the REPL.
But I tried my best.

**Comment by shellscape** [comment]
Thanks for giving it a try. @lukastaegert we might be having repl trouble with v3

**Comment by lukastaegert** [comment]
Yes, the REPL is running Node 12, this will no longer work. We could also think about something like StackBlitz for our reproductions.

**Comment by MicMonen** [comment]
I have about the same problem, would be nice if there is a fix for this.
