### ISSUE TITLE
Update deprecated `magic-string`

### ISSUE THREAD

**Issue by rtritto** [rollup/plugins#1365]
Lowest versions of `magic-string` 0.27.0 dependency use the deprecated `sourcemap-codec` dependency (should be replaced with `@jridgewell/sourcemap-codec`).
`magic-string` dependency needs to be updated in:
- `@rollup/plugin-commonjs`
- `@rollup/plugin-dynamic-import-vars`
- `@rollup/plugin-inject`
- `@rollup/plugin-replace`
- `@rollup/plugin-strip`

### Steps to reproduce
- `yarn init -y`
- `yarn set version canary`
- `yarn add @rollup/plugin-replace`

### Expected Behavior
No warning log

### Actual Behavior
```console
➤ YN0000: ┌ Resolution step
➤ YN0061: │ sourcemap-codec@npm:1.4.8 is deprecated: Please use @jridgewell/sourcemap-codec instead
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings
```

**Comment by marvin-j97** [comment]
Also affects `@rollup/plugin-commonjs`:

```bash
@rollup/plugin-commonjs 23.0.3
└─┬ magic-string 0.26.7
  └── sourcemap-codec 1.4.8
```

**Comment by rtritto** [comment]
Updated with others dependencies.
