### ISSUE TITLE
Is there a way for @rollup/plugin-babel to support configuring another babel.config.js file

### ISSUE THREAD

**Issue by yoyo837** [rollup/plugins#1368]
- Rollup Plugin Name: @rollup/plugin-babel 
- Rollup Plugin Version: latest

### Feature Use Case
```js
const { babel } = require('@rollup/plugin-babel');

babel({
  configFile: 'xxx/xxx/babel.config.js'
})
```

**Comment by shellscape** [comment]
This isn't currently supported, but you could create a symlink to the src directory from whatever directory your config file lives in.
