### ISSUE TITLE
Doc for ignoreTryCatch incorrectly parsed by IDE

### ISSUE THREAD

**Issue by ClementValot** [rollup/plugins#1369]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: ^23.0.3

Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
The source of many a headache, the ignoreTryCatch option defaults to true according to the code 
![image](https://user-images.githubusercontent.com/65364056/206153435-e6b0c91a-d96a-45a4-a47e-3a7f832513f7.png)
But when hovering the options for commonjs, Webstorm (2022.3 here, but was the same in previous versions) indicates that it defaults to false 
![image](https://user-images.githubusercontent.com/65364056/206152625-61f81f6e-734b-49ba-b612-f7b5e0462edb.png)

Very unsure why Webstorm would incorrectly parse the documentation, is it a Webstorm bug, or an inconsistency somewhere in the declaration files?

**Comment by shellscape** [comment]
This is an issue with the types, as seen here. https://github.com/rollup/plugins/blob/fb11bd3a83bb63d9ac41e72be38064e4fa410e52/packages/commonjs/types/index.d.ts#L144

Please feel free to open a PR to correct

**Comment by ClementValot** [comment]
It didn't even occur to me that it would be a tag in the doc -_- 

Following PR changes the tag and corrects a few typos in the docs 
https://github.com/rollup/plugins/pull/1370

**Comment by ClementValot** [comment]
Docs clarified in the above PR
