### ISSUE TITLE
[@rollup/plugin-terser] Broken sourcemap in v0.2.0

### ISSUE THREAD

**Issue by ChoSeoHwan** [rollup/plugins#1371]
- Rollup Plugin Name: @rollup/plugin-terser
- Rollup Plugin Version: 0.2.0
- Rollup Version: 3.6.0
- Operating System (or Browser): window 10
- Node Version: 16.18.0
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior

Generate sourcemap normally

### Actual Behavior

Broken source map with Wraning.

- In v0.1.0
```
{"version":3,"file":"index.js","sources":["../src/errors/RollupBuilderError.ts","../src/errors/OutputError   ....   ACL,IAG0B,IAAzBH,EAAcN,OAAeM,EAAc,GAAKA,CAAa"}
```

- In v0.2.0
```
{"version":3,"file":"index.js","sources":[],"sourcesContent":[],"names":[],"mappings":""}
```

### Additional Information

- Rollup Warning message
```
(!) Broken sourcemap
https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect             
Plugins that transform code (such as "terser") should generate accompanying sourcemaps.
created dist in 3.2s    
```

- `rollup.config`
```
const { DEFAULT_EXTENSIONS } = require('@babel/core');
const resolve = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const babel = require('@rollup/plugin-babel');
const terser = require('@rollup/plugin-terser');
const cleaner = require('rollup-plugin-cleaner');
const peerDepsExternal = require('rollup-plugin-peer-deps-external');
const typescript = require('rollup-plugin-typescript2');
const ttypescript = require('ttypescript');

const typescriptOptions = {
    typescript: ttypescript,
    tsconfig: 'tsconfig.json'
};

const babelOptions = {
    extensions: [...DEFAULT_EXTENSIONS, '.ts'],
    babelHelpers: 'runtime'
};

const resolveOptions = {
    browser: true
};

module.exports = {
    input: 'src/index.ts',
    context: 'window',
    output: {
        dir: 'dist',
        format: 'cjs',
        sourcemap: true,
        exports: 'named',
        name: 'buildRollupOptions'
    },
    plugins: [
        cleaner({ targets: ['dist'] }),
        peerDepsExternal(),
        resolve(resolveOptions),
        typescript({
            ...typescriptOptions,
            tsconfigDefaults: {
                compilerOptions: {
                    outDir: 'dist',
                    plugins: [
                        { "transform": "typescript-transform-paths", "afterDeclarations": true }
                    ]
                }
            }
        }),
        commonjs(),
        babel(babelOptions),
        terser()
    ]
};
```

**Comment by tada5hi** [comment]
@ChoSeoHwan can you confirm that this is still an issue in `v0.2.1` ?

**Comment by brettz9** [comment]
It's still an issue for me in v0.2.1.

**Comment by maxlapides** [comment]
I am also experiencing this issue on `0.2.1`:

```
> rollup -c


src/index.ts → dist/index.min.js...
(!) Broken sourcemap
https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as "terser") should generate accompanying sourcemaps.
created dist/index.min.js in 493ms
```

**Comment by tada5hi** [comment]
@brettz9 @maxlapides this "feature" has never worked before, has it?

**Comment by maxlapides** [comment]
@tada5hi Well we definitely had sourcemaps before, but I'll be honest: I have never tested to see if they're actually working properly.

<img width="1044" alt="Screenshot 2022-12-21 at 12 09 40 PM" src="https://user-images.githubusercontent.com/1874682/208994305-88124622-ba6c-4430-83fb-fec308b22e89.png">

**Comment by tada5hi** [comment]
@maxlapides ok. I created a draft pull request to implement this feature in the meantime. 
Need to write some tests and than I think we are good to go ✌️😊

**Comment by ivands** [comment]
+1 I need sourcemaps for terser

**Comment by tada5hi** [comment]
@ivands I think it won't take that long anymore. Tests are added. 
I'm just waiting for @shellscape to give me feedback or accept the changes. 
Than the feature will be released.

**Comment by YamadaAoi** [comment]
wait for good news

**Comment by tada5hi** [comment]
`v0.3.0` is released. Can you confirm that the source map generation is working now ?

**Comment by maxlapides** [comment]
@tada5hi Thanks so much! Looks like `0.3.0` is perfect. The source map generation on `0.3.0` makes `0.1.0` :)

**Comment by tada5hi** [comment]
@maxlapides I'm happy if it works now. I'm always happy to help ✌️☺️

**Comment by tada5hi** [comment]
@shellscape can you close the issue ?
@ChoSeoHwan please reopen the issue if the source map generation is still not working for you :v:
