### ISSUE TITLE
Compiler Option moduleResolution is ignored and only dependend on module type

### ISSUE THREAD

**Issue by IIIMADDINIII** [rollup/plugins#1375]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 10.0.1
- Rollup Version: 3.7.4
- Operating System (or Browser): Windows 10 22H2
- Node Version: v18.12.0
- Link to reproduction _(⚠️ read below)_: https://github.com/IIIMADDINIII/rollup-typescript-reproduction

### Expected Behavior
I expected that the moduleResolution set in the tsconfig.json is respected and not always overwritten by setModuleResolutionKind. 
https://github.com/rollup/plugins/blob/7b6255774053ef170d9302cbbd8f99d5a58485ed/packages/typescript/src/options/tsconfig.ts#L106-L122

### Actual Behavior
In a Module with type: commonjs in the package.json it is not possible to have a valid bundle and also use NodeNext as the moduleResolution. 

### Additional Information

The Rollup Typescript Plugin always overrides the moduleResolution option based on the module option.

When in the tsconfig.json the module option is set to NodeNext the moduleResolution is set to NodeNext. Because in package.json the type is set to commonjs, typescript is compiling to commonjs. Rollup dose't understand commonjs out of the box, so the dependency module dose't get bundled. All of this is what i am expecting!! No issue so far.

To make the output of typescript compatible with rollup i change the module type to ESNext. This config can be compiled with Typescript without errors because typescript is using the moduleResolution of the tsconfig.json file (NodeNext)!!

In Rollup (with Typescript Plugin) this now dose't compile anymore. The reason is, that the typescript plugin is overriding the moduleResolution to node. So typescript can not find the declarations anymore. This is because i'm declaring the exports of the dependency with the exports field in the package.json which typescript ignores for types when it is set to node moduleResolution. This is due to the setModuleResolutionKind function in src/options/tsconfig.ts.

https://github.com/rollup/plugins/blob/7b6255774053ef170d9302cbbd8f99d5a58485ed/packages/typescript/src/options/tsconfig.ts#L106

I don't know why this function exists and is implemented like it is. When i change this function to not change the moduleResolution option, everything works as expected.

Maybe it is better to not override this option when ES Modules are specified? I think at least we should keep a way to manually set the moduleResolution option.

**Comment by unional** [comment]
Probably due to this, the `exports` field in dependency is not picked up thus I get error like this:

```
warning: @rollup/plugin-typescript TS2307: Cannot find module '@pats/just-sparky/stubs' or its corresponding type declarations.
```

The `@pats/just-sparky/stubs` is in the `exports` field of `@pats/just-sparky/package.json`:

```jsonc
{
  "exports": {
    "./stub": {
       "types": "./esm/stub/index.d.ts",
        "imports": "./esm/stub/index.js",
        "default": "./cjs/stub/index.js"
      }
    }
  }
}
```

**Comment by Polve** [comment]
Can you please give us more details on which modification make to the (rollup?) sources to overcome this problem that is blocking me? Thanks!
