### ISSUE TITLE
RollupError: "XhrIo" is not exported by "node_modules/@firebase/webchannel- wrapper/dist/index.js"

### ISSUE THREAD

**Issue by vdegenne** [rollup/plugins#1388]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: `15.0.1`
- Rollup Version: `3.8.1`
- Operating System (or Browser): Windows 11 (Chrome)
- Node Version: `16.15.0`
- Link to reproduction: https://stackblitz.com/edit/rollup-repro-vutdgr?file=package.json,rollup.config.js

### Actual Behavior

rollup ignores `@firebase/webchannel-wrapper` esm index (referenced in its `package.json`) and instead use the `main` value.

### Expected Behavior

The `"module"` value in `@firebase/webchannel-wrapper/package.json` (`dist/index.esm2017.js`) is expected to be used in the resolution process.

**Comment by omarfkuri** [comment]
I have the exact same issue. Any solutions?
