### ISSUE TITLE
[@rollup/plugin-dynamic-import-vars] Error: [!] (plugin rpt2) Error: Unexpected token (1:8)

### ISSUE THREAD

**Issue by CEbbinghaus** [rollup/plugins#1396]
- Rollup Plugin Name: @rollup/plugin-dynamic-import-vars
- Rollup Plugin Version: 2.0.2
- Rollup Version: 3.9.1
- Operating System (or Browser): Windows
- Node Version: 18.2
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-x1q3g6?file=package.json,rollup.config.js,tsconfig.json,src%2Fmain.ts

### Expected Behavior
It ignores the string interpolation within the function

### Actual Behavior
it crashes because its using string interpolation

**Comment by PranuPranav97** [comment]
I am having the same issue because of this.

**Comment by CEbbinghaus** [comment]
This has not yet been resolved and is still missing comments from anyone on the team.
