### ISSUE TITLE
Don't add file extensions automatically

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/plugins#14]
_This issue was transferred from rollup-plugin-alias, which lacked an issue template_

---

Reviewing the various PRs for rollup/rollup-plugin-alias#11, I was struck by how much extra work is created for the sake of allowing users to do this...

```js
alias({
  foo: 'bar'
})
```

...when they mean this:

```js
alias({
  foo: 'bar.js'
})
```

In my view there's no good reason to support that. Extension-less imports is a bad habit encouraged by Node's ill-conceived module resolution algorithm. Being explicit and obvious (rather than relying on scattered bits of magic) makes life easier for whichever developer inherits a project, and it would allow us to remove a lot of moving parts (including the `resolve` option).

Breaking, obviously, so would have to be a version 2. Thoughts?

**Comment by lukastaegert** [comment]
Another approach could be to use the `this.resolve` context function to resolve this. If someone were to use rollup-plugin-node-resolve, they get the resolution algorithm they know and love, otherwise just what is built-in. @Acionyx has been contracting me because he is working on a fork to do just that but I did not yet find time to have a look.

**Comment by CrashyBang** [comment]
@lukastaegert could you give a small example of using `this.resolve`?

Cheers.

**Comment by lukastaegert** [comment]
Here is a real-world example, though it is probably not a simple one: https://github.com/rollup/rollup-plugin-commonjs/blob/535e8117607731e1e8688be84c3aeb6e5c3b6fa5/src/resolve-id.js#L54

Here it is taking an import of the form `commonjs-proxy:./some-imports.js`, removes the prefix and uses `this.resolve` to find out what path the import of `./some-import.js` resolves to.

**Comment by shellscape** [comment]
#34 was merged and published a little while back. It now uses `this.resolve()` and should alleviate this issue. If it still pops up with the new version, please respond and we'll reopen.
