### ISSUE TITLE
@rollup/plugin-typescript does not emit declarations

### ISSUE THREAD

**Issue by Tomekmularczyk** [rollup/plugins#140]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 2.0.1
- Rollup Version: 1.27.5
- Operating System (or Browser): MacOS
- Node Version: 13.5.0

### How Do We Reproduce?
https://repl.it/repls/SkeletalNanoAlgorithm

### Expected Behavior
It should generate typings files.

So I don't know whether this is a bug or I'm requesting a feature, but when I develop a package with Rollup I want TypeScript declaration files to be outputed. I'm expecting this since this is a default TS behavior when I run `yarn tsc`.

### Actual Behavior

Only built files are outputed.

**Comment by shellscape** [comment]
Thanks for opening an issue and using the repl.it template. This one is already covered by #105. (found by searching the issues for "definition") We're very aware of the problem and that it's very inconvenient, and it's something we're actively working on. Please keep an eye on that issue and associated pull requests.
