### ISSUE TITLE
Rollup Plugin: CommonJS Shim

### ISSUE THREAD

**Issue by tada5hi** [rollup/plugins#1411]
Hey @shellscape,

i would realy like to add the following dynamic plugin to the collection:
https://github.com/unjs/unbuild/blob/main/src/builder/plugins/cjs.ts

The code could either be integrated as part of the `@rollup/plugin-commonjs` plugin or as simple standalone plugin.
This allows us to use `__filename` , `__dirname`,  ... also for esm output bundles. We had some troubles with that in the past, if you still remember :see_no_evil:  ^^
I already asked the creator @pi0 to move it here.
https://github.com/unjs/unbuild/issues/207 

Greetings
Peter

**Comment by tada5hi** [comment]
yep :see_no_evil: , sorry my bad. I will create a proposal for that. 
I think it is useful outside the commonjs plugin and can also used without it.

**Comment by pi0** [comment]
Update:

https://github.com/rollup/plugins/pull/1415

https://github.com/rollup/plugins/tree/master/packages/esm-shim

Thanks @tada5hi ❤️
