### ISSUE TITLE
[JSON] files are not bundled when imported using require

### ISSUE THREAD

**Issue by John98Zakaria** [rollup/plugins#1417]
- Rollup Plugin Name: Json
- Rollup Plugin Version: 6.0.0
- Rollup Version: 3.12.0
- Operating System (or Browser): NodeJs-18
- Node Version: 18
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-8mckzh

### Expected Behavior
When including a json using `require("somejson.json")` rollup should bundle it 

### Actual Behavior
Rollup doesn't bundle it and just copies `require("somejson.json")` to the bundled file.

### Additional Information
`import myJson from './someJson.json' assert { type: 'json' };` works fine, however, you don't have control over your dependencies.

**Comment by lukastaegert** [comment]
`require` is a CommonJS idiom and requires `@rollup/plugin-commonjs` to be parsed as such. Otherwise, Rollup treats it as a call to a global variable.

**Comment by John98Zakaria** [comment]
Thanks now I understand the issue more.
The library I wanted to rollup uses createRequire (didn't know that existed)
```
import { createRequire } from "node:module"

const require = createRequire(import.meta.url)

const json = require("./foo.json")

console.log(json)
```

Which makes this issue a duplicate of https://github.com/rollup/rollup/issues/4274
