### ISSUE TITLE
use syntheticNamedExports

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/plugins#142]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: any

### Feature Use Case
Commonjs exports can be very hard to detect. The new `syntheticNamedExports` feature will be very useful for this. See: https://github.com/rollup/rollup/pull/3295

### Feature Proposal
Implement `syntheticNamedExports` in the commonjs plugin.

If noone is picking this up already, I can take a look at it.

**Comment by lukastaegert** [comment]
> If noone is picking this up already

Not to my knowledge, would be really awesome if you picked this up! You can also add me as a reviewer if you want as I am really interested if the feature actually worked out how it should.

My hope is that as part of this, we can finally deprecated the infamous `namedExports` option, maybe show a warning message if it is used that it is ignored.

I *think*  it should not be too difficult: Just set the flag for every CJS module and run some tests if it actually works. But if there are issues, feel free to contact me (and possibly @manucorporat who originally implemented the Rollup feature).

**Comment by manucorporat** [comment]
Please! Give it a try, and ping me if something not working as expected. This will be awesome for CommonJS integration:

- dynamic named exports
- Exports is a proxy
- circular dependencies that add exports

I think we could leave the plugin as it is, so it keeps working in older versions of rollup, then is latest rollup missing exports fallback to the default export.

Or do we want to require the latest rollup version?

**Comment by LarsDenBakker** [comment]
I played around with this a bit, but it seems something isn't quite correct yet for exported synthetic named exports.

If I take your example, but change:
```js
import {foo, bar, other} from './dep.js'
console.log(foo, bar, other);
```

to: 

```js
export {foo, bar, other} from './dep.js'
```

the output becomes:

```js
const other = 'thing';
var dep = {
   foo: 42,
   bar: 'hello'
};

export { bar, foo, other };
```

so the synthetic named exports aren't actually taken from the object.

I put a repro here: https://github.com/LarsDenBakker/rollup-synthetic-named-exports

**Comment by manucorporat** [comment]
@LarsDenBakker i will take a look today

**Comment by LarsDenBakker** [comment]
Besides that, I did get a fairly large project with a large variety of commonjs modules built and run with a modified version of the commonjs plugin. So thats great news :)

**Comment by shellscape** [comment]
@LarsDenBakker would it be worthwhile for us to take a look at your fork?

**Comment by manucorporat** [comment]
WIP PR to fix this issue: 
https://github.com/rollup/rollup/pull/3319

**Comment by LarsDenBakker** [comment]
> @LarsDenBakker would it be worthwhile for us to take a look at your fork?

Of course, I will make it into a PR
