### ISSUE TITLE
@rollup/plugin-commonjs Exports inside `module.exports = { ... }` never transpile as named exports

### ISSUE THREAD

**Issue by liorJuice** [rollup/plugins#1421]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 24.0.1
- Rollup Version: 3.7.5
- Operating System (or Browser): tried on mac / chrome
- Node Version: 16.14.2
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-xwhsdh

### Expected Behavior
exports inside `module.exports = { ... }` should be added as named exports

### Actual Behavior
exports inside `module.exports = { ... }` only export as default

### Additional Information
i have tried a LOT of options combinations for both rollup and the plugin, and it seems no matter what, exports inside a `module.exports = { ... }` pattern will never transpile as named exports.

**Comment by AncientSwordRage** [comment]
I think I'm getting this too
