### ISSUE TITLE
@rollup/plugin-typescript to support exports fields (TS 4.7)

### ISSUE THREAD

**Issue by unional** [rollup/plugins#1435]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 9.0.2, 11.0.0

### Feature Use Case

Support TS package using `exports` field.

### Feature Proposal

Currently, `@rollup/plugin-typescript` seems to only support reading top-level `types` field, i.e.: 

```jsonc
{
  "name": "pkg-a",
  "types": "./cjs/index.d.ts",
  "typings": "./cjs/index.d.ts" // or
}
```

and not the `exports` field for ESM package:

```jsonc
{
  "name": "pkg-a",
  "type": "module",
  "exports": {
    ".": {
      "types": "./esm/index.d.ts",
      // ...
    },
    "./sub-path": {
      "types": "./esm/sub-path/index.d.ts",
      // ...
    }
}
```

That means in order for this to work without warning:

```ts
import { ... } from 'pkg-a/sub-path'
```

`pkg-a` needs to have the cjs redirect workaround:

```ts
// /sub-path/index.d.ts
export * from '../cjs/sub-path'
```

And it is reading the `cjs` variant instead of the `esm` variant even though rollup is reading the esm code (they CAN be different).

Currently, rollup emit this warning:

```sh
[plugin:typescript] @rollup/plugin-typescript TS2307: Cannot find module 'pkg-a/sub-path' or its corresponding type declarations.
```

if that redirect file is not available.

**Comment by susnux** [comment]
That is a typescript bug and fixed with 5.0 beta, you can try to use `tsc` and see the same error happening.
And you will need to use `moduleResolution: node16` (or `nodenext` or `bundler`).

What does work currently is having all types in the package root:
```json
"exports": {
  ".": {
      "import": "./dist/index.js",
      "types": "./dist/index.d.ts"
    },
    "./foo": {
      "import": "./dist/foo.js",
      "types": "./foo.d.ts"
    }
}
```

so it looks like this:
```
/dist/foo.js
/dist/index.js
/dist/index/.d.ts
/foo.d.ts
/package.json
```
