### ISSUE TITLE
Use of toSource causing scan failures

### ISSUE THREAD

**Issue by zjpersc** [rollup/plugins#1443]
- Rollup Plugin Name: plugin-yaml
- Rollup Plugin Version: 4.0.1

### Expected Behavior / Situation
Not to fail vulnerability scans due to lack of valid licensing

### Actual Behavior / Situation
Failing due to no valid license applied to the dependency

### Modification Proposal
I have put in a request with the author of toSource to apply the zlib license that he has stated he released the code under, which would remedy this issue. However, in the probable possibility that it isn't updated, is there another dependency or code that you could use instead. Otherwise, it could cause complications in our use of the plugin-yaml code.

**Comment by shellscape** [comment]
Thanks for opening an issue. Please feel free to fork `@rollup/plugin-yaml` to modify it to your org's needs for licensing. This isn't a change we're going to make at present, since it's an upstream issue.
