### ISSUE TITLE
@rollup/plugin-typescript noEmitOnError should default to true

### ISSUE THREAD

**Issue by gempain** [rollup/plugins#1444]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 11.0.0 and before

### Expected Behavior / Situation

[`noEmitOnError`](https://github.com/rollup/plugins/tree/master/packages/typescript#noemitonerror) should be true by default. It makes no sense to emit code when the Typescript build fails. It can lead to production code not working as expected.

### Actual Behavior / Situation

By default the value is [`false`](https://github.com/rollup/plugins/tree/master/packages/typescript#noemitonerror).

### Modification Proposal

Change the value from `false` to `true`.

**Comment by pimartin** [comment]
It looks like it was [introduced for the watch mode](https://github.com/rollup/plugins/pull/544).

Maybe a slightly more complex default could be used: `false` when in watch mode, `true` otherwise ?

**Comment by simlmx** [comment]
I agree with the previous comments: the default should be to error when building. But when watching it cannot crash the watch otherwise what's the point.

For me the plugin is unusable if it can not both *error on build* and *not crash on watch*.
