### ISSUE TITLE
Conflicting Documentations for @rollup/plugin-commonjs

### ISSUE THREAD

**Issue by nanometre** [rollup/plugins#1450]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 24.0.1

Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
There is conflicting documentation for the rollup/plugin-commonjs and rollup/plugin-babel. 

On the [official website documentation](https://rollupjs.org/tools/#rollup-plugin-commonjs), it is stated that the babel plugin should come before the commonjs plugin.

But on the [README.md](https://github.com/rollup/plugins/tree/master/packages/babel#using-with-rollupplugin-commonjs) for rollup/plugins-babel repository, it is stated that the rollup/plugin-commonjs must be placed before the babel plugin.

### Your Proposal for Changes
Confirm the correct order of plugins and make the necessary changes in the documentations.

**Comment by sunhaixin** [comment]
have the same question
