### ISSUE TITLE
The compatibility between ESM, tslib, and output.preserveModules

### ISSUE THREAD

**Issue by 8NAF** [rollup/plugins#1460]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 11.0.0
- Rollup Version: 3.19.1
- Operating System (or Browser): Windows 10 10.0.19045
- Node Version: 19.7.0
- Link to reproduction: https://stackblitz.com/edit/rollup-repro-prbaha

### Actual Behavior
I have installed `tslib` to support decorators, and my `rollup.config.ts` file looks like this:
```js
import typescriptPlugin from '@rollup/plugin-typescript'

/** @type import('rollup').RollupOptions */
export default {
    input: './src/main.ts',
    output: {
        dir: 'dist',
        format: 'es',
        preserveModules: true,
    },
    plugins: [typescriptPlugin()],
}
```
As far as I understand, the process of supporting decorators using this plugin involves the following steps:
- Find the `tslib.es6.js` file in `tslib`
- Copy it to the `dist` folder
- Import it (as named import)  into all the files in my project that use decorators \
(`import { __decorate } from '../node_modules/tslib/tslib.es6.js';`).

The issue here is that I compile my project to ESM format, and the `tslib.es6.js` file is imported as a named import, while Node treats it as CommonJS, leading to an error (Node does not allow a CommonJS file to be imported as a named import in an ESM file).

### Expected Behavior
Find a way for Node to recognize this file as an ESM, so that everything works properly.

I have found 3 ways to solve this issue:
1. Change the file extension to .mjs: \
`tslib.es6.js` → `tslib.es6.mjs`

2. Import as default import: \
`import { __decorate } from '../node_modules/tslib/tslib.es6.js';` → \
`import tslib from '../node_modules/tslib/tslib.es6.js';`

3. Directly import `tslib` without copying the `tslib.es6.js` file anymore: \
`import { __decorate } from '../node_modules/tslib/tslib.es6.js';` → \
`import { __decorate } from 'tslib';`

**Comment by tianyingchun** [comment]
keep

**Comment by yoyo837** [comment]
Same here.
