### ISSUE TITLE
@rollup/plugin-node-resolve breaks bundling if --perf flag is set to true

### ISSUE THREAD

**Issue by hjhopp** [rollup/plugins#1464]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 15.0.0
- Rollup Version: 3.1.0
- Operating System (or Browser): Windows 10
- Node Version: 16.19.0
- Link to reproduction _(⚠️ read below)_:

https://replit.com/@hjhopp/rollup-plugin-repro

### Expected Behavior

Node resolve plugin doesn't break bundling when --perf is set to true.

### Actual Behavior

Type error:

```
(plugin node-resolve) TypeError: func.apply is not a function
TypeError: func.apply is not a function
    at plugin.<computed> (/home/runner/rollup-plugin-repro/node_modules/rollup/dist/shared/rollup.js:12705:37)
    at /home/runner/rollup-plugin-repro/node_modules/rollup/dist/shared/rollup.js:23262:40
```

### Additional Information

I was able to resolve this issue by modifying rollup's `getPluginWithTimers` function:

```
function getPluginWithTimers(plugin, index) {
    for (const hook of TIMED_PLUGIN_HOOKS) {
        if (hook in plugin) {
            let timerLabel = `plugin ${index}`;
            if (plugin.name) {
                timerLabel += ` (${plugin.name})`;
            }
            timerLabel += ` - ${hook}`;
            const func = plugin[hook];
            plugin[hook] = function (...args) {
                timeStart(timerLabel, 4);
                const result = (typeof func === "function" ? func : func.handler).apply(this, args); // <-- Here is my modification
                timeEnd(timerLabel, 4);
                return result;
            };
        }
    }
    return plugin;
}
```

It appears that `func` returned by `plugin[hook]` (the "hook" is `resolveId`) here for node resolve is an object shaped like this:

` { order : "post", handler : function }`

I don't know if the rollup code should change, or node resolve plugin's code.

**Comment by lukastaegert** [comment]
That is indeed a bug in Rollup

**Comment by hjhopp** [comment]
Looks like this has already been resolved in a later version of Rollup. :) I'll close this!
