### ISSUE TITLE
Can't import '.ts' file from '.tsx' file

### ISSUE THREAD

**Issue by felixcatto** [rollup/plugins#1465]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 15.0.1
- Rollup Version: 3.20.2
- Operating System (or Browser): Ubuntu 20.04, Chrome 111
- Node Version: 18.14.1
- Link to reproduction: https://github.com/felixcatto/vite-test/tree/bug

### Expected Behavior

When i import '.ts' file from '.tsx' file, and specify '.js' extension, it should be imported.

### Actual Behavior

I get error

### Additional Information

ES modules want that we add file extensions to all files https://nodejs.org/api/esm.html#mandatory-file-extensions
But Typescript doesn't like '.ts', '.tsx', it want '.js', '.jsx', '.mjs', ...

![2023-03-26_11-38](https://user-images.githubusercontent.com/6022888/227763282-bde8be0c-dc76-410a-9177-4172ba9a53d8.png)

  
But if i import **utils.js**, when actual files have different extension i got following error

**index.tsx**
```javascript
import { x } from './utils.js';
```
 
**utils.ts**
```javascript
export const x = '';
```

![2023-03-26_11-41](https://user-images.githubusercontent.com/6022888/227763453-4ed5c655-4cfb-4d99-9ed3-aadd29f6d622.png)
  
 ```
index.tsx  'import'  utils.ts    # error
index.ts   'import'  utils.tsx   # error
index.js   'import'  utils.tsx   # error
index.ts   'import'  utils.ts    # works
index.tsx  'import'  utils.tsx   # works
```

In webpack i can define `resolveextensionalias`  https://webpack.js.org/configuration/resolve/#resolveextensionalias

In rollup nodeResolve  `extensions` option seems combines webpack `extensionalias` & `extensions` options. But only partially. It only works if all extensions matches, i.e. all files have '.tsx'

**Comment by meyfa** [comment]
I think this part may be to blame:

https://github.com/rollup/plugins/blob/e1bb4bdbee0203367c06baa1bcb9844d598d040d/packages/node-resolve/src/index.js#L149-L156

The loop will check the following:

* If the importer is a `.ts` file, then add `.ts` extension to the resolved paths.
* If the importer is a `.tsx` file, then add `.tsx` extension to the resolved paths.

The intended functionality according to the comment would be to add both `.ts` and `.tsx` in both cases.

**Comment by meyfa** [comment]
@felixcatto node-resolve v15.1.0 was just released with my fix (see #1498). Could you verify that this solves your issue?

**Comment by felixcatto** [comment]
@meyfa Yes, it solves first two cases from this list

```
index.tsx  'import'  utils.ts    # error => works now
index.ts   'import'  utils.tsx   # error => works now
index.js   'import'  utils.tsx   # error
index.ts   'import'  utils.ts    # works
index.tsx  'import'  utils.tsx   # works
```

But following scenario doesn't work (I also updated a repo at first post)

**index.js**

```js
import { x } from './utils.js';
console.log(x);
```

**utils.ts**

```js
export const x = 111
```

![2023-05-31_06-33](https://github.com/rollup/plugins/assets/6022888/a15f464f-a10d-4455-9ea9-ada1edef0309)

Of course  it is rare case, when someone want to import `.ts` file from `.js` file. So thanks for fix :wink:

**Comment by meyfa** [comment]
Oh sorry, I totally overlooked that case! And it seems that this works with ts-node out of the box as well, so perhaps Rollup should support it?

I personally think it's a bit unusual to import TS from a JS file.

**Comment by felixcatto** [comment]
Initially i wanted to say yes, but decided to look at Vite behaviour in this situation. And Vite also throws error, but it is quite popular bundler and seems people doesn't have such problems if it doesn't fixed yep. So i would say that it can be ignored.

![2023-05-31_17-42](https://github.com/rollup/plugins/assets/6022888/1c233515-7b42-4c65-8ab5-022f2869ce41)
