### ISSUE TITLE
[plugin-terser] types exported is not same as source

### ISSUE THREAD

**Issue by JounQin** [rollup/plugins#1474]
- Rollup Plugin Name:  terser
- Rollup Plugin Version: 3.20.2

### Expected Behavior / Situation

https://github.com/rollup/plugins/blob/e1bb4bdbee0203367c06baa1bcb9844d598d040d/packages/terser/src/type.ts#L1-L45

### Actual Behavior / Situation

https://github.com/rollup/plugins/blob/e1bb4bdbee0203367c06baa1bcb9844d598d040d/packages/terser/types/index.d.ts#L1-L10

### Modification Proposal

Align with source

**Comment by tada5hi** [comment]
Good catch 👍.
I will fix that.

Greetings 
Peter
