### ISSUE TITLE
[node-resolve] * in exports key can't correctly resolved

### ISSUE THREAD

**Issue by tjx666** [rollup/plugins#1476]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 15.0.2
- Rollup Version: 3.7.5
- Operating System (or Browser): MacOS 13.3 Ventura
- Node Version: 18.5.0
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-t8bmex

### Expected Behavior

`node packages/app/src/main.js` works fine:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/230207486-77d7e9fb-0fab-4d19-86cb-aafc635560e9.png">

Built by vite is also works, because vite use self vite:resolve plugin:

`pnpm -F app build:vite`:

![Uploading image.png…]()

Rollup should build without warnings.

### Actual Behavior

But rollup can't resolve:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/230207607-e8f24334-ba8c-4dba-817d-09bc0e2be42a.png">

### Additional Information

This issue is found when I test package.exports field:

```
{
  "name": "utils",
  "type": "module",
  "exports": {
    "./a/*/c": "./abc.js"
  }
}
```

**Comment by tjx666** [comment]
@lukastaegert can you help to look into this issue?

**Comment by robbiespeed** [comment]
it appears to be broken if anything comes after `*`, even this does not work:
```json
  "exports": {
    "./*.js": {
      "types": "./lib/*.d.ts",
      "import": "./lib/*.js"
    }
  }
```
