### ISSUE TITLE
`@rollup/plugin-typescript` failed to handle `.mts` files

### ISSUE THREAD

**Issue by trim21** [rollup/plugins#1480]
- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: `11.1.0`
- Rollup Version: `3.20.2`
- Operating System (or Browser):
- Node Version: 18
- Link to reproduction _(⚠️ read below)_:

https://github.com/trim21/rollup-ts-plugin-bug-mts

### Expected Behavior

should build

### Actual Behavior

rollup report error about TypeScritp syntax, `can-not-import.mts` is not handled by typescript plugin

**Comment by TrickyPi** [comment]
try using the following config in your repro, it works.
```ts
typescript({
      include: ['**/*.ts', '**/*.mts', '**/*.cts'],
      tsconfig: 'tsconfig.json',
}),
```
