### ISSUE TITLE
TypeScript Plugin fails at building when an import depends on a custom module declaration 

### ISSUE THREAD

**Issue by ericmorand** [rollup/plugins#1481]
- Rollup Plugin Name: typescript
- Rollup Plugin Version:  11.1.0
- Rollup Version: 3.20.2
- Operating System (or Browser): Ubuntu 20
- Node Version: 16.11.1
- Link to reproduction: https://github.com/ericmorand/rollup-plugin-typescript-test

### Expected Behavior

The TypeScript entry point of the project, `index.ts`, import a file named `index.twig`.

```ts
import * as Foo from "./index.twig";

console.log(Foo.render());
```

> index.twig
```twig
{{ "foo" }}
```

This file is _typed_ by the declaration file `types/globals.d.ts` that declares that `.twig` files are modules that expose a `render` function.

```ts
declare module "*.twig" {
    export const render: any;
}
```

When building the project with `tsc`, everything goes fine:

`tsc -p . --outDir dist`

This is the expected behavior of Rollup + the TypeScript plugin since they both depend on the same `tsconfig.json` file.

```json
{
  "include": [
    "index.ts",
    "./types/globals.d.ts"
  ]
}
```

### Actual Behavior

When building with Rollup + the typescript plugin, an error is emitted:

```sh
npx rollup -i index.ts -p '@rollup/plugin-typescript={"tsconfig": "./tsconfig.json"}'

index.ts → stdout...
console.log(undefined());
(!) Missing exports
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
index.ts
render is not exported by index.twig
1: import * as Foo from "./index.twig";
2: console.log(Foo.render());
                   ^
3: //# sourceMappingURL=index.js.map
```

### Additional Information

I hope that I'm not missing something obvious here.

**Comment by ericmorand** [comment]
> I hope that I'm not missing something obvious here.

Well, a few minutes after writing this, I understand my mistake. I have to also include a `twig` plugin.

Extremely sorry for the noise.

**Comment by shellscape** [comment]
No worries. That discovery will probably help someone
