### ISSUE TITLE
@rollup/plugin-terser hangs the process forever after completion when rollup is run in a worker thread

### ISSUE THREAD

**Issue by dumbmatter** [rollup/plugins#1482]
- Rollup Plugin Name: @rollup/plugin-terser
- Rollup Plugin Version: 0.4.0 and 0.4.1
- Rollup Version: 3.20.6 (or any other recent version)
- Operating System (or Browser): Ubuntu 20.04.06
- Node Version: v18.16.0
- Link to reproduction: https://github.com/dumbmatter/rollup-terser-worker-threads

### Expected Behavior

When the build completes, the process should terminate, even if rollup is being run inside a Node.js worker thread.

### Actual Behavior

When using @rollup/plugin-terser 0.4.x and running rollup inside a Node.js worker thread, the build does complete successfully, but the Node.js process never terminates.

Prior versions of @rollup/plugin-terser such as 0.3.0 did not have this problem, and running the same rollup build in the main process (rather than using a worker thread) also works fine even with @rollup/plugin-terser 0.4.x.

### Additional Information

This is very likely related to https://github.com/rollup/plugins/pull/1409 since that was the only PR merged between versions 0.3.0 and 0.4.0, and it's also related to worker threads.

**Comment by dasa** [comment]
This change in the repro code allows the main thread to exit:

```diff
diff --git a/tools/build-worker.js b/tools/build-worker.js
index 106f78b..40e654d 100644
--- a/tools/build-worker.js
+++ b/tools/build-worker.js
@@ -6,6 +6,7 @@ const promise = new Promise(resolve => {
     );
 
     worker.on("message", () => {
+        worker.unref(); // or worker.terminate();
         resolve();
     });
 });
```

**Comment by dumbmatter** [comment]
Interesting, thanks! Do you know why that's required with @rollup/plugin-terser v0.4, but not with v0.3? Like is it a bug in v0.4, or was I somehow only getting lucky that it worked in v0.3 in the first place? I've used worker threads a few times and hadn't previously come across this issue, so it feels a little strange if sometimes I need to unref to get the process to end, but other times I don't.

**Comment by dasa** [comment]
> Do you know why that's required with @rollup/plugin-terser v0.4, but not with v0.3?

Yes, it's not returning early here:
https://github.com/rollup/plugins/blob/83197203e8fb506851abec0706666502b7ae91a8/packages/terser/src/worker.ts#L25-L27

I'll create a PR.

**Comment by dasa** [comment]
PR created at #1483.
