### ISSUE TITLE
Strip Plugin doesn't work with typescript files

### ISSUE THREAD

**Issue by SmartMointy** [rollup/plugins#1485]
- Rollup Plugin Name: Strip
- Rollup Plugin Version: 3.0.2
- Rollup Version: 3.21.0
- Operating System (or Browser): Firefox
- Node Version: 18.9.0
- Link to reproduction: https://stackblitz.com/edit/rollup-repro-sj4zwx

### Expected Behavior
All console.log calls should be removed from the output

### Actual Behavior
Doesn't change the output at all

### Additional Information
The plugin stops working if files end with `.ts`

**Comment by sidneifjr** [comment]
Strip requires an additional object for configuration regarding TypeScript files. A solution is shared in this issue:

https://github.com/rollup/plugins/issues/42#issuecomment-555623043
