### ISSUE TITLE
[commonjs] incompatible with ts node16 moduleResolution + `type: module` package

### ISSUE THREAD

**Issue by JounQin** [rollup/plugins#1488]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 24.1.0
- Rollup Version: 3.21.3
- Operating System (or Browser): macOS
- Node Version: v18.16.0
- Link to reproduction _(⚠️ read below)_: https://github.com/JounQin/test/tree/ts-rollup

### Expected Behavior

No issue

### Actual Behavior

```log
test.ts:3:13 - error TS2349: This expression is not callable.
  Type 'typeof import("/Users/JounQin/Workspaces/GitHub/test/node_modules/@rollup/plugin-commonjs/types/index")' has no call signatures.

3 console.log(commonjs())
              ~~~~~~~~


Found 1 error in test.ts:3
```

`console.log(commonjs.default())` will have no type issue, but it is actually incorrect.

**Comment by JounQin** [comment]
I think this occurs because no `type: module` defined in `@rollup/plugin-commonjs`'s package.json, so TypeScript think the package is commonjs, and then it resolves `export default function commonjs(...)` according to `types` field which represents `exports.default` in its module resolution.

A simple workaround would be exporting `commonjs` as named exports at the same time like `@rollup/plugin-node-resolve`, so that we can use `import { commonjs } from '@rollup/plugin-commonjs'` to bypass this issue.

**Comment by rschristian** [comment]
Duplicate of #1329, no?
