### ISSUE TITLE
inject plugin is replacing source map filename with `null`

### ISSUE THREAD

**Issue by FluffyDiscord** [rollup/plugins#1490]
- Rollup Plugin Name: @rollup/plugin-inject
- Rollup Plugin Version: 5.0.3
- Rollup Version: 3.21.5
- Operating System (or Browser): Linux, Google Chrome 113
- Node Version: 14 (16, 18)
- Link to reproduction: https://github.com/FluffyDiscord/rollup-inject-sourcemap-bug/tree/master

### Expected Behavior
The injection process should not remove sourcemap file name.

### Actual Behavior
The injection process is replacing the filename from sourcemap with `null`.

![image](https://github.com/rollup/plugins/assets/10332247/fcf784d7-fd41-4371-bd9a-2acf7425dda9)

### Additional Information
Using this plugin in dev mode in Vite, which is build on Rollup, replaces filenames in sourcemaps with `null` when the file had something replaced. This should not happen. It makes the debugging process impossible since I have no idea which file the error comes from.

**Comment by michaelchart** [comment]
@FluffyDiscord Did you find a resolution for this? I'm seeing the same issue

**Comment by FluffyDiscord** [comment]
@michaelchart I have abandoned migrating from old webpack to vite for now. I think i have set this line in vit config to false and it fixed itself.

![Screenshot_20230721_171437_Yuzu Browser](https://github.com/rollup/plugins/assets/10332247/d054ca30-6656-4b13-abb1-96e97c2bc843)

**Comment by michaelchart** [comment]
Ah interesting - I will give that a go. Thanks!
