### ISSUE TITLE
@rollup/plugin-image removed from npm registry 

### ISSUE THREAD

**Issue by ntedgi** [rollup/plugins#1494]
when trying to install 

`npm i @rollup/plugin-image`

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rollup%2fplugin-image - Not found

also not found at package home page in npm 

https://www.npmjs.com/package/@rollup/plugin-image

**Comment by eascan** [comment]
getting this as well, using yarn "https://registry.yarnpkg.com/@rollup%2fplugin-image: Not found".

**Comment by dario-rodriguez** [comment]
I'm having the same problem with yarn and npm

**Comment by plotka** [comment]
Having the same issue

**Comment by dor-or** [comment]
Having the same issue

**Comment by dario-rodriguez** [comment]
Looks like a temporary problem with npm registry. It's working right now

**Comment by ntedgi** [comment]
looks like this issue solved and its a temporary problem with npm registry
its working now
