### ISSUE TITLE
[@rollup/plugin-typescript] incorrectly filters out ts files located outside the project root dir

### ISSUE THREAD

**Issue by kyriiherman** [rollup/plugins#1515]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 11.1.0
- Rollup Version: 2.79.1
- Operating System (or Browser): macOS
- Node Version: 16.14.2
- Link to reproduction _(⚠️ read below)_:
https://stackblitz.com/edit/rollup-repro-54tfyi?file=packages%2Fany-package%2Fsrc%2Fmain.js
Steps to reproduce:
1. cd packages/any-package/
2. run `tsc` command: Output is correct, the command runs without errors.
3. run `rollup -c` commands

### Expected Behavior
`@rollup/plugin-typescript` should handle files that included from the outside of the rootDir to be consistent with the `tsc`.

### Actual Behavior

Rollup filters out the `custom.d.ts` file located outside the project root directory. 
Error is the output:
`(!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find module 'icon.svg' or its corresponding type declarations.`

### Additional Information

Passing `include: []` in `@rollup/plugin-typescript` options solves this issue.
The root of this problem is in `getMatcher` fn: https://github.com/rollup/plugins/blob/master/packages/pluginutils/src/createFilter.ts#LL43C52-L43C62.
This fn transforms the default `include` value ({,**/}*.(cts|mts|ts|tsx)) to `/absolute-path-to-the-root-dir/root-dir/{,**/}*.(cts|mts|ts|tsx)` and any path outside the root dir doesn't match against this "regex".

**Comment by shellscape** [comment]
See:

- https://github.com/rollup/plugins/pull/1142
- https://github.com/rollup/plugins/issues/286

This is unlikely to be resolved without community contribution

**Comment by TrickyPi** [comment]
try setting `filterRoot` to `false`, it works.
```js
tsPlugin({
    filterRoot: false,
    tsconfig: './tsconfig.json',
}),
```
