### ISSUE TITLE
[replace] saner default for delimiters

### ISSUE THREAD

**Issue by Hebilicious** [rollup/plugins#1524]
- Rollup Plugin Name: replace
- Rollup Plugin Version: 5.0.2

### Expected Behavior / Situation

Delimiters defaults to  `['(?<!\\.)\\b', '\\b(?!\\.)']`

### Actual Behavior / Situation

Delimiters currently defaults to `['\\b', '\\b(?!\\.)']`

### Modification Proposal

The delimiters defaults are a little too permissive, which means that it's easy to have an error where `globalThis.process.env.NODE_ENV` gets transformed into `globalThis."production"` which causes error in dependencies.

See conversation and and example on how it happened with `graphql` and `nitro` https://github.com/nuxt/nuxt/issues/21768#issuecomment-1613621429

I believe this fix should prevent other users from having the same issues in the future, and shouldn't break existing behaviours. However I am nowhere near a rollup expert and I could be wrong, so feel free to close this if this will break more things than it will fix.

If you think this is a good idea, I am happy to submit a PR with the implementation.

**Comment by shellscape** [comment]
Thanks for the issue. The best route for you would be to make the change and see what tests fail. That would give you (and us) a decent idea of the impact. It'd definitely be considered a breaking change, but that wouldn't stop us from releasing it.
