### ISSUE TITLE
[plugin-node-resolve] can type dependencies be made optional?

### ISSUE THREAD

**Issue by appsforartists** [rollup/plugins#1556]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: 11.2.1

### Expected Behavior / Situation
Unneeded types are not imported

### Actual Behavior / Situation
`@types/node` is a transitive dependency.

```
│  ├─ @rollup/plugin-node-resolve@npm:11.2.1 [dc3fc] (via npm:11.2.1 [dc3fc])
│  │  └─ @types/resolve@npm:1.17.1 (via npm:1.17.1)
│  │     └─ @types/node@npm:17.0.41 (via npm:*)
│  └─ rollup-plugin-node-resolve@npm:5.2.0 [dc3fc] (via npm:5.2.0 [dc3fc])
│     └─ @types/resolve@npm:0.0.8 (via npm:0.0.8)
│        └─ @types/node@npm:17.0.41 (via npm:*)
```

This is blocking my upgrade to TypeScript 5.1.  Presumably types that used to be in `@types/node` are now in the core `typescript` import.  Since I don't target node, having its types in my `node_modules` feels like a bug.

### Modification Proposal
Make the dependency optional.  I don't know enough about the plugin to know if it should be moved to [`peerDependenciesMeta`](https://yarnpkg.com/configuration/manifest/#peerDependenciesMeta) or [`devDependencies`](https://yarnpkg.com/configuration/manifest/#devDependencies).

**Comment by shellscape** [comment]
Could give `bundledDependencies` a shot too

**Comment by appsforartists** [comment]
Note:

You may be able to work around this issue by updating the version in your lockfile (e.g. manually installing `@types/node@20.4.9`).  Even if you don't formally save it in `resolutions`, it should be enough to teach your package manager to not hold onto an obsolete version of the node typings.
