### ISSUE TITLE
Lutts stuff

### ISSUE THREAD

**Issue by luttoo** [rollup/plugins#1561]
- Rollup Plugin Name: 
- Rollup Plugin Version:

Documentation Is:

- [x] Missing
- [x] Needed
- [x] Confusing
- [x] Not Sure?

**Comment by luttoo** [comment]
#1558

**Comment by shellscape** [comment]
@luttoo I'm not sure what you're trying to do, but this repository is not the right venue for experimentation or exploration of Github features. Please refrain from doing this again in the future.
