### ISSUE TITLE
Browser Support for @rollup/plugin-sucrase

### ISSUE THREAD

**Issue by curran** [rollup/plugins#1620]
- Rollup Plugin Name: @rollup/plugin-sucrase
- Rollup Plugin Version: 4

### Feature Use Case
As an Web application developer who wants to allow users of my application to edit and run TS and JSX code in my app, I want to be able to develop a system based on `@rollup/browser` that transpiles JSX and TypeScript, while minimizing the bundle size of my app.

### Feature Proposal
Introduce a new member of the `rollup/plugins` family that supports in-browser transpilation of JSX and TypeScript.

The following are good candidates to research how in-browser support could be added:

 * [@rollup/plugin-sucrase](https://github.com/rollup/plugins/tree/master/packages/sucrase#rollupplugin-sucrase) - It is [possible to run Sucrase in the browser](https://github.com/alangpierce/sucrase/issues/507), perhaps that work could be leveraged here - **This is most promising as the [build](https://github.com/altbdoor/sucrase-build-iife#usage) is pretty small, around 275KB.**
 * [@rollup/plugin-babel](https://github.com/rollup/plugins/tree/master/packages/babel#rollupplugin-babel) - It may be possible to use https://www.npmjs.com/package/@babel/standalone for this, but that is a large [build](https://unpkg.com/browse/@babel/standalone@7.23.2/babel.min.js) at around 2.8 MB.
 * [@rollup/plugin-swc](https://github.com/rollup/plugins/tree/master/packages/swc#rollupplugin-swc) - There is potential to leverage https://www.npmjs.com/package/@swc/wasm-web to support this plugin in the browser. Unfortunately the WASM build is roughly 19MB (see `wasm-web_bg.wasm` in the NPM distribution).

**Comment by curran** [comment]
Related discussion:

 * #5210

**Comment by lukastaegert** [comment]
Requesting a new official plugin is not an issue for Rollup core, maybe for the plugins repo. But the usual way these plugins are created is because someone makes them, then it turns out they are useful to many, so it is suggested to be moved into the core plugins repo. Not the other way around. As you already did half the research, why not create this plugin yourself?

**Comment by curran** [comment]
Indeed! I will attempt this. Thank you for your feedback.
