### ISSUE TITLE
[@rollup/plugin-swc] Errors when setting swc.env as it can't be used with jsc.target

### ISSUE THREAD

**Issue by dmnsgn** [rollup/plugins#1621]
- Rollup Plugin Name: @rollup/plugin-swc
- Rollup Plugin Version: 0.2.1

Some options are set as default in swc:

https://github.com/rollup/plugins/blob/23c5ca77aaf4098f3f425d3285b4f5a8ccc36e40/packages/swc/src/module.ts#L12-L25

Is it so that it "just works" without config?

### Expected Behavior / Situation

Passing valid swc options not to error.

### Actual Behavior / Situation

Passing a swc.env options:

```js
  swc: {
    env: {
      targets: TARGETS,
      mode: "entry",
      coreJs: "3.19",
      shippedProposals: true,
    },
  },
```

will generate the following error:

```console
Error: `env` and `jsc.target` cannot be used together
```

### Modification Proposal

The workaround user space now is to explicitly set jsc target to null:
```js
    jsc: {
      // `env` and `jsc.target` cannot be used together
      target: null,
    },
```

Could it be added as `target: input.swc?.env ? null : 'es2020'`.

Since that's how [swc now works](https://github.com/swc-project/swc/pull/7704/files#diff-05ec577011f6096aac154c266838a96b40e857713f31a3441fc73baf1d90580e):
```rs
        if target.is_some() && cfg.env.is_some() {
            bail!("`jsc.env` and `jsc.target` cannot be used together");
        }
```

**Comment by tada5hi** [comment]
Since the env property is not part of the default, we could just delete jsc.target if the env property is provided by the user config. I will create a pr for that ✌️
