### ISSUE TITLE
CommonJS circular dependencies with transpiled Babel imports

### ISSUE THREAD

**Issue by nathancahill** [rollup/plugins#164]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 11.0.1
- Rollup Version: 1.29.0
- Operating System (or Browser): All
- Node Version: 10, 11, 12

### How Do We Reproduce?

Using @rollup/plugin-commonjs with `postcss` does not correctly resolve internal files within `postcss`, for example `./lib/container.js` from `./lib/rule.js`. The root cause seems to be circular dependencies, caused by mixing `import` and `require` statements before Babel transpilation: https://github.com/postcss/postcss/blob/master/lib/container.es6#L609

Here is a complete example: https://glitch.com/edit/#!/mapgrid-rollup-postcss-repro?path=rollup.config.js:1:0

And a repo: https://github.com/mapgrid/rollup-postcss-repro/

### Expected Behavior

The commonjs plugin handles a mix of transpiled `import` and `require` statements when that creates circular dependencies.

#### Build log
```
(!) Circular dependencies
node_modules/postcss/lib/container.js -> node_modules/postcss/lib/rule.js -> node_modules/postcss/lib/container.js
...
```

#### Runtime error
```
TypeError: superClass is undefined
```

Where `superClass` is the export from `./lib/container.js`

**Comment by shellscape** [comment]
Thanks for the issue :beer:

`@rollup/plugin-commonjs` is known to have trouble with circular references. This is covered in #130. While your reproduction is different, the symptoms are the same. I'm going to drop your repro and description into that issue so we can keep the circular discussions in one spot.
