### ISSUE TITLE
incorrect deprecation message on npm CLI for @rollup/plugin-strip

### ISSUE THREAD

**Issue by revelt** [rollup/plugins#165]
- Rollup Plugin Name: @rollup/plugin-strip
- Rollup Plugin Version: n/a
- Rollup Version: n/a
- Operating System (or Browser): n/a
- Node Version: n/a

### How Do We Reproduce?

The deprecation message on npm is wrong:
<img width="924" alt="depr" src="https://user-images.githubusercontent.com/8344688/72539589-6da4c500-3877-11ea-8a5c-8802982e450c.png">

### Expected Behavior

npm CLI should say `This package has been deprecated and is no longer maintained. Please use @rollup/plugin-strip` — consistent with messaging on `rollup-plugin-json`.

### Actual Behavior

npm CLI says `This module has moved and is now available at @rollup/plugin-buble.`

**Comment by shellscape** [comment]
Thanks! Fixed!
