### ISSUE TITLE
data uri should handle none base64 and also it should hornor dynamic imports

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/plugins#168]
- Rollup Plugin Name: 
- Rollup Plugin Version:
data-uri
### Expected Behavior / Situation
should accept plain text data uris and should accept dynamic imports for all my scenarios
https://github.com/direktspeed/esm-loader

### Actual Behavior / Situation
don't works for anything usefull don't works with dyanmic import and that is used to return a ESM Module

### Modification Proposal
let this work with dynamic imports and string specified data not only base64 as base64 size is always bigger then shortened strings.

**Comment by shellscape** [comment]
Sorry, but I don't understand what you're trying to convey about the base64 strings. Something must be getting lost in translation.

> should accept plain text data uris and should accept dynamic imports for all my scenarios
https://github.com/direktspeed/esm-loader

I'm really not sure what to do with this statement or the repo you've linked to. Most of the maintainers here aren't going to have the time necessary to parse your project and the project's needs. You'll have to do a better job of explaining. 

As for dynamic imports, it's not something we support right now. I'm sorry that it doesn't suit your need. As noted in the README, if dynamic imports is something you need, please open a separate issue for each use case. Test cases for proving those use cases is useful. And of course, as always, we'd welcome a Pull Request for adding the functionality that you need. As of right now, you're the only one to come forward stating it as a critical need.

**Comment by frank-dspeed** [comment]
Implementing it my self thanks for your valueable time.
