### ISSUE TITLE
[@rollup/plugin-replace] Missing sourceMap option within Readme

### ISSUE THREAD

**Issue by EduardoAC** [rollup/plugins#1697]
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: 5.0.5

Documentation Is:
- [X] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Although the option sourceMap [exists](https://github.com/rollup/plugins/blob/master/packages/replace/src/index.js#L139) within the codebase it's not documented likely for historical reasons as it wasn't documented either on the archive plugin [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace) 

### Your Proposal for Changes

Add a new entry to the root README.md as follows 

### `sourceMap`

Type: `Boolean`<br>
Default: `false`

Enables generating sourcemaps for the bundled code. For example, where the plugin is called as follows:

```js
replace({
  sourcemap: true
});
```

**Comment by EduardoAC** [comment]
The `@rollup/plugin-replace` documentation did not include the `sourceMap` option. To speed up the resolution, I've created a PR with the fix.

**Comment by EduardoAC** [comment]
Hi @shellscape, Sorry to bother you, but I don't know the best way to resolve my issue. Can you have a look into this? It should be an easy PR

**Comment by segevfiner** [comment]
I think the default is actually `true`, the code checks if the option was explicitly set to `false` otherwise it is enabled.
