### ISSUE TITLE
Inconsistency with import/export of pluginutils and commonjs plugin

### ISSUE THREAD

**Issue by brettz9** [rollup/plugins#171]
- Rollup Plugin Name:  @rollup/plugin-commonjs
- Rollup Plugin Version: `master` (11.0.1)
- Rollup Version: N/A
- Operating System (or Browser): N/A
- Node Version: N/A

### How Do We Reproduce?

1. Look at https://github.com/rollup/plugins/blob/master/packages/commonjs/src/index.js#L5 , https://github.com/rollup/plugins/blob/master/packages/commonjs/src/transform.js#L4 , and https://github.com/rollup/plugins/blob/master/packages/commonjs/src/utils.js#L4
2. Note how they are importing `@rollup/pluginutils` with the named (curly bracket) syntax.
3. Look at source for pluginutils at https://github.com/rollup/plugins/blob/master/packages/pluginutils/src/index.ts#L8-L15 
4. Note how it is exporting the individuals methods on a single object with `default` (with no named exports).

### Expected Behavior

The imports should either be expressed as default imports or the export should be changed to avoid `default`.

### Actual Behavior

While I don't know that many people will be using the ESM distributions at the moment, I came across the issue when when changing my `esm` config to check or at least give preference to `module` (`"mainFields":["module"]` or `"mainFields":["module", "main"]`) (so as to ensure my tests were using genuine ESM) and instead accidentally running a test script which also ran a Rollup routine. As long as you are including the exports, it is reasonable to expect consistency with ESM import/export behavior.

(FWIW, besides your commonjs plugin, I note that rollup-plugin-babel is also importing pluginutils with named imports.)

Not sure if this ties into #159.

**Comment by shellscape** [comment]
Thanks for writing this up. I've been hunting for potential culprits for #159 and appreciate the heads up on a possible link. We'll dive into this as soon as possible.

**Comment by Andarist** [comment]
@shellscape I believe those two issues are different - this one is just about exported shape of the pluginutils package (so contained to `@rollup/pluginutils` package), while the other one is about `@rollup/plugin-commonjs` not being able to resolve certain stuff (it's contained to `@rollup/plugin-commonjs`).
