### ISSUE TITLE
Not encoding as base64 breaks setups with xml escaping

### ISSUE THREAD

**Issue by neoel** [rollup/plugins#172]
[This update broke my workflow](https://xkcd.com/1172/).

#136 should at least introduce an option of forcing base64 encoding I think.

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by neoel** [comment]
@shellscape Sorry, was unaware there was anything useful in the tempalte. I updated the issue, could you reopen it

**Comment by shellscape** [comment]
@neoel this is frustrating for maintainers. The clip below is highlighted quite prominently in the issue template.

>   Please - do not - remove this template.
>  Please - do not - skip or remove parts of this template.
>  Or your issue may be closed.

While I appreciate you replacing the removed template, you've removed parts of it and disregarded the instructions in the template, which pretty much nukes why we have it there in the first place. Most notably:

```
  Issues without minimal reproductions will be closed! Please provide one by:
  1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     These may take more time to triage than the other options.
  3. Using the REPL at https://rollupjs.org/repl/, or
```

There can be a leaning curve when first starting to work with open source projects, but knowing how to interact and report issues properly on Github projects is a good skill to hone. We'll be happy to reopen the issue when you've taken the time to follow our template correctly.

**Comment by neoel** [comment]
@shellscape Creating a Repl for this case is not going to be minimal, also this bug does not really fit your template nicely. I've updated it to explain the problems it has. Hope this is sufficient.

**Comment by shellscape** [comment]
Sorry, we don't have the bandwidth to triage issues without reproductions.

**Comment by neoel** [comment]
NVM then as #173 hopefully fixes the bug. This bug is accepted in a #136 btw, where the author and reviewer weren't aware of the breakages (as indicated by the template), as with the security concerns of allowing plain html in a src tag.
