### ISSUE TITLE
CommonJS plugin version bump to 26.0.0 causes build issue

### ISSUE THREAD

**Issue by bpneal** [rollup/plugins#1731]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 26.0.0
- Rollup Version: 4.18.0
- Operating System (or Browser): Mac 14.5
- Node Version: 20.13.1
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-bmgxnz?file=package.json,rollup.config.js

### Expected Behavior

Rollup Builds successfully with commonJs Plugin

### Actual Behavior

On Build, build fails with error `SyntaxError: The requested module 'glob' does not provide an export named 'default'`

**Comment by shellscape** [comment]
#1695 introduced the change, and commonjs has the largest test suite in the repo. all tests and builds did pass. @younggglcy please work with @bpneal to triage this, see stackblitz link above.

**Comment by shellscape** [comment]
@bpneal for now I'd recommend downgrading to the last 25.x.x version.

**Comment by shellscape** [comment]
@bpneal I made a quick edit to the plugin and published 26.0.1. Please see if that resolves the issue on your end, I forked your stackblitz and it appeared to.

**Comment by bpneal** [comment]
@shellscape Looks like it is now all working as expected
