### ISSUE TITLE
@rollup/plugin-alias documentation referencing old plugin rollup-plugin-node-resolve

### ISSUE THREAD

**Issue by seetdev** [rollup/plugins#174]
- Rollup Plugin Name: @rollup/plugin-alias
- Rollup Plugin Version: 3.0.0

Documentation Is:

- [ ] Missing
- [] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The README for @rollup/plugin-alias is referencing the old plugin rollup-plugin-node-resolve.
```
This plugin uses resolver plugins specified for Rollup and eventually Rollup default algorithm. If you rely on Node specific features, you probably want rollup-plugin-node-resolve in your setup.
```

### Your Proposal for Changes
Should it reference to https://www.npmjs.com/package/@rollup/plugin-node-resolve and link to it instead?
```
This plugin uses resolver plugins specified for Rollup and eventually Rollup default algorithm. If you rely on Node specific features, you probably want @rollup/plugin-node-resolve in your setup.
```

I will put in the PR if that is the desired result.

**Comment by shellscape** [comment]
Yes it should! Thanks for reporting this.

**Comment by seetdev** [comment]
I have one more question, I am trying out rollup recently and I think there might be a fair amount of links in the documentation in the other plugin README.md. If I am fixing them in the process what will be the easiest way for the maintainers. Should I combine multiple plugins into 1 issue and PR or should every plugin have it's own issue and PR? Wondering what is the best process to create least amount of effort for the reviewers.

**Comment by shellscape** [comment]
If you'd like to see your commits in the changelog for each plugin, then separate PRs. If you don't care about that, one PR is good too.

**Comment by seetdev** [comment]
Thanks. I will work though the other pages and put them in another PR.

**Comment by seetdev** [comment]
@shellscape I think we are good to close this. I went through the documentation and it appears that the other one that might need to change is @rollup/pluginutils. But the package is still using the old versions so I guess rather than updating the documents for that it will be looking to upgrade the dependencies first.
