### ISSUE TITLE
[@rollup/plugin-json] inclusion/exclusion filter fails

### ISSUE THREAD

**Issue by codemasher** [rollup/plugins#1747]
- Rollup Plugin Name: [@rollup/plugin-json](https://github.com/rollup/plugins/tree/master/packages/json)
- Rollup Plugin Version: 6.1.0 (latest as of 2024-07-10)
- Rollup Version: 4.18.1
- Operating System (or Browser): Windows 10
- Node Version: 22.2.0.
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior

When specifying an inclusion or exclusion filter pattern via options, the files should match the given pattern:

`index.js`

```js
// json file with different extension
import some_geojson from './features.geojson' with {type: 'json'};
// json with boring default extension
import some_normal_json from './stuff.json' with {type: 'json'};

// ...
```

`rollup.config.js`

```js
import json from '@rollup/plugin-json';

export default {
	input  : 'src/index.js',
	output : [
		{
			file     : 'dist/dist-src.js',
			format   : 'es',
			sourcemap: true,
		},
	],
	plugins: [
		json({include: ['**/*.(geo)?json']}),
	],
};
```

### Actual Behavior

The given match pattern is ignored when the file extension is not JSON.

### Additional Information

I just spent way too much time to find out that neither the glob patterns or `RegExp` instances i provided were the issue, but this line here

https://github.com/rollup/plugins/blob/8550c4b1925b246adbd3af48ed0e5f74f822c951/packages/json/src/index.js#L12

It should only return `null` when *both* of the conditions are true, not either of them:

```js
if (id.slice(-5) !== '.json' && !filter(id)) return null;
```

After changing this, the inclusion check works as expected.

**Comment by shellscape** [comment]
That's why searching issues first is such an important step in triage. This was reported and discussed here: https://github.com/rollup/plugins/issues/1730

**Comment by shellscape** [comment]
Closing as duplicate. If you'd like to take up the task of expanding what that plugin does, please consider opening a pull request.
