### ISSUE TITLE
[rollup-plugin-typescript] `declarationDir` inside same directory as `file` option

### ISSUE THREAD

**Issue by mririgoyen** [rollup/plugins#1773]
Perhaps related to #1772.

- Rollup Plugin Name: rollup-plugin-typescript
- Rollup Plugin Version: 12.1.0
- Rollup Version: 4.22.4
- Operating System (or Browser):
- Node Version: 20.17

### Expected Behavior

Nested sub-directories continue to be valid.

### Actual Behavior

Based on the breaking change, output must be the same as the declaration directory. However, I believe this check is being over-zealous, disallowing sub-directories _within_ the declaration directory.

After the v12 update, the following error is presented:

```
@rollup/plugin-typescript: Path of Typescript compiler option 'declarationDir' must be located inside the same directory as the Rollup 'file' option.
```

### Additional Information

The declaration directory in `tsconfig.json`:

```
"declarationDir": "lib",
```

The rollup config:

```
  {
    input: 'src/tailwind/config.ts',
    output: [{ file: 'lib/tailwind/config.js', format: 'cjs' }],
    plugins: [
      typescript({
        filterRoot: 'src/tailwind',
      }),
    ],
  },
```

If I simplify the output to `lib/config.js`, the error is gone. However, my directory structure is no longer valid.

**Comment by shellscape** [comment]
We'd be happy to take a look at a Pull Request which resolves this condition, but one which keeps current tests passing.

**Comment by michaelfaith** [comment]
I'm not sure i fully understand the motivation for the change that caused this; the pr didn't really go into much detail as to why this was needed. But, if i understand the code changed, it could be that reversing the order of these params making the path from ts to rollup, rather than rollup to ts, could be enough to fix the case of nested directories within the outDir 
https://github.com/rollup/plugins/blob/4a2358a3f65efc35a6e64bbff00ec5b43de90172/packages/typescript/src/options/validate.ts#L61

**Comment by kahagerman** [comment]
This is also a regression for .d.ts files when we need to write them somewhere else first.

We use [api-extractor](https://api-extractor.com/pages/overview/intro/), so we want to write out the *.d.ts to a different directory (currently `./lib/types`) so they can be post-processed there.

This is broken with versions >=12.1.0.

**Comment by shellscape** [comment]
@kahagerman breaking changes on major versions are not regressions.

this PR will likely not get further discussion on this page. there are active issues and PRs open, please take discussion there.
