### ISSUE TITLE
Missing support for `accessor` prefix in `plugin-commonjs`

### ISSUE THREAD

**Issue by Virus288** [rollup/plugins#1778]
- Rollup Plugin Name: plugin-commonjs
- Rollup Plugin Version: 28.0.0
- Rollup Version: 4.22.5
- Operating System (or Browser): Linux ( arch with kernel 6.10.10 )
- Node Version: 22.9.0
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-mdxka7?file=package.json

### Expected Behavior
I use tsc to compile typescript into esNext code, then rollup to move esNext to commonJs. That way I can have commonJs index alongside esm index. I expected code to move esNext code to commonJs.

### Actual Behavior
I got this error 
```
(plugin commonjs--resolver) RollupError: Unexpected token `#text`. Expected * for generator, private key, identifier or async in /.../src/index.js
```

### Additional Information

As long as I do not use accessor, everything is working just fine. Rollup seems to not recognise accessors. This is my repo. In current state, it does not use accessors and compiles perfectly. Problems starts as soon as I add accessors https://github.com/ApiToaster/ApiToaster

**Comment by lukastaegert** [comment]
It is not the plugin, it is Rollup itself that does not support the feature. Accessors are a stage-1 proposal and may be subject to fundamental changes https://github.com/tc39/proposal-grouped-and-auto-accessors
You can get around this by adding a plugin that transpiles them in some way.
