### ISSUE TITLE
Option 'declarationMap' cannot be specified

### ISSUE THREAD

**Issue by JounQin** [rollup/plugins#179]
- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: `2.1.0`
- Rollup Version: `1.29.0`
- Operating System (or Browser): macOS 10.15.2 (19C57)
- Node Version: v12.14.1

There is no error when using `rollup-plugin-typescript@1.0.1`

### How Do We Reproduce?

https://github.com/rx-ts/pkgr/tree/repro/rollup

branch: `repro/rollup`

run `yarn && yarn build:r`

### Expected Behavior

No Error

### Actual Behavior

```sh
Error: Error TS5069: Option 'declarationMap' cannot be specified without specifying option 'declaration' or option 'composite'.
```

**Comment by shellscape** [comment]
Thanks for the issue. Because of time being in short supply, please break down your reproduction to something more minimal, ideally using the repl.it link provided.

**Comment by JounQin** [comment]
Hmm... After upgrading to `@rollup/plugin-typescript@3.0.0`, it works. 😀
