### ISSUE TITLE
pluginutils broken type; estree-walker has no exported member Node

### ISSUE THREAD

**Issue by MaxMilton** [rollup/plugins#182]
- Rollup Plugin Name: `@rollup/pluginutils`
- Rollup Plugin Version: `3.0.5`
- Rollup Version: `1.29.1`
- Operating System (or Browser): Arch Linux
- Node Version: `13.7.0`

### How Do We Reproduce?

1. Import any method from `@rollup/pluginutils` in a TypeScript project
2. Attempt to build the project

See minimal repro: <https://github.com/MaxMilton/repro-rollup-plugin-utils-types>

### Expected Behavior

Project builds without type errors.

### Actual Behavior

Type error is thrown due to missing type. `estree-walker` does not actually have any `Node` type exported.

```
❯ yarn run build
yarn run v1.21.1
$ tsc index.ts
node_modules/@rollup/pluginutils/types/index.d.ts:1:10 - error TS2305: Module '"../../../estree-walker/types"' has no exported member 'Node'.

1 import { Node } from 'estree-walker';
           ~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Changing `pluginutils/types/index.d.ts` from...

```ts
import { Node } from 'estree-walker';
```

... to...

```ts
import { Node } from 'estree';
```

... resolves the issue.

**Comment by shellscape** [comment]
We'd be happy to review a PR that resolves this.

**Comment by atomicpages** [comment]
Fixed by 2ae08ebacaf9981252664d47e073dbac2a0447e7. Can you please publish `7.0.1`?

**Comment by shellscape** [comment]
@atomicpages thanks for referencing the commit, but please don't ask for package publishes. It adds to the noise and isn't necessary. All plugin packages are published as we have time.

**Comment by atomicpages** [comment]
@shellscape it's definitely _not_ noise. It's blocking if you use `tsc` and you depend on this package -- the build fails because it a bad type check.

**Comment by MaxMilton** [comment]
Thanks for the quick feedback guys and thanks @NotWoods for the fix! :trophy:

**Comment by kimmikirino** [comment]
Hi guys,

Is someone else getting errors from the new version?

![image](https://user-images.githubusercontent.com/29700468/118691921-ef945d80-b7df-11eb-9fde-59bfa6634443.png)

**Comment by maxmilton** [comment]
It's probably a better idea to create a new issue and link back to old one rather than trying to necro a closed issue.
