### ISSUE TITLE
[rollup-plugin-typescript] Breaks on .d.ts declaration inputs

### ISSUE THREAD

**Issue by tangerball** [rollup/plugins#1828]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: latest
- Rollup Version: latest
- Operating System (or Browser): windows10
- Node Version: 16.20.2
- Link to reproduction _(⚠️ read below)_: https://replit.com/@ctjlewis/rollup-plugin-typescript-repro

### Expected Behavior
The plugin should not break on .d.ts inputs, including module declarations.

### Actual Behavior
```
src/env.d.ts → dist...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/env.d.ts (1:8)
1: declare module test {}
           ^
```

**Comment by shellscape** [comment]
There is nothing in the documentation or code that suggests your expectation is reasonable. The plugin was not designed to ingest definition files as the entry. If that's a feature you'd like, please consider contributing. For now, closing this as not planned/wontfix.
