### ISSUE TITLE
@rollup/plugin-node-resolve mainFields doesnt work

### ISSUE THREAD

**Issue by sujini** [rollup/plugins#1830]
- Rollup Plugin Name: 
- Rollup Plugin Version:
- Rollup Version:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
nodeResolve({mainFields: ['main']}),
I'm trying to configure the entry point for a library in '@rollup/plugin-node-resolve' using the mainFields property in the configuration, as specified in the package.json file of the library. 

### Actual Behavior
However, no matter what value I set for mainFields, it always references the root index.js file of the library. How can I specify a different entry point in the mainFields configuration?"

**Comment by sujini** [comment]
@shellscape please comment the reason this issue  closed.. did I make a mistake? I am not good at english...

**Comment by shellscape** [comment]
<img width="602" alt="Screenshot 2024-12-18 at 7 51 19 PM" src="https://github.com/user-attachments/assets/25f872c2-28ce-42e1-b123-cb93ac648660" />
<img width="804" alt="Screenshot 2024-12-18 at 7 51 25 PM" src="https://github.com/user-attachments/assets/9bf604ff-e264-43bb-ab3e-e36dadece603" />

It's OK that you are not good at english. It's not OK to skip the requirements. Open a discussion if you need support.
