### ISSUE TITLE
plugin-typescript V3 ignored noEmitHelpers

### ISSUE THREAD

**Issue by smartrejames** [rollup/plugins#188]
- Rollup Plugin Name: plugin-typescript
- Rollup Plugin Version: 3.0.0
- Rollup Version: 1.30.1
- Operating System (or Browser): macOS 10.15.2
- Node Version: v8.17.0

### How Do We Reproduce?

Change tsconfig.json "noEmitHelpers" to true then build.

### Expected Behavior

The output js file should not contain typescript helper functions like __extends, __assign.

### Actual Behavior

The output js file contains helper functions, tsconfig.json "noEmitHelpers" be ignored.

**Comment by smartrejames** [comment]
My bad, README mentions that tslib always been used.

**Comment by smartrejames** [comment]
Another problem is output did not contain tslib.__xxx too, does it mean importHelper not work?

**Comment by shellscape** [comment]
@smartrejames thanks for the issue, but you didn't follow the issue template. We require a minimal reproduction to triage all bugs. Please refile your second question as a new issue, following the instructions for providing a reproduction, if you feel that's a bug.
