### ISSUE TITLE
Obsolete types from 'estree-walker' are used

### ISSUE THREAD

**Issue by fobdy** [rollup/plugins#189]
- Rollup Plugin Name: `@rollup/pluginutils`
- Rollup Plugin Version: `3.0.6`
- Rollup Version: `1.30.1`
- Operating System (or Browser): macOS `10.13.6`
- Node Version: `12.12.0`

### How Do We Reproduce?

Just use one of the latest rollup plugins that have `@rollup/pluginutils` dependency (`^3.0.0`).

### Expected Behavior
Everything going fine

### Actual Behavior
```bash
../**/node_modules/@rollup/pluginutils/types/index.d.ts:1:10 - error TS2305: Module '"../**/node_modules/@rollup/pluginutils/node_modules/estree-walker/types"' has no exported member 'Node'.
1 import { Node } from 'estree-walker';
```

It seems that latest published `estree-walker` types expose `BaseNode` instead of `Node`.
And latest published `pluginutils` trying to import `Node`. Despite of that actual sources [are fine](https://github.com/rollup/plugins/blob/master/packages/pluginutils/types/index.d.ts).

It seems that solution is to republish `@rollup/pluginutils`.

**Comment by shellscape** [comment]
Please search issues before opening new ones. This has been previously reported and a fix has been merged.
