### ISSUE TITLE
PR #136: needs to be reverted, broke svg's

### ISSUE THREAD

**Issue by neoel** [rollup/plugins#192]
Since #136 (a month) handling of svg's is broken. 
It stated incorrectly:
> Breaking Changes?
> 
> * [ ]  yes (_breaking changes will not be merged unless absolutely necessary_)
> * [x]  no

And therefor it needs to be reverted. 
Since then issues have been raised (and promptly closed :(), and PR's supplied, and closed or not yet merged. 

PR closed and not merged:
- #184
- #158

PR Still open (will fix): #173

Issues opened:
 - #172 
 - #183

- Rollup Plugin Name: plugin-image
- Rollup Plugin Version: 2.0.1
- Rollup Version: - 
- Operating System (or Browser): Any browser
- Node Version: any

### How Do We Reproduce?
Load a svg like this:

```svg
<svg viewBox="0 0 9 9" style="background-color:#AAA"></svg>
```
Needs to be minimally encoded as

```%3Csvg viewBox=%220 0 9 9%22 style=%22background-color:%23AAA%22%3E%3C/svg%3E```

### Expected Behavior
SVG images should be at least properly encoded when using them as data-uri
Only `<`, `>`, `"`, `#` need to be url encoded.

### Actual Behavior
It does not encode the svg source at all.

**Comment by shellscape** [comment]
It's an edge case on chrome that's been reported a number of times. Please refrain from opening such dramatic issues, and from opening duplicates. When #173 is merged the issue will be resolved. Hard code to the previous version if you're impacted by it.
