### ISSUE TITLE
node-resolve 7.1.0 regression

### ISSUE THREAD

**Issue by arcanis** [rollup/plugins#194]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 7.1.0

### How Do We Reproduce?

https://github.com/arcanis/rollup-node-resolve-regression

```
yarn init --install berry
yarn add rollup @rollup/plugin-node-resolve lodash
echo "import 'lodash';" > index.js
// copy the following config
yarn rollup -c
```

```js
import resolve from '@rollup/plugin-node-resolve';

module.exports = {
    input: './index.js',
    output: {
        sourcemap: true,
        format: 'iife',
        name: 'app',
        file: './bundle.js'
    },
    plugins: [
        resolve(),
    ],
};
```

### Expected Behavior

Should build without externals.

Cf https://github.com/yarnpkg/berry/runs/420956592?check_suite_focus=true

### Actual Behavior

Lodash cannot be rebuilt.

Cf https://github.com/yarnpkg/berry/runs/421084236?check_suite_focus=true

Running `yarn add @rollup/plugin-node-resolve@7.0.0` fixes the problem.

**Comment by shellscape** [comment]
Please share a proper reproduction as per the issue template or we will be unable to triage your issue.

**Comment by arcanis** [comment]
@shellscape I've added a repository (https://github.com/arcanis/rollup-node-resolve-regression)

**Comment by shellscape** [comment]
Perfect, thanks.

**Comment by arcanis** [comment]
Digging a bit, the problem seems to come from this line:
https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/index.js#L205

It seems to be throwing `true`, for some reason 🤔

**Comment by arcanis** [comment]
I'll close this issue - I tracked it down to a problem in our own Yarn layer which doesn't properly propagate the `util.promisify.custom` property, hence the problem on `promisify`. Sorry for the blip 🙂

**Comment by shellscape** [comment]
No worries. Yours was the second regression report so we treated it as valid. Any more info you can give that we can use to document the scenario?

**Comment by arcanis** [comment]
In order to let the package files be read directly from their zip storage we currently need to setup a layer on top of the `fs` module. This layer was doing something similar to the following:

```js
fs.exists = (p, ...args) =>{
  isZip(p) ? existsZip(p, ...args) : existsNative(p, ...args);
};
```

The problem is that by doing this we were losing the `util.promisify.custom` symbol, hence why the function was throwing `true` (since `exists` doesn't have an `err` return). We should have done:

```js
fs.exists = (p, ...args) =>{
  isZip(p) ? existsZip(p, ...args) : existsNative(p, ...args);
};
fs.exists[util.promisify.custom] = existsNative[util.promisify.custom];
```

So it really was a problem to fix on our side. Note that on yours I'd still suggest to use `existsSync` rather than `exists`, as asynchronous file checks are semantically a bit unsound (since the file has more chances to disappear between the moment where you check for its existence and the moment you actually use it). But that's not really a big issue 🙂

**Comment by shellscape** [comment]
> I'd still suggest to use existsSync rather than exists, as asynchronous file checks are semantically a bit unsound (since the file has more chances to disappear between the moment where you check for its existence and the moment you actually use it)

That's actually a great point and a good use case for the synchronous version. Thanks for the extra explanation.
