### ISSUE TITLE
Add fetch plugin for bundling absolute HTTPS urls

### ISSUE THREAD

**Issue by NotWoods** [rollup/plugins#210]
Request Checklist:

- [x] I have searched https://npmjs.com/ before opening this issue
- [x] I have searched https://github.com/rollup/awesome before opening this issue

### New Plugin Proposal

Projects like [Deno and Pika CDN](https://dev.to/pika/introducing-pika-cdn-deno-p8b) encourage importing modules from `https://` urls. It would be nice to be able to easily bundle these modules for nomodule builds by fetching them during the build process.

**Comment by lukastaegert** [comment]
I think what you want is https://github.com/mjackson/rollup-plugin-url-resolve
