### ISSUE TITLE
@rollup/plugin-json: Unexpected token

### ISSUE THREAD

**Issue by sinisimattia** [rollup/plugins#213]
Hi everyone, I have a problem with @rollup/plugin-json

Basically it fails whenever I have "**:**" in my file.

**FAILS:**
```
{
    "hey": "how are you?"
}
```

**SUCCESS:**
```
{}
```

**Comment by shellscape** [comment]
Sorry, but we don't offer support here and our issue templates are required. If you believe this is a bug, please refile the issue following the issue template to the letter, including a proper reproduction
