### ISSUE TITLE
Sucrase support to Vue

### ISSUE THREAD

**Issue by joaoeudes7** [rollup/plugins#224]
- Rollup Plugin Name: @rollup/plugin-sucrase
- Rollup Plugin Version: 3.0.0

### Feature Use Case
Support to use transform typescript of code in files `.vue` as plugin works in rollup-plugin-typescript2

### Feature Proposal
Import in plugin in rollup config and generate bundle

**Comment by shellscape** [comment]
We'd be happy to review a PR which added this support.

**Comment by shellscape** [comment]
Hey folks, this one has gone quite stale. We're going to close for housekeeping but we'd happily review any PRs that pop up to resolve this issue.
