### ISSUE TITLE
Replace exclude option does nothing on its own

### ISSUE THREAD

**Issue by darsain** [rollup/plugins#226]
- Rollup Plugin @rollup/plugin-replace
- Rollup Plugin Version: 2.3.1
- Rollup Version: 1.31.1
- Operating System (or Browser): Win 10
- Node Version: 13.7.0

### How Do We Reproduce?

https://repl.it/repls/ChiefUnselfishAssignments

### Expected Behavior

Replace plugin should ignore files matching `exclude` patterns.

### Actual Behavior

No matter how eager I make the `exclude` pattern, the output is always modified. Temporary solution is to use `include` instead, which seems to work around this problem.

I dug into the code and the replacement happens in both `transform` and `renderChunk` hooks. The transform works fine, excluding and not running on what it shouldn't, but that is made pointless when the final bundle file gets replaced as it goes through the `renderChunk` hook, where no `exclude` pattern works on it, since the `id` the `filter(id)` is working with is the final bundle filename, which will never match any useful patterns like `src/**/*` or `node_modules/**/*`.

Is there a reason why the replacement happens on `renderChunk` as well? Seems like `transform` should be enough. Even the [old plugin](https://github.com/rollup/rollup-plugin-replace/blob/master/src/index.js) was only replacing on `transform`.

**Comment by shellscape** [comment]
@lukastaegert @NotWoods so this is an interesting one. In the reproduction above, what ends up as the pattern for `exclude: ['input.js]` is `/ChiefUnselfishAssignments\\-1/input.js`, which micromatch returns `false` for when the `id` in `transform` is `input.js`. 

Really none of the plugins allow passing options for `pluginutils`s `createFilter` method. This would be a case for passing `{ resolve: false }` to `createFilter`. It raises the question of how we should be resolving globs for this matching, and what is the right course of action here and for the other plugins.

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.

**Comment by darsain** [comment]
So sweeping acknowledged bugs that people don't actively complain about under the rug is considered housekeeping?
Seems like a great way to make houses start exploding in the future.

There is nothing wrong with having a valid issue open. I understand if there is none that cares about it enough to fix it at the moment, but straight up closing it implies this has been resolved and everything is tip top.

![image](https://user-images.githubusercontent.com/538801/87078459-f304a300-c224-11ea-9df3-b631a290959d.jpg)

**Comment by shellscape** [comment]
@darsain please keep comments civil. housekeeping is common, most large projects delegate that work to bots. Your issue received no support from the community. If you'd like to submit a PR for resolution, we'll be happy to consider it. Please do keep further discussion on this issue related to the issue and not repo management.
