### ISSUE TITLE
tslib doesn't have file extension

### ISSUE THREAD

**Issue by tu4mo** [rollup/plugins#232]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 3.0.0
- Rollup Version: 1.31.1
- Operating System (or Browser): Mac
- Node Version: 12.16.1

### How Do We Reproduce?

Run Rollup with preserveModules.

### Expected Behavior

_virtual/_tslib has an .js extension.

### Actual Behavior

_virtual/_tslib does not have file extension.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to reopen and triage further.

**Comment by tu4mo** [comment]
@shellscape Here you go: https://repl.it/repls/OrdinaryDefiniteFormula

**Comment by shellscape** [comment]
@NotWoods I reopened this as OP provided a repro

**Comment by NotWoods** [comment]
Fixed in version 4.0.0 of the typescript plugin
