### ISSUE TITLE
Application is not always ran

### ISSUE THREAD

**Issue by lefta** [rollup/plugins#235]
- Rollup Plugin Name: plugin-run
- Rollup Plugin Version: 1.2.0
- Rollup Version: 1.32.0
- Operating System (or Browser): Linux
- Node Version: v12.16.1

### How Do We Reproduce?

I'm not going to make a repro this evening, this is ways too late and there should be enough informations below. I may try to do so on request somewhere in the week, if I find some time.

But this is simple : just make a bundle take some seconds to generate.

### Expected Behavior

After the bundle is generated, it should be ran.

### Actual Behavior

It is not always. At the beggining of the project, it was 1 of 2 times. Now it is almost never running.

### What the \<beep\>

Looking at the source of the plugin, it appears that it is hooked on `generateBundle`. However, from the documentation, the hook is `Called [...] immediately before the files are written`. It looks like if the bundle is too slow to generate, the program is forked before being written, so nothing is starting.

### A fix ?

Moving to the `writeBundle` hook seems to do the trick. At least, it should if I'm right on the cause, and my program started successfully the three times I tried.

If anyone also gets into this bug and need a fix right now, here is a quick (and dirty) one. Just put it in its own file, and use it as a drop in replacement.
```js
import original from '@rollup/plugin-run'

export default (opts = {}) => {
  const res = original(opts)

  const hook = res.generateBundle
  // `dir` is the output directory here, replace with your own.
  res.writeBundle = bundle => hook({ dir: 'dist' }, bundle, true)
  delete res.generateBundle

  return res
}
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.

**Comment by lefta** [comment]
The best I could reproduce is this : https://repl.it/repls/LovingRecklessEquation

However, this is not my exact symptoms : 
* Instead of a crash, I get nothing at all
* You will tell me that the plugins may be shifted. In my project, `run` is already the last one.

At least, this reproduction shows that a race condition is possible. Maybe the size of the bundle is a factor (mine is 7.8k uncompressed), but I have no idea of a library large enough that could be imported and written in the bundle (I think this is the easiest way to have something close enough). Anyway, this would be highly dependent on the setup and the load of the computer / server where the repro is run.

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.
