### ISSUE TITLE
(plugin typescript) Error: Couldn't compile - no more error details printed

### ISSUE THREAD

**Issue by CSchulz** [rollup/plugins#238]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 3.0.0
- Rollup Version: 1.32.0
- Operating System (or Browser): Win 10
- Node Version: 12.16.1

### How Do We Reproduce?
https://repl.it/repls/CriminalQuestionableAbilities

### Expected Behavior
It should compile or give at least a helpful error.

### Actual Behavior
It fails without any helpful error.

I have tried to investigate the diagnostics of typescript but they are empty.

```
            if (output.emitSkipped) {
                // Emit failed, print all diagnostics for this file
                const allDiagnostics = []
                    .concat(services.getSyntacticDiagnostics(id))
                    .concat(services.getSemanticDiagnostics(id));
                emitDiagnostics(ts, this, host, allDiagnostics);
                throw new Error(`Couldn't compile ${id}`);
            }
```

**Comment by CSchulz** [comment]
Thanks for the hint. Is there any plan when 4.0 will be released or is there any existing workaround?

**Comment by NotWoods** [comment]
Out now!
