### ISSUE TITLE
Monorepo: Seamless Package Publishing

### ISSUE THREAD

**Issue by shellscape** [rollup/plugins#24]
- Rollup Plugin Name: n/a
- Rollup Plugin Version: n/a

### Feature Use Case

To publish a module in the monorepo at the moment, we have to manually perform the following tasks:

- merge relevant pull requests (this step won't go away)
- change the package version appropriately
- update the changelog manually from commits
- run `pnpm run publish -- <name>`

### Feature Proposal

I'd like to work some automagic into the `publish` script process. Namely:

- add a `--version` flag, which would accept the same `patch|minor|major` values that npm does
- parse the commit log to pull relevant commits for the target plugin name, and automatically update the CHANGELOG for a plugin. This would require a standard commit format. e.g. `fix(beep)`, `docs(beep)`, `feat(beep)`, etc. And I know that's something that @lukastaegert is not a fan of, so it's worth discussing here.
- finally, actually publish the plugin

Alternatively, we could let the changelog decide what type of a semver update the publish should be, if we all agree to use a commit format that can be parsed as such. `fix|docs|chore` all fall into `patch`, `feat` is minor, and we'd have to have a means of tagging something a breaking change that would necessitate a `major`, or we can use a flag like `--breaking` to specify a major with breaking changes, or `--major` for a major version without breaking changes.

There's also the question of how to annotate the CHANGELOG for a plugin with breaking changes.

/cc @rollup/plugin-maintainers

**Comment by lukastaegert** [comment]
Hi @shellscape, thanks for your awesome work and taking the initiative on this, I am a big fan of automating this.

> And I know that's something that @lukastaegert is not a fan of, so it's worth discussing here.

I know I have been opposed to this for Rollup core, the reason being that
* I do not really like it
* Its main usefulness lies in automated changelog generation, which at the moment I prefer to do at least partially by hand as I find it leads to a better changelog. Also with the squash commits we do in Rollup core (that I really started to like for the nice, readable git log), this does not allow for adding more than a single feature or fix per PR.

For plugins, though, I would value automation above all of these concerns. Everything that reduces maintenance overhead here is a big win for everyone; the barrier for pushing new plugin versions should be as low as possible to avoid rotting code.

If this means we go for something like the angular commit format to be able to use conventional changelog, so be it. One thing to consider is (not sure if you already decided something here) whether to use squash merges or not. Using squash merges means that contributors can use any commit format they like while the chore of writing the commit message basically lies with the person doing the squash, who then has to take care the proper format is used (and this is hard to check automatically when done via the Github web interface as far as I know). This will probably lower the barrier of entry.

**Comment by lukastaegert** [comment]
> this does not allow for adding more than a single feature or fix per PR

At least I think that is the case, did not dive too deeply into conventional-changelog TBH

**Comment by TJKoury** [comment]
FWIW, I get the desire to use a monorepo, but it does feel a little strange having a plugin tell me what package manager I have to use.

**Comment by shellscape** [comment]
@TJKoury I don't understand the concern - the plugins aren't telling anyone which package manager to use.

**Comment by TJKoury** [comment]
@shellscape `To begin, please install pnpm:`.  So you can do all those steps with npm & yarn as well?

**Comment by shellscape** [comment]
@TJKoury I think this misperception might be chalked up to a lack of experience. (This is also not the correct place to comment on the concern, since it's very off-topic.)

The text you quoted is beneath the `Contributing` section on the root README. That means it's _part of the instructions for contribution to the repo_. Plugins are not telling people what package manager to use, but if you want to _contribute_ to the repo, you need to leverage the repo's toolset that we've chosen.

To find instructions for each individual plugin, click on one of the plugin links, or view the module's README on npm.

**Comment by Andarist** [comment]
I've started to love changesets - https://github.com/atlassian/changesets/ - for automatic publishing. It allows you to enforce~ a changelog entry (with appropriate version bump) as part of the PR. It's IMHO great as it:
- allows a changelog entry to be reviewed like every other part of the committed code (committer is sort of responsible for writing such entry)
- can be easily added/edited from GitHub's UI (so can be added "manually" by a maintainer)
- can be edited even after merging to master
- allows for auto publish - this shines for monorepos which contain highly related modules, but can be used as good with other types as well 
- comes with helpful GitHub bot, action & CLI tool

**Comment by TJKoury** [comment]
@shellscape I know very well that it’s under the ‘Contributing’ section.  I contribute to projects I use so that the changes can be rolled into the baseline, as a good open source developer should.

Rather difficult to do if I have to add a new package manager into my workflow for a plug-in.

**Comment by lukastaegert** [comment]
@Andarist great suggestion, looking into the documentation, changesets looks really nice!
Especially love the Github bot.

At the moment, there will not be a lot of dependencies between plugins but this may change in the future. I hope that at some point, we can have a simple format for "preset" plugins that add and configure options and several plugins together for specific scenarios, and then this will be really nice. But even without this, I love how this decouples commit messages from changelog generation and allows for really nice changelogs. Might even be interesting for Rollup core.

**Comment by Andarist** [comment]
Yes - without dependencies between plugins I would just make it autopublish stuff from master each time smth lands there. No reason for „release PRs” prepared by a bot

**Comment by shellscape** [comment]
I'm actually a fan of release PRs. They tend to prevent the "oh crap I forgot some metadata, time to publish another patch version" kind of misfires. I'm definitely going to look into changesets very soon.

**Comment by Andarist** [comment]
They definitely won't hurt much - I just think that with a such "distributed" monorepo as here they might be a little noisy. I guess they are a good starting point though anyway until you get used to changesets workflow.

**Comment by shellscape** [comment]
While I'm still looking into `changesets`, I'd like to take baby steps in getting there. We're starting to get some fixes backing up that need publishing, and I've finally been able to put some time into the publish workflow in the interim. Here's what I've come up with:

```
  Get list of tags for plugin
  git tag --list pluginutils* --sort=-taggerdate

  Get list of commits from last plugin tag
  git log --grep "(pluginutils)" --pretty=format:%s pluginutils-v3.0.1..HEAD

  Sample output:
  fix(pluginutils): makeLegalIdentifier - potentially unsafe input for blacklisted identifier (#116)
  docs(pluginutils): Fix documented type of createFilter's include/exclude (#123)
  chore(pluginutils): update minor linting correction

  Parse messages.

  - docs: patch
  - fix: patch
  - feat: minor
  - chore: none, bail

  Update package.json with new semver

  Create Version Changes
  - ignore /chore(release)/ commits
  Update Changelog

  Add package.json
  Add Changelog.md
  Commit: chore(release): {plugin} v{version}

  Tag: {plugin}-v{version}

  NPM publish

  git push && git push --tags
```

Most of these steps are straightforward and the current publish script does a small amount of this (at the end). I'll be working on getting the bulk of this done today. The only unknown for me is the changelog stuff, but should be able to find the tools to handle that.
