### ISSUE TITLE
Incomplete rollup peerDependency semver

### ISSUE THREAD

**Issue by karolis-sh** [rollup/plugins#246]
I migrated from old plugin `rollup-plugin-commonjs` to `@rollup/plugin-commonjs`  and noticed that peer dependency semvers are different and displays false warnings.

## Previously

![image](https://user-images.githubusercontent.com/3521740/76162052-03efbb80-6142-11ea-8c78-24fdd40e4425.png)

## Now

![image](https://user-images.githubusercontent.com/3521740/76162029-d571e080-6141-11ea-8fd0-749665b403b4.png)

- Rollup Plugin Name: `@rollup/plugin-commonjs` (and looks like all of the plugins here)
- Rollup Plugin Version: `11.0.2`
- Rollup Version: `2.0.2`
- Operating System (or Browser): Mac
- Node Version: `10.15.0`

### How Do We Reproduce?

1. `yarn add rollup`
2. `yarn add @rollup/plugin-commonjs`

### Expected Behavior

No warnings should be displayed.

### Actual Behavior

A peer dependency warning occurs:

`warning " > @rollup/plugin-commonjs@11.0.2" has unmet peer dependency "rollup@^1.20.0".`

---

An `|| ^2.0.0` addition should do the trick:

![image](https://user-images.githubusercontent.com/3521740/76162066-40bbb280-6142-11ea-8eef-42a48fd7b456.png)

**Comment by TrySound** [comment]
@karolis-sh it was not merged yet
https://github.com/rollup/plugins/pull/244

**Comment by shellscape** [comment]
Thanks for reporting this and for the detailed info, but it's just a tad early. Closing in favor of #244.
