### ISSUE TITLE
Second build fails when `incremental` set to `true`

### ISSUE THREAD

**Issue by Moeriki** [rollup/plugins#249]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 4.0.0
- Rollup Version: 2.0.2
- Operating System (or Browser): macOS 10.15.3 (19D76)
- Node Version: 12.16.0

### How Do We Reproduce?

```
git clone git@github.com:Moeriki/bug-rollup-ts-incremental.git
cd bug-rollup-ts-incremental/
npm install
npm run build
npm run build
```

### Expected Behavior

Build succeeds two times.

### Actual Behavior

Build fails the second time.

### Work-around

```
npm run build
npm run clean
npm run build
```

Or set `compilerOptions.incremental` to `false`.

**Comment by shellscape** [comment]
@Moeriki thanks for the issue. Please verify that this also happens when using NPM. NPM is our baseline in the project for issues and repo-based reproductions.

**Comment by Moeriki** [comment]
Tested and verified the same issue with npm.

The issue though may be related to my compiler options. I'm still testing some things.

**Comment by VitorLuizC** [comment]
Maybe this is the cause of https://github.com/rollup/plugins/issues/287

**Comment by VitorLuizC** [comment]
Same happens here and we're using PNPM.

**Comment by shellscape** [comment]
Please use the "edit" function on replies to add info and cut down on noise.

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.

**Comment by VitorLuizC** [comment]
This was fixed?

**Comment by shellscape** [comment]
@VitorLuizC please re-read my previous comment.

**Comment by VitorLuizC** [comment]
I don't understand the concept of housekeeping. You're closing an issue that is not fixed to reduce number of open issues? I can't see the advantages in doing that.

**Comment by shellscape** [comment]
It's quite simple really; we have finite resources and must focus on issues that have activity and active triage. Housekeeping is very common in large projects (most even have bots that handle it for the project). We haven't received any help from the community to resolve this, which is unfortunate but OK, so we're closing this until such time that someone would like to pick up the effort.

If you're interested in contributing a fix for this issue, please do open a PR and we'll get some folks to review it.

**Comment by VitorLuizC** [comment]
I don't see how an open issue consume your finite resources. For me it seems to hide a problem that a new consumer of this lib would face and probably should at least see that is happening and anyone can made a PR to fix it, even when issue is open.
