### ISSUE TITLE
fileName option with [dirname] dosent work correctly, if sourcedir is current file dir

### ISSUE THREAD

**Issue by chrkulbe** [rollup/plugins#252]
- Rollup Plugin Name: plugin-run
- Rollup Plugin Version: 4.0.1
- Rollup Version: 1.29.0
- Operating System (or Browser): Win/Unix/Chrome
- Node Version: 12.14.1

### How Do We Reproduce?

https://repl.it/repls/HorizontalConstantDaemons

new fixture/jpg.js + add jpg.jpg files to fixtures and a subfolder (see imports - copied pgn.png)
```
import jpg from './jpg.jpg';
import jpg2 from './subfolder/jpg.jpg';

export const otherJpg = jpg2;
export default jpg;
```

append to tests.js
```
test.serial(
  'prefix the file with the parent directory of the source file, relative to the sourceDir option2',
  async (t) => {
    await run(t, 'jpg', {
      limit: 0,
      publicPath: './images/',
      fileName: '[dirname][name][extname]',
      sourceDir: join(__dirname, './fixtures')
  });
});
```

result in output/bundle.js for this single test
```
var jpg = "./images//jpg.jpg";

var jpg2 = "./images/subfolder/jpg.jpg";

const otherJpg = jpg2;

export default jpg;
export { otherJpg };
```

with fix 
```
var jpg = "./images/jpg.jpg";

var jpg2 = "./images/subfolder/jpg.jpg";

const otherJpg = jpg2;

export default jpg;
export { otherJpg }; 
```

Following code adds **/** behind **[dirname]** also it is emty
https://github.com/rollup/plugins/blob/bf94a85b488e2506f10ac64c46d53e70f037aba7/packages/url/src/index.js#L59

Following code prefix **outputFileName** with **publicPath** which can ends with **/**
https://github.com/rollup/plugins/blob/bf94a85b488e2506f10ac64c46d53e70f037aba7/packages/url/src/index.js#L62

=> double **//** in **data** path

### Fix
```
.replace(/\[dirname\]/g, relativeDir ? `${relativeDir}${sep}` : '')
```

### Expected Behavior

```
url({
    limit: 0,
    destDir: buildDir + '/assets/images/',
    publicPath: './assets/images/',
    sourceDir: nodejsPath.resolve(sourceDir, 'icons'),
    fileName: '[dirname][name]_[hash][extname]',
    include: ['**/*.svg'],
}),
```

Independent of direcory structure in **sourceDir** all files should be resolved correctly when **fileName** includes **[dirname]**.

**publicPath** ends with */* + file is a child of **sourcDir** => **relativeDir** is empty and must not add a **sep**
**publicPath** ends with */* + file is a descendant of **sourcDir** => **relativeDir** is not empty and adds a **sep**
**publicPath** does not ends with */* => independen of all a **/** mus be added

### Actual Behavior

If **publicPath** ends with **/** and a file is a direct child of **sourceDir**, **[dirname]** is empty and must not add an additional **/** if **[dirname]** is a part of **fileName**.

Also if the trailing */* will be forget on **publicPath** it will be missed when a file is in a subirectory of **sourceDir**.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further. WIthout a proper reproduction we cannot derive tests that match the scenario you're working within, and we cannot issue a proper fix.

**Comment by chrkulbe** [comment]
hope the new test helps to reproduce the bug

**Comment by shellscape** [comment]
We really appreciate you taking the time to report the issue and trace the cause. Really do. But the instructions for adding a proper reproduction could not be more clear. The maintainers here simply don't have the bandwidth to manually reconstruct a reproduction case, and that's why we ask issue reporters to do so. (There are a lot of issues from folks who have done that correctly) We cannot work on this issue without a proper reproduction, as stated in the issue template and the quote in my previous reply.

**Comment by chrkulbe** [comment]
Ok. I will add a repl later from home.

- https://repl.it/@rollup/rollup-plugin-repro is partially block from office
- https://rollupjs.org/repl/ -> here i dont know how to add the url plugin and add folder structure to reproduce the failure

**Comment by chrkulbe** [comment]
https://repl.it/repls/HorizontalConstantDaemons

hope that helps :o)

**Comment by shellscape** [comment]
Thanks!

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.
