### ISSUE TITLE
Upgrade from 3.0.0 to 4.0.0 crashes a build

### ISSUE THREAD

**Issue by houd1ni** [rollup/plugins#253]
- Rollup Plugin Name: typescript-plugin
- Rollup Plugin Version: 4.0.0
- Rollup Version: at least both 1.31.1 and 2.0
- Operating System (or Browser): window 10 latest
- Node Version: 13.x

I get the weird error after upgrade: 
```
[!] (plugin typescript) Error: Could not load D:/p/j/project/src/router.ts (imported by D:\p\j\project\src\main.ts): Debug Failure. False expression: Expected fileName to be present in command line
```

### How Do We Reproduce?
The plugin receives no config and I could not find any correlations with tsconfig. From not common is only that the project uses vue-plugin. Also the project is NDA one, and I cannot publish the whole codebase, but will answer to any questions as quickly as possible. Thanx !

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by etylsarin** [comment]
hi @houd1ni 
could you find a fix after all? I'm having the very same issue.

**Comment by houd1ni** [comment]
> 
> 
> hi @houd1ni
> could you find a fix after all? I'm having the very same issue.

hi @etylsarin  & @mbrevda
I kept running 3.0.0 until accidentally upgraded to 4.1.1 (with ^3.8.3 typescript, ^1.11.1 tslib and ^2.7.3 rollup versions), and it works for now.
