### ISSUE TITLE
Plugin-typescrip v4.0.0 JSX Error

### ISSUE THREAD

**Issue by paulrostorp** [rollup/plugins#254]
The plugin fails to compile jsx (react), getting this error: 
`[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`

- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 4.0.0
- Rollup Version: 2.0.3
- Operating System (or Browser): Mac os v 10.15.3
- Node Version: 12.13.1

### How Do We Reproduce?

https://repl.it/repls/CornsilkShinyRule
Install plugin-typescript and acorn-jsx as explained in the readme. Setup a react component and run rollup.
### Expected Behavior
compilation succeeds

### Actual Behavior
`[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by paulrostorp** [comment]
@shellscape https://repl.it/repls/CornsilkShinyRule

**Comment by rek** [comment]
I am also getting this error. Did you find any resolution yet? I have a simple config only using plugin-typescript.

**Comment by numfin** [comment]
@paulrostorp if i remove outDir from your tsconfig - everything is fine

**Comment by wilomgfx** [comment]
> @paulrostorp if i remove outDir from your tsconfig - everything is fine

If I do that, I get the following error 

`(plugin typescript) Error: @rollup/plugin-typescript: 'outDir' or 'declarationDir' must be specified to generate declaration files.`

I had to use https://github.com/ezolenko/rollup-plugin-typescript2 for now

**Comment by numfin** [comment]
@wilomgfx it's working without declarations.  I'am using typescript2 too btw. It's a lot more stable for me.

**Comment by NotWoods** [comment]
Quick fix for now is to manually set your `rootDir` compiler option to `"src"`. I'll keep working on fixing the default behavior.

**Comment by Mordag** [comment]
any updates on that?

**Comment by shellscape** [comment]
@Mordag please don't post replies asking if there are updates. if there are commits or pull requests related to the issue GitHub will display them in the thread for this issue

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.
