### ISSUE TITLE
Update @rollup/pluginutils peerDependency

### ISSUE THREAD

**Issue by juliovedovatto** [rollup/plugins#257]
- Rollup Plugin Name: @rollup/pluginutils
- Rollup Plugin Version: 3.0.8 (latest)
- Rollup Version: 2.0.3
- Operating System (or Browser): Any
- Node Version: 13

### How Do We Reproduce?

* Install rollup@latest
* install @rollup/pluginutils@latest

### Expected Behavior

No warnings

### Actual Behavior

Showing the following Warning

```
npm WARN @rollup/pluginutils@3.0.8 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
```

Since rollup new version (2.0.0) was released 6 days ago, I think it would be important to update peerDependency as well.

**Comment by shellscape** [comment]
Thanks, we're aware of the release. We'll be updating as we have time. Please feel free to submit PRs as well!
