### ISSUE TITLE
Watch mode cannot recover with typescript

### ISSUE THREAD

**Issue by karolis-sh** [rollup/plugins#258]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 4.0.0
- Rollup Version: 2.0.3
- Operating System (or Browser): mac
- Node Version: 10.15.0

Running rollup in watch mode with typescript plugin if the typescript code is invalid the watcher breaks and exits with exit code 1. This make it impossible to re-build the code on code changes - you need to re-start the command every time.

(`noEmitOnError ` ts compiler option doesn't help here)

### How Do We Reproduce?

https://github.com/karolis-sh/issue-rollup-typescript-1 (has a readme file)

### Expected Behavior

Watch mode should work just like using js files.

### Actual Behavior

Watch mode exits with exit code 1.

**Comment by danimoh** [comment]
Currently you have `noEmitOnError: true` in your project setup. Have you tried `noEmitOnError: false` to let typescript emit stuff even on errors instead of failing?

**Comment by karolis-sh** [comment]
@danimoh yes, it has no effect.

**Comment by Tylerian** [comment]
As stated on plugin readme, it ignores the `noEmitOnError` property defined in `tsconfig.json`.
You must add `noEmitOnError: false` on plugin setup. See example below:

```
/* rollup.config.js */
[...]
plugins: [
  typescript({
    noEmitOnError: false
  })
]
[...]
```

**Comment by karolis-sh** [comment]
@Tylerian yeah, you're right `typescript({ noEmitOnError: false })` makes the plugin usable in development mode.

Though I feel this should be enabled by default in watch mode, otherwise it's rather unintuitive.

**Comment by Tylerian** [comment]
> Though I feel this should be enabled by default in watch mode, otherwise it's rather unintuitive.

Yeah, I agree with that too. Perhaps you can open a new Feature Request so the maintainers can discuss this with you and hopefully agree to add it to the plugin.

**Comment by Hashbrown777** [comment]
For people who come across this because they want it on (/liked the default from before whenever #492 gets released) you can do this

```js
//tsopts
{
    noEmitOnError : !process.env.ROLLUP_WATCH
}
```
