### ISSUE TITLE
@rollup/plugin-replace has larger install size than rollup-plugin-replace

### ISSUE THREAD

**Issue by rdmurphy** [rollup/plugins#26]
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: 2.2.0
- Rollup Version: 1.26.3
- Operating System (or Browser): MacOS
- Node Version: v10.17.0

### How Do We Reproduce?

Hello! 👋 I noticed (for reasons I don't quite follow) that the install size for the replace plugin has seemingly ballooned after getting moved into the monorepo. Before the move it was a cool [2.64 MB](https://packagephobia.now.sh/result?p=rollup-plugin-replace).

<img width="611" alt="image" src="https://user-images.githubusercontent.com/419145/68107661-65ed9b00-fe9a-11e9-89b6-4077cff229a1.png">

But now it's much larger, at [44.4 MB](https://packagephobia.now.sh/result?p=%40rollup%2Fplugin-replace).

<img width="645" alt="image" src="https://user-images.githubusercontent.com/419145/68107688-81f13c80-fe9a-11e9-943e-19e1dc5f2dd5.png">

Is this a miscalcuation or did someone happen to change during the transition?

### Expected Behavior

The install size should be nearly identical post-move to the @rollup/plugin-replace.

### Actual Behavior

It is not.

--

Thank you!

**Comment by lukastaegert** [comment]
Apparently there is now an (implicit?) dependency on TypeScript: https://npm.anvaka.com/#/view/2d/%2540rollup%252Fplugin-replace

**Comment by Rich-Harris** [comment]
Fixed in 2.2.1 — thanks
