### ISSUE TITLE
Typescript plugin compatibility with rollup 2.0

### ISSUE THREAD

**Issue by yangmingshan** [rollup/plugins#263]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: v4.0.0

### Expected Behavior / Situation
Work fine with `rollup` v2.0

### Actual Behavior / Situation
Warning: @rollup/plugin-typescript@4.0.0" has incorrect peer dependency "rollup@^1.20.0".

### Modification Proposal
Is `@rollup/plugin-typescript` v4.0.0 compatible with `rollup` v2.0? If so, `peerDependencies` field needs to be updated.

**Comment by shellscape** [comment]
Please search before opening new issues. There is an open PR to address this.
