### ISSUE TITLE
Replace plugin compatibility with rollup 2.0

### ISSUE THREAD

**Issue by yangmingshan** [rollup/plugins#264]
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: v2.3.1

### Expected Behavior / Situation
Work fine with rollup v2.0

### Actual Behavior / Situation
Warning:
@rollup/plugin-replace@2.3.1" has incorrect peer dependency "rollup@^1.20.0".
@rollup/plugin-replace > @rollup/pluginutils@3.0.8" has incorrect peer dependency "rollup@^1.20.0".

### Modification Proposal
Is `@rollup/plugin-replace` v2.3.1 compatible with `rollup` v2.0? If so, `peerDependencies` field needs to be updated.

**Comment by shellscape** [comment]
Please search before opening new issues. There is an open PR to address this.

**Comment by jharris4** [comment]
> Please search before opening new issues. There is an open PR to address this.

I just searched for the open PR you mention, and if it exists it's not easy to find. A link would be helpful!

**Comment by yangmingshan** [comment]
Opening an issue may help users search.

**Comment by TrySound** [comment]
![image](https://user-images.githubusercontent.com/5635476/76745911-ad106480-6787-11ea-94ef-2f0c914dd20b.png)

**Comment by jharris4** [comment]
@TrySound what are you trying to show in this screenshot?

**Comment by TrySound** [comment]
How "not easy" to find.

**Comment by jharris4** [comment]
> How "not easy" to find.

Lol, I can't tell if you're being sarcastic?! Anyway, none of those PRs mentions the peer dependencies in case you were saying it **is easy** to find.

**Comment by TrySound** [comment]
I meant exactly this pr https://github.com/rollup/plugins/pull/244
If you look at the code it's full of peer dependencies updates. It's exactly what you asked about.
