### ISSUE TITLE
Remove `tslib` from peerDependencies of typescript plugin

### ISSUE THREAD

**Issue by yangmingshan** [rollup/plugins#265]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: v4.0.0

### Expected Behavior / Situation
No warning.

### Actual Behavior / Situation
Warning: @rollup/plugin-typescript@4.0.0" has unmet peer dependency "tslib@*".

### Modification Proposal
`tslib` is optional, I may not need it. It should not be used as a peer dependency.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by NotWoods** [comment]
We force the use of tslib to avoid duplicate code in the bundle. The relative Typescript compiler settings are always used. Without it, the tslib helpers would be copied for each .ts file that uses them. 

It's possible all your files don't utilize any helpers, but this is an edge case where you can just choose to ignore the warning.

**Comment by runspired** [comment]
@NotWoods we could make it optional for npm > 7

```
"peerDependenciesMeta": {
  "tslib": {
    "optional": true
  }
}
```
