### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by niklasgrewe** [rollup/plugins#267]
- Rollup Plugin Name: commonjs 
- Rollup Plugin Version: 11.0.2
- Rollup Version: 2.0.6
- Operating System (or Browser): Chrome
- Node Version: 12.16.1

### How Do We Reproduce

1. download the repo: [sapper-scrollscene](https://github.com/niklasgrewe/sapper-scrollscene)
2. run npm install
3. run npm run dev
4. open developer console in chrome 

### Expected Behavior

I can use the Plugin [ScrollScene](https://github.com/jonkwheeler/ScrollScene) in my svelte component like this:

```js
//my svelte component
<script>
   import { onMount } from 'svelte'
   import { ScrollScene } from 'scrollscene'
   import { gsap } from 'gsap'

   onMount(() => {
        const myTimeline = gsap.timeline({ paused: true })
        const domNode = document.querySelector('#element')
        const scrollTrigger = document.querySelector('.scroll-trigger-01')

         myTimeline.to(domNode, {
            x: -200,
            duration: 1,
            ease: 'power2.out',
          })

           const scrollScene = new ScrollScene({
           triggerElement: scrollTrigger,
           gsap: {
             timeline: tl,
             reverseSpeed: 4,
          },
     })
   })
</script>
```

### Actual Behavior

When i install and use the Plugin [ScrollScene](https://github.com/jonkwheeler/ScrollScene) in my sapper project, i get the error on console: `require is not defined`

Note: I am using the default `rollup.config.js` file from [sapper-template](https://github.com/sveltejs/sapper-template/blob/master/rollup.config.js)

The Problem is the file [scrollmagic-with-ssr](https://github.com/jonkwheeler/ScrollScene/blob/master/src/scrollmagic-with-ssr.ts) from scrollscene plugin

**Comment by shellscape** [comment]
Thanks for opening an issue. We're going to need you to distill that reproduction down to something [minimal](https://git.io/fNzHA) in order to triage from our end. Alternatively, we'd welcome additional triage from your end (and/or even an accompanying PR!)

**Comment by niklasgrewe** [comment]
I added a reproduction on Svelte RPL, hope this will help you:

https://svelte.dev/repl/3f8df9b044f94936b120465a687b3d35?version=3.20.0

**Comment by shellscape** [comment]
Unfortunately we don't have the bandwidth to learn and triage with svelte. We could certainly use a few more volunteers. If you can get this distilled to a minimal reproduction with just rollup, we'll be happy to reopen and look into it further.

**Comment by kotx** [comment]
@niklasgrewe I'm having the same issue but with importing `ipfs-core` on my end, have you found out a solution for this?
