### ISSUE TITLE
Alias plugin is not compatible with rollup-plugin-alias

### ISSUE THREAD

**Issue by thgh** [rollup/plugins#27]
- Rollup Plugin Name: alias
- Rollup Plugin Version: 2.2.0
- Rollup Version: latest
- Operating System (or Browser): unix
- Node Version: 12

### How Do We Reproduce?

Add `alias({ src: __dirname + '/src' })` to rollup plugins

### Expected Behavior

`import 'src/util.js'` works

### Actual Behavior

```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'src/util.js'
```

The API change in plugin-alias@2 breaks the old behaviour for no apparent reason. It's perfectly possible to add a special `entries` option. It's sad that a project with 20k+ downloads/week can just break dependency upgrades because one developer feels like it.
Breaking PR: https://github.com/rollup/rollup-plugin-alias/pull/53
Previous issue: https://github.com/rollup/rollup-plugin-alias/issues/58
Still incompatible PR: https://github.com/rollup/rollup-plugin-alias/pull/61

(sorry for repeating this issue)

**Comment by shellscape** [comment]
@thgh The tone of this one could be a little more friendly. The change was debated and discussed by @thiscantbeserious, @Andarist, and @lukastaegert - hardly one user. I'd argue it was up for a reasonable amount of time for discussion as well. From what I understand, the API changed, but the functionality remains.

**Comment by thiscantbeserious** [comment]
Maybe think about it like this instead:

Its way sadder that a developer feels the need to demand an change for an Open-Source project that he seemingly knows the perfect solution for neither provides the code noir takes part in the discussion of the PR that tries to fix this.

Apart from that - on a more neutral level:

Why don't you stick with V1?

**Comment by Andarist** [comment]
The reason for a change was simple - we believe that this is a better API than what was present in v1. It was hardly for "no apparent reason" - v2 was intentionally published as a major version and thus breaking changes are expected.

**Comment by shellscape** [comment]
@thgh has done a lot for Rollup over the years, so I highly doubt the concerns are conveyed with ill intent. I'd ask everyone commenting take that into consideration. I didn't tag everyone with the intent to cause a pile-on, rather to further discuss the changes that were made.

I'd be interested to know if there's middle ground here.

**Comment by thgh** [comment]
First of all, sorry for the tone of the issue. I think it's fantastic that you all take the initiative to maintain many plugins. Also, I'm definitely not trying to point fingers (even though I see now that it looked that way). It's more that I'm concerned about the stability of the Rollup plugin ecosystem.

Another concern is that tons of developers have struggled to configure webpack. Requiring them to  learn another plugin configuration brings mental overhead. The effort to support both syntaxes in code is trivial, so I think the tradeoff leans in that direction.

I hope the PR brings us closer to middle ground ;-)

Note: I'm currently sticking to v1, but it's marked as deprecated (which triggered me to post this issue).
