### ISSUE TITLE
"ReferenceError: window is not defined" when using @rollup/plugin-commonjs making service worker

### ISSUE THREAD

**Issue by gwynjudd** [rollup/plugins#273]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 10.1.0
- Rollup Version: 2.1.0
- Operating System (or Browser): Chrome
- Node Version: v10.16.3

### How Do We Reproduce?

package.json:

```
{
  "name": "service-worker",
  "version": "1.0.0",
  "description": "service worker for touch",
  "main": "index.js",
  "scripts": {
    "build": "rollup -c"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.8.7",
    "@babel/preset-env": "^7.8.7",
    "@rollup/plugin-node-resolve": "^7.1.1",
    "babel-plugin-transform-async-to-promises": "^0.8.15",
    "rollup": "^2.1.0",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-terser": "^5.3.0"
  },
  "dependencies": {
    "cache-polyfill": "^1.0.1"
  }
}

```

rollup.config.js:

```
import pluginBabel from 'rollup-plugin-babel'
import pluginCommonJS from 'rollup-plugin-commonjs'
import resolve from '@rollup/plugin-node-resolve';
import { terser as pluginTerser } from 'rollup-plugin-terser'

export default {
	input: 'asdf.js',

	plugins: [
		pluginCommonJS(),

		pluginBabel({
			exclude: /node_modules/,

			presets: [
				[
					'@babel/preset-env',
					{
						exclude: ['transform-async-to-generator', 'transform-regenerator'],
					},
				],
			],

			plugins: []
		}),

		// pluginTerser(),
		resolve()
	],

	output: {
		sourcemap: true,
		file: 'sw.js',
		name: 'serviceWorker',
		format: 'iife',
	},
}

```

asdf.js:

`import { cachePolyfill as _caches } from "cache-polyfill";
`

### Expected Behavior

To generate a service worker that can be installed and runs. The above trivial example demonstrates the problem I am seeing.

### Actual Behavior

The generated file includes a reference to "window" which is not defined in a service worker:

![image](https://user-images.githubusercontent.com/314188/77113013-e6e6b100-6a8e-11ea-9f45-9a9018767201.png)

At installation time, this:

![image](https://user-images.githubusercontent.com/314188/77113144-22817b00-6a8f-11ea-8aee-6b447a6e8bd3.png)

Any advice or assistance would be helpful. I've not used rollup before.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
