### ISSUE TITLE
plugin-node-resolve: make generated node-modules folder path customizable

### ISSUE THREAD

**Issue by 0biWanKenobi** [rollup/plugins#277]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: 7.1.1

### Feature Use Case

I'm currently building a chrome extension, but this can be generalized as:
- having the entry point nested in one or more subfolders
- wanting to preserve node modules as separate files
- wanting to preserve source folder tree 
- wanting node_modules folder to be in a specific location (will detail this )

This is an example:
![alt text](https://i.imgur.com/M2Jo5mZ.png) 

`main.js` is nested, and ideally I'd like the generated `node_modules` folder to sit beside it. *However*, if I set the output dir as `dist/src/browser_action`, the resulting folder tree is

`main.js` ->  `dist/src/browser_action/src/browser_action`  ❌
`node_modules` -> `dist/src/browser_action` ✔

and vice versa, if I set the output dir as just `dist` ..

`main.js` ->  `dist/src/browser_action/` ✔
`node_modules` -> `dist/` ❌

### Feature Proposal

If possibile, a way to tell the plugin to use the output dir, or file path. Alternatively, a separate option to tell the plugin where to put its files, similar to postcss's `extract` parameter. Or even just a way to tell the plugin to honor the output path without replicating the input's structure. Because the replication does *not* happen here, for example, because I'm not using `resolve` plugin:

![image](https://user-images.githubusercontent.com/4061104/77214430-7764d600-6b0f-11ea-8b82-74f6fb81e172.png)

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.
