### ISSUE TITLE
@rollup/plugin-legacy npm package not found

### ISSUE THREAD

**Issue by unre4l** [rollup/plugins#278]
- Rollup Plugin Name: @rollup/plugin-legacy
- Rollup Plugin Version: latest
- Rollup Version: -
- Operating System (or Browser): Ubuntu 19.10
- Node Version: 12.16.1 (npm 6.13.4, yarn 1.22.4) 

### How Do We Reproduce?

Run suggested install script from plugin's readme:

```
npm install @rollup/plugin-legacy --save-dev
```

### Expected Behavior

Finds and installs npm module.

### Actual Behavior

```
404 Not Found - GET https://registry.npmjs.org/@rollup%2fplugin-legacy - Not found
npm ERR! 404  '@rollup/plugin-legacy@latest' is not in the npm registry.
```

Screen from repo page: 

![image](https://user-images.githubusercontent.com/8525537/77238694-ed7e4100-6bd2-11ea-8c96-d0407f4ec895.png)

**Comment by shellscape** [comment]
Thanks for reporting. Just published it.
