### ISSUE TITLE
Add a typescript declaration file for rollup-plugin-babel.？

### ISSUE THREAD

**Issue by masx200** [rollup/plugins#279]
- Rollup Plugin Name:  rollup-plugin-babel
- Rollup Plugin Version:4.4.0

### Feature Use Case

Cannot find type declaration file

'@types/rollup-plugin-babel'

### Feature Proposal

Add a typescript declaration file for rollup-plugin-babel.？

**Comment by shellscape** [comment]
Sorry, but that plugin is not yet part of this repo. Please open an issue here: https://github.com/rollup/rollup-plugin-babel
