### ISSUE TITLE
alias.resolve doesn't work for svelte 3

### ISSUE THREAD

**Issue by colesico** [rollup/plugins#28]
- Rollup Plugin Name: @rollup/plugin-alias
- Rollup Plugin Version: 2.2.0
- Rollup Version: 1.26.0
- Operating System (or Browser):  os win 10 firefox
- Node Version: v10.13.0

### How Do We Reproduce?

rollup config:
```
export default {
 ...
plugins: [
 alias({ 
            resolve: ['.js','.svelte' ],
            entries: [
                {find:'@', replacement:'src'}
            ]            
        })
]
}
```
### Expected Behavior
  UiAlertTag  shoud be imported
```
<script>
 // Target file: ...UiAlertTag.svelte

  import UiAlertTag from "@/core/widget/UiAlertTag"; // does not work. Error: coudn't open file...
//   import UiAlertTag from "@/core/widget/UiAlertTag.svelte";  // this is ok.
</script>
```
### Actual Behavior

[!] (plugin Rollup Core) Error: Could not load src/core/widget/UiAlertTag (imported by c:\MyProjects\my\armario\app-webui\src\directory\pages\trademark\UpdateTrademark.svelte): ENOENT: no such file or directory, open 'c:\MyProjects\my\armario\app-webui\src\core\widget\UiAlertTag'
Error: Could not load src/core/widget/UiAlertTag (imported by c:\MyProjects\my\armario\app-webui\src\directory\pages\trademark\UpdateTrademark.svelte): ENOENT: no such file or directory, open 'c:\MyProjects\my\armario\app-webui\src\core\widget\UiAlertTag'

**Comment by colesico** [comment]
this works as expectd. 
```
resolve: ['.svelte','.js'],
            entries: [
                {find:'src', replacement:path.resolve(projectRootDir, "src")}
            ],
```

**Comment by chovyprognos** [comment]
how do i import the alias plugin?
