### ISSUE TITLE
Bad link in packages/node-resolve/README.md

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/plugins#283]
https://github.com/rollup/plugins/tree/master/packages/node-resolve#using-with-rollupplugin-commonjs says:
> Since most packages in your node_modules folder are probably legacy CommonJS rather than JavaScript modules, you may need to use @rollup/plugin-commonjs

The latter is a hyperlink to https://github.com/rollup/plugins/packages/commonjs, but this destination does not exist.  It should be https://github.com/rollup/plugins/tree/master/packages/commonjs.

**Comment by shellscape** [comment]
Sorry, but Issue templates are not optional in this repo. If you would like us to consider this issue, please fill out the appropriate template.

**Comment by dilyanpalauzov** [comment]
I have not realized that the process is that cumbersome.  I do not want, that you consider anything.

**Comment by shellscape** [comment]
Well I guess we can make this more straightforward:

>   If you're using this template to report an issue covered by an existing issue
  type, we'll close it as invalid faster than you can spell 'Mississippi'.

Failure to read the warnings in the issue templates are not the fault of the maintainers of the project. Thousands of prior contributors and amazing folks have used the issue templates to report an issue without anything being "cumbersome." There's just no excuse for disregarding information given to you.
