### ISSUE TITLE
Publish node-resolve to allow using Rollup 2.

### ISSUE THREAD

**Issue by slnovak** [rollup/plugins#285]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: 7.1.1

### Feature Use Case
7.1.1 has a dependency on Rollup @ [^1.29.0](https://github.com/rollup/plugins/blob/node-resolve-v7.1.1/packages/node-resolve/package.json#L62). After #244 ("Audit for Rollup@2.0.0"), the dependency was bumped to [^1.20.0||^2.0.0](https://github.com/rollup/plugins/blob/master/packages/node-resolve/package.json#L48). It'd be great to release a version bump for node-resolve so that it can be used with Rollup 2.

### Feature Proposal
N/A.

**Comment by shellscape** [comment]
Thanks for opening an issue. Plugins are published as maintainers have the chance. Please hold tight.

**Comment by slnovak** [comment]
Thanks! I appreciate all the hard work that library maintainers have be doing to bring Rollup up to 2.0. Sorry for the noise!
