### ISSUE TITLE
Resolved path to babel runtime helpers is broken in Windows

### ISSUE THREAD

**Issue by johannes-z** [rollup/plugins#290]
- Rollup Plugin Name: @rollup/plugin-commonjs (or @rollup/plugin-node-resolve)
- Rollup Plugin Version: ^11.0.2 (^7.1.1)
- Rollup Version: ^2.3.1
- Operating System (or Browser): Windows 10
- Node Version: 11.13.0

### How Do We Reproduce?

```js
export default {
  // ...
  plugins: {
    babel: {
      exclude: 'node_modules/**',
      extensions: ['.js', '.jsx', '.ts', '.tsx', '.vue'],
      presets: [
        [
          '@vue/cli-plugin-babel/preset',
          {
            corejs: 3,
            modules: false,
            useBuiltIns: 'usage',
          },
        ],
      ],
      runtimeHelpers: true,
    },
    resolve(),
    commonjs(),
  }
}
```

### Expected Behavior

Successful build and runable file. 

### Actual Behavior

Adding `commonjs` to the plugin section breaks the final build, because the path is not correctly resolved on windows. `rollup-plugin-vue` has a similar issues, where Backslashes are missing from the path:

```
(!) Unresolved dependencies

C:UsersjohanneszProjectsMyproject
untime/helpers/typeof (imported by ..\..\..\node_modules\regenerator-runtime\runtime.js,  C:UsersjohanneszProjectsMyproject
untime/helpers/typeof?commonjs-external
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by johannes-z** [comment]
This is a commercial project where I'm using rollup. I can share a private repo as reproduction to an assignee.

**Comment by shellscape** [comment]
@johannes-z a private repo would not be a minimal reproduction. Please read the provided link on #2 for instructions for a minimal repo. Alternatively, you can use one of the REPLs to reconstruct a minimal reproduction.

**Comment by johannes-z** [comment]
@shellscape Sorry, must have read over it. I created a repro here: https://github.com/johannes-z/rollup-yarn-path-error

While creating the repro I found out that this has to do with yarn's monorepo symlinking. Without the monorepo rollup builds the bundle correctly. 

See https://github.com/johannes-z/rollup-yarn-path-error/blob/master/packages/core/dist/bundle.js#L2-L5

**Comment by shellscape** [comment]
Thanks for the repo. Because this is specific to yarn, please open an issue with the yarn project and ask them for help to resolve. (We use `pnpm` in this repo and have no issues with `plugin-commonjs` and the way it performs symlinking) We'll leave this open until that issue has a resolution. Please make sure to link back to this one for tracking.

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.
