### ISSUE TITLE
Plugins have incorrect peerDependency fields

### ISSUE THREAD

**Issue by MrJohz** [rollup/plugins#293]
- Rollup Plugin Name: node-resolve (at least, probably others as well)
- Rollup Plugin Version: 7.1.1
- Rollup Version: 2.3.0
- Operating System (or Browser): Linux
- Node Version: v13.7.0

### How Do We Reproduce?

[Repl.it link](https://repl.it/repls/DishonestMajesticRectangles)

Or run these commands in a fresh temp directory:

```
npm init -y
npm install --save-dev rollup
npm install --save-dev @rollup/plugin-node-resolve
```

(That's basically the same as what the Repl.it link does.)

### Expected Behavior

NPM should happily install the two dependencies.

### Actual Behavior

NPM provides the following warnings:

```
npm WARN @rollup/plugin-node-resolve@7.1.1 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @rollup/pluginutils@3.0.8 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
```

In the git repository here, I can see that the `package.json` file has this peer dependency:

```
  "peerDependencies": {
    "rollup": "^1.20.0||^2.0.0"
  },
```

However, if I look at the `package.json` that actually gets distributed to NPM (e.g. [here](https://unpkg.com/@rollup/plugin-node-resolve@7.1.1/package.json)), it looks like this:

```
  "peerDependencies": {
    "rollup": "^1.20.0"
  },
```

I originally raised this as a pnpm issue (pnpm/pnpm#2449) but they pointed out the discrepancy between the two `package.json` files and pointed me at raising a ticket here.

**Comment by shellscape** [comment]
that's not a bug. there's a PR which updated them and some haven't been published as yet. please exercise patience.

**Comment by crfrolik** [comment]
Is there anything we can do to help move this along? It looks like the PR was merged but all that remains is to publish them.
