### ISSUE TITLE
Replace plugin: Unexpected token when using "process" plain text in Svelte

### ISSUE THREAD

**Issue by MichielLeyman** [rollup/plugins#294]
- Rollup Plugin Name: replace
- Rollup Plugin Version: 2.3.1
- Rollup Version: 1.20.0
- Operating System (or Browser): Fedora 31
- Node Version: 10.16.3

### How Do We Reproduce?

https://repl.it/repls/ScarceOverjoyedRoute

### Expected Behavior

Using the plaintext "process" should not stop the application from compiling. Every time I use "process" in the HTML section of a `.svelte` file, things break.
Finding the source of this issue took quite a while, I haven't found any other keywords that break compilation.

### Actual Behavior

`Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`

**Comment by shellscape** [comment]
Thanks for reporting. Do you have a stack trace handy you could add to the issue? (I'm away from my machine right now, but was curious)

**Comment by MichielLeyman** [comment]
```
src/main.js → public/build/bundle.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
src/App.svelte: (24:23)
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/App.svelte (24:23)
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/runner/ScarceOverjoyedRoute/node_modules/rollup/dist/rollup.js:5365:30)
    at Module.error (/home/runner/ScarceOverjoyedRoute/node_modules/rollup/dist/rollup.js:9708:9)
    at tryParse (/home/runner/ScarceOverjoyedRoute/node_modules/rollup/dist/rollup.js:9617:16)
    at Module.setSource (/home/runner/ScarceOverjoyedRoute/node_modules/rollup/dist/rollup.js:9935:33)
    at Promise.resolve.catch.then.then.then (/home/runner/ScarceOverjoyedRoute/node_modules/rollup/dist/rollup.js:12205:20)
```

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.

**Comment by ganigeorgiev** [comment]
@shellscape Please reopen the issue. I've just stumbled upon this and it took me a while to find out what was breaking the compilation. The error output is similar to that posted by @MichielLeyman.

**Comment by shellscape** [comment]
We don't reopen stale issues unless someone is willing to take it on.

**Comment by ganigeorgiev** [comment]
@shellscape Could you at least point me where to look?

**Comment by MichielLeyman** [comment]
@ganigeorgiev If I recall correctly, this happened because I used the replace plugin a certain way to pass environment variables. I ended up passing making variables globally available instead, as a workaround in that project:
```
replace({
  NODE_ENV: JSON.stringify(process.env.NODE_ENV),
})
```

**Comment by ganigeorgiev** [comment]
@MichielLeyman Ah, thank you.

**Comment by brettinternet** [comment]
This error occurred for me when I did not properly stringify a value.
