### ISSUE TITLE
Typescript helpers not been emitted

### ISSUE THREAD

**Issue by roddolf** [rollup/plugins#297]
- Rollup Plugin Name: plugin-typescript
- Rollup Plugin Version: 4, 3, 2 
- Rollup Version: 2.3.3
- Operating System (or Browser): Windows
- Node Version: 10.18.1

### How Do We Reproduce?

Example repo: https://github.com/roddolf/rollup-ts-test
It contains the processed output: `index.js`.
You can also run `npm start`

### Expected Behavior

Emit the respective helpers of typescript.

### Actual Behavior

No helpers are limited thus generating incorrect code.

**Comment by matthew-dean** [comment]
Is this related to this error: `ts.getOutputFileNames is not a function`?

**Comment by NotWoods** [comment]
You may need to update your version of typescript if you're getting that error.

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.

**Comment by tounks** [comment]
> You may need to update your version of typescript if you're getting that error.

not worked
