### ISSUE TITLE
core-js internals not resolved in yarn monorepo

### ISSUE THREAD

**Issue by johannes-z** [rollup/plugins#298]
- Rollup Plugin Name: `@rollup/plugin-node-resolve`
- Rollup Plugin Version: `7.1.1`
- Rollup Version: `2.3.4`
- Operating System (or Browser): Ubuntu 18.04
- Node Version: `v13.12.0`

### How Do We Reproduce?

https://github.com/johannes-z/rollup-babel-yarn

```sh
git clone https://github.com/johannes-z/rollup-babel-yarn
cd rollup-babel-yarn
yarn
yarn workspace consumer build
```

### Expected Behavior
`core-js` internals should be resolved correctly and inlined with the bundle.

### Actual Behavior
`core-js` internals are not resolved: https://github.com/johannes-z/rollup-babel-yarn/blob/master/packages/consumer/lib/main.js#L1-L19

I've also created an issue in `rollup-plugin-babel` because I don't really know which plugin is to blame, but since I investigated a little further, I think it's either `node-resolve` or `common-js`, because babel, node-resolve and commonjs work in a non-monorepo scenario.

For example, if you copy `package/consumer` out of the monorepo, `yarn` and `yarn build`, it will work correctly.

What I tried:

* `preserveSymlinks` does nothing
* add `extensions` to all plugins
* set `rootDir` in `node_resolve`
* removed `typescript` - it doesn't work with or without it, so I left it in
* passing `preserveSymlinks` with `customResolveOptions`
* tried various regex/minmatches within `commonjs`'s `include` option

**Comment by shellscape** [comment]
yarn has notorious issues with symlinking and module resolution in monorepos. We fight it daily in my day job. I'd recommend trying to play with the hoisting settings, or using alternatives like pnpm to see if the issue persists.

**Comment by johannes-z** [comment]
@shellscape Yeah I also use yarn in my day job, and while it's super convenient most of the time, there are times like these where nothing works :joy:

I tried switching to pnpm, but I have the same issue: https://github.com/johannes-z/rollup-babel-yarn/tree/pnpm

pnpm has other flaws too, for example I had to add some devDependencies: https://github.com/johannes-z/rollup-babel-yarn/commit/d165510ea6cf27bd668af9b3a67eedd019505df7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

`preserveSymlinks` didn't help using pnpm either...

**Comment by shellscape** [comment]
good to know thanks for trying that ouy

**Comment by johannes-z** [comment]
Ok this might have been an issue that stems from the `rollup-plugin-babel` plugin. With https://github.com/rollup/rollup-plugin-babel/issues/361#issuecomment-610953491 it gets resolved correctly, even with yarn.

**Comment by shellscape** [comment]
awesome, thank you for the hard work triaging this!
