### ISSUE TITLE
Export `defaults` from `node-resolve` plugin

### ISSUE THREAD

**Issue by KubaJastrz** [rollup/plugins#299]
- Rollup Plugin Name: `node-resolve`
- Rollup Plugin Version: 7.1.1

### Feature Use Case

I want to be able to add `.ts` and `.tsx` extensions when using TypeScript but I have to manually repeat default values which adds up unnecessary manual work. If the defaults were exported, I could reuse them easily.

This would function similarly to [`const { defaults } = require('jest-config')`](https://unpkg.com/browse/jest-config@25.3.0/build/Defaults.js).

I can create a PR if you want.

### Feature Proposal

Add `export` keyword to https://github.com/rollup/plugins/blob/cabe7108f5fa0f618eee07fc2c09392cb88e3de5/packages/node-resolve/src/index.js#L20

**Comment by shellscape** [comment]
Thanks for the issue. Please expand on your use case further, I don't quite understand what you're trying to do. More code would definitely help.

**Comment by KubaJastrz** [comment]
Sorry if I wasn't clear enough. For `node-resolve` plugin to see TypeScript files, it needs to be configured to allow `.ts` and `.tsx` extensions. If I just set `extensions: ['.ts', '.tsx']` it obviously won't work because it will override default extensions.

I could copy and paste defaults and add my custom extensions but I feel like this could be improved by exporting defaults.

You can see the example here: https://github.com/kentcdodds/kcd-scripts/pull/131/files#diff-a1cfe028f2f056e2d30db017481d4ad0R146-R150

**Comment by shellscape** [comment]
Thanks for explaining the use case further. Would it be more useful to expose defaults, or do a deep merge on the defaults and options?

**Comment by KubaJastrz** [comment]
I think that exposing defaults is simpler in terms of implementation and gives more control to the user.
