### ISSUE TITLE
Forgot to publish @rollup/pluginutils?

### ISSUE THREAD

**Issue by csr632** [rollup/plugins#300]
The [package.json in this repo](https://github.com/rollup/plugins/blob/cabe7108f5fa0f618eee07fc2c09392cb88e3de5/packages/pluginutils/package.json#L50) is different from [the package.json in the npm package](https://www.unpkg.com/browse/@rollup/pluginutils@3.0.8/package.json).

This leads to `@types/estree` missing:
![image](https://user-images.githubusercontent.com/18747423/78988738-5d457300-7b64-11ea-9217-d08f8c36aed7.png)

Please publish the latest @rollup/pluginutils!

**Comment by shellscape** [comment]
Please don't open issues about package publishing. we get to that as we are able.
