### ISSUE TITLE
Node.js isn't importing the plugins' es bundles

### ISSUE THREAD

**Issue by nstepien** [rollup/plugins#302]
- Rollup Plugin Name: All of them?
- Rollup Plugin Version: *

### Expected Behavior / Situation
Node.js loads the published es bundles.

### Actual Behavior / Situation
Node.js loads the published cjs bundles instead.

### Modification Proposal
Let's take `@rollup/plugin-node-resolve` as an example:
- The `exports` field must be added to the `package.json`:
  - ```json
      "module": "dist/index.es.mjs",
      "exports": "./dist/index.es.mjs",
    ```
  - the `./` prefix is important, otherwise I get this error:
    ```
    Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target dist/index.es.mjs defined in the package config D:\xxx\node_modules\@rollup\plugin-node-resolve\package.json imported from D:\xxx\rollup.config.mjs.
    ```
  - the `.mjs` extension is important, otherwise I get this error:
    ```
    [!] SyntaxError: Cannot use import statement outside a module
    D:\xxx\node_modules\@rollup\plugin-node-resolve\dist\index.es.js:1
    import { dirname, resolve, extname, normalize, sep } from 'path';
    ^^^^^^
    ```
  - Doc: https://nodejs.org/api/esm.html#esm_packages
- Some imports for commonjs packages might need to be tweaked,  otherwise I get errors like this:
  - ```
    (node:24348) ExperimentalWarning: The ESM module loader is experimental.
    [!] SyntaxError: The requested module '@rollup/pluginutils' does not provide an export named 'createFilter'
    file:///D:/xxx/node_modules/@rollup/plugin-node-resolve/dist/index.es.mjs:6
    import { createFilter } from '@rollup/pluginutils';
             ^^^^^^^^^^^^
    ```
  - This can be fixed by using the default module export:
    ```js
    import pluginUtils from '@rollup/pluginutils';
    const { createFilter } = pluginUtils;
    ```
  - Doc: https://nodejs.org/api/esm.html#esm_interoperability_with_commonjs

**Comment by shellscape** [comment]
Given that this is first and only report we've had about this, I'd like to ask for a reproduction repo with specific instructions covering what versions, flags, etc need to be present in order to reproduce the scenario in which a change is necessary. Once we've got that to play with, we'll start triage.

**Comment by nstepien** [comment]
FWIW this isn't a bug, the plugins still work when using an mjs config file, but Node.js falls back to importing the cjs modules instead.
It does affect the new babel plugin, as I now have to do
```js
import babel from '@rollup/plugin-babel';
// ...
babel.default({ ... })
```
instead of just
```js
import babel from '@rollup/plugin-babel';
// ...
babel({ ... })
```

The other plugins I've used work fine with the default export.
Let me know if you still want a repro repo.

**Comment by NotWoods** [comment]
FYI you can use `import { babel } from '@rollup/plugin-babel'`. (That should be updated in docs & other plugins). I think supporting module import in latest Node is low priority as the CJS versions work just as well.

**Comment by NetOperatorWibby** [comment]
I believe the error I have is related to this:

```error
[!] Error: No valid exports main found for '~/project/node_modules/@rollup/pluginutils'
Error: No valid exports main found for '~/project/node_modules/@rollup/pluginutils'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (~/project/node_modules/@rollup/plugin-commonjs/dist/index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
```

The plugins in my rollup config are `@rollup/plugin-commonjs`, `rollup-plugin-livereload`, `@rollup/plugin-node-resolve`, `rollup-plugin-stimulus`, and `@rollup/plugin-sucrase`. I'll update this comment once I figure out which one is giving me issues.
