### ISSUE TITLE
plugin @rollup/plugin-node-resolve is not published and doesn't work with @babel/plugin-typescript

### ISSUE THREAD

**Issue by stalniy** [rollup/plugins#303]
- Rollup Plugin Name: @rollup/node-resolve
- Rollup Plugin Version: 7.1.1
- Rollup Version: 2.6.0
- Operating System (or Browser): Chrome, Linux Antegros
- Node Version: v12.13.0

### How Do We Reproduce?

**You can find reproduction here** - https://repl.it/repls/SubduedOriginalSystems

### Expected Behavior

Plugin correctly resolves path and allows to import typescript types from other files

### Actual Behavior

There are actually 2 issues:
1. If you try to install `@rollup/plugin-node-resolve` using `yarn`, you will get warnings:
    > warning " > @rollup/plugin-node-resolve@7.1.1" has incorrect peer dependency "rollup@^1.20.0". 
    > warning "@rollup/plugin-node-resolve > @rollup/pluginutils@3.0.8" has incorrect peer dependency "rollup

    After checking source code on github I see that 7.1.1 was published 2 month ago and plugin was adopted to 2.0 version 24 days ago. So, it seems that version was not published!
2. Probably due to unpublished plugin rollup@2 is incorrectly works with @rollup/plugin-node-resolve@7.1.1. I'm trying to import typescript types from another file and get error

   > Error: 'Test' is not exported by src/types.ts, imported by src/index.ts

**Comment by shellscape** [comment]
Thanks for reporting. we publish as we have time

**Comment by stalniy** [comment]
I understand that you do not have always time to do all the things in such a big project. I can understand this because I support my own open source project. Thanks for doing a great job! I like rollup and its ecosystem, even wrote 2 own plugins myself

Unfortunately this blocks me to upgrade to rollup to 2.x version :(

Did you consider to use something like https://semantic-release.gitbook.io/semantic-release/ ?

**Comment by shellscape** [comment]
We have but there is usually a lot of nuance with publishing these.

Also please feel free to add your plugins to roll-up/awesome!

**Comment by shellscape** [comment]
We've just published a bunch of packages tonight, including this one.

**Comment by stalniy** [comment]
Unfortunately the same example doesn't work even with new versions. I'll try to setup the demo with versions were it works
