### ISSUE TITLE
Mixing import and require of external module leads to undefined _commonjsExternal variable

### ISSUE THREAD

**Issue by michaelfig** [rollup/plugins#305]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 11.1.0
- Rollup Version: 2.6.1
- Operating System (or Browser): MacOS
- Node Version: v13.8.0

### How Do We Reproduce?

1. Create a file named `test-bug.js`.  If you need to see the code in action, then `yarn install @agoric/harden`:

```js
import harden from '@agoric/harden';
debugger;
harden({});
const harden2 = require('@agoric/harden');
harden2({});
```

2. Run rollup with the following configuration:

```js
import rollup from 'rollup';
import resolvePlugin from '@rollup/plugin-node-resolve';
import commonjsPlugin from '@rollup/plugin-commonjs';

const bundle = await rollup({
    input: './test-bug.js',
    treeshake: false,
    preserveModules: true,
    external: ['@agoric/harden'],
    plugins: [
      resolvePlugin({ preferBuiltins: true }),
      commonjsPlugin(),
    ],
});
const { output } = await bundle.generate({
  exports: 'named',
  format: 'cjs',
  sourcemap: true,
});
console.log(output[0]);
 ```

### Expected Behavior

Imports and requires of `@agoric/harden` can be mixed, leading to correct behaviour.

### Actual Behavior

`harden_commonjsExternal` is not defined.

Here is the output of the above code:

```js
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var harden = _interopDefault(require('@agoric/harden'));
require('./_virtual/harden_commonjs-external');

harden_commonjsExternal.default({});

harden_commonjsExternal.default({});
```

Note that the `require('./_virtual/harden_commonjs-external')` is not assigned to a variable

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to reopen and triage further.

**Comment by crfrolik** [comment]
I made an attempt to create a repl.it from the example @michaelfig posted. Hopefully I did it right: https://repl.it/@crfrolik/SimplisticVirtualModem

**Comment by michaelfig** [comment]
> I made an attempt to create a repl.it from the example @michaelfig posted. Hopefully I did it right: https://repl.it/@crfrolik/SimplisticVirtualModem

Thanks!  That exactly captures the failure I was seeing.

**Comment by danielgindi** [comment]
I think it's a bug with rollup's `preserveModules: true` feature.
It only happens with it on, and I see the output from `commonjs` plugin being right and valid.

I've added a `function` test, with the following files:
*_config.js*:
```js
module.exports = {
  options: {
    preserveModules: true
  }
};
```

*main.js*:
```js
import Path from 'path';
const Path2 = require('path');

t.is(Path.normalize('foo\\bar'), Path2.normalize('foo\\bar'));
```

Now `commonjs` plugin spits out:
*main.js*:
```js
import 'path';
import Path2 from 'path?commonjs-proxy';

import Path from 'path';


t.is(Path.normalize('foo\\bar'), Path2.normalize('foo\\bar'));
```

*path?commonjs-external*:
```js
import path from "path"; export default path;
```

Now rollup spits out:
```js
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var path = _interopDefault(require('path'));
require('./_virtual/_path_commonjs-external');

t.is(_path_commonjsExternal.normalize('foo\\bar'), _path_commonjsExternal.normalize('foo\\bar'));
```

The "virtual" file is there, but for some reason `rollup` removes variable assignment from `require('./_virtual/_path_commonjs-external')` to `Path2` which is apparently renamed to `_path_commonjsExternal` (but still removed).

**Comment by danielgindi** [comment]
@shellscape Note that the bug seems not to be in `commonjs` plugin at all, but in rollup's `preserveModules: true` feature. This issue should be reopened there. I wrote a detailed summary of this.

**Comment by shellscape** [comment]
@lukastaegert should we transfer this issue to rollup/rollup?

**Comment by lukastaegert** [comment]
Yes, though I hope we can find a reproduction without this plugin.

**Comment by danielgindi** [comment]
> Yes, though I hope we can find a reproduction without this plugin.

Easily, just copying and pasting the previous rollup-commonjs output into repl, letting rollup roll it up.
https://repl.it/repls/WiseSpectacularEditors

Just ignore the runtime error, as it does not have the 'path' module in the repl. Look at the output folder.

**Comment by lukastaegert** [comment]
Created rollup/rollup#3517 to track with a simple rollup-only repro

**Comment by lukastaegert** [comment]
@danielgindi Ah, sorry, missed your last comment, thanks!
