### ISSUE TITLE
Plugin commonjs, output changed unexpectedly from `11.0` to `11.1`

### ISSUE THREAD

**Issue by Fadoli** [rollup/plugins#309]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 11.1.0
- Rollup Version: 2.6.1
- Operating System (or Browser): Linux Ubuntu 19.10
- Node Version: 12.13.1

### How Do We Reproduce?

Bugs occurs when packing file that is an export and not a final executable file.

This happens when packing for a Node-Red module. Those module (for Node-Red) use module.exports to be later imported by the runtime.

```js
// Here we import files we need
const lib = require (...)

// Here we do the expected Node-Red friendly export
module.exports = function (RED) {
       // Here the main node-red module code
}
```

### Expected Behavior

As of `11.0`, the module.exports is properly kept in the output file

### Actual Behavior

As of `11.1`, the module.exports is not kept in the output file

If more details are required, I can provide examples.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
