### ISSUE TITLE
`module.require` is not supported

### ISSUE THREAD

**Issue by arantes555** [rollup/plugins#310]
- Rollup Plugin Name: `@rollup/plugin-commonjs`
- Rollup Plugin Version: up to 11.1.0
- Rollup Version: 1.27.14
- Operating System (or Browser): any
- Node Version: 12

### How Do We Reproduce?

Node has 2 ways inside a CommonJS module to require another CommonJS module : the classic `require()` that everyone uses, and the less-well-known `module.require()` (doc here : https://nodejs.org/api/modules.html#modules_module_require_id ).

Here is an REPL that reproduces the issue : https://repl.it/repls/SociableSimpleDictionaries

If you directly do `node cjs.js`, it works. But if you do `npx rollup -c && node output/bundle.js` it fails because of `module.require`.

(To be honest, I have no idea why anyone would want to use `module.require` in real life, but as it happens some well-known projects do use it, like lodash - https://github.com/lodash/lodash/blob/master/.internal/nodeTypes.js#L20 - and this is how I happened upon this bug, by trying to rollup lodash)

### Expected Behavior

Calls to `module.require`should be considered like calls to `require`.

### Actual Behavior

Calls to `module.require`are ignored by rollup-plugin-commonjs, so they fail because `module` is modified to an object that just has an `module.export` property.

**Comment by danielgindi** [comment]
Yeah the functions that detected whether a `require` exists were never written to look for `module.require`. I'm not even sure they should, as `module` could easily be used for a local variable name, while just `require` will *probably* not be used in nodejs code for variable names.

**Comment by arantes555** [comment]
I think the parser would be able to differentiate between `module` being top-level or not

**Comment by lukastaegert** [comment]
It should. Not sure about the details of the commonjs plugin at the moment but usually there is an `attachScopes` called somewhere in the plugin which creates variable scopes that again can be used to determine if a variable is global. Should already be in place for `require` itself somewhere.

**Comment by danielgindi** [comment]
> It should. Not sure about the details of the commonjs plugin at the moment but usually there is an `attachScopes` called somewhere in the plugin which creates variable scopes that again can be used to determine if a variable is global. Should already be in place for `require` itself somewhere.

Found it, it’s the `scope` thing. Works perfectly. Although `master` has an issues with the test snapshots, inconsistent between platforms. So a small PR I sent does not get a V.
