### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by huzedong2015** [rollup/plugins#312]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 4.1.1
- Rollup Version: 2.6.1
- Operating System (or Browser): windows 10
- Node Version: 6.14.4

### How Do We Reproduce?

**build success**
```
import { name } from "./package.json";
import typescript from "@rollup/plugin-typescript";

export default {
	input: "src/index.ts",
	output: {
		file: `dist/${name}.esm.js`,
		format: "es",
	},
	plugins: [typescript()],
};
```

**build fail**

```
import { name } from "./package.json";
import typescript from "@rollup/plugin-typescript";

export default {
	input: "src/index.ts",
	output: [
		{
			file: `dist/${name}.esm.js`,
			format: "es",
			plugins: [typescript()],
		},
	],
};
```

### Expected Behavior
Build success

### Actual Behavior
Build error
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
