### ISSUE TITLE
Publish new version of @rollup/plugin-json

### ISSUE THREAD

**Issue by maoueh** [rollup/plugins#313]
Hopefully, I picked the right report category, otherwise, I'm sorry.

Just wanted to request a release of current `plugin-json` plugin. It fixes the peer dependency for rollup@2 and the current published version still list only 1.x version.

Thanks and no rush here, just a gentle notice.

**Comment by shellscape** [comment]
_Thanks for the issue. Please make sure to use an issue template for future contributions._ `plugin-json` will be included in the next round of publishes.
