### ISSUE TITLE
[@rollup/plugin-replace] Wrong rollup peer dependency

### ISSUE THREAD

**Issue by berniegp** [rollup/plugins#314]
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: 2.3.1
- Rollup Version: 2.6.1
- Operating System (or Browser): all
- Node Version: all

### How Do We Reproduce?
Go to https://unpkg.com/@rollup/plugin-replace@2.3.1/package.json
Notice this part:
```
  "peerDependencies": {
    "rollup": "^1.20.0"
  },
```

### Expected Behavior
```
  "peerDependencies": {
    "rollup": "^1.20.0||^2.0.0"
  },
```
like for example https://unpkg.com/@rollup/plugin-buble@0.21.3/package.json

### Actual Behavior
Without the `||^2.0.0` part, npm complains with:
```
npm WARN @rollup/plugin-replace@2.3.1 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
```

packages/replace/package.json already has the proper value in place. However, somehow the changes from https://github.com/rollup/plugins/commit/371f4246068f3f469e046ecbe329b897eed9a692#diff-5b19258157281544930cb47aaaa2882f did not go in the 2.3.1 release. I think it just needs a new npm release with a version bump.

**Comment by shellscape** [comment]
Packages are published as we have time to. Warnings don't impact NPM functionality.

**Comment by berniegp** [comment]
Thanks for your reply. I understand that of course. I mixed up the dates and thought the 2.3.1 release happened *after* the commit I referenced. I try to avoid ignoring warnings when possible as they can cause real problems.
