### ISSUE TITLE
Bump Rollup version in `plugin-replace@2.3.1` to `2.x`

### ISSUE THREAD

**Issue by navimaia** [rollup/plugins#316]
- Rollup Plugin Name: plugin-replace
- Rollup Plugin Version: 2.3.1

### Expected Behavior / Situation
Not provide any npm warnings with the newest version of Rollup

### Actual Behavior / Situation
Produces following warning when using `npm install`:
`npm WARN @rollup/plugin-replace@2.3.1 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.`

### Modification Proposal
Bump the Rollup version in plugins package.json file.

**Comment by TrySound** [comment]
See here https://github.com/rollup/plugins/issues/314

**Comment by shellscape** [comment]
Closing as duplicate
