### ISSUE TITLE
YAML support could be improved by switching libraries

### ISSUE THREAD

**Issue by eemeli** [rollup/plugins#318]
- Rollup Plugin Name: @rollup/plugin-yaml
- Rollup Plugin Version: 2.1.0

### Expected Behavior / Situation
The plugin could support all YAML versions and be otherwise more spec-compliant, as well as supporting YAML maps with non-string-keys.

### Actual Behavior / Situation
The plugin is not as compliant as it could be, and stringifies all map keys.

### Modification Proposal
The base YAML library of the plugin could be switched from [`js-yaml`](https://www.npmjs.com/package/js-yaml) to [`yaml`](https://www.npmjs.com/package/yaml), which would improve the plugin's YAML support. For a comparison of spec-compliance, see the [YAML Test Matrix](https://matrix.yaml.io/), which shows results for `js-yaml` as "js-yaml-json" and `yaml` as "js-event" and "js-json". Also note that `yaml` also supports earlier versions of the spec, not just YAML 1.2.

For context, I'm the developer of `yaml`, and am interested in providing a Rollup plugin for my library. I would prefer to help develop this official plugin, rather than publishing a different one. I'm quite willing to submit a PR for this change, but thought it'd be more appropriate to ask first if it'd be welcome.

**Comment by shellscape** [comment]
These types of issues are always tricky. Whenever we move from one lib to another there's usually politics to deal with. (see the turbocolor debacle in rollup/rollup)

On the surface, support of older versions of yaml isn't compelling; 1.2 was drafted in 2009. 10 years might as well be 100 in tech, and 1.2 support as a baseline isn't unreasonable.

I'm not sure how to read the graph you linked to; there's no key for reading it and I unfortunately don't have time to deep dive it. If you could provide a side by side comparison, that would be helpful.

I'd say we're open to the idea, but there will be a high bar to making the switch.

**Comment by eemeli** [comment]
Unfortunately, with YAML, one can't rely on real-world services using version 1.2. For instance, Docker Compose and Travis CI both still parse config files as YAML 1.1. Work is ongoing to improve the situation, but at least for now YAML 1.1 is still very much with us.

Regarding the YAML test matrix, the following are some of the parsing differences between `js-yaml` and the spec:

```js
const { safeLoad } = require('js-yaml')

// Parsing error for tags or anchors on keys
safeLoad('!!str key: value')
safeLoad('&anchor key: value')
// both throw YAMLException: end of the stream or a document separator is expected
// expected: { key: 'value' }

// Parsing error for flow collection with : on line after key
safeLoad('{ key\n: value }')
// throws YAMLException: missed comma between flow collection entries
// expected: { key: 'value' }

// Parsing error for !local tags
safeLoad('!local value')
// throws YAMLException: unknown tag !<!local>
// expected: 'value'

// Invalid folding when a line ends with white space
safeLoad('"fold \nspace"')
// actual:   'fold  space'
// expected: 'fold space'
```

`yaml` will parse all of the above without any problems. It also has optional support for using a native JS Map to represent mappings, which allows for complex keys to be fully supported without needing to stringify them:

```js
const { safeLoad } = require('js-yaml')
const YAML = require('yaml')

safeLoad('{ [one, two]: three }')
// { 'one,two': 'three' }

YAML.parse('{ [one, two]: three }')
// { '[ one, two ]': 'three' }
// YAMLWarning: Keys with collection values will be stringified as YAML due to JS Object restrictions. Use mapAsMap: true to avoid this.

YAML.parse('{ [one, two]: three }', { mapAsMap: true })
// Map(1) { [ 'one', 'two' ] => 'three' }
```

**Comment by shellscape** [comment]
Thanks for the additional info. I took some time to dive into that:

> Unfortunately, with YAML, one can't rely on real-world services using version 1.2. For instance, Docker Compose and Travis CI both still parse config files as YAML 1.1. Work is ongoing to improve the situation, but at least for now YAML 1.1 is still very much with us.

That's not entirely accurate. _Older_ versions of `docker-compose`, specifically version 1.x, uses yaml@1.1, but as of `docker-compose` v2 they support yaml@1.2. Given that docker compose is already on v3, I'd argue that users of v1 are hopelessly behind. As for Travis CI, well, that doesn't surprise me.  If folks are trying to import their Travis configs using the plugin and it doesn't work out, I'd be more apt to point them in a different direction.

I tried some googling to see what other major players were using older versions of Yaml and came up dry. For instance, `serverless` which also happens to use `js-yaml` is on 1.2. 

Appreciate the code samples, but I think we'd need more of a side-by-side, version-to-version type of comparison to make an educated decision.

**Comment by eemeli** [comment]
>Appreciate the code samples, but I think we'd need more of a side-by-side, version-to-version type of comparison to make an educated decision.

Could you clarify whether you're looking for the differences already mentioned in my previous posts to be presented differently, or for something else?
