### ISSUE TITLE
`@rollup/plugin-typescript`: Must the tsBuildInfo file be located in the output.dir path?

### ISSUE THREAD

**Issue by BitYoungjae** [rollup/plugins#319]
https://github.com/rollup/plugins/blob/c09509f8b2bad0743ea6a70c55fa79ffaa18a1c7/packages/typescript/src/options/validate.ts#L82

According to the content below, don't have to..

> These .tsbuildinfo files can be safely deleted and don’t have any impact on our code at runtime - they’re purely used to make compilations faster. We can also name them anything that we want, **and place them anywhere we want using the --tsBuildInfoFile flag.**
--**source :** [TypeScript: Handbook - TypeScript 3.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html)

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
