### ISSUE TITLE
Should the tsBuildInfo file be located inside output.dir?

### ISSUE THREAD

**Issue by BitYoungjae** [rollup/plugins#320]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version:4.1.1

### Expected Behavior / Situation

Should the `tsBuildInfo` file be located inside `output.dir`?
According to the content below, we don't have to..

> These .tsbuildinfo files can be safely deleted and don’t have any impact on our code at runtime - they’re purely used to make compilations faster. We can also name them anything that we want, **and place them anywhere we want using the --tsBuildInfoFile flag.**
--**source :** [TypeScript: Handbook - TypeScript 3.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html)

Therefore, the REPL below should be build without an error.

[Repl.it - tsBuildInfo Issue](https://repl.it/repls/FlawedStrongCharmap)

### Actual Behavior / Situation

If the `tsBuildInfo` file is not inside `output.dir`, an error occurs.

### Modification Proposal

Please delete or modify the code below..

https://github.com/rollup/plugins/blob/c09509f8b2bad0743ea6a70c55fa79ffaa18a1c7/packages/typescript/src/options/validate.ts#L82

**Comment by shellscape** [comment]
@NotWoods possible bug, possible local environment issue. please have a look.

**Comment by marlon-tucker** [comment]
I'm also hitting this issue, rollup is enforcing the tsBuildInfoFile being placed in the `dir` folder (configured in rollup), which is the build output so this cache pollutes that directory.

**Comment by mhmo91** [comment]
re-opening this again!

**Comment by jacobbogers** [comment]
any resolution on this? whould would be the solution? remove the check?
