### ISSUE TITLE
preserveModules in yarn monorepo outputs full project path

### ISSUE THREAD

**Issue by johannes-z** [rollup/plugins#321]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: `7.1.3` 
- Rollup Version: `2.6.1` 
- Operating System (or Browser): Ubuntu 1804 / Chromium
- Node Version: 13.13.0

#### Reproduction

```sh
git clone ...
yarn
cd packages/office-ui-fabric-vue
yarn rollup -c
(check ./lib)
```

### Expected Behavior

Modules should be emitted into `./lib/`, e.g. `./lib/index.js`.

### Actual Behavior

Modules are emitted with the relative path to the project root, e.g. `./lib/packages/office-ui-fabric-vue/src/index.js`. 

I think this might stem form the `_virtual` folder being emitted from the project root rather than the package root. Maybe this is an issue with i.e. `node-resolve`? Sadly I have no idea where to look to triage this...

**Comment by shellscape** [comment]
_(It looks like you used the template from rollup/rollup 😄 )_

Thanks for the repo, but I'm afraid there's a bit too much going on there to effectively triage. In the plugin repo's issue template for bugs, there's a link that explains what and why we need a _minimal_ reproduction. I don't think we'll be able to triage this one for you unless you're able to drill / distill your repo down to a minimal reproduction case. Like a teensy tiny reproduction that exhibits the same behavior.

**Comment by johannes-z** [comment]
*(Yeah, sorry. Initially I wanted to open it in rollup, but I wasn't sure if it was plugin related or not...)*

You are totally right, sorry. I created a small repro to showcase this issue. I've included the built files in git:

```sh
git clone https://github.com/johannes-z/rollup-yarn-preserveModules
yarn install
# optional, already built, doesn't use rollup anyway
cd packages/producer
yarn build

cd packages/consumer
yarn build
```

`packages/consumer` then created `./lib/packages/consumer/src/index.js`.

I've also tried `pnpm`: `packages/consumer` created `./lib/src/index.js` in this case...

**Comment by 0biWanKenobi** [comment]
Not sure, but could it be related to #277 ? I opened that issue as a suggestion, but later realized that plugin-node-resolve is actually messing up output paths..

**Comment by cbravo** [comment]
I am running into this same issue now @johannes-z did you ever solve it?

**Comment by johannes-z** [comment]
yes. you have to mark every node module put into _virtual as external, then the output will be correct.

**Comment by pmrotule** [comment]
I had the same issue and was finally able to fix it by defining `src` as the `output.preserveModulesRoot`:

```js
output: {
  dir: 'dist',
  format: 'esm',
  sourcemap: 'inline',
  preserveModules: true,
  preserveModulesRoot: 'src',
},
```
