### ISSUE TITLE
@rollup/plugin-yaml: update rollup

### ISSUE THREAD

**Issue by mindrones** [rollup/plugins#328]
- Rollup Plugin Name: @rollup/plugin-yaml
- Rollup Plugin Version: 2.1.0

### Expected Behavior / Situation

Not getting warnings with a recent rollup.
 
### Actual Behavior / Situation

Getting a warning about missing rollup when using rollup 2.7.2.

```WARN @rollup/plugin-yaml@2.1.0 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
```

### Modification Proposal

Update `rollup` version.

Sorry for the trivial report, time permitting I'll look into this myself!

**Comment by shellscape** [comment]
Please don't open issues for package install warnings.
