### ISSUE TITLE
@rollup/pluginutils: update rollup

### ISSUE THREAD

**Issue by mindrones** [rollup/plugins#329]
- Rollup Plugin Name: @rollup/pluginutils
- Rollup Plugin Version: 3.0.8

### Expected Behavior / Situation

Not getting warnings with a recent rollup.
 
### Actual Behavior / Situation

Getting a warning about missing rollup when using rollup 2.7.2.

```WARN @rollup/pluginutils@3.0.8 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
```

### Modification Proposal

Update `rollup` version.

**Comment by shellscape** [comment]
Already is. Please don't open issues for package warnings.
