### ISSUE TITLE
bundled helpers when using .generated

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/plugins#331]
- Rollup Plugin Version: v5

### Feature Use Case
When using the new babel `.generated` option, we lose the ability to deduplicate babel helpers. They're duplicated in each chunk. This really adds up, especially when compiling to es5. It would be useful to deduplicate these helpers, even when using `.generated.`

### Feature Proposal
I created a babel + rollup plugin which adds imports for babel helpers and emits a separate chunk with only the used babel helpers.

It's quite complex because when using `.generated` we're no longer in the rollup build phase, rollup cannot help us anymore. We're on our own. For example because we can't emit chunks anymore, the helper chunk has to be emitted as an asset. Rollup can't do the module format compilation for us either, so we do that manually as well. Currently only esm and systemjs is supported, but others can be added.

After https://github.com/rollup/plugins/pull/108 gets merged, I think it would be useful to merge this back upstream to the babel plugin.

You can find the code here:

https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/src/babel/babel-plugin-bundled-helpers.js
https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/src/babel/rollup-plugin-bundled-babel-helpers.js

**Comment by lukastaegert** [comment]
Awesome work!

**Comment by shellscape** [comment]
@LarsDenBakker thanks for leading this. Please do get the wheels moving on merging into the plugin.
