### ISSUE TITLE
The operator ?.  is not supported

### ISSUE THREAD

**Issue by khusamov** [rollup/plugins#332]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: v4.1.1
- Rollup Version: v2.7.2
- Operating System (or Browser): Windows 10
- Node Version: v12

### How Do We Reproduce?

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src\functions\fetchScript.ts (17:31)
15:     return (new Promise((resolve, reject) => {
16:         const script = createAndAppendScript(url, resolve, reject);
17:         const signal = options?.signal;
                                   ^
18:         if (signal) {
19:             const abort = () => {
```

### Expected Behavior

Module builds correctly

### Actual Behavior

Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.

**Comment by niklaskorz** [comment]
I experienced the same issue today. The fix is quite easy: make sure to specify a target in your tsconfig that is below ES2020 (e.g., ES2019) so the operator gets transpiled.

**Comment by khusamov** [comment]
@niklaskorz Thanks! The problem was solved!
