### ISSUE TITLE
[commonjs plugin]: Support Promised dynamic require

### ISSUE THREAD

**Issue by guybedford** [rollup/plugins#341]
### Feature Use Case

There seem to be a few reports now with the lack of support for dynamic `require(expression)` in these transforms.

### Feature Proposal

I'd like to suggest the plugin support the following pattern:

```js
Promise.resolve(require(expression))
```

being rewritten to:

```js
import(expression)
```

Users of projects that want to support this transform can then ensure their dynamic imports are wrapped in a promise and know they will support ES module conversion this way.

**Comment by shellscape** [comment]
@guybedford is this something you're interested in working on? Doing some housekeeping and cleaning up some old issues and was curious.

**Comment by guybedford** [comment]
This was a pattern I was trying to push while ES modules were still not available in Node.js properly as a sort of forwards compatibility path.

But there was zero interest in this actually, so I don't think this is realistically something that will provide any benefits to anyone.

Probably best to just close it, but if interest does ever pick up it is certainly something we can consider.
