### ISSUE TITLE
Using @rollup/plugin-babel with native ECMAScript module babel configuration file

### ISSUE THREAD

**Issue by perrin4869** [rollup/plugins#344]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.0.0

Documentation Is:

I couldn't find any issues tracking this.
Babel [added support for native ESM modules](https://babeljs.io/blog/2020/01/11/7.8.0#support-every-configuration-file-extension-10783-https-githubcom-babel-babel-pull-10783-and-10903-https-githubcom-babel-babel-pull-10903) in `7.8.0`, but noted that `rollup-plugin-babel` would support them in the next version.
I tried to use an ESM module with the brand new `@rollup/plugin-babel@5` today, but unfortunately I got an error:
`Error while loading config - You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously.`

I couldn't find any documentation on the matter in the `README` for the plugin nor an issue tracking the progress, so I thought I'd open it here.

Regards!

**Comment by shellscape** [comment]
Thanks for opening an issue. Please don't remove portions of an issue template or modify them to taste. The format and information in them has been carefully curated.

This looks more like a bug issue than documentation, so please do refile a new bug issue with the required info.
