### ISSUE TITLE
Option to specify output paht for generated html

### ISSUE THREAD

**Issue by boojum** [rollup/plugins#346]
- Rollup Plugin Name: @rollup/plugin-html
- Rollup Plugin Version: 0.1.1

### Feature Use Case
Currently it is impossible to output generated html to a custom directory, it is always outputted alongside the main `js` bundle. The use case here is keeping `js` and `html` files separated, for example: if I save the bundle to `public/js` I would like to be able to save `index.html` to `public`.

### Feature Proposal
Add an extra configuration option - perhaps `dir` or `output` - allowing to specify where generated `html` will be saved.

**Comment by shellscape** [comment]
Thanks for the issue.

I workaround would be to move the file after the build using npm scripts:

```json
"postbuild": "mv dist/index.html dist/html/index.html"
```

**Comment by boojum** [comment]
```
> "postbuild": "mv dist/index.html dist/html/index.html"
 ```
Yeah, that would work but - as you said - its only a workaround. Or one could even use [rollup-plugin-copy](https://github.com/vladshcherbin/rollup-plugin-copy). It would be nice to specify options related to the plugin in the actual plugin configuration ;-)

It's not a deal breaker or anything but definitely something nice to have. I'm very much a beginner in the `javascript` world but I'll try to come up with a possible PR. Although it might take me considerable amount of time.

**Comment by shellscape** [comment]
I'm not sure if we want to mess with the output settings for the rollup bundle. The way that this works is that the html file is added as a build asset so it takes advantage of the rollup build hooks and could have more processing done on it by another plugin. If we mess with the output for the build then that could have adverse effects.

You could probably use a separate input/output group in the rollup config with @rollup/plugin-virtual to specify an input, with the the html plugin, and rollup-plugin-delete to remove the js file created from the virtual input. Way more complicated than a post-build script though.

**Comment by boojum** [comment]
Thanks for the explanation. I think that the `postcss` plugin works like that as well, and it does sound like the right way to do it. Implementing this feature would involve deep changes to the current plugin architecture, and frankly, that would be a lot of effort to support somewhat niche use case.

I'm happy to close the issue but as you assigned labels to it, I'll leave it up to you.
