### ISSUE TITLE
Chunk hash based on source code when using generated

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/plugins#350]
When using v5's `.generated` option, the chunk hashes are based on the the original source code rather than the babel output. This can be problematic when changing the babel config or when plugins update to fix bugs. 

I'm not sure if it is possible for generate/output plugins to change chunk hashes?

**Comment by Andarist** [comment]
I'm also unsure if this is possible, maybe some other @rollup/plugin-maintainers would know.

**Comment by Andarist** [comment]
Seems like [this comment](https://github.com/rollup/rollup-plugin-babel/issues/337#issuecomment-566913396) might be relevant here. It says that currently, this is not possible but probably will become possible in the future.
