### ISSUE TITLE
filename missing when using getBabelOutputPlugin

### ISSUE THREAD

**Issue by gingur** [rollup/plugins#351]
When using `babel.generated`, the `filename` is not being provided to the babel options. https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js#L182. I think `outputOptions.dir` + `chunk.fileName` should give the appropriate filename.

**Comment by federico-po** [comment]
`filename` needs to be passed when using `getBabelOutputPlugin`.

```js
// rollup.config.js
import path from 'path'
import { getBabelOutputPlugin } from '@rollup/plugin-babel';
const config = {
  // other configs
  plugins: [
    getBabelOutputPlugin({
      configFile: path.resolve(__dirname, 'babel.config.js'),
      filename: 'bundle',
    }),
  ],
};

```
