### ISSUE TITLE
[commonjs] original ignore: [ 'conditional-runtime-dependency' ] does not work anymore

### ISSUE THREAD

**Issue by 3cp** [rollup/plugins#353]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 11.1.0
- Rollup Version: 2.7.3
- Operating System (or Browser): macOS 10.15.4
- Node Version: 12.16.0

### How Do We Reproduce?

I try to migrate from `rollup-plugin-commonjs` to `@rollup/plugin-commonjs`. Then encountered runtime error:

```
Error: Dynamic requires are not currently supported by @rollup/plugin-commonjs
```

In rollup.config.js
```js
    commonjs({
      ignore: [ 'conditional-runtime-dependency' ]
    })
```

In order to support a [dynamic require at runtime](https://github.com/makesjs/makes/blob/656ef725fef090182a9ed3257436c23abd9faf4e/lib/skeleton-config.js#L16) (it requires files from a tmp folder).

Obviously latest `@rollup/plugin-commonjs` removed support of `'conditional-runtime-dependency'` in ignore array.
### Expected Behavior

I expect some way to do the same trick.

### Actual Behavior

I got runtime error on Dynamic requires. Going back to old commonjs plugin for version release.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
