### ISSUE TITLE
[html] Is it possible to release plugin-html ? Not done since many months :)

### ISSUE THREAD

**Issue by vperron** [rollup/plugins#354]
- Rollup Plugin Name: html
- Rollup Plugin Version: 1.2 ?

### Feature Use Case
This plugin has not been released since a very long time, and many features and bugfixes have been merged since though.

### Feature Proposal
Would it be possible to package and release a new version of this plugin ? About this I can give no help unfortunately :/

**Comment by shellscape** [comment]
Please don't open issues asking for plugin publishing. We publish as appropriate :rocket:
