### ISSUE TITLE
@rollup/plugin-babel and regeneratorRuntime error with 'external' helpers

### ISSUE THREAD

**Issue by cutterbl** [rollup/plugins#357]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.0.0
- Rollup Version: 2.7.5
- Operating System (or Browser): Mac
- Node Version: 10.14.0

I have the following config:

```js
import path from 'path';
import babel from '@rollup/plugin-babel';
import clear from 'rollup-plugin-clear';
import { eslint } from 'rollup-plugin-eslint';
import cleanup from 'rollup-plugin-cleanup';
import pkg from '../package.json';

export default [
  {
    input: path.join(__dirname, '../src/index.js'),
    output: [
      {
        file: pkg.module,
        format: 'es',
        sourcemap: true,
        exports: 'named',
      },
    ],
    plugins: [
      clear({
        targets: [path.join(__dirname, '../dist')],
        watch: true,
      }),
      eslint(),
      babel({
        babelHelpers: 'external',
      }),
      cleanup(),
    ],
  },
];
```

Along with the following `babel.config.json` file

```
{
  "presets": ["@babel/preset-env"],
  "plugins": ["@babel/external-helpers"]
}
```

I have a babel external helpers file I load in the browser. When I include my built file (which built without error), I get the following console error:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

Inspecting my built file, I find several references to the `reneratorRuntime`.

Did I miss something?

### Expected Behavior

Built file would allow for using the external babel helpers

### Actual Behavior

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

[Here is the repo](https://github.com/cutterbl/soundtouchjs-audio-worklet) where I'm trying to get this working.

**Comment by JMarkoski** [comment]
Duplicate: [https://github.com/rollup/plugins/issues/356](https://github.com/rollup/plugins/issues/356)

**Comment by shellscape** [comment]
@JMarkoski thanks. Closing as duplicate.
