### ISSUE TITLE
babel README needs a little cleanup 

### ISSUE THREAD

**Issue by dasa** [rollup/plugins#365]
- Rollup Plugin Name:  babel
- Rollup Plugin Version: 5.0

Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

- At: https://github.com/rollup/plugins/tree/master/packages/babel#options 

> (or most likely ES6 when Rollup 2 will be released)

Rollup 2 has been released, and I think it's still ES5 compatible.

- At: https://github.com/rollup/plugins/tree/master/packages/babel#external-dependencies

> hence the exclude: 'node_modules/**' in the example above

I don't see the example being referenced.

**Comment by Andarist** [comment]
> Rollup 2 has been released, and I think it's still ES5 compatible.

Will have to check that. From what I recall the premise was that the generated wrapper code should become ES6+ in Rollup 2, but maybe this didn't get into the final release.

Thanks for pointing out both issues - will handle them 🔜
