### ISSUE TITLE
Typescript plugin not compatible with rollup-plugin-postcss for inline styles, rollup-plugin-typescript supported it.

### ISSUE THREAD

**Issue by 42shadow42** [rollup/plugins#366]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 4.1.1
- Rollup Version: 2.7.6
- Operating System (or Browser): Windows 10, Chrome
- Node Version: v12.16.3

### How Do We Reproduce?
~~[reproduce-typescript-css-issue.zip](https://github.com/rollup/plugins/files/4576118/reproduce-typescript-css-issue.zip)~~ https://repl.it/repls/TrickyGhostwhitePriorities

### Expected Behavior
```
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var cn = _interopDefault(require('classnames/bind'));

function styleInject(css, ref) {
  if ( ref === void 0 ) ref = {};
  var insertAt = ref.insertAt;

  if (!css || typeof document === 'undefined') { return; }

  var head = document.head || document.getElementsByTagName('head')[0];
  var style = document.createElement('style');
  style.type = 'text/css';

  if (insertAt === 'top') {
    if (head.firstChild) {
      head.insertBefore(style, head.firstChild);
    } else {
      head.appendChild(style);
    }
  } else {
    head.appendChild(style);
  }

  if (style.styleSheet) {
    style.styleSheet.cssText = css;
  } else {
    style.appendChild(document.createTextNode(css));
  }
}

var css_248z = ".index-module_class__2W5bv {\r\n    color: blue;\r\n}";
var styles = {"class":"index-module_class__2W5bv"};
styleInject(css_248z);

var cx = cn.bind(styles);

```
### Actual Behavior
```
'use strict';

Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var bind_1 = tslib_1.__importDefault(require("classnames/bind"));
var index_module_css_1 = tslib_1.__importDefault(require("./index.module.css"));
var cx = bind_1.default.bind(index_module_css_1.default);
```

**Comment by 42shadow42** [comment]
@shellscape Can you take a look at this and let me know if anything else is needed?

**Comment by shellscape** [comment]
@42shadow42 we generally won't download zip files for reproductions because that's a bit of a security risk. The issue template gives you the three options for providing a reproduction. I suggest you follow those instructions if you'd like someone to triage this issue for you.

**Comment by 42shadow42** [comment]
You should be able to reproduce at https://repl.it/repls/TrickyGhostwhitePriorities, you can see the expected behavior by changing typescript() to typescript_old() in the rollup configuration plugins section.

**Comment by 42shadow42** [comment]
If it helps, it works as expected on version 2.1.0

**Comment by 42shadow42** [comment]
I got it working by changing module to 'ESNext' in my tsconfig, it appears in version 2.1.0 it was 'defaulting' to ESNext, where 'defaulting' appears to be overriding, because I had specified a module in my tsconfig.

@shellscape Thanks for taking a look and being open to this issue, it appears this wasn't a bug with this version, but a bug with previous versions that made upgrading unexpected.

**Comment by shellscape** [comment]
Thanks for continuing to triage this. I'm sure it will help someone.
