### ISSUE TITLE
html: Add plugin context to the template params.

### ISSUE THREAD

**Issue by pkit** [rollup/plugins#367]
- Rollup Plugin Name: html
- Rollup Plugin Version: master

### Expected Behavior / Situation

Need to use plugin context in the template function

### Actual Behavior / Situation

Currently the `template` arguments are `({ attributes, bundle, files, meta, publicPath, title })`

### Modification Proposal

Add plugin context to the params.
Why: mainly to use `addWatch()` for some second level template sources.
Actually can add a PR to do it, looks pretty simple.
But maybe there are considerations on why it's not a good idea?

**Comment by shellscape** [comment]
Thanks for the issue. I'd like to see more about the use case.

**Comment by pkit** [comment]
```
[
indexHtml({
    publicPath: '/',
    title: 'My App',
    template: ({ files, attributes, publicPath }) => {
      const htmlTemplateFile = 'html/index.html'
      const scripts = (files.mjs || [])
        .map(({ fileName }) => {
          const attrs = makeHtmlAttributes(attributes.script)
          return `<script src="${publicPath}${fileName}" ${attrs}></script>`
        })
        .join('\n')
      let index = fs.readFileSync(htmlTemplateFile)
      index = String(index).replace(/%HTML_ATTRS%/g, makeHtmlAttributes(attributes.html))
      index = index.replace(/%PUBLIC_URL%/g, publicPath.slice(0, -1))
      index = index.replace(/%TITLE%/g, title)
      return index.replace(/%SCRIPTS%/g, scripts)
    },
  }),
]
```

html/index.html

```
<!DOCTYPE html>
<html %HTML_ATTRS%>
<head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>%TITLE%</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Montserrat:300,400,500,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/dmuy/Material-Toast/mdtoast.min.css">
</head>
<body>
<noscript>You need to enable JavaScript to run this app.</noscript>
<div id="root"></div>
<div id="menus"></div>
<div id="portals" >
    <div id="dialog"></div>
</div>
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/dmuy/Material-Toast/mdtoast.min.js"></script>
<script type="module">
  window.addEventListener('error', function (e) {
    systemError(e.error.message);
    return false;
  });

  window.addEventListener('unhandledrejection', function (e) {
    systemError(e.reason.message);
    return false;
  });

  function systemError (message) {
    mdtoast(`Error: ${message}`, {
      duration: 10000,
      type: 'error'
    });
  }
</script>
%SCRIPTS%
</body>
</html>
```

**Comment by shellscape** [comment]
Hm. That's an interesting use case. I'm not sure that the template function is the best place for that. Let me bounce this off of a few people for more ideas.

**Comment by pkit** [comment]
@shellscape yep, it's pretty hacky, but I haven't found any other way to have a custom HTML with dynamic content parts.

**Comment by shellscape** [comment]
@lukastaegert what would be the "right" way to provide access to `addWatch` here in your mind, while making this painless for users?

@pkit I was thinking that maybe a very simple `@rollup/plugin-watch` might be in order that would accept a glob of files to add watchers for.

Thoughts?

**Comment by pkit** [comment]
@shellscape yep, seems like a good idea actually
I was thinking that `watch.include` in the rollup options would do it for me. But it's kinda for a different purpose...
