### ISSUE TITLE
Plugin node resolve not working on certain packages

### ISSUE THREAD

**Issue by gptt916** [rollup/plugins#369]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: 7.1.3
- Rollup Version: latest
- Operating System (or Browser): Mac, Firefox
- Node Version: 12 lts

### How Do We Reproduce?

https://repl.it/repls/OnerlookedExperiencedTrials

### Expected Behavior
Resolve should find 'freezeframe' and include it in the bundled output

### Actual Behavior
Resolve does not find 'freezeframe'

**Comment by shellscape** [comment]
We're closing this issue as stale as it's more than 30 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
