### ISSUE TITLE
@rollup/plugin-babel preflightCheck logic

### ISSUE THREAD

**Issue by liuyuchenzh** [rollup/plugins#370]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.0.0
- Rollup Version: 2.8.1
- Operating System (or Browser): MacOS 10.15.4
- Node Version: 12.16.0

### How Do We Reproduce?

`rollup.config.js`

```js
import babel from "@rollup/plugin-babel"

export default [
  {
    input: 'src/main.js',
    output: {
      file: "dist/index.esm.js",
      format: 'esm',
    },

    plugins: [
      babel({
        exclude: ['node_modules/**'],
        babelHelpers: 'runtime'
      })
    ]
  }
]
```

`.babelrc.js`

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false
      }
    ]
  ],
  plugins: ['@babel/plugin-transform-runtime'],
}

```

### Expected Behavior

Bundle seamlessly without any error.

### Actual Behavior

```shell
(plugin babel) Error: You must use the `@babel/plugin-transform-runtime` plugin when `babelHelpers` is "runtime".
```

### Potential fix method

https://github.com/rollup/plugins/blob/3f731a530724f8167bcc73d8cf6058fe9a87bcb5/packages/babel/src/preflightCheck.js#L67

Here `transformOptions.plugins.length` is checked. 

However `transformOptions` seems to be the option user pass to `@rollup/babel-plugin`, not the option that will be actually consumed by babel.

https://github.com/rollup/plugins/blob/3f731a530724f8167bcc73d8cf6058fe9a87bcb5/packages/babel/src/transformCode.js#L12

This is the existing approach to get the "real" babel config options.

May adopt the same strategy here too?

**Comment by shellscape** [comment]
@liuyuchenzh Please add a reproduction as asked for in the issue template or we'll have to close this issue.

**Comment by liuyuchenzh** [comment]
Close this until I can provide a proper reproduction.
