### ISSUE TITLE
@rollup/plugin-url published on NPM does not seem to have updated package.json

### ISSUE THREAD

**Issue by tonix-tuft** [rollup/plugins#371]
Hello,

I am trying to upgrade rollup from `rollup@^1.0.0` to `rollup@^2.0.0` in my projects.

If I install `rollup@^2.8.2`, npm complains about `@rollup/plugin-url` needing a peer of `rollup@^1.20.0`:

```
npm WARN @rollup/pluginutils@3.0.8 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @rollup/plugin-url@4.0.2 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
```

Although in `@rollup/plugin-url`'s `package.json` (https://github.com/rollup/plugins/blob/master/packages/url/package.json) the `peerDependencies` range is correct:

```js
{
    ...
    "peerDependencies": {
      "rollup": "^1.20.0||^2.0.0"
    },
    ...
}
```

It does not seem to be the same as in the `package.json` you published to NPM, if you look at this `package.json` -> https://unpkg.com/@rollup/plugin-url@4.0.2/package.json

You will see that it only has:

```js
{
    ...
    "peerDependencies": {
      "rollup": "^1.20.0"
    },
    ...
}
```

### Expected Behavior

Align `package.json` on NPM so that it also has the correct peer dep range like here on GitHub:

```js
{
    ...
    "peerDependencies": {
      "rollup": "^1.20.0||^2.0.0"
    },
    ...
}
```

I hope my issue is clear and you understood what I mean. Thank you!

**Comment by tonix-tuft** [comment]
@shellscape Could please write a brief comment about why you closed this issue? I still see the wrong out-to-date `package.json` on https://unpkg.com/@rollup/plugin-url@4.0.2/package.json and when I install the plugin in my project. Thank you!

**Comment by poteirard** [comment]
You can use v5 which is updated :) https://unpkg.com/@rollup/plugin-url@5.0.0/package.json
