### ISSUE TITLE
Plugins should specify `repository.directory` in `package.json`

### ISSUE THREAD

**Issue by silverwind** [rollup/plugins#374]
I noticed many if not all plugins do not specify `repository.directory` in their `package.json` which breaks certain tooling like Dependabot and OctoLinker. Currently they specify

````json
"repository": "rollup/plugins",
````

It would be better to do specify `directory` to fix those tools:

````json
"repository": {
  "type" : "git",
  "url" : "https://github.com/rollup/plugins.git",
  "directory": "packages/<name>"
}
````

where `<name>` is the name of the directory inside the repo. From [npm docs](https://docs.npmjs.com/files/package.json#repository):

> If the package.json for your package is not in the root directory (for example if it is part of a monorepo), you can specify the directory in which it lives

Related discussion: https://github.com/OctoLinker/OctoLinker/issues/927

**Comment by shellscape** [comment]
Thanks, we'll consider this.

In the future please use our issue templates. This is a pretty clear Modification issue.

**Comment by silverwind** [comment]
Here is the issue template FWIW. I did not use it as it seemed unsuitable for this kind of issue.

---

- Rollup Plugin Name: all
- Rollup Plugin Version: all
- Rollup Version: all
- Operating System (or Browser): all
- Node Version: all

### How Do We Reproduce?

1. Install https://github.com/OctoLinker/OctoLinker extension
2. Click Link to `@rollup/plugin-node-resolve` https://github.com/silverwind/updates/blob/cdf48118cfbe1ee4595ac41854b50f345661fe5a/rollup.config.js#L33

### Expected Behavior

Link goes to https://github.com/rollup/plugins/tree/master/packages/node-resolve

### Actual Behavior

Link goes to https://github.com/rollup/plugins

**Comment by dasa** [comment]
Hopefully this change will make this open the directory as well: `npm repo @rollup/plugin-babel`

**Comment by shellscape** [comment]
@silverwind to make this happen we need to do things a little different than your PR. Referencing https://github.com/npm/normalize-package-data#what-normalization-currently-entails for spec, we'll need you to:

- Use the following format for specifying `repository`:

```json
{
  "repository": { "url": 'rollup/plugins', "directory": 'packages/foo' }
}
```

- One commit per plugin on the PR branch, in the format of:

```
chore(plugin-name): add directory to package repository field
```

Where `plugin-name` is the shortname of a plugin. e.g. `commonjs` for `@rollup/plugin-commonjs`. The commit message should be the same for each plugin commit. That will allow us to do a regular merge and each plugin's changelog will reflect correctly. (It's not ideal, but we rarely do mass updates to the repo)
