### ISSUE TITLE
Plugins requiring old rollup version

### ISSUE THREAD

**Issue by tommck** [rollup/plugins#379]
@rollup/plugin-inject@4.0.1 requires a peer of rollup@^1.20.0
- Rollup Plugin Name: @rollup/plugin-inject (+ others including @rollup/pluginutils@3.0.8)
- Rollup Plugin Version: 4.0.1
- Rollup Version: 2.9.1
- Operating System (or Browser): Windows
- Node Version: 12

### How Do We Reproduce?
just install them  both
https://repl.it/repls/FrostyFavorableClients

### Expected Behavior
The packages would be updated when rollup is

### Actual Behavior
They're depending on a pretty old version (even major version behind)

**Comment by tommck** [comment]
Closing without any information?  What the heck?

**Comment by tommck** [comment]
@shellscape any explanation?

**Comment by shellscape** [comment]
I blame the mobile UX, that was supposed to be close with comment.

We publish package updates as we're able to. Please have patience and refrain from opening issues for NPM warnings.

Also please use the 'Edit' function on replies to avoid creating additional noise.

**Comment by tommck** [comment]
Well, it's my experience that warnings about missing peer dependencies are often a big deal, meaning a package won't function properly as-is.  That coupled with the difference being a _major_ version led me to believe that I can't trust this version of the plugins to work correctly.

If it will work with later versions, do you want me to send a PR to update?
I'm not familiar with the code base, but I can update package references rather quickly.
