### ISSUE TITLE
Using plugin-babel as output plugin for TypeScript input

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/plugins#380]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.0.0
- Rollup Version: 2.9.1
- Operating System (or Browser): Linux
- Node Version: v14.2.0

### How Do We Reproduce?

I want to generate from the same Typescript input two outputs: one for ES6 and one for ES5.  For this I want to use rollup/plugin-babel as output plugin. In particular, I want to have two outputs for the same input: one generated by rollup, that is not touched by babel, and one transpiled by babel.  (So I want to have output as array)
 
I create a file, i.ts:
```typescript
let a: string = '44'
```
and rollup.config.js.  This works:
```javascript
import babel from '@rollup/plugin-babel';

export default {
    input: 'i.ts',
    output: {
        esModule: true,
        format: 'es',
    }, plugins: [
        babel({extensions: ['.ts'], babelHelpers: 'bundled', presets: [['@babel/preset-typescript']]})
    ]
}
```
but does not let me create two outputs from one input.  This fails:
```javascript
import babel from '@rollup/plugin-babel';

export default {
    input: 'i.ts',
    output: {
        esModule: true,
        format: 'es',
        plugins: [babel({babelHelpers: 'bundled', presets: [['@babel/preset-typescript']]})]
    }
}
```
with:
```
i.ts → stdout...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
i.ts (1:5)
1: let a: string = '44'
        ^
```
This also fails with the same error:
```javascript
import {getBabelOutputPlugin} from '@rollup/plugin-babel';

export default {
    input: 'i.ts',
    output: {
        esModule: true,
        format: 'es',
        plugins: [getBabelOutputPlugin({babelHelpers: 'bundled', presets: [['@babel/preset-typescript']]})]
    }
}
```
### Expected Behavior

I expect that rollup is forced by output-plugin-babel to ignore the TypeScript annotations.

### Actual Behavior

Rollup struggles with the TypeScript annotations.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by dilyanpalauzov** [comment]
I just realized that babel cannot be used just as output plugin, for the case that the input is in TypeScript and there are two outputs: one transpiled by babel and one untouched, as for the untouched plugin babel is not involved and nothing convinces rollup to handle TypeScript input.
