### ISSUE TITLE
@rollup/plugin-babel: babelHelpers option error

### ISSUE THREAD

**Issue by dangreen** [rollup/plugins#381]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.0.0
- Rollup Version: 1.13.0
- Operating System (or Browser): macOS
- Node Version: v11.15.0

### How Do We Reproduce?

https://github.com/canvg/canvg/pull/1046#discussion_r423445163

### Expected Behavior

Lookup `@babel/plugin-transform-runtime` over babelrc and presets.

### Actual Behavior

With `babelHelpers: 'runtime'` @rollup/plugin-babel lookup `@babel/plugin-transform-runtime` only in plugin options, but plugin-transform-runtime is included in preset (or in babelrc).

```
src/index.ts → lib/index.js, lib/index.es.js...
[!] (plugin babel) Error: You must use the `@babel/plugin-transform-runtime` plugin when `babelHelpers` is "runtime".

node_modules/regenerator-runtime/runtime.js
Error: You must use the `@babel/plugin-transform-runtime` plugin when `babelHelpers` is "runtime".

    at error (/Users/dangreen/github/canvg/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/Users/dangreen/github/canvg/node_modules/rollup/dist/shared/node-entry.js:11878:12)
    at Object.error (/Users/dangreen/github/canvg/node_modules/rollup/dist/shared/node-entry.js:12912:24)
    at Object.error (/Users/dangreen/github/canvg/node_modules/rollup/dist/shared/node-entry.js:12081:38)
    at preflightCheck (/Users/dangreen/github/canvg/node_modules/@rollup/plugin-babel/dist/index.js:188:11)

error Command failed with exit code 1.
```

**Comment by lijialiang** [comment]
I encountered the same problem

rollup.config.js

```
import babel, { getBabelOutputPlugin } from '@rollup/plugin-babel'

export default {
  input: './index.js',
  output: {
    format: 'umd',
    dir: 'dist'
  },
  plugins: [
    getBabelOutputPlugin({
      configFile: path.resolve(__dirname, '.babelrc'),
      allowAllFormats: true
    }),
    babel({
      babelHelpers: 'runtime'
    })
  ]
}
```


.babelrc

```
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-class-properties",
      { "loose": true }
    ],
    [
      "@babel/plugin-transform-runtime",
      { "corejs": 2 }
    ]
  ]
}
```

```
./index.js → dist...
[!] (plugin babel) Error: You must use the `@babel/plugin-transform-runtime` plugin when `babelHelpers` is "runtime".

node_modules/@babel/runtime-corejs2/core-js/promise.js
```

**Comment by lijialiang** [comment]
I found a configuration method to avoid this error

```
babel({
    babelHelpers: 'runtime',
    skipPreflightCheck: true
})
```

but how do you compile the dependencies of babel runtime to a file? :(

**Comment by shellscape** [comment]
@dangreen A link to a PR is not a proper reproduction.

Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further. Given there's a workaround already posted, we'll leave this open, but the rollup team won't triage this until a proper repro is added.

**Comment by dangreen** [comment]
@shellscape https://repl.it/repls/IckyBrightCache

**Comment by IanMitchell** [comment]
Ran into this too while updating dependencies. Happy to push the WIP branch if it helps

**Comment by anthonator** [comment]
@shellscape looks like @dangreen provided a reproduction. Does that suffice? Is there anything else you need from us?

**Comment by shellscape** [comment]
A PR would be amazing. I'm not the sole contributor here and I haven't worked on the Babel plugin.

**Comment by chovy** [comment]
I'm still getting this.

**Comment by phun-ky** [comment]
Same here.

**Comment by tjyuanpeng** [comment]
add `exclude` to config
that`s works to me.

```
babel({    
  babelHelpers: 'runtime',
  exclude: '**/node_modules/**',
}),
```

**Comment by lkangle** [comment]
> add `exclude` to config, it works for me
> 
> ```
> babel({    
>   babelHelpers: 'runtime',
>   exclude: '**/node_modules/**',
> }),
> ```

Yes, it solved my problem, too

**Comment by dsrkafuu** [comment]
> 
> 
> add `exclude` to config, it works for me
> 
> ```
> babel({    
>   babelHelpers: 'runtime',
>   exclude: '**/node_modules/**',
> }),
> ```

Works great for me 😀

**Comment by zfarhad** [comment]
> add `exclude` to config, it works for me
> 
> ```
> babel({    
>   babelHelpers: 'runtime',
>   exclude: '**/node_modules/**',
> }),
> ```

If it doesn't work, use this one:

`babel({
            babelHelpers: 'runtime',
            exclude: /^(.+\/)?node_modules\/.+$/
        })`

**Comment by coramat** [comment]
Unfortunately, I am still getting this issue with:

```
    babel({
      extensions: [...DEFAULT_BABEL_EXTENSIONS, '.ts', '.tsx'],
      exclude: /^(.+\/)?node_modules\/.+$/,
      babelHelpers: 'runtime'
    }),
```

I also tried using` skipPreflightCheck: true` but it is breaking other behaviors so I had to remove it.

Has anyone any other suggestions?
Thanks:)

**Comment by zfarhad** [comment]
> Unfortunately, I am still getting this issue with:
> 
> ```
>     babel({
>       extensions: [...DEFAULT_BABEL_EXTENSIONS, '.ts', '.tsx'],
>       exclude: /^(.+\/)?node_modules\/.+$/,
>       babelHelpers: 'runtime'
>     }),
> ```
> 
> I also tried using` skipPreflightCheck: true` but it is breaking other behaviors so I had to remove it.
> 
> Has anyone any other suggestions? Thanks:)

Can you share your code base? rollup config, babel config, package.json and etc
I will try to reproduce the error and look at it closely.

**Comment by coramat** [comment]
Hi! Thanks for the fast reply:)
Unfortunately, I cannot share the code base, but I can attach the rollup config and package.json in case you notice something odd.

rollup config:
```js
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import babel from '@rollup/plugin-babel';
import postcss from 'rollup-plugin-postcss';
import bundleSize from 'rollup-plugin-bundle-size';
import replace from '@rollup/plugin-replace';
import svgr from '@svgr/rollup';
import typescript from 'rollup-plugin-typescript2';
import { DEFAULT_EXTENSIONS as DEFAULT_BABEL_EXTENSIONS } from '@babel/core';

import pkg from './package.json';

const isProd = process.env.NODE_ENV === 'production';
const isTesting = process.env.NODE_ENV === 'testing';
const processEnv = isProd || isTesting ? 'production' : 'development';

export const baseConfig = ({ mainFile = pkg.main, moduleFile = pkg.module, injectCSS = true } = {}) => ({
  input: 'src/index.ts',
  external: ['react', 'react-dom', (id) => id.includes('@babel/runtime')],
  onwarn(warning, rollupWarn) {
    if (warning.code !== 'CIRCULAR_DEPENDENCY') {
      rollupWarn(warning);
    }
  },
  output: [
    {
      file: mainFile,
      format: 'cjs',
      sourcemap: true,
      exports: 'named',
    },
    {
      file: moduleFile,
      format: 'esm',
      sourcemap: true,
      exports: 'named',
    },
  ],
  plugins: [
    replace({
      __ENV__: JSON.stringify(processEnv),
      __REACT_FLOW_VERSION__: JSON.stringify(pkg.version),
      preventAssignment: true,
    }),
    bundleSize(),
    postcss({
      minimize: isProd,
      inject: injectCSS,
    }),
    svgr(),
    resolve(),
    typescript({
      clean: true,
    }),
    commonjs({
      include: 'node_modules/**',
    }),
    babel({
      extensions: [...DEFAULT_BABEL_EXTENSIONS, '.ts', '.tsx'],
      exclude: /^(.+\/)?node_modules\/.+$/,
      babelHelpers: 'runtime'
    }),
  ],
});

export default isProd && !isTesting
  ? [
      baseConfig(),
      baseConfig({
        mainFile: 'dist/nocss/ReactFlow-nocss.js',
        moduleFile: 'dist/nocss/ReactFlow-nocss.esm.js',
        injectCSS: false,
      }),
    ]
  : baseConfig();

```
package.json

```json
{
  "scripts": {
    "build": "rollup -c --environment NODE_ENV:production && postcss src/*.css --dir dist",
    "start": "rollup -w -c",
    "start:examples": "cd example && npm start",
    "build:examples": "cd example && npm run build",
    "start:testserver": "npm run build && npm run start:examples",
    "build:dev": "npm install && npm run build && cd example && npm install && npm run build",
    "dev:wait": "start-server-and-test start:testserver http-get://localhost:3000",
    "test": "BROWSER=none npm run dev:wait test:chrome",
    "test:chrome": "cypress run --browser chrome --headless",
    "test:firefox": "cypress run --browser firefox",
    "test:all": "npm run test:chrome && npm run test:firefox",
    "cypress": "npm run dev:wait cy:open",
    "cy:open": "cypress open",
    "release": "npm run test && release-it",
    "release:notest": "release-it",
    "release:next": "release-it --preRelease=next"
  },
  "dependencies": {
    "@babel/runtime": "^7.16.3",
    "@types/d3": "^7.0.0",
    "@types/react-redux": "^7.1.18",
    "classcat": "^5.0.3",
    "d3-selection": "^3.0.0",
    "d3-zoom": "^3.0.0",
    "fast-deep-equal": "^3.1.3",
    "react-draggable": "^4.4.4",
    "react-redux": "^7.2.4",
    "redux": "^4.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/plugin-transform-runtime": "^7.16.4",
    "@babel/preset-env": "^7.15.0",
    "@babel/preset-react": "^7.14.5",
    "@rollup/plugin-babel": "^5.3.0",
    "@rollup/plugin-commonjs": "^20.0.0",
    "@rollup/plugin-node-resolve": "^13.0.4",
    "@rollup/plugin-replace": "^3.0.0",
    "@svgr/rollup": "^5.5.0",
    "@types/redux": "^3.6.31",
    "@types/resize-observer-browser": "^0.1.6",
    "autoprefixer": "^10.3.3",
    "babel-preset-react-app": "^10.0.0",
    "cypress": "^8.3.1",
    "postcss": "^8.3.6",
    "postcss-cli": "^8.3.1",
    "postcss-nested": "^5.0.6",
    "prettier": "2.3.2",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "release-it": "^14.11.5",
    "rollup": "^2.56.3",
    "rollup-plugin-bundle-size": "^1.0.3",
    "rollup-plugin-livereload": "^2.0.5",
    "rollup-plugin-postcss": "^4.0.1",
    "rollup-plugin-serve": "^1.1.0",
    "rollup-plugin-typescript2": "^0.30.0",
    "start-server-and-test": "^1.13.1",
    "typescript": "^4.4.2"
  },
  "peerDependencies": {
    "react": "16 || 17",
    "react-dom": "16 || 17"
  },
  "files": [
    "dist",
    "nocss"
  ]
}
```

**Comment by zfarhad** [comment]
> Hi! Thanks for the fast reply:) Unfortunately, I cannot share the code base, but I can attach the rollup config and package.json in case you notice something odd.
> 
> rollup config:
> 
> ```js
> import resolve from '@rollup/plugin-node-resolve';
> import commonjs from '@rollup/plugin-commonjs';
> import babel from '@rollup/plugin-babel';
> import postcss from 'rollup-plugin-postcss';
> import bundleSize from 'rollup-plugin-bundle-size';
> import replace from '@rollup/plugin-replace';
> import svgr from '@svgr/rollup';
> import typescript from 'rollup-plugin-typescript2';
> import { DEFAULT_EXTENSIONS as DEFAULT_BABEL_EXTENSIONS } from '@babel/core';
> 
> import pkg from './package.json';
> 
> const isProd = process.env.NODE_ENV === 'production';
> const isTesting = process.env.NODE_ENV === 'testing';
> const processEnv = isProd || isTesting ? 'production' : 'development';
> 
> export const baseConfig = ({ mainFile = pkg.main, moduleFile = pkg.module, injectCSS = true } = {}) => ({
>   input: 'src/index.ts',
>   external: ['react', 'react-dom', (id) => id.includes('@babel/runtime')],
>   onwarn(warning, rollupWarn) {
>     if (warning.code !== 'CIRCULAR_DEPENDENCY') {
>       rollupWarn(warning);
>     }
>   },
>   output: [
>     {
>       file: mainFile,
>       format: 'cjs',
>       sourcemap: true,
>       exports: 'named',
>     },
>     {
>       file: moduleFile,
>       format: 'esm',
>       sourcemap: true,
>       exports: 'named',
>     },
>   ],
>   plugins: [
>     replace({
>       __ENV__: JSON.stringify(processEnv),
>       __REACT_FLOW_VERSION__: JSON.stringify(pkg.version),
>       preventAssignment: true,
>     }),
>     bundleSize(),
>     postcss({
>       minimize: isProd,
>       inject: injectCSS,
>     }),
>     svgr(),
>     resolve(),
>     typescript({
>       clean: true,
>     }),
>     commonjs({
>       include: 'node_modules/**',
>     }),
>     babel({
>       extensions: [...DEFAULT_BABEL_EXTENSIONS, '.ts', '.tsx'],
>       exclude: /^(.+\/)?node_modules\/.+$/,
>       babelHelpers: 'runtime'
>     }),
>   ],
> });
> 
> export default isProd && !isTesting
>   ? [
>       baseConfig(),
>       baseConfig({
>         mainFile: 'dist/nocss/ReactFlow-nocss.js',
>         moduleFile: 'dist/nocss/ReactFlow-nocss.esm.js',
>         injectCSS: false,
>       }),
>     ]
>   : baseConfig();
> ```
> 
> package.json
> 
> ```json
> {
>   "scripts": {
>     "build": "rollup -c --environment NODE_ENV:production && postcss src/*.css --dir dist",
>     "start": "rollup -w -c",
>     "start:examples": "cd example && npm start",
>     "build:examples": "cd example && npm run build",
>     "start:testserver": "npm run build && npm run start:examples",
>     "build:dev": "npm install && npm run build && cd example && npm install && npm run build",
>     "dev:wait": "start-server-and-test start:testserver http-get://localhost:3000",
>     "test": "BROWSER=none npm run dev:wait test:chrome",
>     "test:chrome": "cypress run --browser chrome --headless",
>     "test:firefox": "cypress run --browser firefox",
>     "test:all": "npm run test:chrome && npm run test:firefox",
>     "cypress": "npm run dev:wait cy:open",
>     "cy:open": "cypress open",
>     "release": "npm run test && release-it",
>     "release:notest": "release-it",
>     "release:next": "release-it --preRelease=next"
>   },
>   "dependencies": {
>     "@babel/runtime": "^7.16.3",
>     "@types/d3": "^7.0.0",
>     "@types/react-redux": "^7.1.18",
>     "classcat": "^5.0.3",
>     "d3-selection": "^3.0.0",
>     "d3-zoom": "^3.0.0",
>     "fast-deep-equal": "^3.1.3",
>     "react-draggable": "^4.4.4",
>     "react-redux": "^7.2.4",
>     "redux": "^4.1.1"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.15.0",
>     "@babel/plugin-transform-runtime": "^7.16.4",
>     "@babel/preset-env": "^7.15.0",
>     "@babel/preset-react": "^7.14.5",
>     "@rollup/plugin-babel": "^5.3.0",
>     "@rollup/plugin-commonjs": "^20.0.0",
>     "@rollup/plugin-node-resolve": "^13.0.4",
>     "@rollup/plugin-replace": "^3.0.0",
>     "@svgr/rollup": "^5.5.0",
>     "@types/redux": "^3.6.31",
>     "@types/resize-observer-browser": "^0.1.6",
>     "autoprefixer": "^10.3.3",
>     "babel-preset-react-app": "^10.0.0",
>     "cypress": "^8.3.1",
>     "postcss": "^8.3.6",
>     "postcss-cli": "^8.3.1",
>     "postcss-nested": "^5.0.6",
>     "prettier": "2.3.2",
>     "prop-types": "^15.7.2",
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2",
>     "release-it": "^14.11.5",
>     "rollup": "^2.56.3",
>     "rollup-plugin-bundle-size": "^1.0.3",
>     "rollup-plugin-livereload": "^2.0.5",
>     "rollup-plugin-postcss": "^4.0.1",
>     "rollup-plugin-serve": "^1.1.0",
>     "rollup-plugin-typescript2": "^0.30.0",
>     "start-server-and-test": "^1.13.1",
>     "typescript": "^4.4.2"
>   },
>   "peerDependencies": {
>     "react": "16 || 17",
>     "react-dom": "16 || 17"
>   },
>   "files": [
>     "dist",
>     "nocss"
>   ]
> }
> ```

I try this one without typescript and there is no problem. This error may be due to typescript configuration.

**Comment by coramat** [comment]
Thank you very much for trying!
I tried uninstalling and reinstalling the project and it worked. Maybe there was some cached data...

**Comment by wsdmzy** [comment]
> Thank you very much for trying! I tried uninstalling and reinstalling the project and it worked. Maybe there was some cached data...

hi, how to solve it?

**Comment by enes-get-local** [comment]
I m still getting this error.

Rollup.config.js

```
import { DEFAULT_EXTENSIONS } from '@babel/core';
import babel from '@rollup/plugin-babel';
import typescript from 'rollup-plugin-typescript2';
import commonjs from '@rollup/plugin-commonjs';
import external from 'rollup-plugin-peer-deps-external';
import postcss from 'rollup-plugin-postcss';
import resolve from '@rollup/plugin-node-resolve';
import url from '@rollup/plugin-url';
import svgr from '@svgr/rollup';
import { terser } from 'rollup-plugin-terser';
import typescriptEngine from 'typescript';
import pkg from './package.json';

const config = {
  input: 'src/index.ts',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      exports: 'named',
    },
    {
      file: pkg.module,
      format: 'es',
      exports: 'named',
    },
  ],
  plugins: [
    postcss({
      plugins: [],
      minimize: true,
      extensions: ['.css'],
    }),
    external({
      includeDependencies: true,
    }),
    typescript({
      typescript: typescriptEngine,
      include: ['*.js+(|x)', '**/*.js+(|x)'],
      exclude: ['coverage', 'config', 'dist', 'node_modules/**', '*.test.{js+(|x), ts+(|x)}', '**/*.test.{js+(|x), ts+(|x)}'],
    }),
    commonjs(),
    babel({
      extensions: [...DEFAULT_EXTENSIONS, '.ts', 'tsx'],
      babelHelpers: 'runtime',
      exclude: /node_modules/,
    }),
    url(),
    svgr(),
    resolve(),
    terser(),
  ],
};

export default config;

```

package.json

```
 "engines": {
    "node": ">=14",
    "npm": ">=6"
  },
  "scripts": {
    "start": "NODE_ENV=development BABEL_ENV=development styleguidist server --open",
    "styleguide:build": "NODE_ENV=production BABEL_ENV=production styleguidist build",
    "build": "rimraf dist && NODE_ENV=production BABEL_ENV=production rollup -c",
    "build:watch": "rollup -c -w",
    "test": "jest",
    "test:coverage": "jest --coverage --forceExit --colors",
    "lint": "yarn check-types && yarn eslint && yarn stylelint",
    "lint:fix": "yarn eslint:fix && yarn stylelint:fix",
    "eslint": "eslint . --ext .js,.jsx,.tsx,.ts",
    "eslint:fix": "eslint . --ext .js,.jsx,.tsx,.ts --fix",
    "stylelint": "stylelint \"**/*.{css,scss,sass}\"",
    "stylelint:fix": "stylelint \"**/*.{css,scss,sass}\" --fix",
    "check-types": "tsc",
    "audit:fix": "npx yarn-audit-fix",
    "prepare": "yarn build",
    "prerelease": "yarn lint:fix && yarn test:coverage",
    "release": "yarn publish",
    "predeploy": "yarn styleguide:build",
    "deploy": "gh-pages -d styleguide"
  },
  "peerDependencies": {
    "react": "^17.x",
    "react-dom": "^17.x"
  },
  "devDependencies": {
    "@babel/core": "^7.16.7",
    "@babel/eslint-parser": "^7.16.5",
    "@babel/plugin-proposal-class-properties": "^7.16.7",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-syntax-flow": "^7.16.7",
    "@babel/plugin-transform-react-jsx": "^7.16.7",
    "@babel/plugin-transform-runtime": "^7.16.8",
    "@babel/preset-env": "^7.16.8",
    "@babel/preset-react": "^7.16.7",
    "@babel/preset-typescript": "^7.16.7",
    "@babel/runtime": "^7.16.7",
    "@popperjs/core": "^2.11.2",
    "@rollup/plugin-babel": "^5.3.0",
    "@rollup/plugin-commonjs": "^21.0.1",
    "@rollup/plugin-node-resolve": "^13.1.3",
    "@rollup/plugin-url": "^6.1.0",
    "@svgr/rollup": "^6.2.0",
    "@svgr/webpack": "^6.2.0",
    "@testing-library/dom": "^8.11.2",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/react-hooks": "^7.0.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/bluebird": "^3.5.36",
    "@types/enzyme": "^3.10.11",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "@types/react": "^17.0.38",
    "@types/react-dom": "^17.0.11",
    "@typescript-eslint/eslint-plugin": "^5.9.1",
    "@typescript-eslint/parser": "^5.9.1",
    "@wojtekmaj/enzyme-adapter-react-17": "^0.6.6",
    "babel-jest": "^27.4.6",
    "babel-loader": "^8.2.3",
    "babel-plugin-css-modules-transform": "^1.6.2",
    "babel-plugin-named-asset-import": "^0.3.8",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-preset-react-app": "^10.0.1",
    "css-loader": "^6.5.1",
    "enzyme": "^3.11.0",
    "enzyme-to-json": "^3.6.2",
    "eslint": "^8.7.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-config-react-app": "^7.0.0",
    "eslint-import-resolver-webpack": "^0.13.2",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jest": "^25.7.0",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "file-loader": "^6.2.0",
    "gh-pages": "^3.2.3",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.4.7",
    "jest-environment-jsdom": "^27.4.6",
    "jest-pnp-resolver": "^1.2.2",
    "jest-watch-typeahead": "^1.0.0",
    "postcss": "^8.4.5",
    "postcss-scss": "^4.0.3",
    "prettier": "^2.5.1",
    "process": "^0.11.10",
    "react": "^17.0.2",
    "react-app-polyfill": "^3.0.0",
    "react-docgen-typescript": "^2.2.2",
    "react-dom": "^17.0.2",
    "react-styleguidist": "^11.1.8",
    "react-test-renderer": "^17.0.2",
    "react-transition-group": "^4.4.2",
    "regenerator-runtime": "^0.13.9",
    "rimraf": "^3.0.2",
    "rollup": "^2.64.0",
    "rollup-plugin-peer-deps-external": "^2.2.4",
    "rollup-plugin-postcss": "^4.0.2",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-typescript2": "^0.31.1",
    "sass": "^1.48.0",
    "sass-loader": "^12.4.0",
    "style-loader": "^3.3.1",
    "stylelint": "^14.2.0",
    "stylelint-prettier": "^2.0.0",
    "stylelint-scss": "^4.1.0",
    "ts-toolbelt": "^9.6.0",
    "typescript": "^4.5.4",
    "url-loader": "^4.1.1",
    "webpack": "^5.66.0",
    "yarn-audit-fix": "^9.0.6"
  },
  "dependencies": {
    "@apollo/client": "^3.5.8",
    "@fingerprintjs/fingerprintjs-pro": "^3.5.5",
    "classnames": "^2.3.1"
  }
}

```

**Comment by ryancwalsh** [comment]
After coming here from https://github.com/google/clasp/blob/e851215b8abe4de282c62c4d61076c85e89a56ba/docs/esmodules.md, I similarly have been unable to solve this error: 
```
 [!] (plugin babel) Error: You must use the `@babel/plugin-transform-runtime` plugin when `babelHelpers` is "runtime".
```

**Comment by JusticHentai** [comment]
I got the same error in pnpm workspaces 

and solve it with `skipPreflightCheck: 'true',`
``js
babel({
        babelHelpers: 'runtime',
        skipPreflightCheck: 'true',
        extensions: [...DEFAULT_EXTENSIONS, '.ts'],
        exclude: /^(.+\/)?node_modules\/.+$/,
      }),
```

**Comment by dennykoch** [comment]
Problem still exists!

**Comment by zjtt** [comment]
收到啦，谢谢
