### ISSUE TITLE
[enhancement] Plugin: `livereload@latest`

### ISSUE THREAD

**Issue by dmgolembiowski** [rollup/plugins#383]
Request Checklist:

- [X] I have searched https://npmjs.com/ before opening this issue
- [X] I have searched https://github.com/rollup/awesome before opening this issue

### New Plugin Use Case
NPM suggested that "[I] should bug the author to publish it (or use the name yourself!)" in regard to livereload under the `@rollup` directory. Specifically, when running:
```bash
npm install --save-dev @rollup/plugin-livereload
```
the response was:
```bash
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rollup%2fplugin-livereload - Not found
npm ERR! 404 
npm ERR! 404  '@rollup/plugin-livereload@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

The need for this plugin follows the growing trend of using `@rollup` submodules for name consolidation and also tries to match the latest stable version of [livereload](https://github.com/livereload/livereload-js)
### New Plugin Proposal
I propose appropriating the `rollup-plugin-livereload` packaging to `@rollup/plugin-livereload`.

**Comment by shellscape** [comment]
Thanks for your interest. We leave it up to plugin authors to express interest in bringing their plugin into the official repo, and then evaluate the plugin at that point. I would suggest opening an issue here https://github.com/thgh/rollup-plugin-livereload to see if the author is interested in moving it here.

**Comment by thgh** [comment]
Feel free to move the livereload plugin and [others](https://www.npmjs.com/search?q=author%3Athgh%20rollup-plugin) to this repo. After the code is duplicated and published on @rollup, I will add a big message in the README that recommends to use the @rollup/plugin- version instead.

Maybe @jonkoops can help?

**Comment by jonkoops** [comment]
Yes, I can certainly help out with this. I have no objection of making it an official plugin and doing maintenance for it 👍

**Comment by shellscape** [comment]
@jonkoops thanks for stepping up to maintain the plugin. please feel free to start the migration in a PR. we'll guide you through it. once your PR is merged, we'll make you a codeowner of that plugin.

**Comment by jonkoops** [comment]
Great! We're actually in the process of cleaning up the code in our repo first, once things settle down I will take the initiative to move things over here.
