### ISSUE TITLE
plugin-babel: clarify what the skipPreflightCheck does

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/plugins#384]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.0.0

Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
https://github.com/rollup/plugins/tree/master/packages/babel#skippreflightcheck says:
> Before transpiling your input files this plugin also transpile a short piece of code for each input file. This is used to validate some misconfiguration errors, but for sufficiently big projects it can slow your build times so if you are confident about your configuration then you might disable those checks with this option.

### Your Proposal for Changes

It shall say what short piece of code exactly is transpiled and explain how keeping the default, additional compile-time, is in the interest of the user.

**Comment by shellscape** [comment]
@Andarist can you take this one?

**Comment by Andarist** [comment]
I've missed this issue before - sorry for that. I don't believe this is worth documenting though, we can add more checks in the future and it's not worth listing all of them here. This should be treated as a blackbox validation from my point of view.
