### ISSUE TITLE
[plugin-commonjs] new release ?

### ISSUE THREAD

**Issue by ashubham** [rollup/plugins#385]
@shellscape I know this has been talked about before, but it will be great to have clarity on when the new `plugin-commonjs` will be released. We are seeing daily flakiness with `namedExports` because we are using a monorepo setup.

**Comment by shellscape** [comment]
Issues asking for or about package publishing, will be closed without discussion moving forward. We simply get too many of them, and I grow weary of replying with the same message repeatedly:

We publish packages as we are able and when it's appropriate. Please exercise patience, or fork and publish on a personal scope until publishing.occurs.
