### ISSUE TITLE
[plugin-commonjs] Uncaught SyntaxError: Identifier 'react' has already been declared

### ISSUE THREAD

**Issue by ashubham** [rollup/plugins#388]
- Rollup Plugin Name: plugin-commonjs
- Rollup Plugin Version: master (unreleased)
- Rollup Version: 2.7.6 / 2.9.1
- Operating System (or Browser): OSX
- Node Version: 12.16.1

### How Do We Reproduce?

When using a lazy import along the commonjs plugin (unreleased master version), there seems to be an error in code generation causing React to be referred twice. I see this in my generated bundle:

```
import { a7 as useParams, R as react, r as react } from './index-1ed8b09b.js';
import { a as useLoadAnswerSessionMutation, A as Answer } from './answer-f19c7b7a.js';

const SavedAnswerPage = ({ answerId }) => {
    const { answerId: answerIdParam } = useParams();
    const answerGuid = answerId || answerIdParam;
    const [loadAnswer, { loading, data }] = useLoadAnswerSessionMutation(answerGuid);
    react.useEffect(() => {
        loadAnswer();
    }, []);
    if (loading || !data)
        return react.createElement("div", null, "Loading ...");
    return react.createElement(Answer, null);
};

export default SavedAnswerPage;
export { SavedAnswerPage };
//# sourceMappingURL=saved-answer-eb6381df.js.map
```

Notice `react` being imported twice.

FWIW, the `index-1ed8b09b.js` export line looks like:
```
export {Button as$, envFlags as A, eventCollector as B, Chip as C, userAction as D, systemConfigService as E, jsUtil as F, jsonConstants_1 as G, stringUtil_2 as H, translations_2 as I, blinkConstants_1 as J, jsUtil_4 as K, stringUtil_1 as L, logger_3 as M, browserUtil_7 as N, tslib_es6 as O, pubSub as P, Icon as Q, react as R, IconColor as S, IconSize as T, IconID as U, Horizontal as V, Checkbox as W, useCheckboxState as X, Vertical as Y, View as Z, LoadingIndicator as _, useQuery as a, lodash$2 as a0, cloneChildren as a1, translate as a2, Modal$1 as a3, ModalSize as a4, __extends as a5, getRenderRoot as a6, useParams as a7, useLazyQuery as b, useGlobalClientState as c, client as d, createCommonjsModule as e, commonjsGlobal as f, unwrapExports as g, result as h, reactIs as i, reactIs as j, reactDom as k, reactDom as l, useTranslation$1 as m, lodash$3 as n, classnames as o, propTypes as p, blinkConstants as q, react as r, src as s, translations as t, useMutation as u, lodash as v, logger as w, stringUtil as x, sessionStore as y, jsonConstants as z};
```

Notice here again Libs like `ReactDom`, `reactIs` and `React` are exported twice. Incidentally these are the same libs which needed the `namedExport` in the first place.

I am using dynamic import like:
```
// app.js
const SavedAnswer = React.lazy(() =>
    import('./pages/search-pages/saved-answer'),
);
```

The error goes away if I do not use dynamic imports.

### Expected Behavior

`React` and other libs should be imported only once.

### Actual Behavior

Double imports cause an error.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
