### ISSUE TITLE
plugin-virtual module IDs limited to exact-match strings

### ISSUE THREAD

**Issue by jasonkarns** [rollup/plugins#389]
- Rollup Plugin Name: virtual
- Rollup Plugin Version: 2.0.2

### Feature Use Case

I'm attempting to stub out some modules that exist within a package. However, the virtual plugin's keys only seem to accept exact string matches, whereas the module is imported in many places, all by different string names (due to relative paths).

Say I want to stub out a module that lives at `src/utils/foo.js`.

Due to the relative path from the importing module, this module may be imported via any of the following:

`import foo from './src/utils/foo'`
`import foo from '../src/utils/foo'`
`import foo from '../../src/utils/foo'`
`import foo from './utils/foo'`
`import foo from './foo'`

Even worse, some of the import statements may add the `.js` suffix, while others not.
Compounding the problem, `foo` may be at `foo/index.js` or `foo.js`, so the possible permutations of the import declaration are even greater.

### Feature Proposal

I propose the virtual plugin adopt an options format similar to the alias plugin; such that the module IDs may be provided as fully qualified paths (ie, already resolved via `path.resolve`) and/or regex patterns.

**Comment by shellscape** [comment]
Thanks for your issue. We'd be happy to review a Pull Request which added this feature.
