### ISSUE TITLE
plugin-babel: explain how input with the same import works for both typescript and @babel/preset-typescript

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/plugins#393]
- Rollup Plugin Name: plugin-babel
- Rollup Plugin Version: 5.0.0

Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
I want to use `@rollup/plugin-babel` and `@babel/preset-typescript` to strip the type hints and compile fast.  I want to be able to use the same input for both the TypeScript compiler (tsc) and for `@rollup/plugin-babel`/`@babel/preset-typescript`.

```javascript
import b from './b.ts'
```
is valid JavaScript, but not allowed by TypeScript.  With
```javascript
import b from './b.js'
```
or
```javascript
import b from './b'
```
TypeScript opens `./b.ts` if it exists, but this does not work with `@rollup/plugin-babel` + `@babel/preset-typescript` out of the box.

To have input, that works both in TypeScript (tsc) and `@rollup/plugin-babel`+`@babel/preset-typescript` one has 
* to use the `import b from './b'` syntax and 
* tell `@rollup/plugin-node-resolve` about the `.ts` extension

### Your Proposal for Changes

Add to the examples at https://github.com/rollup/plugins/blob/master/packages/babel/README.md one specially for Rollup+TypeScript:
```javascript
import resolve from '@rollup/plugin-node-resolve'
…
plugins:  [
  resolve({extensions: ['.js', '.ts']})
  babel({extensions: ['.js', '.ts]}, ...)
]
```

accommodating https://github.com/Microsoft/TypeScript-Babel-Starter (but without `include: ['src/**/*']`, and accommodating https://github.com/a-tarasyuk/rollup-typescript-babel, or at least including links to those.

Ideally, if plugin-node-resolve.extensions contains '.ts', plugin-babel shall get this somehow and do not require from the user to type it again.

**Comment by LarsDenBakker** [comment]
I don't think this is related to rollup at all, this should be explained in the documentation of babel, the babel typescript plugin and/or typescript.

**Comment by dilyanpalauzov** [comment]
I think this belongs to the documentation of `@rollup/plugin-babel`.  The babel-typescript-plugin knows nothing about rollup-plugin-node-resolve.

There are two levels of indirections here:
1. Strip type hints from TypeScript in babel
2. Integrate babel in rollup

Ideally the desired outcome shall be described at all involved places, but currently it is described nowhere.

Since the documentation of rollup-plugin-babel talks about extensions:['.ts'] passed to itself already, it needs some more words about passing the same extensions to node-resolve().

**Comment by dilyanpalauzov** [comment]
https://github.com/rollup/plugins/tree/master/packages/sucrase#usage contains
> plugins: [resolve({extensions: ['.js', '.ts']})...]

so this snippet is as much relevant in packages/babel/README.md

**Comment by shellscape** [comment]
@dilyanpalauzov if you'd like to create a tutorial or article for this, we'd be happy to link to it from our README for the babel plugin. As your proposal is, it's out of scope for this repo.
