### ISSUE TITLE
Continuous Delivery of releases

### ISSUE THREAD

**Issue by manucorporat** [rollup/plugins#396]
As an open source maintainer I empatice with the struggles of maintaining a big open source project, and rollup/plugins specially looks like a hard one.

I would love to discuss about a Continuos Delivery of releases, performed in the CI.

- Users get access to the latest fixed asap
- Maintainers does not have to go the tedious release process
- More predictable release cycles
- Controlled: maintainer can still hold a release by not updating the package.json

## Possible solution

1. Maintainer updates the package version in the package.json

2. On each commit merged to master, a script looks at the published version of every package, and performs the npm publish for the ones that have a greater release number.

**Comment by shellscape** [comment]
That's something that might happen in the future but not at the moment. Many releases contain nuance that needs to be manually inspected. I understand that many projects use CI for this purpose and I've been involved in many that do. 

Quality of release is going to outweigh the appetite for instant gratification for the time being.

**Comment by manucorporat** [comment]
Makes sense, feel free to close then!

**Comment by shellscape** [comment]
Cool, will do.
