### ISSUE TITLE
Plugin TypeScript uses a non-standard file location when logging

### ISSUE THREAD

**Issue by orta** [rollup/plugins#398]
- Rollup Plugin Name: TypeScript 
- Rollup Plugin Version: "3.1.1"

Super low priority, but a good first issue for someone. 

### Expected Behavior / Situation

```sh
[ROLLUP] bundles src/index.ts → dist...
[ROLLUP] [!] (plugin typescript) Error: @rollup/plugin-typescript TS2554: Expected 3 arguments, but got 2.
[ROLLUP] src/index.ts (56:33)
[ROLLUP] 
[ROLLUP] 56       const setupContainerDiv = handleSetupScreen({ baseURL, setup: getAuthDeets, didJoinRoom }, utils)
[ROLLUP]                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ROLLUP] 
[ROLLUP]   src/setupScreen.ts:6:3
[ROLLUP]     6   utils: PluginUtils
[ROLLUP]         ~~~~~~~~~~~~~~~~~~
[ROLLUP]     An argument for 'utils' was not provided.
```

The first one: `src/index.ts (56:33)` (which I'm pretty sure comes form this plugin) doesn't match `src/setupScreen.ts:6:3` which is the standard in TS (and generally ideal for CLI commands because shells support cmd + clicking to get directly to the line/char also)

### Actual Behavior / Situation

```
[ROLLUP] [!] (plugin typescript) Error: @rollup/plugin-typescript TS2554: Expected 3 arguments, but got 2.
[ROLLUP] src/index.ts:56:33
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by shellscape** [comment]
@orta you've heavily modified out issue template, and I can't tell what it's supposed to be. If it's a bug report, please refile using that template and fill out all sections. If it's a modification proposal (as it looks like that's the template you started to use) please refile and fill out the entire template. To help save the sanity of the maintainers, we do not allow modifying or removing portions of our issue templates.
