### ISSUE TITLE
`node-resolve` plugin no longer supports "default" require import

### ISSUE THREAD

**Issue by alexlafroscia** [rollup/plugins#402]
- Rollup Plugin Name: `node-resolve`
- Rollup Plugin Version: `v8.0.0`
- Rollup Version: `1.25.2` (through `broccoli-rollup`)
- Operating System (or Browser): macOS
- Node Version: `12.16.2`

### How Do We Reproduce?

https://repl.it/@alexlafroscia1/UnsightlyAliceblueExternalcommand

### Expected Behavior

The plugin function would be accessible by requiring `@rollup/plugin-node-resolve`

### Actual Behavior

The package no longer has a "default export" of the plugin function when importing through Node rather than ESM. While configuring Rollup directly supports the ESM style, configuring Rollup i
indirectly (like in our case, through the Broccoli wrapper plugin) does not.

Since the default ESM export is a function, I would expect the same to be true when requiring it in Node.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by alexlafroscia** [comment]
Reproduction through repl.it

https://repl.it/@alexlafroscia1/UnsightlyAliceblueExternalcommand

**Comment by shellscape** [comment]
Looks like this is expected. Changelog contains notes which address this: https://github.com/rollup/plugins/blob/master/packages/node-resolve/CHANGELOG.md#v800

**Comment by alexlafroscia** [comment]
I guess so. As a user, it seems pretty weird that ESM supports a default export but Node does not. Especially when _all_ of the documentation shows usage of the default export.

**Comment by alexlafroscia** [comment]
I'll close this, as the change seems intentional. The changelog entries just make this pretty hard to notice

> * feat: Add default export (#361)
> * feat: export defaults (#301)

Especially when ESM still _does_ support a default. You have to do a fair amount of digging to find out that _just_ the node usage changed.

**Comment by shellscape** [comment]
> You have to do a fair amount of digging to find out that just the node usage changed.

You're of course welcome to that observation, but I would disagree that it takes a _fair amount_. It takes a normal/expected amount for major versions imho.

**Comment by omsmith** [comment]
Just to add a note, given the changelog I was a bit confused at first when looking at this today since I _am_ using ESM via a `rollup.config.mjs`. However, since node doesn't use the module field in package.json, it's also impacted by the `require`-targetting breaking change.

```diff
- import nodeResolve from '@rollup/plugin-node-resolve';
+ import nodeResolvePlugin from @rollup/plugin-node-resolve';
+ const { nodeResolve } = nodeResolvePlugin;
```
