### ISSUE TITLE
ES import does not work

### ISSUE THREAD

**Issue by AlttiRi** [rollup/plugins#403]
- Rollup Plugin Name: ---
- Rollup Plugin Version: 3.0.10
- Rollup Version: ---
- Operating System (or Browser): Windows
- Node Version: 14.3.0

I get the error when I import something from `pluginutils` inside an ES module:
```
import {createFilter} from "@rollup/pluginutils";
        ^^^^^^^^^^^^
SyntaxError: The requested module '@rollup/pluginutils' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from '@rollup/pluginutils';
const {createFilter} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:135:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)

```

### How Do We Reproduce?
Create the project from 2 files:

_package.json_

```js
{
  "name": "example",
  "version": "1.0.0",
  "type": "module",
  "devDependencies": {
    "@rollup/pluginutils": "3.0.10"
  }
}
```

_example.js_

```js
import {createFilter} from "@rollup/pluginutils";
```
Run `example.js`

### Expected Behavior
No errors. `index.es.js` was imported.

### Actual Behavior
The error that is listed above. `index.js` was imported.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by AlttiRi** [comment]
https://github.com/AlttiRi/ex-403.git

**Comment by AlttiRi** [comment]
The Readme file has been added, I expect all the bureaucratic formalities to be completed.

**Comment by AlttiRi** [comment]
It's would be OK if the issue was closed as duplicate or smth other, but currently it is closed for no reason. It's force me create a new one.
