### ISSUE TITLE
[plugin-babel] esm import not working

### ISSUE THREAD

**Issue by gera2ld** [rollup/plugins#404]
- Rollup Plugin Name: @rollup/plugin-babel, @rollup/plugin-node-resolve
- Rollup Plugin Version: @rollup/plugin-babel@5.0.2, @rollup/plugin-node-resolve@8.0.0
- Rollup Version: 2.10.5
- Operating System (or Browser): Mac OS X 10.15.4
- Node Version: 14.0.0

### How Do We Reproduce?

In `rollup.conf.js`, add:

```js
import babel from '@rollup/plugin-babel';

console.log(babel);
```

Then run `rollup -c rollup.conf.js`.

### Expected Behavior

Expect `babel` to be a function.

### Actual Behavior

`babel` is an object:

```
{
  babel: [Function (anonymous)],
  createBabelInputPluginFactory: [Function: createBabelInputPluginFactory],
  createBabelOutputPluginFactory: [Function: createBabelOutputPluginFactory],
  default: [Function (anonymous)],
  getBabelInputPlugin: [Function (anonymous)],
  getBabelOutputPlugin: [Function (anonymous)]
}
```

Similar issue also occurs in `@rollup/plugin-node-resolve`.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
