### ISSUE TITLE
default export of plugin-node-resolve does not work when using untranspiled (*.mjs) rollup config

### ISSUE THREAD

**Issue by arlac77** [rollup/plugins#408]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 8.0.0 (7.x was working)
- Rollup Version: 2.10.8
- Operating System (or Browser): darwin
- Node Version: 14.3.0

### How Do We Reproduce?

when importing plugin from an untranspiled config file (rolloup.plugin.mjs) 
```js
import resolve from "@rollup/plugin-node-resolve";

export default {
    plugins: [resolve()]
};
```

### Expected Behavior
default export to be the resolve function

### Actual Behavior

```
rollup -c rollup.config.mjs
[!] TypeError: resolve is not a function
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
