### ISSUE TITLE
@rollup/plugin-commonjs: Named import is undefined from UMD module with default export

### ISSUE THREAD

**Issue by BryceMehring** [rollup/plugins#409]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 12.0.0
- Rollup Version: 2.10.8
- Operating System (or Browser): Browser
- Node Version: 12.16.1

### How Do We Reproduce?

https://repl.it/repls/EasygoingStudiousFeed

Rollup version 2.3.4 and onward seems to be causing the issue. Rollup version 2.3.3 does not have the issue and the code works as expected. The reproduction link uses the latest version of rollup and the commonjs plugin. Similar to https://github.com/rollup/plugins/issues/400

### Expected Behavior

Named imports from UMD modules with a default export should resolve to the correct variable.

### Actual Behavior

Named imports are resolving from the default export which in this case is undefined.

**Comment by danielgindi** [comment]
This is the exact same issue as #400.  
Please refer to my reply there and read carefully. Following the links is also recommended.  
The gist of it - we follow the babel standard with __esModule export for interop between CJS and ESM. It does not support both named exports and default export, and there's no good choice between them.

So there are two ways to do this correctly,
1. Add the named exports over the defaults exports too - to make them compatible (also with webpack and other packers). This is what most people do.
2. Use destructured `require` combined with #414

**Comment by shellscape** [comment]
Closing in favor of #400.
