### ISSUE TITLE
default export of plugin-node-resolve does not work when using untranspiled (*.mjs) rollup config

### ISSUE THREAD

**Issue by arlac77** [rollup/plugins#412]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 8.0.0 (7.x was working)
- Rollup Version: 2.10.8
- Operating System (or Browser): Darwin
- Node Version: 14.3.0

### How Do We Reproduce?

```sh
rollup -c rollup.config.mjs # use node native esm
```

```js
import resolve from "@rollup/plugin-node-resolve";

export default {
    plugins: [resolve()]
};
```

[plugin-node-resolve-from-native-esm](https://github.com/arlac77/plugin-node-resolve-from-native-esm.git)

### Expected Behavior

default export to be the resolve function

### Actual Behavior

```
rollup -c rollup.config.mjs
[!] TypeError: resolve is not a function
```

[Actions output](https://github.com/arlac77/plugin-node-resolve-from-native-esm/runs/703603436?check_suite_focus=true#step:4:9)

**Comment by kuoruan** [comment]
Same issue here.

**Comment by shellscape** [comment]
_Pull requests for Node 14+ ES Module issues are welcome. Node 14+ ES Module issues that are open for more than 30 days without an accompanying PR will be closed as abandoned._

**Comment by brettz9** [comment]
In case it is the same issue, I'm seeing this error on Node 10 (though with a file being exported to have an mjs extension rather than the Rollup config itself using mjs)

**Comment by jrgleason** [comment]
Is there a work around for this? I am hitting it too

**Comment by shellscape** [comment]
@jrgleason if there was, you'd likely see it here in the comments. We welcome contributions for these types of issues.

**Comment by arlac77** [comment]
@jrgleason 

try resolve.nodeResolve()

```
import resolve from "@rollup/plugin-node-resolve";

export default {
plugins: [
    resolve.nodeResolve()
]
}
```

**Comment by jrgleason** [comment]
@arlac77 Thanks that looks like it worked

**Comment by arlac77** [comment]
@rollup/plugin-node-resolve@8.1.0 has fixed the problem
Thanks
