### ISSUE TITLE
Use `deep-freeze` equivalent with valid `license` metadata

### ISSUE THREAD

**Issue by brettz9** [rollup/plugins#420]
- Rollup Plugin Name:  @rollup/plugin-node-resolve
- Rollup Plugin Version: 8.0.0

### Expected Behavior / Situation

Uses a dependency (`deep-freeze`) that has valid `license` meta-data

### Actual Behavior / Situation

Depends on `deep-freeze` which [specifies "public domain"](https://github.com/substack/deep-freeze/issues/19), which is not a valid SPDX identifier that automated license checking tools can parse.

### Modification Proposal

Depend on an equivalent module or version without this issue.

**Comment by shellscape** [comment]
We're not in the business of policing other packages' metadata. Please take up the issue with that package.

**Comment by brettz9** [comment]
I wasn't asking for you to police their metadata, but not to not put your own users at risk for linking to packages with invalidly specified license terms. And as linked, I did take up the issue with them, but I haven't had luck previously with this author updating his packages.

**Comment by shellscape** [comment]
I don't believe we are putting anyone "at risk." This is an open source lib and anyone concerned about that package is welcome to fork and remove that dependency.

Please consider this matter closed.
