### ISSUE TITLE
Code stripped from original embedded code

### ISSUE THREAD

**Issue by devleaks** [rollup/plugins#421]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 12.0.0
- Rollup Version: 2.10.9
- Operating System (or Browser):
- Node Version: 13.8.0

### How Do We Reproduce?

Test case [here](https://github.com/devleaks/lap).

I use a piece of code from leaflet (mapping library) and one of its plugin leaflet-ant-path.
A piece of code of one of leaflet-ant-path function is (unuglified from dist):
```JavaScript
{
    key: "_calculateAnimationSpeed",
    value: function()
    {
        var t = this.options,
            e = this._map,
            n = this._animatedPathId;
        if (!t.paused && e)
        {
            var r = e.getZoom(),
                o = document.getElementsByClassName(n),
                i = 1 + t.delay / 3 / r + "s",
                a = ["-webkit-", "-moz-", "-ms-", "-o-", ""]
                .map(function(t)
                {
                    return "".concat(t, "animation-duration: ").concat(i);
                })
                .join(";");
            Array.from(o, function(t)
            {
                (t.style.cssText = a), t.setAttribute("data-animated", "true");
            });
        }
    },
}
```

For unknown (buggy?) reason, this is the code in the generated rollup bundle that is passed to `createCommonjsModule` and later to `unwrapExports`.

It is missing a portion of the code.
```JavaScript
{
    key: "_calculateAnimationSpeed",
    value: function()
    {
        var t = this.options,
            e = this._map,
            n = this._animatedPathId;
        if (!t.paused && e)
        {
            var r = e.getZoom(),
                o = document.getElementsByClassName(n),
                i = 1 + t.delay / 3 / r + "s";
        }
    },
}
```

Why does this code get stripped? I can't tell if it is a plugin issue (commonjs) or a general rollup issue. Is this a tree shaking issue? Shaked too much? Please leave my baobab alone :-D.

### Expected Behavior
In test case, blue and purple line is animated. Start the working.html file.

### Actual Behavior
Blue purple line is not animated because of stripped code. (the portion of code that is stripped precisely add the animation classes to the svg elements.)

**Comment by shellscape** [comment]
Thanks for the issue. You've found a problem with Rollup itself. Please open this issue at rollup/rollup.

**Comment by devleaks** [comment]
OK thanks.
[Here is the new issue](https://github.com/rollup/rollup/issues/3603).
