### ISSUE TITLE
[@rollup/plugin-commonjs] 12.0 multi-entry build not exposing __moduleExports

### ISSUE THREAD

**Issue by yyx990803** [rollup/plugins#424]
- Rollup Plugin Name: `@rollup/plugin-commonjs`
- Rollup Plugin Version: 12.0.0
- Rollup Version: 2.11.2
- Operating System (or Browser): macOS
- Node Version: 14.3.0

### How Do We Reproduce?

- Building with two CJS dependencies as entries (`react-is` & `prop-types`) and output ESM versions of them
- `prop-types` requires `react-is` - generated code uses `reactIs.__moduleExports`
-  generated code of `react-is` doesn't expose `__moduleExports`.

Repro: https://github.com/yyx990803/rollup-commonjs-bug

- `npm run build`
- Serve `index.html` on a local server

### Expected Behavior

`react-is` code should expose `__moduleExports`

### Actual Behavior

It doesn't.

**Comment by lukastaegert** [comment]
Looks like a duplicate of #411 for which there is already a pending PR, can you check if this works for you?

**Comment by yyx990803** [comment]
Yeah seems like a duplicate.
