### ISSUE TITLE
[node-resolve] More control over `browser` field resolution

### ISSUE THREAD

**Issue by yyx990803** [rollup/plugins#428]
- Rollup Plugin Name: `@rollup/plugin-node-resolve`
- Rollup Plugin Version: Latest

### Feature Use Case

Currently the ecosystem has really inconsistent usage of the `browser` field:

- Some packages use it as a way to alias already resolved fields:
  -  `styled-components` uses the object format to alias its Node-ESM entry to a browser ESM build.
  - `axios` uses the object format to alias a sub-path (http adaptor) to a browser compatible version.

Both cases above work as intended.

- Some packages use it as a fallback field after `module` field (e.g. [`firebase/app` which points it to a cjs file despite already having a module field](https://unpkg.com/browse/firebase@7.14.6/app/package.json))

Obviously it's problematic usage on firebase's end, but with `browser` always taking highest priority, Rollup will be using the less optimal build of `firebase/app` instead of its ESM build.

For more context, in [Vite](https://github.com/vitejs/vite) we are trying to support all above deps, and in the case of `firebase/app`, the only way for it to work during dev (which uses native ESM) is to resolve `module` field with higher priority than `browser` (when it's a string). But this leads to inconsistency between dev and build because `@rollup/plugin-node-resolve` takes `browser` over `module`. Disabling `browser` would break support for `axios` and other valid use cases for the `browser` field.

### Feature Proposal

- One solution is to respect `browser`'s position in the `mainFields` array when it's a string:

  ```js
  mainFields: ['module', 'jsnext', 'jsnext:main', 'browser', 'main']
  ```

  With the above config, string `browser` values only take precedence over `main`.

  If `browser` is an object, it's used as an alias for already resolved paths so the order does not affect its behavior.

- To avoid the breaking change, we can add an extra option to enable the behavior suggested above.

**Comment by yyx990803** [comment]
nvm, I decided to drop `browser` field support in Vite.

**Comment by lukastaegert** [comment]
Make sense. Still I thought `browser` field position in `mainFields` should actually be observed, maybe something is not working as intended.

**Comment by yyx990803** [comment]
Ah, actually, after reading the source and testing it, position of `browser` in `mainFields` *is* actually respected when it's a string. I was reading the description of the `browser: true` option and assumed the highest precedence behavior is applied even when `browser` is included inside `mainFields`!
