### ISSUE TITLE
Modules with 'syntheticNamedExports' need a default export.

### ISSUE THREAD

**Issue by sirgalleto** [rollup/plugins#431]
[Original here](https://github.com/ionic-team/rollup-plugin-node-polyfills/issues/6)

- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 12.0.0
- Rollup Version: 2.10.8
- Operating System (or Browser): MacOS Catalina 10.15.4
- Node Version: 12.16 

# How Do We Reproduce?
1. Install a commonjs library with a single `module.exports`. 
2. Do a import default. `Import from 'library'`
3. build with `transformMixedEsModules: true`. 

https://repl.it/repls/StainedOrchidUserinterface

# Expected Behavior
If I understand well, the `transformMixedEsModules` should first patch the default export and then pass it to `syntheticNamedExports`

# Actual Behavior
transformMixedEsModules: true in commonjs() config:

```
Modules with 'syntheticNamedExports' need a default export. 
```

**Comment by shellscape** [comment]
We'll be happy to triage this once you've completed our bug issue template.

**Comment by sirgalleto** [comment]
@shellscape updated, let me know if I'm missing something. 

Thanks!

**Comment by mgrsskls** [comment]
I'm having the the same issue. @sirgalleto Were you able to find out anything?

**Comment by lukastaegert** [comment]
See https://github.com/ionic-team/rollup-plugin-node-polyfills/issues/6#issuecomment-664109066 for explanation. The actual bug in this plugin will be fixed soon, but your code will still be broken unless you make sure `rollup-plugin-node-polyfills` is placed AFTER `@rollup/plugin-commonjs` in your plugins array.
