### ISSUE TITLE
Maybe tests, at the very least should test against TS type definitions. 

### ISSUE THREAD

**Issue by seivan** [rollup/plugins#434]
### Expected Behavior / Situation
Expect plugins to work when configuring Rollup with Typescript

### Actual Behavior / Situation
Getting compiler errors with various plugins not matching Rollups type definitions.

### Modification Proposal
If plugins aren't going to be written in Typescript, could they at the very least have a test case making sure they match the interface Rollup is expecting? 

[This](https://github.com/rollup/plugins/pull/433) one was missing `name` which is also documented and Rollup doesn't define it as optional, which is even better than documentation. So testing against that is a decent way of making sure the docs are followed.

**Comment by shellscape** [comment]
Sure, we'd be happy to review a PR for those changes. Please feel welcome to open individual PRs per plugin that you'd like to see test changes for.

Going to close this as resolved for house-cleaning purposes, as we'd welcome contributions for test improvement.
