### ISSUE TITLE
namedExports option missing

### ISSUE THREAD

**Issue by matthew-dean** [rollup/plugins#437]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: latest

Documentation Is:

- [X] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

In the Rollup documentation (https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module), it says:

> This error frequently occurs with CommonJS modules converted by @rollup/plugin-commonjs, which makes a reasonable attempt to generate named exports from the CommonJS code but won't always succeed, because the freewheeling nature of CommonJS is at odds with the rigorous approach we benefit from in JavaScript modules. It can be solved by using the namedExports option, which allows you to manually fill in the information gaps.

I have the error described `Error: "[name] is not exported by [module]"` but there is no namedExports option. This link provided goes nowhere: https://github.com/rollup/plugins/tree/master/packages/commonjs#custom-named-exports

### Your Proposal for Changes

Either document `namedExports` or update the Rollup documentation to clarify how to solve this issue without it.

**Comment by shellscape** [comment]
That option was deprecated and has now been removed in a [recent PR](https://github.com/rollup/plugins/pull/427). It looks like your issue is with the rollup documentation and not the plugin itself. That being the case, you should open a docs issue on rollup/rollup instead.

**Comment by matthew-dean** [comment]
@shellscape It's not a documentation issue. I looked at the code for the commonjs plugin, and it says that namedExports are now handled automatically. However, for [this file](https://github.com/vue-typed/vue-typed/blob/v2.0.1/index.js), it fails. Is there a way to resolve this?

**Comment by shellscape** [comment]
We don't offer support here (as the issue templates all say - they also have links to support options). If you think it's a bug, please open an issue using the bug template and make sure to fill out all fields.

**Comment by matthew-dean** [comment]
@shellscape Very well: https://github.com/rollup/plugins/issues/438

**Comment by liajoy** [comment]
Is there a alternative option for namedExports?
