### ISSUE TITLE
[plugin-commonjs] fails to resolve named exports

### ISSUE THREAD

**Issue by matthew-dean** [rollup/plugins#438]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 11.1.0
- Rollup Version: 2.6.1
- Operating System (or Browser): Mac
- Node Version: 12.16.1

### How Do We Reproduce?

Vue-typed v2.0.1 has this module: https://github.com/vue-typed/vue-typed/blob/v2.0.1/index.js

Using this code:
```
import { Component } from 'vue-typed'
```
Rollup / CommonJS fails to resolve `exports.Component` to a named export `Component`

### Expected Behavior

Rollup succeeds in converting `exports.Component` to a named export `Component`

### Actual Behavior

Rollup / the CommonJS plugin fails.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by matthew-dean** [comment]
Ah damn it...

**Comment by shellscape** [comment]
😄 Sorry, the script I run to catch that is pretty quick. Get a good reproduction together and we'll re-open this.

**Comment by matthew-dean** [comment]
@shellscape I can, and I know you're busy but... would you be willing to, off the top of your head, point me in a direction where the problem might lie?

**Comment by shellscape** [comment]
Unfortunately I can't. I'm not a Vue guy and I haven't run into the same issue myself. That's why we ask for the reproductions. Most of the bugs we see are extremely nuanced and only pop up under certain conditions.

Another thought - you might have more luck of someone knowing that error without a reproduction by posting in some Vue support channels/chats as well - Vite is using Rollup under the hood and I know that the Vue core devs are very familiar with with Rollup now.

**Comment by matthew-dean** [comment]
@shellscape Fair enough, I appreciate your feedback!

**Comment by JuoCode** [comment]
@shellscape I have the same problem in my react project, please see https://replit.com/@gjdrift/rollup-plugin-repro

**Comment by malvika1596** [comment]
Hi @matthew-dean is this issue resolved? I am facing a similar issue with the legacy app while trying to update to newer version of commonjs.
