### ISSUE TITLE
Provide option to strip comments from JSON files (JSONC)

### ISSUE THREAD

**Issue by panoply** [rollup/plugins#44]
- Rollup Plugin Name: @rollup/plugin-json
- Rollup Plugin Version: 4.0.0

### Feature Use Case

Comments in JSON are a thing. While one can strip comments from JSON files before passing contents to the json plugin it would be nice if the plugin provided this an option for convenience sake.

### Feature Proposal

You could leverage the [strip-json-comments](https://github.com/sindresorhus/strip-json-comments/blob/master/index.js) module or use an expression (_something like_ `^[^"{}[\],]*?\/\*?\/?.*?(?:\*\/)?$`_would *maybe* suffice_ ) – either way you get the point. Probably best to provide as an opt in to prevent files being parsed for comments by default.

**Comment by shellscape** [comment]
The `strip` plugin is really meant to only target code, and while it could technically be used on other files, the default filter is `'**/*.js'`. This is a good opportunity for a new third party plugin, but not a great fit for the `strip` plugin. Thanks for opening the issue, and please do submit a plugin for this to rollup/awesome if you take that task on.

**Comment by panoply** [comment]
Yeah, nah. 

```js
import { createFilter, dataToEsm } from '@rollup/pluginutils'
import strip from 'strip-json-comments'

export default function json (options = {}) {
  const filter = createFilter(options.include, options.exclude)
  const indent = 'indent' in options ? options.indent : '\t'
  const jsonc = 'jsonc' in options ? options.jsonc : false

  return {
    name: 'json',

    // eslint-disable-next-line no-shadow
    transform (json, id) {
      if (id.slice(-5) !== '.json' || !filter(id)) return null

      return {
        code: dataToEsm(JSON.parse(jsonc ? strip(json) : json), {
          preferConst: options.preferConst,
          compact: options.compact,
          namedExports: options.namedExports,
          indent
        }),
        map: { mappings: '' }
      }
    }
  }
}
```

**Comment by gemxx** [comment]
> Yeah, nah.
> 
> ```js
> import { createFilter, dataToEsm } from '@rollup/pluginutils'
> import strip from 'strip-json-comments'
> 
> export default function json (options = {}) {
>   const filter = createFilter(options.include, options.exclude)
>   const indent = 'indent' in options ? options.indent : '\t'
>   const jsonc = 'jsonc' in options ? options.jsonc : false
> 
>   return {
>     name: 'json',
> 
>     // eslint-disable-next-line no-shadow
>     transform (json, id) {
>       if (id.slice(-5) !== '.json' || !filter(id)) return null
> 
>       return {
>         code: dataToEsm(JSON.parse(jsonc ? strip(json) : json), {
>           preferConst: options.preferConst,
>           compact: options.compact,
>           namedExports: options.namedExports,
>           indent
>         }),
>         map: { mappings: '' }
>       }
>     }
>   }
> }
> ```

This is really helpful for jsonc used
