### ISSUE TITLE
[commonjs] mixed esm/cjs output

### ISSUE THREAD

**Issue by bugzpodder** [rollup/plugins#441]
- Rollup Plugin Name: rollup-plugin-commonjs
- Rollup Plugin Version: latest
- Rollup Version: latest
- Operating System (or Browser): macOS
- Node Version: 12

### How Do We Reproduce?

https://repl.it/repls/PlasticSubduedQueryplan
https://repl.it/repls/OutgoingIntrepidLifecycles

### Actual Behavior
I have a 3rd party lib esm build with a require call.  I can't seem to transform it without the require call.

I think the issue is rollup doesn't like `export var x = require('./foo');`

original:
https://www.unpkg.com/browse/react-use@15.1.1/esm/util.js

**Comment by LarsDenBakker** [comment]
What sort of behavior are you expecting here? That file can't run in node js as is either.

**Comment by TrySound** [comment]
This is not valid code in node native es modules. Better to avoid mixing esm and cjs and and rely only on one module system.

**Comment by bugzpodder** [comment]
sounds like we should close this, I wasn't sure if its a bug or simply invalid as rollup plugin simply barfs on it.  Thanks!
