### ISSUE TITLE
Missing option documentation

### ISSUE THREAD

**Issue by mdouglasbrett** [rollup/plugins#450]
- Rollup Plugin Name: @rollup/plugin-strip 
- Rollup Plugin Version: "^1.3.3"

Documentation Is:

- [X] Missing
- [X] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The strip plugin has `include` and `exclude` options that are not documented on its dedicated page. The fallback for `include` is any `.js` file, `.jsx` is skipped unless specified.

### Your Proposal for Changes
Add the `include` and `exclude` options to the documentation in the dedicated readme.

**Comment by shellscape** [comment]
Would be happy to review a PR which added this documentation.
