### ISSUE TITLE
[commonjs] ignore: [ 'conditional-runtime-dependency' ] no longer working

### ISSUE THREAD

**Issue by RobCC** [rollup/plugins#453]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version:13.0.0
- Rollup Version: 2.16.1
- Operating System (or Browser): Windows
- Node Version: 12.16.1

### How Do We Reproduce?

I'm trying to read a config file (in the form of a JS file returning an object) using `require`:
```js
function readJSFile(relativePath) {
   const jsFile = require(relativePath);
}
```
This gets compiled into:
```js
function commonjsRequire() {
  throw new Error('Dynamic requires are not currently supported by @rollup/plugin-commonjs');
}
```

I search and found an option on `rollup-plugin-commonjs` named `conditional-runtime-dependency` to prevent this issue, but seems that it's no longer working.

Here's a [REPL.it](https://repl.it/@RobCC/PlainFrizzyQuadrilateral#.replit) with an example.

As for context, I'm trying to use a small code that will run on node to read a config file in the form of a JS file, similar to `babel.config.js`.

### Expected Behavior

An alternative or workaround to accomplish this without getting the current issue.

### Actual Behavior

Got a runtime error: `Dynamic requires are not currently supported by @rollup/plugin-commonjs`.

**Comment by shellscape** [comment]
Thanks for opening an issue. Unfortunately this isn't a bug report, because you're reporting that the plugin is working as expected but doesn't support a condition that you'd like it to. This is more a support request, asking for help. Support isn't something we offer here, and the issue templates contain resources for reaching out for support. We're going to close this issue as a support request, but other users may still leave comments.

**Comment by RobCC** [comment]
Understood.

For anyone having this issue, I separated the function that had the dynamic import into a separate file (e.g. named `reader.js`), then proceeded to add it as `dynamicRequireTargets`:

```js
 plugins: [
    commonjs({
      dynamicRequireTargets: [
        './path/to/reader.js'
      ],
    }),
    getBabelOutputPlugin({
      presets: ['@babel/preset-env'],
      plugins: [['@babel/plugin-transform-runtime', { useESModules: false }]]
    }),
  ],
```

Side note:
I also use `rollup-plugin-preserve-shebangs`. Seems like adding `dynamicRequireTargets` breaks it. I raised an issue for this [here](https://github.com/elado/rollup-plugin-preserve-shebangs/issues/4). In the meantime, I used `banner` to insert the shebangs into the final build file.

```js
output: {
    // ...
    banner: '#!/usr/bin/env node',
  },
```
