### ISSUE TITLE
Remove braces in if else statement after replacement

### ISSUE THREAD

**Issue by vladshcherbin** [rollup/plugins#457]
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: 2.3.3

### Expected Behavior / Situation

When replacing in if else statements, it would be nice to have braces removed, code:

```js
if (process.env.NODE_ENV === 'development') {
  console.log('dev')
} else {
  console.log('prod')
}
```

Result:

```js
console.log('prod');
```

### Actual Behavior / Situation

Current result:

```js
{
  console.log('prod');
}
```

### Modification Proposal

If possible, it would be nice to have result without braces with correct indentation.

**Comment by shellscape** [comment]
We might just want to enable RegExp so that kind of boundary can be handled by users.
