### ISSUE TITLE
[image] compare to url plugin

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#459]
- Rollup Plugin Name: image
- Rollup Plugin Version: `master`

Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The url plugin imports images as data URIs. Is the image plugin only a subset of the functionality of the url plugin? I'm not sure why the image plugin exists in that case.

### Your Proposal for Changes

Mention the url plugin in the image plugin docs and compare the two. Or deprecate and remove the image plugin if it adds nothing that the url plugin doesn't already do.

**Comment by shellscape** [comment]
Thanks for the issue. The biggest difference is the `dom` option on `plugin-image` but they both work slightly differently under the covers as one explicitly targets images, the other uris to any file type. It's not a subset but moreso a cousin.
