### ISSUE TITLE
Lack of support for `const enum` in typescript

### ISSUE THREAD

**Issue by cortopy** [rollup/plugins#463]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 4.1.2
- Rollup Version: 2.17.1
- Operating System (or Browser): Linux
- Node Version: 12

### How Do We Reproduce?

In a ts file, I have an enum like this:

```ts
export const enum PATH {
  ABOUT = "/about",
  CATALOGUE = "/books",
  // ....
}
```

I've been using `@rollup/plugin-typescript` version 2.17.1 until today and it was working fine.

However, when I just tried to upgrade to 4.1.2, I get the following error:

```
Error: 'PATH' is not exported by src/lib/navRoutes.ts, imported by src/components/atoms/icon/NavIcon.svelte
```
The weird thing is that if I convert the enum to a normal object, it works. I've tested it with other enums and I have the same result

### Expected Behavior
The build succeeds

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by ShaMan123** [comment]
+1

**Comment by ShaMan123** [comment]
https://replit.com/@ShaMan123/rollup-plugin-repro-ts-enum?v=1
