### ISSUE TITLE
something  wrong with babel plugin and polyfill

### ISSUE THREAD

**Issue by 1o1w1** [rollup/plugins#466]
- Rollup Plugin Name:   @rollup/plugin-babel
- Rollup Plugin Version:5.0.3
- Rollup Version:2.17.1
- Operating System (or Browser): chrome  83.0.4103.106
- Node Version: v12.13.1

### How Do We Reproduce?
 reproduction :   https://github.com/1o1w1/temp_rollup-polyfill
  open /example/index.html 

### Expected Behavior
no  error in   /dist/temp.umd.js
### Actual Behavior
![image](https://user-images.githubusercontent.com/22697045/85250174-6ae27780-b488-11ea-9586-c3629d88bc42.png)

demo is no error  when i remove babel plugin.  i think it is something wrong with polyfill.

**Comment by Andarist** [comment]
This looks like a Rollup bug around cyclic deps or similar to me.

commonjs plugin receives [this file](https://github.com/zloirock/core-js/blob/717ff8bca8e68508ef6cef7eb673d0b39265739a/packages/core-js-pure/override/internals/export.js) and transforms it to:
```js
/* imports */
var _export = function() { /* fn body */ }
export default _export;
export { _export as __moduleExports };
```
So on its own, it looks just OK.

Babel plugin is just responsible for code transformation and it does its job on file by file basis - it doesn't resolve imports or anything like that. In the final output we can see this `_exports` being used **before** it gets declared. It appears in the output as its usage and an import statement to the module containing it has been inserted by Babel, but Babel itself has no control over how (and in what order) things get flat-bundled later.

@shellscape I'm afraid I won't have time to reduce this repro case to a minimal one, so it could be reported to Rollup itself.

**Comment by 1o1w1** [comment]
I need help ,  reopen the issue please @Andarist  @shellscape

**Comment by shellscape** [comment]
@1o1w1 please follow the advice above and post the the error and reproduction to `rollup/rollup`
