### ISSUE TITLE
[node-resolve]: Support "browser" field external mappings

### ISSUE THREAD

**Issue by guybedford** [rollup/plugins#472]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: latest

### Feature Use Case

The package.json `"browser"` field supports external mappings of the form:

```js
{
  "browser" {
    "external": "newexternal",
    "./local.js": "external/subpath"
  }
}
```

For example see https://github.com/sodium-friends/sodium-universal/blob/master/package.json#L14

### Feature Proposal

By default the node-resolve plugin is currently handling these as local package paths instead of external resolutions as they should be.

**Comment by volkanunsal** [comment]
This is very much needed.

**Comment by shellscape** [comment]
@volkanunsal we'd happily review a pull request that fulfilled this request

**Comment by guybedford** [comment]
I'm going to reopen this one as it seems like an important omission in the default resolution behaviour unless I've missed that it's been addressed already.

**Comment by volkanunsal** [comment]
I looked at the source code to potentially provide a patch for it, but the resolution algorithm is so convoluted and written in an idiosyncratic way. I can't make head or tail of it.
