### ISSUE TITLE
Watching broken in TypeScript 4.1.2 and newer (including latest version 5.x+)

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#478]
### Overview

This regression is almost certainly caused by https://github.com/rollup/plugins/pull/352. That's the only real commit in 4.1.2 and things work with 4.1.1. Furthermore that puts `createWatchProgram` in an `if` statement.

This issue has been reported by a few different users of the Sapper web framework (also created by Rich Harris) over the past few days https://github.com/sveltejs/sapper/issues/1293

### Environment

- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: 4.1.2
- Rollup Version: 2.18.0
- Operating System (or Browser): Ubuntu
- Node Version: v12.16.3

### How Do We Reproduce?

[Reproduction repo](https://github.com/babichjacob/sapper-ts-mismatch)

Steps:

1. Clone and install
2. Run `npm run dev`
3. Make a GET request, such as by visiting in the browser, `/fails` and see the result `1`
4. Modify `src/routes/fails.ts` and change `1` to `2`. The change will be picked up and "rebuild"
5. Do 3 again but still see `1` instead of the new `2`

### Expected Behavior

The page should change

### Actual Behavior

The page doesn't change

**Comment by babichjacob** [comment]
Also can reproduce on
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 5.0.1
- Rollup Version: 2.18.1
- System (or Browser): macOS 10.15.5
- Node v14.4.0

**Comment by shellscape** [comment]
_Fwiw we don't typically triage plugin issues on versions that are a full major behind_

We're happy to review PRs that address the issue.

**Comment by benmccann** [comment]
This is also broken in the latest release

**Comment by dionysiusmarquis** [comment]
@benmccann a quick fix could be to add `process.env.ROLLUP_WATCH = true` right before the `rollup.watch` inside the sapper `RollupCompiler` watch hook. But it might be better to wait for the PR

**Comment by benmccann** [comment]
Ah, thanks @dionysiusmarquis !  This one is actually a bug in Sapper then. I'll move this issue to that repo

**Comment by benmccann** [comment]
Here's the link to the issue I filed over in the Sapper repo: https://github.com/sveltejs/sapper/issues/1301

**Comment by benmccann** [comment]
Here's the PR that will fix this: https://github.com/rollup/plugins/pull/449
