### ISSUE TITLE
@rollup/plugin-babel - Transpile dependencies marked as external by rollup

### ISSUE THREAD

**Issue by johannes-z** [rollup/plugins#482]
- Rollup Plugin Name: `@rollup/plugin-babel`
- Rollup Plugin Version: `^5.0.4`

### Feature Use Case
When marking a node_module dependency as `external` through rollup, `@rollup/plugin-babel` is never processing this dependency, even when you add it to the plugin's `include` config option - *which makes sense, as those files are never read by rollup in the first place*.

For example, in my project I build an AMD/UMD bundle, with the following `external` option:
```js
  external: [
    'vue',
    'lodash',
    /^@pnp.*/,
  ]
```

`@pnp/sp` for example uses features such `es.map` however, which isn't supported natively in IE11. Using `@babel/preset-env`, I would want to be able to specify which node_modules to transpile (but not include in the bundle), in order for my bundle to provide the necessary polyfills, while still being able to load these kind of dependency with a module loader such as SystemJS or RequireJS.

#### Example
* My project uses the feature `es.array.map`, which of course gets polyfilled since my source code is transpiled by babel.
* My project uses `@pnp/sp`, which is marked as external, and gets loaded with RequireJS' `require(...)`.
    * `@pnp/sp` requires `es.map`, which does **NOT** get polyfilled, since it cannot be transpiled as it is flagged as external by rollup.

### Feature Proposal
*Disclaimer: I'm not sure if this should be a feature of `@rollup/plugin-babel` or the core rollup lib, so I'm sorry if this is out of scope here.*

Add an option to `@rollup/plugin-babel`, that allows me to specify dependencies that get processed by babel, but are not included in the final bundle. 

I'm not certain as to what this option should look like, but maybe something like this:
```js
babel({
  transpileDependencies: [ require('@pnp/sp') ] // reads, transpiles, and adds detected ES features that need to be polyfilled according to the browserslist config to the final bundle.
})
```

---

Workaround solution: Manually specifying which polyfills you need for not-bundled dependencies, i.e. by adding `es.map` by hand. - *bad if the dependency's required ES features change over time*.

**Comment by TrySound** [comment]
Looks like your proposal is out of rollup scope. External dependencies mean they are handled later by other tool, either node or bundler. What you ask really depends on usage. It's not clear where transpiled modules should be placed and how resolved.

**Comment by TrySound** [comment]
Perhaps you could still transpile and dependencies but specify then in [manualChunks](https://rollupjs.org/guide/en/#outputmanualchunks) instead.

**Comment by shellscape** [comment]
I've tagged @Andarist for his thoughts on this as well. I'm in agreement with @TrySound on using manualChunks. There are too many unknowns around the external deps to know what to do and how to handle them. Typically external deps (e.g. those residing in node_modules) are ignored by babel in most configs.

**Comment by Andarist** [comment]
Same thoughts here - it's a job for `manualChunks` or things like https://github.com/module-federation/rollup-federation

**Comment by shellscape** [comment]
OK. Looks like we have consensus there. Thanks @johannes-z for opening the issue. We'll close this for now, but please feel free to continue the discussion.
