### ISSUE TITLE
TypeError: babel is not a function when using Node 14

### ISSUE THREAD

**Issue by looeee** [rollup/plugins#485]
- Rollup Plugin Name: **@rollup/plugin-babel**  
- Rollup Plugin Version: **5.0.4**
- Rollup Version: **2.18.1**
- Operating System (or Browser): **Windows**
- Node Version: **v14.4.0**

### How Do We Reproduce?

``` js
import babel from '@rollup/plugin-babel';
import { rollup } from 'rollup';

const plugins = [
  nodeResolve({
    mainFields: ['module'],
  }),
  commonjs({
    include: 'node_modules/**',
  }),
  babel(),
];

const inputOptions = {
  plugins: plugins,
  input: 'src/index.js'
};

const bundle = await rollup(inputOptions);
```

If you need additional details let me know. I cannot use repl.it as that uses Node 12.x

### Expected Behavior

Transpiled and bundled code.

### Actual Behavior

ERROR: `TypeError: babel is not a function`

#### Attempt 1 (failed):

``` js
import { babel } from '@rollup/plugin-babel/dist/index.es.js';
```

ERROR: 
```
SyntaxError: The requested module '@rollup/plugin-babel/dist/index.es.js' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
```

#### Attempt 2 (success):

Import default and use `babel.babel`: 

``` js
import babel from '@rollup/plugin-babel';
import { rollup } from 'rollup';

const plugins = [
  nodeResolve({
    mainFields: ['module'],
  }),
  commonjs({
    include: 'node_modules/**',
  }),
  babel.babel(),
];

const inputOptions = {
  plugins: plugins,
  input: 'src/index.js'
};

const bundle = await rollup(inputOptions);
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by looeee** [comment]
Making a repo won't make this any easier for someone to triage. You need Node 14.x and a repo cannot supply that. 

An even smaller code sample to reproduce this, as long as you have Node 14.x installed:

``` js
import babel from '@rollup/plugin-babel';

// Boom, issue demonstrated in 2 lines.
babel();
```

Requiring me to set up a repo before you'll consider this issue is non-constructive, and makes me feel like I wasted time in reporting it. 

I get that you're busy. So am I.

**Comment by TrySound** [comment]
It's not clear whether you are trying to use native es modules and how do you enable it. We do not have enough information to help you.

**Comment by shellscape** [comment]
> Making a repo won't make this any easier for someone to triage. You need Node 14.x and a repo cannot supply that.

False. There are several tools that can be used to assert the right node version, including NVM.

> Requiring me to set up a repo before you'll consider this issue is non-constructive, and makes me feel like I wasted time in reporting it.

>I get that you're busy. So am I.

I'm sorry that you feel that the instructions that everyone else follows don't apply to you, and I'm sorry that we value our time as equal to yours.

You willfully chose not to provide the info that we require to triage issues from a multitude of different users across a multitude of different environments, each with specific nuances. As such, we willfully decline triaging your issue.

https://liberamanifesto.com/

**Comment by cowwoc** [comment]
For what it's worth, I had the same problem and discovered that replacing `babel.babel()` in the plugin section with `babel.babel` fixed the problem. I hope this helps others.

**Comment by lukastaegert** [comment]
That would look to me that Rollup just ignored the plugin in that case. Can you confirm that Babel transformations were still applied?

**Comment by cowwoc** [comment]
@lukastaegert I think so... How would I tell exactly?

**Comment by lukastaegert** [comment]
Well, depends on the setting. You could add `@babel/plugin-env` and write an arrow function. Or `@babel/plugin-syntax-jsx` and see if you can write JSX without Rollup throwing an error.

**Comment by cowwoc** [comment]
You are right. If the plugin list contains `babel` the plugin gets ignored silently. If I pass `babel.babel()` instead it works fine now.

So the original bug reporter was correct: under Node 14 you have to invoke `babel.babel()` instead of `babel()`. Either something is wrong with the plugin code or the documentation needs to be updated accordingly.

**Comment by lukastaegert** [comment]
I still would love to have some kind of reproduction. There should not be a difference in Node 14 unless you have `type: module` somewhere in your `package.json` or using `.mjs` file extensions. Otherwise there will be no progress here, we cannot look into your computer to read your code. Pack it into a gist, pack it into a repo, something like that.

**Comment by cowwoc** [comment]
I do in fact have `"type": "module"` in my package.json file.

Okay, I will try to finalize my current unit of work as soon as possible and push my changes. Once that's done I'll provide you with a link to my project which you can checkout and build on your end.

**Comment by lukastaegert** [comment]
In the meantime, have a look at this: https://rollupjs.org/guide/en/#using-untranspiled-config-files
Changing your config extension to `.mjs` could solve your issue.

**Comment by cowwoc** [comment]
FYI, I removed `"type": "module"` in `package.json` because tape (unit tests) is not compatible with it and sure enough all of a sudden `babel()` is a function instead of `babel.babel()`.

If you want to reproduce this problem, take a project you've used for testing elsewhere and simply enable `"type": "module"` in it. You should get the error right away.
