### ISSUE TITLE
Rollup plugin URL should use the emitFile API

### ISSUE THREAD

**Issue by bastienrobert** [rollup/plugins#489]
- Rollup Plugin Name: `@rollup/plugin-url`
- Rollup Plugin Version: *

### Expected Behavior / Situation
It should use the emitFile API to prevent watch to infinitely loop.

### Actual Behavior / Situation
Actually, the plugin is using `FS` and is writing to the disk which causes the file watcher to trigger a rebuild.

I think it'll be great to update the doc to specify it's a bad practice (https://rollupjs.org/guide/en/#thisemitfileemittedfile-emittedchunk--emittedasset--string).

### Modification Proposal
> Ideally the plugin should be updated to the use the proper emitFile API, or change the plugin hook to writeBundle instead which makes more sense anyways than generateBundle.
[PepsRyuu](https://github.com/PepsRyuu/nollup/issues/101#issuecomment-654382610)

**Comment by shellscape** [comment]
We'd be happy to review a PR to resolve this.

**Comment by bastienrobert** [comment]
It’s under investigation 😉

**Comment by adamzerella** [comment]
I believe this is still unresolved? Why was this issue closed?

**Comment by shellscape** [comment]
@adamzerella The bot's message looks clear to me - this requires community resolution, and none was provided, so the issue was stale and closed. The same will happen to the new issue you opened if no one steps up to help resolve it.

**Comment by jacksteamdev** [comment]
I can see why this issue went stale. I was considering a PR, but this plugin does much more than just emit assets.

1. This plugin has a lot of customization options that make a conversion more complex: `fileName`, `publicPath`, `sourceDir`, and `destDir`. Some of these options might be better handled by another plugin or option: `sourceDir` is probably an alias. `fileName` and `destDir` are things that might be handled by `assetFileNames`, but would this be desirable?

2. It seems that the design of this plugin allows for a dest folder outside of the Rollup dest dir. It can be configured to break watch mode by outputting to a folder that Rollup is watching. Is this something we want to allow?

These would be breaking changes, and these are probably features people use. All in all, I think a new plugin without the extra options would be better for the most common use cases. Maybe `rollup-plugin-url-assets`?

**Comment by art-solopov** [comment]
I second the issue. I'm guessing not using the `emitFile` API is why [the manifest plugin](https://github.com/shuizhongyueming/rollup-plugin-output-manifest) can't handle the generated files (normally it handles all assets).
