### ISSUE TITLE
getCjsExportFromNamespace messes up default exports

### ISSUE THREAD

**Issue by Veetaha** [rollup/plugins#491]
- Rollup Plugin Name: `@rollup/plugin-commonjs`
- Rollup Plugin Version: `13.0.0`
- Rollup Version: `2.18.1`
- Operating System (or Browser): Vscode extension host (I guess it is bare nodejs process)
- Node Version: `12.8.1`

### How Do We Reproduce?
[Link to REPL](https://repl.it/join/vhpbczoh-veetaha)

[Use the following rollup.config.js](https://github.com/rust-analyzer/rust-analyzer/blob/41feb816c98894d48df97193eb085738e405a3c2/editors/code/rollup.config.js#L1-L21):
```ts
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import nodeBuiltins from 'builtin-modules';

export default {
    input: 'out/src/main.js',
    plugins: [
        resolve({
            preferBuiltins: true
        }),
        commonjs()
    ],
    external: [...nodeBuiltins, 'vscode'],
    output: {
        file: './out/src/main.js',
        format: 'cjs'
    }
};
```

Add `"node-fetch": "^2.6.0"` to `package.json`
Write the following code (in reality it is generated by `tsc` as the first step before invoking rollup):
```ts
const fetch = require("node-fetch");
console.log(typeof fetch.default);
```
When run in node REPL this works fine:

<details>
<summary>Output</summary>

```
$ node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> const fetch = require("node-fetch");
undefined
> console.log(typeof fetch.default)
function
```
</details>

### Expected Behavior
When packaged with rollup it must work the same as in node REPL (it must not crash in our production!)

### Actual Behavior
It outputs `undefined`.
The reason is that the bundle contains the following:
```ts
function getCjsExportFromNamespace (n) {
	return n && n['default'] || n;  // <--- this is the culprit
}

var lib = /*#__PURE__*/Object.freeze({
	__proto__: null,
	'default': fetch,
	Headers: Headers,
	Request: Request,
	Response: Response,
	FetchError: FetchError
});

var fetch = getCjsExportFromNamespace(lib);

console.log(typeof fetch.default);
```

cc @lukastaegert 
related: https://github.com/rust-analyzer/rust-analyzer/issues/5257#issuecomment-655435271

**Comment by lukastaegert** [comment]
Looks like this one should be added to #481

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by Veetaha** [comment]
@shellscape here is the reproduction: https://repl.it/join/vhpbczoh-veetaha
try running
`node ./output/bundle.js` and `node ./input.js` to see the difference
