### ISSUE TITLE
Watching and compiling stops when having an error in Typescript file

### ISSUE THREAD

**Issue by simonvanbennekom** [rollup/plugins#492]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 5.0.1
- Rollup Version: 2.20.0

### How Do We Reproduce?

clone this repo: https://github.com/simonvanbennekom/rollup

```console
npm install
npm run watch
```

```typescript
namespace Account {
    export function onLoad(){
        var number = 1;
        privateFunction(number);
    }

    function privateFunction(input : number) {
        console.log(input)
    }
}

```

Change value of number variable in Account.ts, to "" and Save the file

### Expected Behavior

```console
Terminal should show this kind of message: Argument of type 'string' is not assignable to parameter of type 'number'.
```

### Actual Behavior

```console
rollup v2.20.0
bundles ./Scripts/Account.ts → Scripts...
created Scripts in 1.1s

[2020-07-08 13:33:02] waiting for changes...
rollup v2.20.0
bundles ./Scripts/Account.ts → Scripts...

Terminal will be reused by tasks, press any key to close it.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by simonvanbennekom** [comment]
@shellscape Hi updated the post, added a repository and steps to reproduce. Hope this is enough so you can help me with my issue. Thanks

**Comment by shellscape** [comment]
>   Please - do not - skip or remove parts of this template.

Please add the sections of the issue template that you removed.

**Comment by simonvanbennekom** [comment]
@shellscape sorry, missed that. fixed it now.

**Comment by shellscape** [comment]
You have no `rollup.config.js` file in your reproduction repo. You'll need one and you'll need to configure the `typescript` plugin in order to use TS. Following your instructions I receive:

```
[!] Error: ENOENT: no such file or directory, open '/Users/code/forks/rollup/rollup.config.js'
```

I'm sorry but the issues here are not a forum for support. I searched our issues here and I found #255 and #258 which might be related. I encourage you to check out and discuss on the issues which address the same problem.

**Comment by simonvanbennekom** [comment]
> You have no `rollup.config.js` file in your reproduction repo. You'll need one and you'll need to configure the `typescript` plugin in order to use TS. Following your instructions I receive:
> 
> ```
> [!] Error: ENOENT: no such file or directory, open '/Users/code/forks/rollup/rollup.config.js'
> ```
> 
> I'm sorry but the issues here are not a forum for support. I searched our issues here and I found #255 and #258 which might be related. I encourage you to check out and discuss on the issues which address the same problem.

noEmitOnError fixes the problem. sorry for the inconvenience.

**Comment by shellscape** [comment]
No worries. Glad you found the fix.
