### ISSUE TITLE
eslint-plugin official package

### ISSUE THREAD

**Issue by alexgwolff** [rollup/plugins#494]
Request Checklist:

- [X] I have searched https://npmjs.com/ before opening this issue
- [X] I have searched https://github.com/rollup/awesome before opening this issue

### New Plugin Use Case
Hello, it looks like the [rollup-plugin-eslint]( https://github.com/TrySound/rollup-plugin-eslint)
no longer receives updates. Could this plugin be officially provided?
It is a simple package, but it is important  have "official support"

**Comment by shellscape** [comment]
We would be open to having that in the repo, but you'll have to ask the author for that first :+1:

**Comment by TrySound** [comment]
Feel free to migrate. I will be glad to archive the repo.

**Comment by shellscape** [comment]
Need to keep this one around
