### ISSUE TITLE
At present most plugins do not work when rollup is used programatical in node as esm

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/plugins#498]
- Rollup Plugin Name: 
- Rollup Plugin Version:
- Rollup Version:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
Only one example but we need to tackle that in all plugins

node rollup.build.mjs
```js
import { rollup } from './node_modules/rollup/dist/es/rollup.js'
// This Should work and also this
import resolve from '@rollup/plugin-node-resolve/dist/index.js';
// This Should work and also this
import resolve from '@rollup/plugin-node-resolve/dist/index.es.js';
```

### Actual Behavior
build.mjs
```js
import { rollup } from './node_modules/rollup/dist/es/rollup.js'

// Example importing cjs inside node esm
import resolve from '@rollup/plugin-node-resolve/dist/index.js'; // fails as { DEFAULTS, nodeResolve, default }  gets exported 
// Here resolve === { DEFAULTS, nodeResolve, default }
const { nodeResolve: resolve } = resolveExports

// Example importing es inside node esm
import resolve from '@rollup/plugin-node-resolve/dist/index.es.js'; // fails as the package it self is not marked as module 
```

Solution is to do it like with rollup and create for every plugin a structure like /dist/es/${plugin-name}.js
and a added package.json {"type": "module"}

### reproducer
npm install rollup @rollup/plugin-node-resolve@8.0.0

build.mjs
```js
import { rollup } from './node_modules/rollup/dist/es/rollup.js'

// Example importing cjs inside node esm
import resolve from '@rollup/plugin-node-resolve/dist/index.js'; // fails as { DEFAULTS, nodeResolve, default }  gets exported 
// Here resolve === { DEFAULTS, nodeResolve, default }

// Workaround
import resolve from '@rollup/plugin-node-resolve/dist/index.js'; // fails as { DEFAULTS, nodeResolve, default }  gets exported 
const { nodeResolve: resolve } = resolveExports

// Example importing es inside node esm
import resolve from '@rollup/plugin-node-resolve/dist/index.es.js'; // fails as the package it self is not marked as module 
```

We should think about way to solve that for all plugins like rollup-plugin-string which is from TrySound we need a consistent Plugin Boilerplate maybe.

**Comment by shellscape** [comment]
_(To set a good example for other contribs we should put together a tiny repro repo)_

**Comment by frank-dspeed** [comment]
@shellscape you mean a example plugin boilerplate?

**Comment by shellscape** [comment]
Naw like a small repo that reproduces the problem, to set a good example. When users report issues and we close their issues due to lack of reproduction, we tell them that we hold everyone to that same standard. So I want to make sure we're true to that.

**Comment by frank-dspeed** [comment]
@shellscape the best standard would be to publish only esm and tell them about dynamic import and dynamic import pollyfills like systemjs-node or stealjs or npm package ESM and simply forget about showing and using cjs anywhere as that module system dies.

**Comment by shellscape** [comment]
I'm not sure where communication is breaking down between us here 😄  I'm asking you to take that code blurb from `Actual Behavior` and make that a functional repo that we can execute and see the bad result - a reproduction. e.g. `Link to reproduction` should never be empty for any bug issue opened by anyone.

**Comment by frank-dspeed** [comment]
@shellscape added at the additional info section

**Comment by shellscape** [comment]
I appreciate the effort, but that's not what we ask users to do. I can't stress enough that we have to set a good example for everyone else. please put that reproduction in one of the formats that the bug ticket asks for. I'm not trying to be overly difficult, I'm just holding ourselves to the same standards that we hold users to when they open a new bug issue
