### ISSUE TITLE
Extending tsconfig in a parent folder breaks `es` compilation

### ISSUE THREAD

**Issue by jun-sheaf** [rollup/plugins#499]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 5.0.2
- Rollup Version: 2.21.0
- Operating System (or Browser): Mac OS
- Node Version: 14
- Link to reproduction _(⚠️ read below)_: Not required

### Expected Behavior
Using a tsconfig that has been extended should compile.

### Actual Behavior
Suppose
```json
{
 "extends": "../tsconfig.json"
 ...
}
```
is a tsconfig file extending a monorepo's tsconfig file. Also suppose the format of an output in `rollup.config.js` is `es`. Then you will get
```sh
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths and do not contain invalid characters, received "../tsconfig.tsbuildinfo".
```

### Additional Information
N/A

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.
