### ISSUE TITLE
[plugin-babel] should works with query param in path

### ISSUE THREAD

**Issue by csr632** [rollup/plugins#500]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.1.0
- Rollup Version: 2.21.0
- Operating System (or Browser): latest repl.it
- Node Version: latest repl.it
- Link to reproduction _(⚠️ read below)_: https://repl.it/@csr632/rollup-plugin-repro-1#input.js

### Expected Behavior

The plugin should accept module id with query param in it.

The motivation is similar to [how node-resolve plugin support hash and query](https://github.com/rollup/plugins/pull/487).

### Actual Behavior

[It doesn't recognize `.ts` extension](https://github.com/rollup/plugins/blob/279fc1302baea059da5f4515199acf042fc5fd49/packages/babel/src/index.js#L104) because the module id is `file.ts?query=asd`.

### Additional Information

In my case, when I am doing some special import, I store some infomation in the query, so that my plugin can treat it differently.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by shellscape** [comment]
Seriously, follow the template. Don't modify it.

**Comment by csr632** [comment]
I am very sorry! I have updated the issue.

**Comment by shellscape** [comment]
Thank you

**Comment by Andarist** [comment]
Out of curiosity - why this query is there? What it is used for? I would love to know more about the use case here.

**Comment by lukastaegert** [comment]
I believe it is a rather interesting pattern of passing parameters to plugins that handle imports to allow per-import configuration. The big advantage is that the source code can still be easily run unmodified in a browser as the import is still a valid URL.

**Comment by csr632** [comment]
> Out of curiosity - why this query is there? What it is used for? I would love to know more about the use case here.

`moduleId with query + rollup plugin` enablue us to import thing with special effect.

For example, I have a plugin to do special transform to some modules: 
```
{
   name: 'template-variable-plugin',
   transform(code, id) {
     const varValue = getValueFromQuery(id)
     code.replace('$template_var$', varValue)
  }
}
```
In my app code, I can import thing with this special effect:
```
import value from './my-module.tsx?varValue=123'
```

**Comment by Andarist** [comment]
We could allow this - I assume that we should transform each such request independently, right? Caching based on a filename alone is not sufficient in this case.

@csr632 would you like to work on this one?

**Comment by csr632** [comment]
I will work on it in this weekend.

**Comment by Andarist** [comment]
That's great, can't wait. Please ping me in the PR thread once you do it - I will try to review asap.
