### ISSUE TITLE
[pluginutils] (or any other rollup part) should not depend on "blatantly non ESM" modules

### ISSUE THREAD

**Issue by pkit** [rollup/plugins#503]
- Rollup Plugin Name: pluginutils
- Rollup Plugin Version: HEAD

### Expected Behavior / Situation

Compiles in browser

### Actual Behavior / Situation

Does not compile, because `picomatch` is a cjs-only module with no default export.

```
Error: 'default' is not exported by https://cdn.jsdelivr.net/npm/picomatch@2.2.2/index.js
```

### Modification Proposal

`picomatch` looks abandoned ([typed proposition](https://github.com/micromatch/picomatch/pull/53) hangs for 9 month already), just replicate the functionality within plugin itself.
I can probably create a PR if you want.

**Comment by shellscape** [comment]
Thanks for opening an issue. Unfortunately this is not within a reasonable proposal. Plugins are intended for use at development-time and not at runtime. If you are attempting to use any during runtime in a browser environment, please use a compatible compiler.

**Comment by pkit** [comment]
Use case is codesandbox-like in browser dev env.
Where custom `rollup.config.js` should be able to load and transpile correctly.
Although I think what I really need is just a `commonjs` plugin without the `load()` hook.
Thanks.
