### ISSUE TITLE
The plugin not works with stenciljs

### ISSUE THREAD

**Issue by derldalfor100** [rollup/plugins#504]
- Rollup Plugin Name: The plugin not works with stenciljs
- Rollup Plugin Version: 4.1.0
- Rollup Version: 1.27.14
- Operating System (or Browser): Chrome with Stenciljs version 1.8.5
- Node Version: ---
- Link to reproduction _(⚠️ read below)_: https://derldalfor100.tinytake.com/media/d876f3?filename=1595515275453_TinyTake23-07-2020-05-39-51_637311119953425124.png&sub_type=thumbnail_preview&type=attachment&width=366&height=800

### Expected Behavior
Read the local JSON files by import
### Actual Behavior

Error:  Consider using '--resolveJsonModule' to import module with '.json' extension

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
