### ISSUE TITLE
[TypeScript] How can I disable `outDir` without modifying `tsconfig.json` like previous versions?

### ISSUE THREAD

**Issue by JounQin** [rollup/plugins#505]
- Rollup Plugin Name: 
- Rollup Plugin Version:

### Expected Behavior / Situation

No error.

### Actual Behavior / Situation

```log
Error: @rollup/plugin-typescript: 'dir' must be used when 'outDir' is specified.
```

### Modification Proposal

I tried

```ts
typescript({
  outDir: null
})
```

**Comment by shellscape** [comment]
There isn't near enough information to begin to consider this issue, and you neglected to provide requested info in the template. It also looks like you've tried to report a bug using the modification template, which isn't correct. Please use the correct template and be sure to fill the entire template in.
