### ISSUE TITLE
TypeScript override `module` to ESNext

### ISSUE THREAD

**Issue by aminya** [rollup/plugins#514]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 5.0.2

### Feature Use Case
Bundling without modifying the original tsconfig of the project

### Feature Proposal
@rollup/plugin-typescript should override the `module` compiler option to `ESNext` by default. Usually, people use `module: commonjs` in their tsconfig. But when they want to use Rollup they should pass an extra option to the typescript plugin to make bundling work.
```js
typescript({ module: "ESNext"})
```

I think this only makes an issue when someone uses synchronous lazy `require` in their code for some other purpose (which Rollup does not modify correctly).

Babel plugin issues a warning if babel modifies the `import`s to `require`. But the TypeScript plugin does nothing.

**Comment by shellscape** [comment]
This can be accomplished with a `tsconfig` for bundling which extends a base config and overrides that property. This is a very common practice. See: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends

Given that there's an easy workaround, we'll need a more compelling use case or argument to increase the surface area of the options available and increase complexity of the plugin.

**Comment by aminya** [comment]
I don't think using multiple `tsconfig` is simpler than managing this automatically. For now, I prefer to pass the option directly to the Rollup plugin.

The use case is obvious. Not ding this is a bug. If you don't pass this option, Rollup only uses the entry file as the bundle with a bunch of `reuqire` in it with the wrong path.

For example, the bundle of this (src/index.ts):
```ts
import { ITerminal, IPtyOpenOptions, IPtyForkOptions, IWindowsPtyForkOptions } from './interfaces';

let terminalCtor: any;
if (process.platform === 'win32') {
  terminalCtor = require('./windowsTerminal').WindowsTerminal;
} else {
  terminalCtor = require('./unixTerminal').UnixTerminal;
}

```
becomes:

dist/index.ts
```ts
const { ITerminal, IPtyOpenOptions, IPtyForkOptions, IWindowsPtyForkOptions } = require('./interfaces');

let terminalCtor: any;
if (process.platform === 'win32') {
  terminalCtor = require('./windowsTerminal').WindowsTerminal;
} else {
  terminalCtor = require('./unixTerminal').UnixTerminal;
}
```
[Ref.](https://github.com/oznu/node-pty-prebuilt-multiarch/pull/14)

which is totally incorrect. Because `./interfaces` is in the `src` folder.

This means the typescript plugin does not work in a majority of examples with the default options.

**Comment by shellscape** [comment]
> I don't think using multiple tsconfig is simpler than managing this automatically.

I disagree. That is a serviceable workaround to achieve what you want and satisfy your use case. It is not the job of a package to support every possible configuration for every user, especially so when a good alternative exists - in this case, using functionality built into TypeScript itself.

**Comment by aminya** [comment]
At least you include a warning in the plugin like how the babel plugin does.
https://github.com/rollup/plugins/blob/9ad41a0760b4eeed9fd26d2da9b5122aa8a351e5/packages/babel/src/preflightCheck.js#L7-L14

cc: @lukastaegert
