### ISSUE TITLE
[commonjs] Stray unused require() in output

### ISSUE THREAD

**Issue by ashubham** [rollup/plugins#518]
- Rollup Plugin Name: plugin-commonjs
- Rollup Plugin Version: 14.0.0
- Rollup Version: 2.22.0
- Operating System (or Browser): Chrome / Mac
- Node Version: 12.15.0
- Link to reproduction _(⚠️ read below)_:

https://repl.it/@ashubham/StrayRequiresBug

After running rollup, the `output/index.js` file has stray require statements, the return values of which are never used. Just commenting out these lines makes the code work.

![image](https://user-images.githubusercontent.com/6115911/88853771-12984700-d1a5-11ea-8f8b-a4e2d0abfe82.png)

### Expected Behavior

Output should not contain `require` statements.

### Actual Behavior

Output contains require statements, causing it to fail in the browser.

### Additional Information

This may be an issue with the `monaco-yaml` library. But, its unlikely because these require statements are stray and rollup seems to have already replaced the usages appropriately.

**Comment by lukastaegert** [comment]
It seems like some library is mixing up ES modules with require statements. For me, adding the `transformMixedEsModules: true` option to the commonjs plugin fixed it.

**Comment by ashubham** [comment]
@lukastaegert Thanks for your response, is there a reason why I would not leave that option as default true ? As then it would handle this case out of the box.

**Comment by lukastaegert** [comment]
And break Electron code-bases that need to keep their require statements.

Besides that, mixing ESM and require is a non-existent module format made popular solely by Webpack and hence misunderstood by library authors as "something you do". A library that does this can only ever be used with a bundler. Hence I am feeling reluctant to add this by default. I would rather hope people start pestering library authors to stop doing that.

**Comment by ashubham** [comment]
Thanks for the colour. And, I completely agree with the general sentiment of pushing towards using the platform rather than creating bad abstractions. I have tried to use as much pure ES libraries as possible, but still we have a big team and there are some packages which we just cannot get rid of in the short term.

Do you foresee any issues apart from what you mention above if I use this in my setup ? (I have a web app) Can this cause errors on other pure ESM modules ?

**Comment by lukastaegert** [comment]
Only if they use a global variable named `require`. So I think usually it is safe to turn on. It might incur a performance hit when bundling as now ESM needs to be processed as well as CJS. This could be reduced by using the `include`/`exclude` options.

**Comment by ashubham** [comment]
Cool, thanks!
