### ISSUE TITLE
Internal error: http is not defined (using TypeScript and Svelte)

### ISSUE THREAD

**Issue by hydroper** [rollup/plugins#521]
Using latest packages (@rollup/plugin-typescript and the most relevant Svelte Rollup plugin package), when I run `rollup -c` the build goes fine, but when I execute my Svelte application occurs the following error:

```
ReferenceError: http is not defined
  at main.ts:18
```

(main.ts has no code at line 18 and no "http" name involved.)

When I don't use TypeScript it works, though. Probably this internal error is on the Rollup plugins.

Repository:

https://github.com/recoyx/recoyxSite

Sorry for lack of information as I'm out of my development environment as of writting.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by hydroper** [comment]
Sorry, I was in a phone!

**Comment by asahelk** [comment]
> Using latest packages (@rollup/plugin-typescript and the most relevant Svelte Rollup plugin package), when I run `rollup -c` the build goes fine, but when I execute my Svelte application occurs the following error:
> 
> ```
> ReferenceError: http is not defined
>   at main.ts:18
> ```
> 
> (main.ts has no code at line 18 and no "http" name involved.)
> 
> When I don't use TypeScript it works, though. Probably this internal error is on the Rollup plugins.
> 
> Repository:
> 
> https://github.com/recoyx/recoyxSite
> 
> Sorry for lack of information as I'm out of my development environment as of writting.

Did you solve the error? I'm getting the same issue

**Comment by Klaider** [comment]
@asahelk I don't remember exactly, but basically your NPM dependencies have to be `devDependencies` in package.json, did you check for this?

**Comment by asahelk** [comment]
@Klaider I already checked but my problem was on rollup.config. I didn't know that typescript plugin must be after resolve. Thanks anyway.

**Comment by KevinTaleb** [comment]
@asahelk , Im running into the same error and doesn't know how to fix it, any help?
My `rollup.config.js` : 

```
import svelte from 'rollup-plugin-svelte';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import sveltePreprocess from 'svelte-preprocess';
import typescript from '@rollup/plugin-typescript';
import css from 'rollup-plugin-css-only';

const production = !process.env.ROLLUP_WATCH;

function serve() {
	let server;

	function toExit() {
		if (server) server.kill(0);
	}

	return {
		writeBundle() {
			if (server) return;
			server = require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
				stdio: ['ignore', 'inherit', 'inherit'],
				shell: true
			});

			process.on('SIGTERM', toExit);
			process.on('exit', toExit);
		}
	};
}

export default {
	input: 'src/main.ts',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		svelte({
			preprocess: sveltePreprocess({ sourceMap: !production }),
			compilerOptions: {
				// enable run-time checks when not in production
				dev: !production
			}
		}),
		// we'll extract any component CSS out into
		// a separate file - better for performance
		css({ output: 'bundle.css' }),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration -
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
		commonjs(),
		typescript({
			sourceMap: !production,
			inlineSources: !production
		}),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};

```

**Comment by denis-rossati** [comment]
Same problema here. It only happens when I'm using axios with typescript

My rollup version: 2.70.1
Axios version: 0.26.1
TS version: 4.6.3

My build is like

```
(function (http, https, stream, tty, os, zlib) {
    'use strict';
     // bunch of code
})(http, https, stream, tty, os, zlib);
//# sourceMappingURL=custom.js.map
```

I mean, how it cannot find the http package? Someone already made an workaround on this?
