### ISSUE TITLE
Internal error: http is not defined

### ISSUE THREAD

**Issue by hydroper** [rollup/plugins#522]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 5.0.2
- Rollup Version: 2.23.0
- Operating System (or Browser): Windows 10, Opera
- Node Version: 14+
- Link to reproduction: https://github.com/recoyx/recoyxSite (client folder)

### Expected Behavior

No console error.

### Actual Behavior

I get a ReferenceError when executing my application entry point:

```
ReferenceError: http is not defined
  at main.ts:18
```

### Additional Information

- [main.ts:18](https://github.com/recoyx/recoyxSite/blob/master/client/src/main.ts#L18) has no code and there is no "http" name involved.
- When I don't use TypeScript the expected behavior is accomplished.

**Comment by shellscape** [comment]
Sorry, but that is not a _minimal reproduction_ as requested in the issue template. 

>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).

**Comment by hydroper** [comment]
The code is little, but now I did remove `import axios from 'axios'` (I did not even use axios, just imported reaply) from my phone and it did expected behavior.

**Comment by shellscape** [comment]
Please read the link provided above. Maintainers do not have time to triage an app. We need a minimal reproduction.

**Comment by hydroper** [comment]
Okay, once I get in the laptop I'll edit this.
