### ISSUE TITLE
typescript plugin generates duplicate code when one entry point import another entry point on windows

### ISSUE THREAD

**Issue by EqualMa** [rollup/plugins#526]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 5.0.2
- Rollup Version: 2.23.0
- Operating System (or Browser): Windows 10 (1909)
- Node Version: 12.18.3
- Link to reproduction _(⚠️ read below)_: https://github.com/EqualMa/rollup-typescript-duplicate-repro

### Expected Behavior
input: 

```typescript
// entry point a.ts
export function hello() {
  return "hello";
}

// entry point b.ts
import { hello } from "./a";

export function sayHello() {
  console.log(hello());
}
```

output:

```javascript
// a.js
function hello() {
  return "hello";
}
exports.hello = hello;

// b.js
const a_1 = require("./a");
function sayHello() {
  console.log(a_1.hello());
}
exports.sayHello = sayHello;
```

### Actual Behavior

output:

```javascript
// a.js
Object.defineProperty(exports, '__esModule', { value: true });

function hello() {
    return "hello";
}

exports.hello = hello;


// b.js
Object.defineProperty(exports, '__esModule', { value: true });

function hello() {
    return "hello";
}

function sayHello() {
    console.log(hello());
}

exports.sayHello = sayHello;
```

### Additional Information

Note that this issue **seems to only occur on Windows**, so I use an git repo url as repro link rather than repl.it

**Comment by YevhenKap** [comment]
Same occurs for me too.

- Rollup Plugin Name: typescript
- Rollup Plugin Version: 6.0.0
- Rollup Version: 2.29.0
- Operating System (or Browser): MacOS 10.15.7
- Node Version: 14.12.0

I have one class that is imported in many files. TypeScript duplicates this class in output bundle :(
