### ISSUE TITLE
Bad CJS Transformation after 14.0 upgrade

### ISSUE THREAD

**Issue by ashubham** [rollup/plugins#527]
- Rollup Plugin Name: Commonjs
- Rollup Plugin Version: 14.0.0
- Rollup Version: 2.26
- Operating System (or Browser): OSX / Chrome
- Node Version: 12.16
- Link to reproduction _(⚠️ read below)_:

https://repl.it/@ashubham/BadCJSTransformation

Find two files in the `output` directory of the above repl. 

`index.js` for the latest output
`index@13.0.0.js` for the 13.0.0 output.

Basically look at the `useSSR` module transformation, in 13.0.0 it worked becuase we did an `unwrapExports` which seems to be missing in 14.0.0

### Expected Behavior

in the 13.0.0 version the transformation looked like:

![image](https://user-images.githubusercontent.com/6115911/89231249-cc265c00-d599-11ea-91b0-4135ed57dff8.png)

![image](https://user-images.githubusercontent.com/6115911/89231267-d5afc400-d599-11ea-943c-4fffa2c88257.png)

### Actual Behavior

There is no longer an `unwrapExport` causing the browser to fail to load the module with `useSSR is not a function`. 

![image](https://user-images.githubusercontent.com/6115911/89231161-9ed9ae00-d599-11ea-8d70-85daa046dcf2.png)

**Comment by lukastaegert** [comment]
This is already fixed in master awaiting the next release.

**Comment by shellscape** [comment]
@ashubham please confirm that this has been resolved in the latest version.
