### ISSUE TITLE
Fail on 'npm install' - '@rollup/pluginutils@^3.0.8' is not in the npm registry

### ISSUE THREAD

**Issue by MagedMYoussef** [rollup/plugins#531]
- Rollup Plugin Name: @rollup/pluginutils
- Rollup Plugin Version: All
- Rollup Version:
- Operating System (or Browser): Windows
- Node Version: 8 & 10
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
This package was working correctly, but suddenly I got this error. I think something is wrong with the npm registry.

### Actual Behavior

![image](https://user-images.githubusercontent.com/12249157/89519271-6249c480-d7dc-11ea-8bc9-609f535f5e3c.png)

**Comment by Ashot-KR** [comment]
see https://github.com/rollup/plugins/issues/530#issuecomment-669843222

**Comment by anandtripathi5** [comment]
Suddenly failing for me as well

**Comment by Ashot-KR** [comment]
there is problem with npm – https://status.npmjs.org/
