### ISSUE TITLE
Accept .geojson in @rollup/plugin-json

### ISSUE THREAD

**Issue by Havegum** [rollup/plugins#538]
- Rollup Plugin Name: @rollup/plugin-json 
- Rollup Plugin Version: 4.1.0

### Feature Use Case
Geojson-files are json-files but typically use the .geojson-extention. It would be nice if @rollup/plugin-json could work with these without renaming them.

### Feature Proposal
Accept the geojson-extention for json-parsing.

I believe the following changes [here](https://github.com/rollup/plugins/blob/master/packages/json/src/index.js) should do it:
```diff
---if (id.slice(-5) !== '.json' || !filter(id)) return null;
+++if (!id.split('.').pop().match(/^(geo)?json$/i) || !filter(id)) return null;
```

**Comment by shellscape** [comment]
Thanks for opening an issue and for your suggestion. While we'd love to support every use case for every user, it's just not feasible with the limited resources we have. If we adopt this extension, then we'd officially have to support not only the extension, but the file format and any changes that the format may undergo in the future.

Instead, I'd suggest creating a simple one-file plugin for use in your config to support that file format and extension. (The source for the json plugin is so small, you could event keep it within your rollup config if you wanted to)

**Comment by n370** [comment]
@Havegum I have followed @shellscape suggestion and created a new package (https://github.com/n370/rollup-plugin-geojson) based on `@rollup/plugin-json@4.1.0`. You can use it now if you want.

**Comment by shellscape** [comment]
@n370 please do add that to rollup/awesome

**Comment by shellscape** [comment]
Thanks, could you open a formal PR off of your fork for tracking?

**Comment by n370** [comment]
Damn it! my bad, I forgot to open the PR. Here it is https://github.com/rollup/awesome/pull/86.

**Comment by mryellow** [comment]
> If we adopt this extension, then we'd officially have to support not only the extension, but the file format and any changes that the format may undergo in the future.

Nonsense. It's like any JSON file and will remain like any JSON file going forward.

**Comment by mryellow** [comment]
> I ended up creating a plugin to address this discussion a while ago https://github.com/n370/rollup-plugin-geojson.

Problem is things like Vite just use the JSON plugin and expect it to work with any type of JSON file.
