### ISSUE TITLE
rollup doesn't fully process modules when using dynamicRequireTargets

### ISSUE THREAD

**Issue by perrin4869** [rollup/plugins#545]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 15.0.0
- Rollup Version: 2.26.2
- Operating System (or Browser): slackware64-current
- Node Version: 14.4
- Link to reproduction _(⚠️ read below)_: https://github.com/perrin4869/rollup-readable-stream

### Expected Behavior
The repo with the reproduction above should produce an executable `index.out.js` when bundling in `readable-stream`, which has circular dependencies. This can be accomplished by using the `dynamicRequireTargets` option.

### Actual Behavior
It fails to run with the following error thrown:

```bash
❯ node index.out.js
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module './lib/_stream_readable.js'
Require stack:
- /home/perrin4869/univapaycast/rollup-readable-stream/index.out.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at commonjsRequire (/home/perrin4869/univapaycast/rollup-readable-stream/index.out.js:148:9)
    at /home/perrin4869/univapaycast/rollup-readable-stream/index.out.js:159:30
    at createCommonjsModule (/home/perrin4869/univapaycast/rollup-readable-stream/index.out.js:18:5)
    at Object.<anonymous> (/home/perrin4869/univapaycast/rollup-readable-stream/index.out.js:153:16)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/perrin4869/univapaycast/rollup-readable-stream/index.out.js'
  ]
}
```

### Additional Information
@danielgindi originally implemented the featured confirmed that it should work as expected in the issue below:
https://github.com/nodejs/readable-stream/issues/348

**Comment by danielgindi** [comment]
@perrin4869 I apologize but I missed some misconfigurations in your repo!

First, you declared `include: /node_modules/` for commonjs, which means you don't let it to continue transpiling the main file after it gets some commonjs stuff injected to it.
Second, you need to add `transformMixedEsModules: true`, as your main file is going to be a mix of ES imports, and commonjs stuff coming in from the `readable-stream` module and from the commonjs helpers.

I tested with removing the `include` (or extending it) and adding `transformMixedEsModules` - and your repo works fine.

@lukastaegert I think it makes sense to automatically continue tranforming any file that gets commonjs helpers injected into it right?

**Comment by perrin4869** [comment]
Yeah, turning those options on automatically when using `dynamicRequireTargets` sounds like a good idea to me!
Otherwise we need to add a note in the `README` :)
