### ISSUE TITLE
[inject] README is missing on npmjs.com

### ISSUE THREAD

**Issue by eight04** [rollup/plugins#546]
- Rollup Plugin Name:  inject
- Rollup Plugin Version: 4.0.2
- Rollup Version:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_:

https://www.npmjs.com/package/@rollup/plugin-inject
It says `"Unable to find a readme for @rollup/plugin-inject@4.0.2"`

Not sure if this is an npm issue.

**Comment by shellscape** [comment]
>   🚨 Your issue will be CLOSED if:
>     - This template is removed
>     - Parts of this template are removed

As stated at the very top of our issue template, your issue is being closed because you removed parts of our issue template.
