### ISSUE TITLE
[pluginutils] attachScopes ignores variables declared in for-of statement

### ISSUE THREAD

**Issue by eight04** [rollup/plugins#547]
- Rollup Plugin Name: pluginutils
- Rollup Plugin Version: 4.0.0
- Rollup Version:
- Operating System (or Browser): Windows 10 x64
- Node Version: v13.8.0
- Link to reproduction _(⚠️ read below)_: https://repl.it/repls/BasicMidnightblueAmoebas#index.js

### Expected Behavior

The local scope should contain variable `a`.

### Actual Behavior

The local scope doesn't contain variable `a`.

### Additional Information

It has been reported once but the issue is closed:
https://github.com/rollup/plugins/issues/113

**Comment by shellscape** [comment]
Pull requests to resolve this issue are welcome. This is unlikely to get a fix without community contribution.

**Comment by eight04** [comment]
I took a look at the [test file](https://github.com/rollup/plugins/blob/55a9cb20d7686750aa104d6a45a7d6834f57ba4a/packages/pluginutils/test/attachScopes.ts#L6), it seems that the ast is hand-crafted. Do I have to find some ways to build them manually? or can we generate the AST by parsing readable source code?

**Comment by lukastaegert** [comment]
My guess is that they were created by pasting some code here: https://astexplorer.net/ Alternatively of course you could just run acorn in your test.

**Comment by eight04** [comment]
Can we merge #551 first? I will start working on for-loop issues after that.

**Comment by eight04** [comment]
Relate: #548, #549
