### ISSUE TITLE
[pluginutils] attachScopes leaks for-loop variables defined with const/let to outer scope

### ISSUE THREAD

**Issue by eight04** [rollup/plugins#548]
- Rollup Plugin Name:  pluginutils
- Rollup Plugin Version: 4.0.0
- Rollup Version:
- Operating System (or Browser): Windows 10
- Node Version: 13.8.0
- Link to reproduction _(⚠️ read below)_:  
  * ForStatement: https://repl.it/repls/StaidAvariciousFactor
  * ForInStatement: https://repl.it/repls/ElatedWelllitCharacters

### Expected Behavior

The outer scope shouldn't contain variable `a` thus it should print

```
false
true
```

### Actual Behavior

```
true
true
```

### Additional Information

It has been reported once but the issue is closed:
#113

**Comment by shellscape** [comment]
Thanks for opening an issue. Pull requests to resolve this issue are welcome. This is unlikely to get a fix without community contribution.
