### ISSUE TITLE
[pluginutils] attachScopes should add scope object to ForStatement.test and ForStatement.update

### ISSUE THREAD

**Issue by eight04** [rollup/plugins#549]
- Rollup Plugin Name: pluginutils
- Rollup Plugin Version: 4.0.0
- Rollup Version:
- Operating System (or Browser): Windows 10
- Node Version: 13.8.0
- Link to reproduction _(⚠️ read below)_: https://repl.it/repls/WeightyUnnaturalBoolean

### Expected Behavior

With the following code, 
```js
for (let a = 0; a < 10; a++) {
  console.log(a);
  let b = 10;
}
```
There are two different scopes. ForStatement.body (i.e. BlockStatement) can access variable `a` and variable `b`. However, ForStatement.test and ForStatement.update (i.e. BinaryExpression and UpdateExpression) can only access variable `a`.

### Actual Behavior

`attachScopes` only attaches scope object to BlockStatement

**Comment by shellscape** [comment]
Thanks for opening an issue. Pull requests to resolve this issue are welcome. This is unlikely to get a fix without community contribution.
