### ISSUE TITLE
Building @babel/standalone fails on commonjs@15

### ISSUE THREAD

**Issue by JLHwung** [rollup/plugins#557]
- Rollup Plugin Name: commonjs@15.0.0, babel@5.2.0
- Rollup Version: 2.26.5
- Operating System (or Browser): macOS
- Node Version: 14.8.0
- Link to reproduction _(⚠️ read below)_: https://github.com/JLHwung/babel/compare/rollup-2-plugin-commonjs-15

Rollup Config: https://github.com/JLHwung/babel/blob/95dc47882afbe98064f90420108f69b35b070f4a/Gulpfile.js#L123-L164

```
make bootstrap
```

### Expected Behavior
Build all babel artifacts.

### Actual Behavior
throws
```
Error: 'default' is not exported by rollupPluginBabelHelpers.js, imported by node_modules/chalk/templates.js
```
See https://github.com/JLHwung/babel/runs/1033102860#step:6:573 for the error logs.

### Additional Information

I believe it is an integration issue between `@rollup/plugin-babel` and `@rollup/plugin-commonjs`: The `plugin-babel` [serves](https://github.com/rollup/plugins/blob/c5227447e1038e7b06583a202013e43c7aeccb73/packages/babel/src/index.js#L144-L149) a virtual file `rollupPluginBabelHelpers.js` via the `load` hook. It is am ESM moudle generated from `@babel/core`. So I guess what happens here is the babel helper is added to the `chalk/templates` (because of for-of helpers) but for some reason transformed as `require` when Rollup is processing. On reading https://github.com/rollup/plugins/tree/master/packages/commonjs#esmexternals, it seems that I should specify `esmExternals`, so I tried add to `commonjs` the following options.
```
esmExternals: ["\0rollupPluginBabelHelpers", "rollupPluginBabelHelpers"]
```

But the build still fails. Even in the end `esmExternals` works for this virtual file, it feel like a hack and I hope it can be processed by `@rollup/plugin-babel`. 

Another issue may be related: I tried downgraded `commonjs@14` but our standalone test fails: https://github.com/babel/babel/runs/1033085554#step:10:128 I haven't investigate yet.

As a workaround we are pinning `commonjs` to 13: https://github.com/babel/babel/pull/12010

**Comment by lukastaegert** [comment]
Would it be possible to boil this problem down to have a reproduction that only contains few files and as few plugins as possible and directly calls Rollup? `esmExternals` sounds like it does not apply here anyway because it only applies to files that are NOT bundled? Fiddling with `requireReturnsDefault` sounds like more of an option, but it is `false` by default meaning it should not cause issues here.

**Comment by JLHwung** [comment]
@lukastaegert Sorry for the late reply. Here is a reproduction repo: https://github.com/JLHwung/rollup-plugin-issue-557

It bails when a babel option `sourceType: "unambiguous"` is configured. So it involves how Babel play with `@rollup/plugin-babel`. I will see if there is any I can do on Babel side.

**Comment by lukastaegert** [comment]
Did you try version 15.1.0 of the commonjs plugin?

**Comment by JLHwung** [comment]
@lukastaegert The reproduction repo uses 15.1.0.
