### ISSUE TITLE
Im looking a way for get output in chunks, no in a full file.

### ISSUE THREAD

**Issue by kasec** [rollup/plugins#558]
Hey there! currently new with rollup, im playing with plugins right now, but i did not understand at all.
Im looking a way that my entry files can sort and not be in a full file.
I hope someone can help me and my message be understandable.
something like this: but with many [entries] (https://rollupjs.org/guide/en/#input).
```js
// rollup.config.js
export default {
  ...,
  input: {
    a: 'src/main-a.js',
    'b/index': 'src/main-b.js'
  },
  output: {
    ...,
    entryFileNames: 'entry-[name].js'
  }
};
```

**Comment by shellscape** [comment]
Hey there. As our issue templates try to convey, we don't offer support here. Please try one of the support options listed in the issue templates

**Comment by kasec** [comment]
I got it.
