### ISSUE TITLE
Unable to use `plugin-node-resolve` on Node@13.3.0

### ISSUE THREAD

**Issue by shikaan** [rollup/plugins#559]
- Rollup Plugin Name: `@rollup/plugin-node-resolve`
- Rollup Plugin Version: `v9.0.0`
- Rollup Version: `2.26.6`
- Operating System (or Browser): Mac OSX 10.15.6
- Node Version: `v13.3.0`
- Link to reproduction: _Sorry about this, but I wasn't able to pick the specific problematic Node version on REPL.it_

### Expected Behavior

Upon running `npx rollup -c --compat` and using `plugin-node-resolve` I should be able to bundle my package on Node `v13.3.0`

### Actual Behavior

Upon running `npx rollup -c --compat` and using `plugin-node-resolve` yields 
```
[!] Error: No valid exports main found for '[REDACTED]/node_modules/@rollup/plugin-node-resolve'
```

### Additional Information

1. The problem is not happening on latest `13.x.x` versions, only on that specific one (my current guess is that it's related to conditional exports for the package)

2. This is the configuration, just in case

```js
const { nodeResolve } = require('@rollup/plugin-node-resolve')
const commonjs = require('@rollup/plugin-commonjs')
const typescript = require('@rollup/plugin-typescript')
const { terser } = require('rollup-plugin-terser')

const pkg = require('./package.json')

module.exports = {
  input: './lib/index.ts',
  output: {
    file: pkg.main,
    format: 'umd',
    name: 'package'
  },
  plugins: [
    typescript(),
    nodeResolve(),
    commonjs({ extensions: ['.ts', '.js'] }),
    terser({
      format: {
        comments: false,
        ecma: 5
      }
    })
  ]
}
```

**Comment by TrySound** [comment]
Node 13.3 has a bug with native es modules. It's end of life and will not get any security updates. You should use node 10, 12 or 14.

**Comment by shikaan** [comment]
I guess we can close this, then :) Hopefully someone wondering in the internet will find it useful
