### ISSUE TITLE
Plugin is not transforming virtual modules

### ISSUE THREAD

**Issue by Tundon** [rollup/plugins#567]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: ^5.0.2

### Expected Behavior / Situation

Take an example config as followed, (also available in this reproducible link: https://repl.it/repls/FocusedAptOutsourcing#rollup.config.js):

```javascript
import typescript from '@rollup/plugin-typescript';
import resolve from '@rollup/plugin-node-resolve';

export default [
  // this physically present typescript file works fine, as expected
  {
    input: "src/main.ts",
    plugins: [
      resolve(),
      typescript()
    ]
  },

  // this virtually loaded file doesn't work
  {
    input: "src/virtual.ts",
    plugins: [
      {
        resolveId(source) {
          if (source == "src/virtual.ts") return source;

          return null;
        },
        load(id) {
          if (id == "src/virtual.ts") return virtualContent;

          return null;
        }
      },
      resolve(),
      typescript()
    ]
  },
]

var virtualContent = `
interface IType {
  name: string;
}

export function hello(t: IType) {
  console.log(t.name);
}
`
```
I would assume since the custom plugin loaded the module, the typescript plugin would just transform the module without any problem.
### Actual Behavior / Situation
The second config would have an error
`[!] Error: The keyword 'interface' is reserved (Note that you need plugins to import files that are not JavaScript)`

### Modification Proposal
I believe this is because the typescript plugin is using `load` hook to transform the module (which I am a bit confused the reasoning).

Maybe I missed something behind, but I do think the `transform` hook is a better place for compiling typescript modules.

**Comment by Tundon** [comment]
A little digging, I found this https://github.com/rollup/plugins/pull/217, that explains some of the reason why the plugin is not using `transform` hook.

**Comment by shellscape** [comment]
@NotWoods may be able to elaborate on this a bit more

**Comment by NotWoods** [comment]
We're currently using the `BuilderProgram` API because its meant for tools like Rollup to compile Typescript code and get the results, including type definitions. I'm exploring other systems because there are other bugs introduced by the load hook, but I want to keep type definition generation.

**Comment by Tundon** [comment]
@NotWoods The `BuilderProgram` choice does make sense. I'll close this for now, but feel free to reopen this as a tracking method if needed.

**Comment by Nojus0** [comment]
Wasted 4 hours looking through the plugin development docs to see what I was doing wrong, at the end, I just needed to switch to `rollup-plugin-typescript2` plugin.

**Comment by fallaciousreasoning** [comment]
Did you ever find a workaround for this @Tundon?

**Comment by Tundon** [comment]
No, I stayed away from virtual, and actually create a tmp file with dynamically populated content.
