### ISSUE TITLE
bundle the generated d.ts files to one declaration file

### ISSUE THREAD

**Issue by imjeen** [rollup/plugins#568]
- Rollup Plugin Name:  @rollup/plugin-typescript
- Rollup Plugin Version: 5.0.2

### Feature Use Case

Writing a library with typescript and building by rollup. Below is my basic config to generate the d.ts files. And How to bundle the declaration files to a file? 

```javascript
import typescript from '@rollup/plugin-typescript';
import resolve from '@rollup/plugin-node-resolve';

export default [
  {
    input: 'src/index.ts',
    output: {
      dir: './',
      entryFileNames: 'lib/index.js',
      format: 'cjs',
    },
    plugins: [
      typescript({
        declaration: true,
        declarationDir: 'lib/types/',
        rootDir: 'src/'
      }),
      resolve(),
     // ... others
    ]
  },
]
```

By the way：how to resolve path alias in declaration files (d.ts)  when not bundle them.

### Feature Proposal

it would be popular that there is an option to bundle the declaration files?

**Comment by arodic** [comment]
It would also be useful to be able to generate declaration file when compiling typescript source into one file. Right now this cannot work:
```
export default {
  input: 'input.ts',
  output: {
    file: 'output.js',
    format: 'es'
  },
  plugins: [typescript({
    declaration: true
  })]
};
```

You get following error:

```
You are using one of Typescript's compiler options 'declaration', 'declarationMap' or 'composite'. In this case 'outDir' or 'declarationDir' must be specified to generate declaration files.
```

But if you use 'outDir' or 'declarationDir', you cannot use `file`!

**Comment by shellscape** [comment]
Given the age of the issue and the lack of interest, we''re going to close this one. If anyone happens across this and would like to work on a Pull Request to satisfy it, we'll be happy to reopen and mark in progress. There is also this third party plugin https://github.com/Swatinem/rollup-plugin-dts which appears to satisfy the immediate need.
