### ISSUE TITLE
plugin-typescript can not compile customized file name 

### ISSUE THREAD

**Issue by NewFuture** [rollup/plugins#571]
- Rollup Plugin Name:  @rollup/plugin-typescript
- Rollup Plugin Version: >=3.0.0
- Rollup Version: 2.26.11
- Operating System (or Browser): any
- Node Version:  node12
- Link to reproduction _(⚠️ read below)_:

Can not compile files which not end with `.ts `

For example there a file named  `comm.wxts`. (just a typescript file with customized extension name)
It will show errors
```
Could not find source file: /wxs/comm.wxts'.
```

But it works in v2.1.0

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
