### ISSUE TITLE
If the entry module is commonjs, the output won't have named export

### ISSUE THREAD

**Issue by csr632** [rollup/plugins#572]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 15.0.0
- Rollup Version: 2.26.11
- Operating System (or Browser): Chrome
- Node Version: 12.16.2
- Link to reproduction _(⚠️ read below)_: https://repl.it/@csr632/rollup-repro#dist/react.js

### Expected Behavior
**I am trying to build react into esm. So that I can use it in browser's native esm envirenment.**

I expect the output to have named export:
```
// dist/react.js
// ...
export { Component, useState, useEffect };
```

### Actual Behavior

The output only have a default export:
```
// dist/react.js
// ...
const React = { Component, useState, useEffect };
export default React;
```

I can no longer do `import { useState } from '/output/dist/react.js';` in browser. It will give error `the module does not provide an export named 'useState'`.

### Additional Information

How can [jspm.dev](https://jspm.dev/react) build react into esm with named export? Isn't it using rollup too? @guybedford  Could you share how you do it?

**Comment by csr632** [comment]
As guybedford [replied in discord](https://discord.com/channels/570400367884501026/570400367884501032/754458375370178671), the named exports extraction done by [cjs-module-lexer](https://github.com/guybedford/cjs-module-lexer)

**Comment by shellscape** [comment]
fwiw that discord link doesn't work for me

**Comment by csr632** [comment]
> fwiw that discord link doesn't work for me

jspm discord invite link: https://discord.gg/dNRweUu

**Comment by csr632** [comment]
[I have created a rollup plugin to fix this](https://github.com/vitejs/vite/pull/825#issuecomment-695201499). In the options hook I replace cjs entry with a proxy entry module which re-export all named export from the original cjs entry.

@lukastaegert Do you think this fix can be done in the `@rollup/plugin-commonjs`?

**Comment by JayaKrishnaNamburu** [comment]
Is this is something related --> https://github.com/pikapkg/snowpack/blob/4c66f9a12ea13ec59c3c59e2383464da510fa12b/esinstall/src/rollup-plugins/rollup-plugin-wrap-install-targets.ts#L23 Like how snowpack wraps the module with all the sub-modules that can be installed.
