### ISSUE TITLE
Rollup plugin URL should utilise `assetFileNames` as the hashed file name

### ISSUE THREAD

**Issue by adamzerella** [rollup/plugins#573]
- Rollup Plugin Name: `url`
- Rollup Plugin Version: `latest`

### Expected Behavior / Situation
I would expect that when emitting an asset, the hashed filename would be the same as what the Rollup API defines i.e `assetFileNames` https://rollupjs.org/guide/en/#outputassetfilenames

### Actual Behavior / Situation
This plugin creates a fixed **sha1** 16 character long hash when emitting asset file names e.g https://github.com/rollup/plugins/blob/6cd15b94cb88943d8e9bc62b7c5d71ac1fb8a457/packages/url/src/index.js#L37

### Modification Proposal
If `assetFileNames` is defined within the Rollup config, the resulting file name hash should be aligned to it.

**Comment by DrSensor** [comment]
@probot reopen
till end of December
