### ISSUE TITLE
WASM: eval prevents dead code elimination

### ISSUE THREAD

**Issue by arvigeus** [rollup/plugins#574]
- Rollup Plugin Name: WASM
- Rollup Plugin Version: 5.1.0

### Expected Behavior / Situation

If no wasm code is used then the code generated from this plugin should be removed by `terser`

### Actual Behavior / Situation

Terser is unable to remove `_loadWasmModule` due to having `eval` in it

### Modification Proposal

https://github.com/rollup/plugins/blob/master/packages/wasm/src/index.ts#L66
Don't use eval here. Terser cannot remove the function: [source](https://github.com/terser/terser/issues/497#issuecomment-544469100)

**Comment by shellscape** [comment]
Happy to review a PR to resolve this. I'd recommend using `Function` if possible

**Comment by arvigeus** [comment]
Why the requires have to be in eval anyway?

I think the solution should be something like:

```js
var fs = (new Function( 'return require("fs")' )())
var path = (new Function( 'return require("path")' )())
```

I hope the tests will tell me if I am wrong.

**Comment by arvigeus** [comment]
Did not work. Tests failed. I don't understand the code enough to know how to fix it.

**Comment by arvigeus** [comment]
I would do it, but I need help
