### ISSUE TITLE
@rollup/plugin-typescript: Rollup 'sourcemap' option must be set to generate source maps

### ISSUE THREAD

**Issue by abdonrd** [rollup/plugins#576]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: v6.0.0
- Rollup Version: v2.26.11
- Operating System (or Browser): macOS
- Node Version: v12
- Link to reproduction: https://github.com/IBM/pwa-lit-template/pull/138#issuecomment-692770438

### Actual and Expected Behavior

When I run [the `tsc` command](https://github.com/IBM/pwa-lit-template/pull/138/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R24), my project compiles without any problem.

But when I use the `@rollup/plugin-typescript` I have this error:

>(!) Plugin typescript: @rollup/plugin-typescript: Rollup 'sourcemap' option must be set to generate source maps.
>[!] (plugin typescript) Error: @rollup/plugin-typescript: 'outDir' or 'declarationDir' must be specified to generate declaration files.
>Error: @rollup/plugin-typescript: 'outDir' or 'declarationDir' must be specified to generate declaration files.

My expectation is that it works the same way.

### Additional Information

Why I need to add properties if it works with the `tsc`?

Thanks in advance!

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by shellscape** [comment]
Also, please search before opening issues. This is a duplicate of another https://github.com/rollup/plugins/issues/216#issuecomment-588511407
