### ISSUE TITLE
TypeError: [PATH] is not a function

### ISSUE THREAD

**Issue by BryceMehring** [rollup/plugins#577]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 15.0.0
- Rollup Version: 2.26.11
- Operating System (or Browser): Browser
- Node Version: v12.18.3
- Link to reproduction _(⚠️ read below)_: https://repl.it/repls/CluelessAwfulRatio#.replit

### Expected Behavior

No error should be thrown when importing the CJS vue component.

### Actual Behavior

The following error is thrown when importing the CJS vue component:
```
TypeError: external_commonjs_vue_commonjs2_vue_root_Vue_default.a.extend is not a function
```

`external_commonjs_vue_commonjs2_vue_root_Vue_default.a.extend` doesn't exist. 

`external_commonjs_vue_commonjs2_vue_root_Vue_default.a.default.extend` does exist

### Additional Information

I built the `cjs_module.js` using the vue cli where vue is externalized from the CJS module

**Comment by BryceMehring** [comment]
Digging into this a bit more it looks like the option `requireReturnsDefault` and setting it to `auto` does what I need to fix this issue from occuring.

**Comment by shellscape** [comment]
Thanks for digging. Closing as resolved.
