### ISSUE TITLE
From 5.1.0: TypeError: Cannot read property '__esModule' of undefined

### ISSUE THREAD

**Issue by frederikhors** [rollup/plugins#583]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 5.1.0
- Rollup Version: 2.28.1
- Operating System (or Browser): Windows 10, Chrome 85
- Node Version: 12.18.4

### Expected Behavior

Using https://github.com/rixo/rollup-plugin-svelte-hot I'm trying to import `gql` like this:

`import gql from 'graphql-tag'`.

It works great with default `sveltejs/template` rollup flow, but here I have this error:

`TypeError: Cannot read property '__esModule' of undefined`.

If I remove that line it works.

If I revert back to 5.0.0 everything works fine.

---

Related: https://github.com/rixo/rollup-plugin-svelte-hot/issues/9

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by frederikhors** [comment]
Oh! This is ridiculous.

**Comment by shellscape** [comment]
I agree.

**Comment by frederikhors** [comment]
Here we are: https://github.com/frederikhors/svelte-template-hot.

Steps:

1. `npm install` in root
1. `npm run dev:rollup` in root

Can you re-open now?

Thanks.

**Comment by shellscape** [comment]
Unfortunately that's not a minimal repo. Please read the provided instructions as mentioned in the template, here: https://git.io/fNzHA. We don't have the resources to triage an entire app for users, which is what you provided. You'll have to narrow the issue, or take the larger issue to the folks who maintain that svelte template.

**Comment by frederikhors** [comment]
It's a small repo. 30 seconds to reproduce the issue with a small edit from `5.1.0` to `5.0.0`.

**Comment by frederikhors** [comment]
I''m perfectly here: https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff#how-to-create-a-minimal-reproduction with my reproduction anyway.

**Comment by rixo** [comment]
The folks who maintain that Svelte template here! :wave: 

Sure, the repro was not good for you. The Rollup config is hacked at runtime by the HMR plugin hu hu... But to me, it makes sense, and it's minimal indeed.

I've narrowed the issue down to SystemJS + preserveModules + @rollup/plugin-commonjs@15.1.

~~~js
import commonjs from '@rollup/plugin-commonjs'
import resolve from '@rollup/plugin-node-resolve'

export default {
  input: 'source.js',
  output: {
    format: 'system',
    preserveModules: true,
    dir: 'output'
  },
  plugins: [
    resolve({ browser: true }),
    commonjs(),
  ]
}
~~~

I've made a minimal repro from Rollup's perspective: https://github.com/rixo/repro-rollup-commonjs-system

Sorry, couldn't make sense of REPL.it... or I experienced technical issues... can't really tell! :sweat_smile:

**Comment by shellscape** [comment]
Thanks @rixo, that'll help out the folks who maintain the commonjs plugin.

**Comment by lukastaegert** [comment]
Thanks for the repro, this is definitely a weird error. For starters, it only appears to happen with `preserveModules: true`. Moreover, it does not seem to appear when choosing format "es", it seems to be very specific to SystemJS. This will require further digging.

**Comment by lukastaegert** [comment]
Ok, this is in fact a bug in Rollup core! It is here in the code for the commonjs proxy for the parser:

```js
System.register(['../node_modules/graphql/language/parser.mjs.js', './_commonjsHelpers.js'], function (exports) {
	'use strict';
	var parser, getAugmentedNamespace;
	return {
		setters: [function (module) {
			parser = module;
		}, function (module) {
			getAugmentedNamespace = module.getAugmentedNamespace;
		}],
		execute: function () {

			var parser = exports('default', /*@__PURE__*/getAugmentedNamespace(parser));

		}
	};
});
```

The issue here is that the `var parser` in the `execute` function is shadowing the `var parser` defined above. I will need to take a look why this is not deconflicted, might not be trivial to fix but this is definitely important.

**Comment by lukastaegert** [comment]
Please try again with Rollup@2.28.2
