### ISSUE TITLE
New Plugin - XML

### ISSUE THREAD

**Issue by Mlocik97** [rollup/plugins#586]
Request Checklist: 

- [ ] I would like to have XML plugin, that would work similiar to JSON plugin, so I can handle and process xml files with rollup.

- [X] I have searched https://npmjs.com/ before opening this issue
  (found one plugin, but it's unofficial, really buggy, with only few users.) 
- [X] I have searched https://github.com/rollup/awesome before opening this issue

### New Plugin Use Case
Same as json plugin, just for xml files.

**Comment by shellscape** [comment]
Thanks for the issue. This is unfortunately not a full proposal, and there's nothing for the team to act on here. Please take some time to think through how you would have the plug-in behave and document it thoroughly. (it also looks like you tried to add another checkbox and we're not sure why)

**Comment by Mlocik97** [comment]
I think, converting XML to HTML Collection. https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection

I need to do something, I was able to do with jQuery https://api.jquery.com/jQuery.parseXML/ but not on client-side, not even server-side, but even before server is inicialized (so build time).

It should help for example in Svelte/Sapper where I have {@html htmlcollection} where I can bind HTML, that would be parsed from XML.

**Comment by shellscape** [comment]
I'd recommend converting your XML to JSON before the build as a step and using the JSON plugin, or you could use https://github.com/bdadam/rollup-plugin-html to target XML files and load them in the build as a string, and use an interpreter on the string if needed. I think there are a number of routes you could take without needing a new plugin.
