### ISSUE TITLE
[commonjs] node_modules referenced relatively to output folder instead of name

### ISSUE THREAD

**Issue by johannes-z** [rollup/plugins#592]
- Rollup Plugin Name: @rollup/plugin-commonjs 
- Rollup Plugin Version: ^15.1.0
- Rollup Version: ^2.28.2
- Operating System (or Browser): Ubuntu 1804
- Node Version: v10.19.0
- Link to reproduction: https://repl.it/repls/KosherElderlyInformationtechnology#rollup.config.js

### Expected Behavior
Proper import statements:

```js
import 'core-js/modules/es.array.index-of.js';
import 'core-js/modules/es.object.to-string.js';
import 'core-js/modules/es.reflect.construct.js';
import 'core-js/modules/es.regexp.to-string.js';
import classCallCheck from '@babel/runtime/helpers/classCallCheck.js';
import createClass from '@babel/runtime/helpers/createClass.js';
import inherits from '@babel/runtime/helpers/inherits.js';
import possibleConstructorReturn from '@babel/runtime/helpers/possibleConstructorReturn.js';
import getPrototypeOf from '@babel/runtime/helpers/getPrototypeOf.js';
```

See also [Babel REPL](https://babeljs.io/en/repl#?browsers=ie%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=NwCghgzgngdgxgAgGYFd4BcCWB7GCC2YmMIAlAgN4BQCCcuE6CATgKYQoA2TAvAmAHciTdO3RkadBtk6sAdJ2wBzEHLVsO3UlQC-pMsCpVIsRKgw48oxgjKVJbdCmZ4A2gEYANAgBM3gMzeACzeAKwAurpAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=)

### Actual Behavior
*Wrong* import statements:

```js
import '../../../../../node_modules/core-js/modules/es.array.index-of.js';
import '../../../../../node_modules/core-js/modules/es.object.to-string.js';
import '../../../../../node_modules/core-js/modules/es.reflect.construct.js';
import '../../../../../node_modules/core-js/modules/es.regexp.to-string.js';
import classCallCheck from '../../../../../node_modules/@babel/runtime/helpers/classCallCheck.js';
import createClass from '../../../../../node_modules/@babel/runtime/helpers/createClass.js';
import inherits from '../../../../../node_modules/@babel/runtime/helpers/inherits.js';
import possibleConstructorReturn from '../../../../../node_modules/@babel/runtime/helpers/possibleConstructorReturn.js';
import getPrototypeOf from '../../../../../node_modules/@babel/runtime/helpers/getPrototypeOf.js';
```

Related to this, the output of `preserveModules: true` is completely broken:
![image](https://user-images.githubusercontent.com/9069888/94532095-b651b200-023d-11eb-8faa-f1c9eae40216.png)
(the contents of `tmp` should be inside `lib`, not inside a folder representing the package's folder structure)

This happens inside of a yarn monorepo. The dependencies are hoisted to the workspace root, and referenced by the commonjs plugin. This apparently has a bad side effect of messing up the output.

### Additional Information
`preserveModule` is needed for library code, as it results in better, tree-shakable code.

Removing any code/plugins/etc related to commonjs fixes the paths and the emitted folder structure. Commonjs is needed though to get `@babel/preset-env` to work...

**Comment by lukastaegert** [comment]
If you want imports like 'core-js/modules/es.array.index-of.js' to be maintained in the output you must declare them as "external". This is achieved easiest by making "external" a function or pattern.

Otherwise this output is not "broken" as you put it, it is the only way to maintain the relative file positions if you are bundling stuff from `node_modules`. But I am sure you chose the wording due to your own frustration and not to insult.

Also, you might want to play around with https://rollupjs.org/guide/en/#outputpreservemodulesroot to improve the directory structure if you need to keep your node_modules fodler in the build.

**Comment by johannes-z** [comment]
Oh I see, sorry, I genuinely thought this is an issue of that plugin. `external` does fix the path's. The reason why I thought the emitted code is broken is, that it's unusable by other npm projects. I tried importing my library code, but those `../../node_modules...` paths didn't work.

I'll test `output.preserveModulesRoot`, thanks!

**Comment by lukastaegert** [comment]
Those paths should work as long as the generated (not the original) `node_modules` folder is still in the correct position. If something is not resolving correctly there, then it is a bug.
