### ISSUE TITLE
inserting random `index.js#` into a require import containing a #. (breaking the import)

### ISSUE THREAD

**Issue by MarkLyck** [rollup/plugins#595]
- Rollup Version: Latest
- Operating System: Macos Catalina
- Node Version: 14
- reproduction url: See easy 1 step below.

### Expected Behavior
Rollup should not treat require statements with a `#` in it as a URL.

### Actual Behavior
Getting the following error trying to use memoizee (npm package) with rollup:

```
Could not load /Users/mark/ypm/xxxx/cloud-one2/node_modules/es5-ext/array/index.js#/e-index-of (imported by node_modules/memoizee/normalizers/get-fixed.js): ENOENT: no such file or directory, open '/Users/mark/ypm/xxxx/cloud-one2/node_modules/es5-ext/array/index.js#/e-index-of'
```

I checked my node modules and `node_modules/es5-ext/array/#/e-index-of.js` exists.

I'm not sure why the import ends up being `es5-ext/array/index.js#/e-index-of` (there is no `index.js` in the require path)

Looking at the `get-fixed.js` inside memoizee in the node modules. The require is perfectly fine:

`var indexOf = require("es5-ext/array/#/e-index-of")`

My guess is that the `#` freaks out rollup somehow? Honestly I've never seen a folder called `#` before, and have no clue why `es5-ext` decided that was a good idea. But other build systems have no problems handling this.

Sounds like the issue is that Rollup treats that as a URL, in which case "es5-ext/array/#/e-index-of" is really "es5-ext/array/" (anything after a hash in a URL isn't a part of the path itself).

### Reproduction:

- Install memoizee in any rollup project.
- import it anywere.
- run `yarn build`

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by MarkLyck** [comment]
@shellscape I did add reproduction (which is literally 1 step, with an extremely clear description of exactly what is happening).

I would highly recommend you read the issues, and maybe become a little more helpful, when people are trying to help you understand bugs in your software, rather than just dismissing everything immediately.

never seen this behaviour in any open source library before.

If you want people to stop using your software. This is definitely the way to handle that... Your "repl." system does not have a method to run it correctly.

But I added a url for you regardless. Even though it's pretty useless for replicating the issue.

**Comment by shellscape** [comment]
We ask the same of users as we we.do contributors and maintainers. There's little excuse for willingly ignoring directions. You would be better served as a user to properly respect the time and effort of maintainers by following the guidelines for contribution to projects.

Best of luck to you in your endeavors with another tool.
