### ISSUE TITLE
Faulty output when using transformMixedEsModules: true

### ISSUE THREAD

**Issue by josejulio** [rollup/plugins#596]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 15.1.0
- Rollup Version: 2.28.2
- Operating System (or Browser): Fedora 32
- Node Version: v10.22.1
- Link to reproduction _(⚠️ read below)_: https://repl.it/repls/JampackedShowyComputerscience#rollup.config.js

### Expected Behavior

Should produce valid code when using `transformMixedEsModules: true` .

### Actual Behavior

When using `transformMixedEsModules: true` is producing faulty code (Unexpected token at line 24:0). 

### Additional Information

To see the actual code that is failing, I added a `console.log` (because I have no idea how to see the temporal files, please let me know if is possible :D) to rollup code:  `sed -i '9710 a console.log(module.code);' node_modules/rollup/dist/shared/node-entry.js`

It shows the following code when trying to build:

```js
import 'stuff';
import isDeepEqual from 'stuff?commonjs-proxy';

// https://github.com/streamich/react-use/blob/master/src/util.ts
// This file is found in the package react-use under: node_modules/react-use/esm/util.js

export var isClient = typeof window === 'object';
export var on = function (obj) {
    var args = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        args[_i - 1] = arguments[_i];
    }
    return obj.addEventListener.apply(obj, args);
};
export var off = function (obj) {
    var args = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        args[_i - 1] = arguments[_i];
    }
    return obj.removeEventListener.apply(obj, args);
};
export
```

The original code is: 
```js
// input.js
// https://github.com/streamich/react-use/blob/master/src/util.ts
// This file is found in the package react-use under: node_modules/react-use/esm/util.js

export var isClient = typeof window === 'object';
export var on = function (obj) {
    var args = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        args[_i - 1] = arguments[_i];
    }
    return obj.addEventListener.apply(obj, args);
};
export var off = function (obj) {
    var args = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        args[_i - 1] = arguments[_i];
    }
    return obj.removeEventListener.apply(obj, args);
};
export var isDeepEqual = require('stuff');

// stuff.js
export default function stuff () {
  console.log('hello world');
}
```

**Comment by lukastaegert** [comment]
I see, yes this is a bug. So it turns out it does not handle exports that contain require expressions:

```js
export var isDeepEqual = require('stuff');
```

The usual logic to handle require expressions kicks in here, removing the expression with the assignment, but it leaves the export keyword in place and also forgets, well, to export something.

**Comment by josejulio** [comment]
Thanks for confirming, I though it was a bug but was unsure.

One question though, is there a way to preserve or see the intermediary output right before the fail?

**Comment by lukastaegert** [comment]
You can write a simple plugin that just implements a `transform` hook. These hooks are always called for all plugins. If you make this the last plugin and do not return anything from this hook, then it is ideal to just look the id and code of all input modules as seen by Rollup core.

i.e.

```
{
  transform(code, id) {
    console.log(id);
    console.log(code);
    console.log('=======\n');
  }
}
```

could be the whole plugin.
