### ISSUE TITLE
Clearer error if tslib is not installed

### ISSUE THREAD

**Issue by NotWoods** [rollup/plugins#598]
- Rollup Plugin Name: 
- Rollup Plugin Version:

### Feature Use Case
The error message if TypeScript tries to find tslib is a little unclear, and has [caused some user confusion](https://github.com/rollup/plugins/issues/243#issuecomment-670149948).

We explicitly import the `tslib.es6.js` subfile to avoid a dependency on the node resolve plugin, so this makes the error more confusing. 

### Feature Proposal
Change error message to something like `Cannot find module 'tslib', is it installed?`

**Comment by shellscape** [comment]
Sounds good to me.

**Comment by henriquehbr** [comment]
This one would be a great improvement in terms of DX
