### ISSUE TITLE
[TypeScript] allow enabling the plugins without TS files

### ISSUE THREAD

**Issue by apfelbox** [rollup/plugins#600]
- Rollup Plugin Name: typescript (`@rollup/plugin-typescript`) 
- Rollup Plugin Version: `6.0`

### Expected Behavior / Situation
Allow enabling the plugin, even if no `.ts` file is compiled.

### Actual Behavior / Situation
Right now, if you build a JS dependency graph **without any** typescript file, you get an error:

```
@rollup/plugin-typescript TS18003: No inputs were found in config file '/.../tsconfig.json'. Specified 'include' paths were '["**/*.tsx","**/*.ts","**/*.mjsx","**/*.mjs","**/*.jsx","**/*.js"]' and 'exclude' paths were '["node_modules","vendor"]'.
```

### Modification Proposal
As I am building a generic bundler, I can't know if there is any typescript file in the dependency graph (as it doesn't have to be an entry file). So I would like to just always enable support for typescript. 

But unfortunately, I can't do that, because if I enable this plugin and there is not a single input file for the typescript compiler, this plugin will throw and fail the build.

**Comment by shellscape** [comment]
Unfortunately this is a limitation of using TypeScript's core API within the plugin. See: https://github.com/Microsoft/TypeScript/issues/17155, `TS18003` is a TypeScript error, not a plugin error. The plugin is simply forwarding the error onto the user.

At present I don't see a huge call for this from the community. We're speaking about new feature "voting" processes as a team and may implement that to give the userbase a voice, but the threshold on this kind of feature/change would likely be over 100 votes in favor, and I'm not sure you'd get that.

Alternatively, you might want to look into dynamically adding the plugin to the config, within the config, or during runtime if you're using the Rollup API, after examining the inputs using a module that does fast tree traversal.

**Comment by lukastaegert** [comment]
You could implement this by writing a wrapper plugin that exposes all hooks of the TypeScript plugin as dummies but once the first `.ts` file is passed through the `resolveId` hook, you dynamically instantiate the plugin, call its `buildStart` hook (it should be ok to pass the `this` context of the `resolveId` hook) and replace all dummy hooks with ones that forward to the TypeScript plugin. 

Alternatively maybe you want to consider not having proper type-checking and rather add something like https://github.com/rollup/plugins/tree/master/packages/sucrase? It would also be slightly faster.

**Comment by NickCarducci** [comment]
I think Typescript wishes you to make a `decs.d.ts` file next to your `output.file` destination. Two errors with one go

````
declare module "react";
declare module "react-dom";
declare module "react-transition-group";
declare module "react-router-dom";
````
