### ISSUE TITLE
[dynamic-import-vars] Use hash maps instead of switch case

### ISSUE THREAD

**Issue by TheComputerM** [rollup/plugins#603]
- Rollup Plugin Name: dynamic-import-vars
- Rollup Plugin Version: 1.1.0

### Expected Behavior / Situation
There is no expected behavior, this modification might improve the performance.

### Actual Behavior / Situation
```js
function __variableDynamicImportRuntime0__(path) {
   switch (path) {
     case './files/t1.js': return import('./t1-6798a80b.js');
     case './files/t2.js': return import('./t2-e8dc31bb.js');
     case './files/t3.js': return import('./t3-8b291724.js');
     default: return Promise.reject(new Error("Unknown variable dynamic import: " + path));
   }
 }
```

### Modification Proposal
Something like a hash map.
```js
function __variableDynamicImportRuntime0__(path) {
  const map = {
     './files/t1.js': import('./t1-6798a80b.js'), 
     './files/t2.js': import('./t2-e8dc31bb.js'),
     './files/t3.js': import('./t3-8b291724.js')
  }
  return map[path];
 }
```

Maybe this will improve the performance if there are too many files.

**Comment by TheComputerM** [comment]
Also, just a question, is there a reason why dynamic-import-vars is not mentioned in the base README.md?

**Comment by shellscape** [comment]
Probably just missed adding it to the README during review of the new plugin PR.

**Comment by lukastaegert** [comment]
This is definitely something I also thought about but forgot. But in your version, all imports would be executed immediately, maybe rather something like

```js
const map = {
     './files/t1.js': function () {return import('./t1-6798a80b.js')}, 
     './files/t2.js': function () {return import('./t2-e8dc31bb.js')},
     './files/t3.js': function () {return import('./t3-8b291724.js')}
}

function __variableDynamicImportRuntime0__(path) {
  return map[path]();
 }
```

By extracting the map, you would also lose the overhead of recreating the object each time. I guess PRs are welcome.

**Comment by LarsDenBakker** [comment]
Is that objectively faster?

**Comment by TheComputerM** [comment]
Creating a benchmark...

**Comment by LarsDenBakker** [comment]
Also don't forget the helpful error message when an import does not exist. That would trigger a prototype lookup, though we don't really need to optimize for that.

**Comment by TheComputerM** [comment]
In Java
```
Switches will always be as fast as if not faster than hash maps. Switch statements are transformed into direct lookup tables
```
Don't know the case for JavaScript.

**Comment by LarsDenBakker** [comment]
Note that an object literal is not a hash map, lookups can trigger prototype walks especially when keys are dynamic. You could use `Map` but then you need to consider polyfills. Or I think `Object.create(null)` also protects against it. 

With a switch you get language-level lazy evaluation, with an object you need to use functions to prevent direction execution. A benchmark will really tell the difference though.

This is all pretty extreme micro level though, since this code doesn't really run all that often to make an impact.

**Comment by lukastaegert** [comment]
> Don't know the case for JavaScript.

Don't think so, at least I remember running some benchmarks for this at some point in the past. Not sure if this is still correct, though. Problem is that logic can be triggered in the expressions that make up cases.

> Note that an object literal is not quite like a Java hash map

true, this would fix it:

```
const map = {
    __proto__: null,
     './files/t1.js': function () {return import('./t1-6798a80b.js')}, 
     './files/t2.js': function () {return import('./t2-e8dc31bb.js')},
     './files/t3.js': function () {return import('./t3-8b291724.js')}
}
```

But yes, it is probably a micro-optimzation that does not even make the code smaller.

**Comment by LarsDenBakker** [comment]
Good point, code size might actually be the most important factor here.

**Comment by TheComputerM** [comment]
After running some proper benchmarks, switches perform better than maps in this case due to each object value being a function. Previously my benchmarks were flawed.
Closing the issue.
