### ISSUE TITLE
Strip Plugin 2.0.0 doesn't remove code block

### ISSUE THREAD

**Issue by patoi** [rollup/plugins#605]
- Rollup Plugin Name: @rollup/plugin-strip
- Rollup Plugin Version: 2.0.0
- Rollup Version: 2.29.0
- Operating System (or Browser): MacOS Catalina 10.15.7 (19H2), all browsers
- Node Version: v12.19.0
- Link to reproduction _(⚠️ read below)_: https://github.com/patoi/reprod-svelte-plugin-strip-01

### Expected Behavior

Strip removes code block (unittest) as in documentation, result is HELLO WORLD! in linked github code.

### Actual Behavior

Strip doesn't remove code block (unittest) as in documentation, result is HELLO STRIP DOESN'T WORK! in linked github code.

**Comment by shellscape** [comment]
Thanks for the issue, but please try providing a more minimal reproduction, without Svelte and without the additional plugins.

**Comment by patoi** [comment]
Thanks for quick response! It works fine without Svelte. I used default (offical) Svelte template project with stip plugin (as documented), but it doesn't wok (may be my bad).
Is this plugin working with Svelte? Do you know any use case?
Thanks for your reply!

**Comment by shellscape** [comment]
That's good info. It sounds like Svelte's structure, build process, or possibly another plugin is causing issues. If I were to guess, the code you're targeting is being modified before the strip plugin sees it. A reorder of plugins might be needed. I'd start there.

**Comment by patoi** [comment]
I tried with several ordering, but it doesn't work. Thanks for your help!
