### ISSUE TITLE
TypeError: babel is not a function

### ISSUE THREAD

**Issue by cowwoc** [rollup/plugins#613]
Hi,

I had the same problem as https://github.com/rollup/plugins/issues/485 and I just wanted to note that the solution was to replace `babel()` in the plugin section with `babel`.

I don't know why this is needed but I can confirm that when I run the build through a debugger, `babel()` returns an object. The plugin documentation seems to imply this is a function which seems to indicate there is some sort of bug there.

Anyway, I hope this helps other users who might run into the same problem.

**Comment by shellscape** [comment]
Please comment on the related ticket in the future. Even if it is closed, the ticket will remain searchable and able to be referenced.

**Comment by cowwoc** [comment]
@shellscape I'd love to, but someone locked the original ticket. I do not have permissions to add a comment on it. Can you remove the lock?

**Comment by shellscape** [comment]
Thanks, I hadn't realized it was. Unlocked!
