### ISSUE TITLE
[wasm] can't import wasm-bindgen generated wasm file

### ISSUE THREAD

**Issue by canadaduane** [rollup/plugins#617]
- Rollup Plugin Name: `@rollup/plugin-wasm`
- Rollup Plugin Version: 5.1.0
- Rollup Version: 2.32.0
- Operating System (or Browser): Mac OS 10.14.6
- Node Version: 12.19.0
- Link to reproduction _(⚠️ read below)_: https://github.com/canadaduane/rapier3d-wasm-rollup-issue/tree/rollup

### Expected Behavior

When importing a WASM file that has been compiled by rust and generated by wasm-bindgen, `@rollup/plugin-wasm` should import its external symbols.

### Actual Behavior

Building the linked project above (`yarn build` on the `rollup` branch) results in the following (abbreviated) output, with many more `is not exported` symbols not shown:

```
...
node_modules/@dimforge/rapier3d/rapier_wasm3d_bg.js
rawphysicspipeline_removeCollider is not exported by node_modules/@dimforge/rapier3d/rapier_wasm3d_bg.wasm
1187:         _assertClass(bodies, RawRigidBodySet);
1188:         _assertClass(colliders, RawColliderSet);
1189:         wasm.rawphysicspipeline_removeCollider(this.ptr, handle, broadPhase.ptr, narrowPhase.ptr, bodies.ptr, colliders.ptr);
                   ^
1190:     }
1191: }
node_modules/@dimforge/rapier3d/rapier_wasm3d_bg.js
__wbg_rawquerypipeline_free is not exported by node_modules/@dimforge/rapier3d/rapier_wasm3d_bg.wasm
1205:         this.ptr = 0;
1206:
1207:         wasm.__wbg_rawquerypipeline_free(ptr);
                   ^
1208:     }
1209:     /**
...
```

### Additional Information

I've analyzed the particular wasm file in the link above, using [wasm-nm](https://github.com/fitzgen/wasm-nm) and [wasm2wat](https://github.com/WebAssembly/wabt) and the external symbols are being exported.

I've asked the author of rapier3d whether the `wasm-bindgen` [deploy target](https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html#bundlers) is `web` or `bundler`. I'll follow up when I hear back.

UPDATE: it's [using the default](https://github.com/dimforge/rapier.js/blob/f16fcddf54f57baceea44d495069ae05542a0a73/rapier3d/build_rust.sh#L3), which is `--target bundler`.

Note: also talking about this in a [snowpack discussion](https://github.com/snowpackjs/snowpack/discussions/1356#discussioncomment-104187).

**Comment by shellscape** [comment]
Thanks for opening an issue. We're a little short on help for the wasm plugin at the moment, so please do open a PR if you have the opportunity.

**Comment by noandrea** [comment]
Hi, so far the rollup wasm is very promising except for this issue. I'd like to help but I am not very familiar with the problem, can someone maybe point me in the right direction about what needs to be done?

**Comment by shellscape** [comment]
@noandrea thanks for following up. we'd love your help! The best starting point would be to fork the reproduction and step through the plugin code to understand how it works, and then hopefully what point in the code is producing the bad result.

**Comment by shroomist** [comment]
I've tried to get this wasm plugin working with the library that used bindgen for their wasm.
I'm targeting browsers, so no luck here.
nodejs works like charm, kudos rollup, loving it.
falling back to webpack unfortunately for now.

**Comment by pastelmind** [comment]
@Menci has written a [WASM plugin for Vite](https://github.com/Menci/vite-plugin-wasm) that is compatible with wasm-bindgen. Since Vite uses Rollup under the hood and shares most of its plugin architecture, perhaps @rollup/plugin-wasm could learn some tips from vite-plugin-wasm? Alternatively, it doesn't hurt to use Vite as a build tool--although this also has challenges.

**Comment by Menci** [comment]
Let me check if I can make a rollup version of my plugin?

**Comment by Menci** [comment]
I wonder how is [top-level await](https://github.com/Menci/vite-plugin-top-level-await) supported in Rollup's module formats (iife, umd) which is not in Vite?

**Comment by calebtuttle** [comment]
I'm experiencing a similar issue. Has any progress been made on this?
