### ISSUE TITLE
mistake in plugin-virtual readme

### ISSUE THREAD

**Issue by damooo** [rollup/plugins#62]
- Rollup Plugin Name: virtual
- Rollup Plugin Version: *
- Rollup Version: *
- Operating System (or Browser): *
- Node Version: *

### How Do We Reproduce?
in README

### Expected Behavior
at https://github.com/rollup/plugins/tree/master/packages/virtual#install install command should be right

### Actual Behavior

presently it is command to install `yaml` plugin instead

**Comment by shellscape** [comment]
Fixed by #63
