### ISSUE TITLE
[json] feature: quote property-names to better synergise with terser

### ISSUE THREAD

**Issue by eiksch** [rollup/plugins#623]
- Rollup Plugin Name: json
- Rollup Plugin Version: latest 4.1.0

### Feature Use Case
When working together with terser, it's property mangler will mangle imported json objects used as dictionary (a common use-case for json imports), therefore destroying their purpose. See [this terser feature request with example](https://github.com/terser/terser/issues/862). Terser has the possibility to use the `keep_quoted` config, to ignore quoted properties, but `rollup-plugin-json` has no possibility to quote properties.

### Feature Proposal
Add the option `quote_properties default: false`. When set to `true`, the plugin will output quoted property names.

**Comment by shellscape** [comment]
Thanks for the issue. Are you asking the JSON plugin to make allowances for mangling that terser performs? If so, it seems like the terser plugin/core is the offending party here and the issue should be taken up with them for compatibility.

I'm not sure we'll get much benefit to the JSON plugin userbase as a whole by adding extra complexity for an integration edge case.

**Comment by eiksch** [comment]
The rollup community has no real alternative to terser when looking into ES5+ mangling/compressing so imo it would make sense to create this synergy.

It may be an edge case as you said, and I'm the one with the problem. I can't say what others would think about this. :D

**Comment by shellscape** [comment]
It does merit looking into. Would you be able to put together a test case demonstrating this using the REPL, a test on a fork, or a repo?

**Comment by eiksch** [comment]
Ill do a repo later. thanks

**Comment by eiksch** [comment]
[repo](https://github.com/eiksch/rollup-json-issue-623)

I used terser directly in this case. see asserts in `src/index.js` for quick doc

**Comment by shellscape** [comment]
Given the comments in the issue you tagged, I think this is a reasonable feature to add. Would you be willing to look into a PR to introduce this feature?
