### ISSUE TITLE
improvement to @rollup/plugin-html docs

### ISSUE THREAD

**Issue by simonxabris** [rollup/plugins#630]
- Rollup Plugin Name: @rollup/plugin-html
- Rollup Plugin Version: 0.2.0

Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The docs say that the `template` option receives an object that has a `files` property (this is correct up to this point) that is an `Array` of `AssetInfo` or `ChunkInfo`, which in my experience is not the case. The `files` property actually contains a `js`, `css` and `map` keys which are of type `Array<AssetInfo | ChunkInfo>`.

### Your Proposal for Changes

My proposal is pretty simple, It should be explained in the docs that `files` is an object with the following keys: `js`, `css`, `map` and they are of type `Array<AssetInfo | ChunkInfo>`. If you think this is OK I'll be happy to provide a PR with these changes!

**Comment by shellscape** [comment]
Reopening since we have a PR in progress for this.
