### ISSUE TITLE
HTML & Typescript

### ISSUE THREAD

**Issue by ispyinternet** [rollup/plugins#636]
Anybody know how to get `rollup/plugin-typscript` and `rollup/plugin-html` to work together?

I've tried both commonjs and es6 (so .js file includes either `import 'file.html'` and `require('file.html')`) but rollup always bails with `Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`

Not sure it makes any difference but I've tried switching order of plugins too.

Starting to lose the will :(

**Comment by shellscape** [comment]
Thanks for opening an issue. Unfortunately we don't offer support here. Please see the issue templates for a few support options. Well also be opening our Discord server in the coming week or so.

**Comment by ispyinternet** [comment]
issue was thinking that `rollup/plugin-html` was the newer version of `rollup-plugin-html` 😩
