### ISSUE TITLE
es6 compile error (aperator OF)

### ISSUE THREAD

**Issue by d-kochanzhi** [rollup/plugins#64]
- Rollup Plugin Name: @rollup/plugin-buble
- Rollup Plugin Version: 0.20.0
- Rollup Version:1.1.2
- Operating System (or Browser):
- Node Version:

### How Do We Reproduce?

cant compile this code:

 for (var key of data.keys()) {
\\ iteration of FormData 
}

https://developer.mozilla.org/ru/docs/Web/API/FormData/keys

### Expected Behavior

compile

### Actual Behavior

Error

UnhandledPromiseRejectionWarning: Error
    at Function.missingTransform (\node_modules\@rollup\plugin-buble\node_modules\buble\dist\buble.cjs.js:376:9)

**Comment by shellscape** [comment]
@d-kochanzhi thanks for opening an issue but you missed a very important part of the template:

> Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Work to isolate the problem and provide the exact steps in this issue, or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a minimal reproduction.

**Comment by shellscape** [comment]
@d-kochanzhi please let us know when you've added a reproduction so that we can begin to triage this. We're going to close this issue for now, but will reopen it when a repro has been added.
