### ISSUE TITLE
@rollup/babel has a dep on @types/estree@0.0.39 which breaks @types/eslint

### ISSUE THREAD

**Issue by kentcdodds** [rollup/plugins#640]
- Rollup Plugin Name: `@rollup/plugin-babel`
- Rollup Plugin Version: latest (`5.2.1`)
- Rollup Version: latest (N/A)
- Operating System (or Browser): N/A
- Node Version: N/A
- Link to reproduction _(⚠️ read below)_: https://github.com/rollup/plugins/pull/639#issuecomment-724180787

### Expected Behavior

`@types/estree@0.0.41` (latest) should be installed and deduped

### Actual Behavior

`@types/estree@0.0.39` gets installed and doesn't play nice with other types packages

### Additional Information

More info in this PR: https://github.com/rollup/plugins/pull/639

**Comment by shellscape** [comment]
@Andarist any chance you have a moment to tackle this?

**Comment by Andarist** [comment]
I'm afraid that I won't have time to handle this soon. With 2 small kids at home and multiple OSS projects to maintain I'm really struggling with finding time lately to do all the things I'd like. Given this require a dependency update and not something really specific to the plugin itself I would say that anyone can do it (a team contributor or an external one). 

I'm not sure about that breaking change in the `@rollup/pluginutils` - but maybe the upgrade could be done in a backward-compatible manner by joining the options with `cwd` to match the `@rollup/pluginutils@3` behavior? That would allow us to avoid a new major for `@rollup/plugin-babel`

**Comment by tianyingchun** [comment]
I think all rollup plguin should be upgrade `@rollup/pluginutils` from `3.1.0` to `4.1.0` this issue can be resolved.

**Comment by Andarist** [comment]
Right, I would prefer to avoid a breaking change in the `@rollup/plugin-babel` though so ideally it should be explored if it's possible to do this upgrade in such a way. The issue stays open for anyone that cares about this and would like to contribute a PR for this.

**Comment by dasa** [comment]
> Right, I would prefer to avoid a breaking change in the `@rollup/plugin-babel` though so ideally it should be explored if it's possible to do this upgrade in such a way.

Would it be possible to move `@types/estree` from `dependencies` to `devDependencies` in a 3.x release of `@rollup/pluginutils`?

**Comment by sir-captainmorgan21** [comment]
@shellscape @Andarist any word on this? Still an issue with breaking eslint. `@rollup/pluginutils` has been updated to point to the latest of `@types/estree`, but a good amount of the other plugins are pointing to an older version of `@rollup/pluginutils`.
