### ISSUE TITLE
Typescript plugin produces duplicate output when used with multiple entry points on Windows

### ISSUE THREAD

**Issue by antross** [rollup/plugins#643]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 6.0.0
- Rollup Version: 2.32.0
- Operating System (or Browser): Windows
- Node Version: 12.16
- Link to reproduction _(⚠️ read below)_: https://github.com/antross/rollup-plugin-typescript-repro

This occurs when using multiple entry points in which one references code from the other.

### Expected Behavior
In the bundled output the second entry point imports content from the first to avoid duplicating code. This is what rollup normally does when this plugin isn't present.
```js
import { one } from './one.js';

function two() {
    one();
    console.log('two');
}

export { two };
```

### Actual Behavior
In the bundled output the second entry point inlines content from the first, duplicating code (since the first entry point also is generated and still has this code).
```js
function one() {
    console.log('one');
}

function two() {
    one();
    console.log('two');
}

export { two };
```

### Additional Information
Removing @rollup/plugin-typescript from the plugins array eliminates the repro.

Making a quick local edit to wrap the return value from the plugin's `resolveId` method in a call to `path.normalize` appears to fix the issue, suggesting rollup is expecting an exact string match on the ID. Since the plugin is returning a POSIX normalized path even on Windows, this would cause the string comparison to fail if rollup is expecting an OS normalized path.:
https://github.com/rollup/plugins/blob/b12acfa910905d2cf2ec486be9f596de4de151bf/packages/typescript/src/index.ts#L101

Apart from fixing this plugin, it may be worth making rollup itself more flexible to handle paths with different types of separators than the host OS (so other plugins don't suffer from the same issue). Curious to hear your thoughts. Thanks!

**Comment by shellscape** [comment]
Thanks for the issue. While this isn't the spot to speak to Rollup core suggestions (that should be done in `rollup/rollup`) we do appreciate you raising the problem here. Since none of our maintainers are Windows users, we're going to be in a pickle reproducing it locally, and the best we'll be able to do is use your reproduction to try and create a failing test, as we do have CI that will run in Windows. Given that, would you be up for submitting a fix PR and a test for this?

**Comment by antross** [comment]
> Given that, would you be up for submitting a fix PR and a test for this?

Sure thing. I'll start working on a PR today.
