### ISSUE TITLE
Can't import named exports from a CJS file in an ESM file

### ISSUE THREAD

**Issue by stephenwade** [rollup/plugins#648]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 16.0.0
- Rollup Version: 2.33.2
- Operating System (or Browser): macOS 10.15.7
- Node Version: 15.1.0
- Link to reproduction: https://github.com/stephenwade/rollup-plugin-issue-repro

### Expected Behavior

I can import named exports from a CJS file in an ESM file.

The code I used is shared in #481 as an example that should work, under the heading "Example with statically detected named exports".

**Input**

```
// "main.js"
import { foo } from "./dep.js";
console.log(foo);

// "dep.js"
exports.foo = "foo";
```

**Output**

```js
// "bundle.js"
var foo = "foo";

console.log(foo);
```

### Actual Behavior

I get the following error from Rollup:

```
src/main.js → output...
[!] Error: 'foo' is not exported by src/dep.js, imported by src/main.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/main.js (1:9)
1: import { foo } from "./dep.js";
            ^
2: console.log(foo);
```

### Additional Information

To reproduce, clone the repository linked above, then run:

```bash
$ npm install
$ npm run rollup
```

**Comment by shellscape** [comment]
Probably related to #481

**Comment by stephenwade** [comment]
@shellscape I agree, in fact the code I used was taken from an example in that issue that said it should work.

**Comment by lukastaegert** [comment]
You are limiting the plugin to only process files with the `.cjs` extension.

**Comment by stephenwade** [comment]
Agh, you're right @lukastaegert. Taking out the `extensions` key makes everything work as expected.

Thanks!
