### ISSUE TITLE
Documentation problem or bug (maybe in my brain)

### ISSUE THREAD

**Issue by lesar** [rollup/plugins#650]
> Hey there! If you need help or tech support then this is not the place to
ask. Please head to the [Rollup Discord](https://is.gd/rollup_chat)

without success

> instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

I tried.  

> If you arrived here because you think Rollup's documentation is unclear,
insufficient or wrong, please consider creating an issue for the documentation
instead.

I have no found where is docu github. I search [here](https://github.com/rollup)  

I have post this question:
https://stackoverflow.com/questions/64862413/how-to-use-commonjs-rollup-and-babel-together

please help  

is a configuration problem across plugin. I do not wont to transpill into last js. I have to use Node 10 syntax, bundle required files and translate jsx into js

**Comment by shellscape** [comment]
Sorry, we don't offer support on the repo. Please use the support channels (as you said you've tried) and exercise patience.
