### ISSUE TITLE
Browser field regression

### ISSUE THREAD

**Issue by skeggse** [rollup/plugins#66]
rollup/rollup-plugin-node-resolve#127 introduced changes that broke our particular use of `pkg.browser`. We have packages that have a single import when used from node, but separate imports when used in browser modules.

For instance, let's say we have a `utils` module:

```
utils/
  package.json
  node.index.js
  dist/
    browser/
      string/
        index.js
  src/
    string/
      index.js
```

```js
// package.json
{
  "name": "utils",
  "main": "node.index.js",
  "browser": {
    "string/index.js": "dist/browser/string/index.js"
  }
}
```

```js
// node.index.js
exports.string = require('./src/string');
```

Which we use in two ways:

```js
// from node (no bundler)
const {string: {interpolate}} = require('utils');
```

```js
// from browser target (with rollup-plugin-node-resolve, {browser: true})
import {interpolate} from 'utils/string';
```

Because `string/index.js` isn't a real file, `resolve` fails to find it, and `resolveId` gives a falsy `resolved`. In `3.0.0`, this was different, as it took the `id` `utils/string` and tried to resolve it with a few different paths, including `utils/string/index.js`. It looked that key up in the `browser` object, and got `dist/browser/string/index.js`, which exited, so all was well.

I realize this may not be a use-case you want to support (I'm curious to know what tweaks you'd make to the structure of the `utils` package to achieve the import goals), but it was supported in `3.0.0`. To me, this makes rollup/rollup-plugin-node-resolve#127 a major rev, and `3.0.1` a backwards-incompatible change.

Not trying to call anybody out on this - it's a super weird use-case; just pointing out that the use-case exists, and wondering if it's something we want to support vs a use-case that shouldn't be supported in the first place.

**Comment by shellscape** [comment]
@StreetStrider would you like to submit a PR for updating the docs?

**Comment by StreetStrider** [comment]
@shellscape, will do.

**Comment by StreetStrider** [comment]
@shellscape #138
