### ISSUE TITLE
Buble plugin error: operator ?. is not supported.

### ISSUE THREAD

**Issue by cyberalien** [rollup/plugins#660]
- Rollup Plugin Name: @rollup/plugin-buble
- Rollup Plugin Version: 0.21.3
- Rollup Version: 2.33.2
- Operating System (or Browser): OSX 11.0.1
- Node Version: 15.2.0
- Link to reproduction _(⚠️ read below)_: https://repl.it/join/xgulnnjm-vjacheslavtrush

Code that buble fails to parse:
```js
const test = {
	foo: 1
};
console.log(test?.foo);
```

### Expected Behavior

Expected buble to parse that syntax.

### Actual Behavior

Throws error:
```
[!] (plugin buble) SyntaxError: Unexpected token (4:17)
input.js (4:17)
1 : const test = {
2 :   foo: 1
3 : };
4 : console.log(test?.foo);
                     ^
SyntaxError: Unexpected token (4:17)
```

**Comment by shellscape** [comment]
This is going to be an upstream issue in https://github.com/bublejs/buble. Please report the issue there.
