### ISSUE TITLE
"Insufficient Rollup version" with commonjs plugin v17.0.0

### ISSUE THREAD

**Issue by flayks** [rollup/plugins#667]
- Rollup Plugin Name: plugin-commonjs
- Rollup Plugin Version: 17.0.0
- Rollup Version: 2.34.0
- Operating System (or Browser): macOS 11.0.1
- Node Version: 15.3.0

### Actual Behavior
I get this error:
```
Error: Insufficient Rollup version: "@rollup/plugin-commonjs" requires at least rollup@2.30 but found rollup@2.0.
```

**Comment by shellscape** [comment]
This isn't a bug: https://github.com/rollup/plugins/blob/master/packages/commonjs/package.json#L50

**Comment by flayks** [comment]
I have Rollup 2.34.0 installed on my project tho, so I'm a bit confused why I get this error?

```json
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "rollup-plugin-hot": "^0.1.1",
  },
```

**Comment by shellscape** [comment]
That'll be an issue with your package manager of choice and your environment. Somewhere it thinks you have the wrong version installed. It's not an issue with the commonjs plugin.

**Comment by flayks** [comment]
That seems to come from the CommonJS plugin to me:
```
Error: Insufficient Rollup version: "@rollup/plugin-commonjs" requires at least rollup@2.30 but found rollup@2.0.
    at validateRollupVersion (/Users/flayks/sites/site/routify/node_modules/.pnpm/@rollup/plugin-commonjs@17.0.0_rollup@2.34.0/node_modules/@rollup/plugin-commonjs/dist/index.js:591:11)
    at Object.buildStart (/Users/flayks/sites/site/routify/node_modules/.pnpm/@rollup/plugin-commonjs@17.0.0_rollup@2.34.0/node_modules/@rollup/plugin-commonjs/dist/index.js:1504:7)
```

**Comment by shellscape** [comment]
If you're adamant that it's a plug-in problem, open a new issue with _a valid reproduction_.
