### ISSUE TITLE
Unresolved dependencies when "exports" field property's value is array

### ISSUE THREAD

**Issue by sosukesuzuki** [rollup/plugins#670]
- Rollup Plugin Name:  `@rollup/plugin-node-resolve`
- Rollup Plugin Version: `11.0.0`
- Rollup Version: `2.34.0`
- Operating System (or Browser): `MacOS Catalina`
- Node Version: `v14.5.0`
- Link to reproduction _(⚠️ read below)_: https://github.com/sosukesuzuki-sandbox/rollup-plugin-node-resolve-11-bug-repro

### Expected Behavior

Successful bundle for packages whose `"exports"` field in `package.json` is array like below:

```js
{
  "name": "pkg",
  "exports": {
    ".": "./main.js",
    "./util": [
      {
        "import": "./util.mjs"
      },
      "./util.js"
    ]
  }
}
```

### Actual Behavior

Unable to bundle, output like this:

```
(!) Plugin node-resolve: Package subpath './util' is not defined by "exports" in /Users/sosukesuzuki/development/rollup-plugin-node-resolve-11-bug-repro/pkg/package.json
(!) Unresolved dependencies
```

### Additional Information

Please see [the reproduce repository link](https://github.com/sosukesuzuki-sandbox/rollup-plugin-node-resolve-11-bug-repro). Also this bug was found from https://github.com/prettier/prettier/pull/9804.

If this is my misunderstand, sorry please close this.

**Comment by lukastaegert** [comment]
I tried it out and it seems to be supported in latest Node 14. I am also seeing this in the wild as used by `yargs-parser`, which is why Rollup cannot update node-resolve right away. But I also could not find any official documentation, which is odd. The only thing I could find was Webpack's take on it here, but I would hardly consider that official: https://webpack.js.org/guides/package-exports/

As it appears to be supported, maybe this is just a documentation issue cc @guybedford ?

**Comment by guybedford** [comment]
Yes it is supported and in the spec (per the modules documentation on the Node.js project) but not explicitly documented as it is not a recommended feature for any use cases.

This comes from the builtins fallback feature that import maps originally supported, and Node.js can provide support for that similarly if necessary in future by supporting. I believe webpack may be encouraging the array form via https://webpack.js.org/guides/package-exports/#alternatives but we don't encourage using it in Node.js.

**Comment by lukastaegert** [comment]
That means we should support it nonetheless?

> per the modules documentation on the Node.js project

Where is that?

**Comment by guybedford** [comment]
Yes I agree it should be supported.

The exact resolver specification can be found at https://nodejs.org/dist/latest-v15.x/docs/api/esm.html#esm_resolver_algorithm_specification, and the array resolution is detailed in PACKAGE_TARGET_RESOLVE under the array condition.

**Comment by LarsDenBakker** [comment]
Will pick this up.
