### ISSUE TITLE
Trying to migrate from rollup-plugin-typescript to @rollup/plugin-typescript is aggravating and filled with errors and arbitrary requirements

### ISSUE THREAD

**Issue by kaiyoma** [rollup/plugins#671]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.0.0
- Rollup Version: 2.33.1
- Operating System (or Browser): n/a
- Node Version: 14.15.0
- Link to reproduction _(⚠️ read below)_: n/a

### Expected Behavior
It should be easy or documented how to migrate from one plugin to the other.

### Actual Behavior
It is not easy or seemingly documented.

### Additional Information
I have a lerna repo with several rollup projects that are working great with rollup-plugin-typescript, but in the interest of staying updated, I'm trying to migrate to @rollup/plugin-typescript, but it's proven to be very difficult so far. Here's the first error I got:

```
Error: @rollup/plugin-typescript: Rollup 'dir' option must be used when Typescript compiler option 'declarationDir' is specified.
```

Um, okay, why? I can't find any explanation about this and it's not a requirement with the old plugin. Fine, I add `output.dir`, and now I get this:

```
Error: You must set either "output.file" for a single-file build or "output.dir" when generating multiple chunks.
```

Well, I _was_ setting `output.file` since I have a single-file build, but apparently that wasn't valid. Okay, I drop `output.file`, and now I get this:

```
Error: @rollup/plugin-typescript: Path of Typescript compiler option 'declarationDir' must be located inside Rollup 'dir' option.
```

What? Why? I don't see any reason why this needs to be true, especially since my current build puts the output and typings in sibling directories and it's totally fine. Again, seemingly no documentation about why this is required now. Okay, fine, I move one directory inside the other. Now I'm getting this:

```
error TS5055: Cannot write file '<package>/dist/typings/src/index.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '<package>/dist/typings/src/lib.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '<package>/dist/typings/test/fixtures.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '<package>/dist/typings/test/lib.spec.d.ts' because it would overwrite input file.
```

And that's where I'm at now. Why are the requirements for this plugin so different than the previous one? Some of them seem arbitrary and the overall process is pretty painful. Is there something I'm missing here?

**Comment by shellscape** [comment]
We don't offer support here, and this isn't the place to vent your frustrations. Use one of the support options in mentioned in the issue templates.
