### ISSUE TITLE
babel package fails linting

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#677]
- Rollup Plugin Name: babel
- Rollup Plugin Version: `master`
- Rollup Version: ^2.23.0
- Operating System (or Browser): Ubuntu
- Node Version: 14.8.0
- Link to reproduction _(⚠️ read below)_: https://github.com/rollup/plugins

### Expected Behavior

Linting should pass

### Actual Behavior

```
$ git clone git@github.com:rollup/plugins.git
$ pnpm install
$ cd packages/babel
$ pnpm lint
test/as-input-plugin.js
  12:82  error  Missing file extension for ".."        import/extensions
  12:82  error  Unable to resolve path to module '..'  import/no-unresolved

test/as-output-plugin.js
  9:70  error  Missing file extension for ".."        import/extensions
  9:70  error  Unable to resolve path to module '..'  import/no-unresolved

```

**Comment by shellscape** [comment]
You'll need to run `pnpm run build` before that'll work. It's a little catch-22 for making the tests use the actual built plugin and also linting the tests all the same.
