### ISSUE TITLE
inconsistent linting of readmes

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#678]
- Rollup Plugin Name: various
- Rollup Plugin Version: `master`
- Rollup Version: N/A
- Operating System (or Browser): Ubuntu
- Node Version: 14.8.0
- Link to reproduction _(⚠️ read below)_: https://github.com/rollup/plugins

### Expected Behavior

Linting on my machine returns this: https://github.com/rollup/plugins/pull/676

### Actual Behavior

The version checked into `master` is this: https://github.com/rollup/plugins/pull/666

**Comment by shellscape** [comment]
🤔 I think a modification ticket would have been more appropriate here. Not really a bug to report, but a maintenance issue for the repo.

**Comment by shellscape** [comment]
@benmccann I _think_ this has been resolved. Can you confirm?
