### ISSUE TITLE
commonjs patch a default which breaks enumeration code

### ISSUE THREAD

**Issue by chengcyber** [rollup/plugins#683]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 17.0.0
- Rollup Version: 2.30.0
- Operating System (or Browser): MacOS
- Node Version: 12
- Link to reproduction _(⚠️ read below)_: https://repl.it/@chengcyber/rollup-repro-1#rollup.config.js

### Expected Behavior

```
Object.defineProperty(all$1, 'default', { value: all });
```

not enumerable just like `__esModule`.

### Actual Behavior

```
// main.js
import * all from './all';
console.log(Object.keys(all));

// all.js
Object.defineProperty(exports, '__esModule', { value: true });
exports.A = 'a';
```

is compiled to

```
var all$1 = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.assign(/*#__PURE__*/Object.create(null), all, {
    'default': all,
    A: A
}));

console.log(Object.keys(all$1));
```

`all$1` logout `default` and A, expecting only A

**Comment by Mater1996** [comment]
this cause @ant-design/icons error
