### ISSUE TITLE
[node-resolve] corrupts project source files on Windows

### ISSUE THREAD

**Issue by fantaclaus** [rollup/plugins#689]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 11.0.0
- Rollup Version: 2.34.1
- Operating System (or Browser): Win7, Win10
- Node Version: 12.18.3, 14.15.0
- Link to reproduction: https://github.com/fantaclaus/rollup-node-resolve-bug

### Expected Behavior

Rollup creates the 'out' folder and places there the compiled files: main.js and lib.js

### Actual Behavior

No 'out' folder is created. Instead, the source files get changed (surprise! :astonished: ).

For example, the file 'src/main.js' starts with the following line now:

```js
import { f1 } from '../../../D:/rollup-node-resolve-bug/src/lib.js';
```

It is supposed that the project is located in `D:\rollup-node-resolve-bug` folder.

### Additional Information

This issue arises when someone uses such file manage as Total Commander and tries to run Rollup scripts from it. By default this file manager launches external programs while setting the working directory with a drive letter in lower case.

As I understand, the source of the bug is the fact that `fs.realpath.native` function on Windows platform isn't consistent with other path-manipulation functions such as `fs.realpath`, `path.resolve` etc. It always returns the drive-letter in the upper case while the others use the same case as `process.cwd()`.

The function `fs.realpath.native` is used in the package `resolve`, which is used by 'plugin-node-resolve'.

**Comment by shellscape** [comment]
`fs.realpath.native` is the standard way to do this. I'm not sure we're open to a change for an edge case like TotalCommander launching scripts and munging the drive letter. You might consider reporting that issue to them as well.

**Comment by fantaclaus** [comment]
@shellscape Well, in the case of Total Commander we can manage it somehow of course... But it could be someone else who will stumble on this inconsistency in a more compicated build process and the source of the problem is not obvious at all. Even in this relatively simple case our team has wasted a whole working day to find the cause of the build failure.

In my opinion this is a serious bug because it leads to the corruption of all source files of the project and all source files of all imported dependencies! (or maybe it's Rollup itself who should take care of protecting the source files from overwriting?)

Anyway, Node resolves module names in the case-insensitive way on Windows. Including the drive-letter. Shouldn't node-resolve plugin work the same way?

Eventually, why use `fs.realpath.native`? Why not use `fs.realpath` or `path.resolve` instead? They work as expected.

**Comment by shellscape** [comment]
@tjenkinson @danielgindi your takes on this?

**Comment by danielgindi** [comment]
Actually, `realpath.native` is a weird function that really does not comply with other node functions. It does not keep original casing of the drive letter.
But one could argue that a drive letter on windows is always upper-case so the behavior is correct.

But there's another issue with it, and that's the fact that Windows works on a case-insensitive FS.
This means that if you do `realpath.native("c:\\windoWS")` you'll get back `"C:\\Windows"`.
And this will break any cache or lookup against paths that come from the code.
This will not happen on linux- when using a case-sensitive fs.

I think we should consider to either switch to the internal `realpath`, or combine the two in order to resolve + normalize.

**Comment by bahkostya** [comment]
I am experiencing the same issue, I also opened a related issue in `rollup` https://github.com/rollup/rollup/issues/4118. Could you please take a look at this?
