### ISSUE TITLE
auto-install yarn tests

### ISSUE THREAD

**Issue by shellscape** [rollup/plugins#69]
- Rollup Plugin Name: auto-install
- Rollup Plugin Version: latest

### Expected Behavior / Situation

I'd really enjoy it if the tests passed consistently. I frequently have to rerun the Circle CI workflows because of failed `yarn` tests. 

### Actual Behavior / Situation

☝️ same same

### Modification Proposal

I'd like to nuke the yarn test that is failing intermittently. If someone can spot a way to get it working 100% of the time, I'm all for it. 

Thoughts?

/cc @rollup/plugin-contributors @rollup/plugin-maintainers

**Comment by Andarist** [comment]
While mocking is often not the right answer it seems that it might be here. We don't actually care how yarn (or any other package manager) installs stuff (what artifacts does it leave behind) - we could only check if it has been invoked correctly and trust it to do its job fine when invoked for real.

**Comment by shellscape** [comment]
That's very apt, and sounds like the right way to go.
