### ISSUE TITLE
node-resolve plugin slows build from 0.7sec to 1.2 sec

### ISSUE THREAD

**Issue by xtracoder** [rollup/plugins#696]
- Rollup Plugin Name: plugin-node-resolve
- Rollup Plugin Version: 11.0.0
- Rollup Version: 2.34.1
- Operating System (or Browser): windows
- Node Version: 14
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
node-resolve plugin does no cause significant slow-down

### Actual Behavior
enabling 'node-resolve' slows build from 0.7sec to 1.2 sec
(output is 8k lines)

### Additional Information
My library actually does not use any of installed node_modules - therefore I expect zero-performance footprint when enabling "node-resolve" plugin.

I've debugged the build - slowness comes from the resolveId(). After adding this check ...
```
    async resolveId(importee, importer, opts) {
    if( importee[0] === '.' || importee.indexOf(':') !== -1 )
        return null;
```
... performance goes to normal. I expect the check is really missing because imports starting from './' or '..' are not from 'node_modules' (unless importer is from node_modules), the same is about 'absolute' paths (contains ':' on windows or starts with '/' on *nix).

Can this be fixed?

I do not have easy steps to reproduce the measurable performance issue - I need to generate plenty of files for that. However I think use-case is clear just from the description.

---- **Added some time later:**
 
Demo project to reproduce the problem:
https://github.com/xtracoder/node-resolve-slowness-demo

npm run noNodeResolve --> 420ms
npm run withNodeResolve --> 700ms = 66% slower

**Comment by shellscape** [comment]
We're happy to accept pull requests that improve performance. Node resolution is not limited to `node_modules` and is a complex operation with an insane number of edge cases that have to be accounted for. If you're not using node-flavor resolution and you're not using `node_modules` then you shouldn't need the package. At this time I can't really consider this a bug.

**Comment by xtracoder** [comment]
Yes, I've disabled that plugin for now, but it means for me that if I need at least one 'node' dependency some time later - it will cost me 70% slower build performance (now - 0.5s + base 0.7s). I expect I'll get 10-times more files at the end of development - in absolute numbers delay from node-resolve may go to ~5-sec ...

PS: I do not think I'll be able to resolve this issue absolute correctly by myself :)

**Comment by lukastaegert** [comment]
I guess it would also be worth having a deeper look at the plugin what is causing the actual slowness. Because previously, node-resolve was actually making builds *faster* because it had efficient caching for directory lookups that vanilla Rollup lacks. So maybe the new logic should be checked if there are places where we need to reintroduce some caching.

**Comment by xtracoder** [comment]
I've added link to demo project to reproduce the issue into the end of first message.

https://github.com/xtracoder/node-resolve-slowness-demo
npm run noNodeResolve --> 420ms
npm run withNodeResolve --> 700ms = 66% slower
