### ISSUE TITLE
Incremental build not working

### ISSUE THREAD

**Issue by cdalexndr** [rollup/plugins#698]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.0.0
- Rollup Version: 2.34.2
- Operating System (or Browser): Win10
- Node Version: v10.16.0
- Link to reproduction _(⚠️ read below)_: https://github.com/cdalexndr/rollup-plugin-issue-698

### Expected Behavior
Compilation successfull.

### Actual Behavior
`Error: @rollup/plugin-typescript: Rollup 'dir' option must be used when Typescript compiler options 'tsBuildInfoFile' or 'incremental' are specified.`

### Additional Information
I have a working build configuration that outputs bundles.

When I add `incremental` to my `tsconfig.json`, the build fails with:
`Error: @rollup/plugin-typescript: Rollup 'dir' option must be used when Typescript compiler options 'tsBuildInfoFile' or 'incremental' are specified.`

If I add `dir: ".rollup.dir"` to my `rollup.config.js`, then build fails with another error:
`Error: You must set either "output.file" for a single-file build or "output.dir" when generating multiple chunks.`

Isn't incremental build supported? I expected this feature to be plug and play.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by cdalexndr** [comment]
Added test repo in original post.

**Comment by shellscape** [comment]
Thanks.

@NotWoods @benmccann please have a peek. https://github.com/rollup/plugins/pull/535 added support for this, but I'm not really able to give the user direction based on the tests that were added for incremental builds.

**Comment by benmccann** [comment]
It looks like `incremental` is only supported with `dir` and not `file`

@cdalexndr I probably won't have a chance to look at this, but I imagine the fix for this would be very similar to https://github.com/rollup/plugins/pull/687 where multiple outputs were supported only with `dir` and not `file`. If you want to take a stab at it I'd be happy to help review

**Comment by shellscape** [comment]
@cdalexndr could you try the following to verify if things work:

- modify the typescript plugin's source in node_modules to comment out that check
- add `dir` to rollup options, leaving `file` in there

I'm curious if Rollup will throw an error or if it succeeds.

**Comment by sbrunov** [comment]
Dear Andrew Powell (@shellscape),

I have just tried running Rollup with both `dir` and `file` properties specified for one of my projects.  
Please, note that I have not modified the TypeScript Rollup plugin source code.

A Rollup build fails with the following error message:

> [!] Error: You must set either "output.file" for a single-file build or "output.dir" when generating multiple chunks.
> Error: You must set either "output.file" for a single-file build or "output.dir" when generating multiple chunks.
> ```
> Error: You must set either "output.file" for a single-file build or "output.dir" when generating multiple chunks.
>     at error (/current-project/node_modules/rollup/dist/shared/rollup.js:5275:30)
>     at getDir (/current-project/node_modules/rollup/dist/shared/rollup.js:19950:16)
>     at normalizeOutputOptions (/current-project/node_modules/rollup/dist/shared/rollup.js:19784:14)
>     at getOutputOptions (/current-project/node_modules/rollup/dist/shared/rollup.js:20147:12)
>     at getOutputOptionsAndPluginDriver (/current-project/node_modules/rollup/dist/shared/rollup.js:20142:12)
>     at handleGenerateWrite (/current-project/node_modules/rollup/dist/shared/rollup.js:20119:74)
>     at write (/current-project/node_modules/rollup/dist/shared/rollup.js:20087:20)
>     at Array.map (<anonymous>)
>     at build (/current-project/node_modules/rollup/dist/bin/rollup:1497:37)
>     at runRollup (/current-project/node_modules/rollup/dist/bin/rollup:1649:21)
> ```
> npm ERR! code 1

P.S. Having the incremental build support (the feature requested by this GitHub issue) would be great!

Best regards,  
Sergey Brunov.

**Comment by MelvinWM** [comment]
@shellscape Could it make sense to re-open this issue, given that it still seems to be relevant (and that #859 has not been completed or merged)?

**Comment by shellscape** [comment]
Yeah, bot isn't supposed to close issues that have a PR.
