### ISSUE TITLE
jsx: `preserve` does not compile

### ISSUE THREAD

**Issue by zanona** [rollup/plugins#72]
Hi,
I'm trying to compile `.tsx` preserving the JSX output but have a problem whenever using `jsx: 'preserve'`. It only works when using `jsx: 'react'` but it's not the output I'm looking for.
Any ideas or workarounds or am I missing something?

Thanks

<details>
<summary><b>rollup.config.json</b></summary>

```js
import typescript from 'rollup-plugin-typescript';

export default {
	output: {name: 'foo', format: 'iife'},
	plugins: [
		typescript({
			jsx: 'preserve',
			target: 'esnext',
			lib: ['es5', 'es6', 'dom']
		})
	]
};
```

</details>

<details>
<summary><b>main.tsx</b></summary>

```tsx
export default <span>Yo!</span>
```
</details>

```bash
rollup -c -- main.tsx
```

```bash
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
lib/scripts/main.tsx (1:15)
1: export default <span>Yo!</span>
                  ^
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

**Comment by shellscape** [comment]
@zanona pleas try the solution posted by @bhabgs. Happy to reopen if that doesn't fit the bill.

**Comment by zanona** [comment]
Hi, @shellscape. Unfortunately I am not using babel.

**Comment by lukastaegert** [comment]
You do not need a Babel plugin, you an acorn plugin, namely 'acorn-jsx'. This will make Rollup's parser acorn handle JSX tokens.

See https://rollupjs.org/guide/en/#acorninjectplugins which exactly describes your use-case.

**Comment by zanona** [comment]
Thanks @lukastaegert.
I just tested and it worked pretty well. Thanks.
Considering this, would it be sensible to say that the `preserve` option on this plugin would only work when using it the way you suggested? It may be worth documenting it perhaps?

**Comment by lukastaegert** [comment]
Definitely worth a docs update as it may help others with a similar use-case, PR welcome!

**Comment by MartijnHols** [comment]
Is Acorn a last step of this plugin or a part of Rollup? I think it's the latter, so then shouldn't this only be necessary if you want to preserve JSX in the final output, but not if you want another plugin (e.g. babel) to compile it instead? The [current text](https://github.com/rollup/plugins/tree/master/packages/typescript#preserving-jsx-output) seems to suggest it's always required when `jsx` is set to `preserve`, while all I'm trying to achieve is have the raw JSX run through babel macros, then convert it to regular JS.

**Comment by Greasen** [comment]
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
packages/virtual-list/src/virtual-list.tsx

还是会有这样的情况发生，这是为什么？

**Comment by Greasen** [comment]
> [!] 错误：意外的令牌（请注意，您需要插件才能导入不是 JavaScript 的文件） packages/virtual-list/src/virtual-list.tsx
> 
> 还是会有这种情况发生，这是为什么？

已解决：
import jsx from 'acorn-jsx';

acornInjectPlugins: [jsx()],
