### ISSUE TITLE
[node-resolve] entry points fallback being ignored

### ISSUE THREAD

**Issue by intrnl** [rollup/plugins#721]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 11.0.0
- Rollup Version: 2.33.3
- Operating System (or Browser): Linux (Arch Linux 5.9.12-zen1-1-zen)
- Node Version: v15.3.0
- Link to reproduction: [Repl.it playground][4]

According to [Node.js documentations][1], you are able to use arrays of files to use as entrypoint, sort of as a fallback mechanism.

```json
{
  "exports": {
    ".": ["./dist/file1.js", "./dist/file2.js"]
  }
}
```

### Expected Behavior

The plugin is able to parse the array of entries

### Actual Behavior

The array is being ignored

### Additional Information

I believe Webpack 5 has an undocumented feature where it supports conditional exports inside the array, is this worth implementing or should it just be ignored since it's not official?

Example of packages using it is: [escalade][2] and [is-core-module][3]

[1]: https://nodejs.org/api/packages.html#packages_exports
[2]: https://github.com/lukeed/escalade/blob/2477005062cdbd8407afc90d3f48f4930354252b/package.json#L17-L20
[3]: https://github.com/inspect-js/is-core-module/blob/51aca38cdf05e8d6264e28dc7af7a483270e18ae/package.json#L8-L10
[4]: https://repl.it/@intrnl/rollup-plugin-repro-node-resolve-1#input.js

**Comment by shellscape** [comment]
Please do search before opening new issues 😄  #693

**Comment by intrnl** [comment]
Ahahaha, sorry, was only looking at the issues and not the pull requests :see_no_evil:
