### ISSUE TITLE
Repo: Run CI against all sub-packages for global changes

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#722]
### Expected Behavior / Situation

If a package is bumped in `package.json` it should rerun the tests and linting for all packages

### Actual Behavior / Situation

I think the linting at least only runs for packages that are changed. I'm not sure if this is true of the tests as well

### Modification Proposal

The easiest way to fix this would be to just always run all the tests and lint all the code. It would take longer, but CI minutes are free on public repos and it wouldn't slow down development since users can still test and lint an individual package.

**Comment by shellscape** [comment]
Quick add: We're able to run all of the tests in parallel locally on most machines. Once we crossed the 20th plugin or thereabouts, Circle CI (and Github Actions) started running out of memory and the builds would fail. For repo-level changes, we likely need a serial run of all tests and linting, and holy crap that's not going to be quick.

**Comment by benmccann** [comment]
Is there a reason to have both Circle CI and Github Actions vs for example consolidating on Github Actions?

**Comment by shellscape** [comment]
it sure if ts a good reason per se, but I prefer Circle. using actions is just a stop gap since circle's windows builds aren't free

**Comment by lukastaegert** [comment]
The latter is actually no longer true, which is why I lately started investigating into this: https://circleci.com/pricing/

**Comment by shellscape** [comment]
That's great news. Given the parity, I'm now interested in comparing the two solutions. I'm partial to Circle, but we should look into this. For what it's worth, the memory issues for running "all the things" in parallel on CI were shared by both Github Actions and Circle. Let's deep dive this.

**Comment by shellscape** [comment]
FWIW I'm planning on ditching Circle CI for this repo in the near future. Github Actions have really matured to a nice place.
