### ISSUE TITLE
commonjs/node-resolve does not expand all require, yielding invalid outputs

### ISSUE THREAD

**Issue by jacogr** [rollup/plugins#724]
- Rollup Plugin Name: commonjs/node-resolve 
- Rollup Plugin Version: 17.0.0/11.0.0
- Rollup Version: 2.34.2
- Operating System (or Browser): Mac OS 10.15.2
- Node Version: v15.3.0
- Link to reproduction _(⚠️ read below)_: https://github.com/jacogr/test-rollup-memoizee

### Expected Behavior

I would expect the memoizee requires to be correctly expanded.

### Actual Behavior

The memoizee statements are short-circuited, resulting in undefined outputs, not intended by the library code.

### Additional Information

The linked repo has the full config, the built output and also explains in the README where the discrepancies are seen.

**Comment by Venjy** [comment]
I meet the same issue. The code meaning be changed by rollup.
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/54059831/158092565-86bbb26b-2c92-4b7d-8252-e29265b3cd5f.png">
