### ISSUE TITLE
node-resolve cannot resolve exports entry

### ISSUE THREAD

**Issue by FredKSchott** [rollup/plugins#727]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 11.0.0
- Rollup Version: latest
- Operating System (or Browser): Mac
- Node Version: v12.18.3
- Link to reproduction: see below

### Reproduction

```
// script.mjs
import {rollup} from 'rollup';
import cjsPlugin from '@rollup/plugin-commonjs';
import resolvePlugin from '@rollup/plugin-node-resolve';
rollup({
    input: {
        'bundle.js': 'input.js',
    },
    plugins: [
        resolvePlugin(),
        cjsPlugin(), 
    ],
});

// input.js
import _extends from '@babel/runtime/helpers/esm/extends';

// @babel/runtime/package.json ("exports" field contains entry for "./helpers/esm/extends")
https://unpkg.com/browse/@babel/runtime@7.12.5/package.json
```

### Expected Behavior

`@babel/runtime/helpers/esm/extends` resolves correctly, based on [package "exports" map](https://unpkg.com/browse/@babel/runtime@7.12.5/package.json).

### Actual Behavior

```
(node:60458) UnhandledPromiseRejectionWarning: Error: Could not load /Users/fks/Code/snowpack/node_modules/@babel/runtime/helpers/esm/extends (imported by input.js): ENOENT: no such file or directory, open '/Users/fks/Code/snowpack/node_modules/@babel/runtime/helpers/esm/extends'
```

### Additional Information

I can reproduce in both CJS & ESM mode for Node. I know that https://github.com/rollup/plugins/issues/684 exists but I think this is a different issue, since in this case the export map is actually correct, and both the import and export map entry are extensionless.

**Comment by TrySound** [comment]
This is fixed here https://github.com/rollup/plugins/pull/675 but not released yet

**Comment by shellscape** [comment]
_(@FredKSchott note that's not a valid reproduction, and we hold everyone to providing one that matches an option from the template)_

**Comment by FredKSchott** [comment]
Thank you! Looking forward to that fix getting released. Feel free to close this if it's already being tracked elsewhere. 

@shellscape apologies! it was late at night and I was rushing to wrap up and head to bed :)

**Comment by dimfeld** [comment]
Confirmed upgrading the node-resolve plugin to 11.0.1 works. Thanks!

**Comment by shellscape** [comment]
Whoops, meant to comment. Closing citing the latest version working.
