### ISSUE TITLE
[plugin-replace] The docs are confusing

### ISSUE THREAD

**Issue by PierBover** [rollup/plugins#737]
- Rollup Plugin Name: plugin-replace
- Rollup Plugin Version: ^2.3.4

Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [x] Not Sure?

### Please Explain in Detail...

The docs of `plugin-replace` state that it's possible to directly use primitives as values. This gives the false impression that primitives values will be injected as is which is wrong.

This is the example given in the docs:

```
    replace({
      __buildEnv__: 'production',
      __buildDate__: () => new Date(),
      __buildVersion: 15
    })
```

In this case `__buildEnv__` will not be replaced by the string `production` in the bundled code as the docs seem to imply. What will actually happen is that the bundled code will be looking for a `production` variable.

To inject primitive strings either `'"production"'` (with two pairs of quotes) or `JSON.stringify('production')` should be used.

After that the docs state that `For complex values, use JSON.stringify.` which is also confusing as non-complex values do need to be *stringified* too.

### Your Proposal for Changes

Not sure if this is the result of a change in the plugin itself or the docs have been always like this.

I can do a PR with changes to the docs to make this abundantly clear and prevent future confusion.

**Comment by shellscape** [comment]
This is webpack's equivalent to our `replace` plugin: https://webpack.js.org/plugins/define-plugin/#usage. Does that description make more sense for you?

**Comment by PierBover** [comment]
Yeah I think Webpack's explanation is more clear. This bit in particular:

> Note that because the plugin does a direct text replacement, the value given to it must include actual quotes inside of the string itself. Typically, this is done either with alternate quotes, such as '"production"', or by using JSON.stringify('production').

**Comment by shellscape** [comment]
@PierBover check out #785 and let me know if you think that covers it.

**Comment by PierBover** [comment]
Thanks @shellscape this is a lot better. I will close this issue.
