### ISSUE TITLE
Plugin Request: Kotlin

### ISSUE THREAD

**Issue by Richienb** [rollup/plugins#738]
Request Checklist:

- [x] I have searched https://npmjs.com/ before opening this issue
- [x] I have searched https://github.com/rollup/awesome before opening this issue

### New Plugin Use Case

Useful for using Kotlin and to some extent, Java in Javascript.

For my use case, there is a Kotlin library that doesn't have a Javascript implementation so by compiling it, I am able to use it.

Here's how it could work:

```ts
import {sum} from "./index.kt"

console.log(sum(1, 2))
```

```kt
@JsName("sum")
public fun sum(a: Int, b: Int): Int {
    return a + b
}
```

### New Plugin Proposal

Kotlin **already** provides an official [transpilation API on npm](https://www.npmjs.com/package/@jetbrains/kotlinc-js-api) and [helper library](https://www.npmjs.com/package/kotlin), we just need to use it. 

With that said, here's a working bootleg plugin:

```js
import {compile as compileKotlin} from "@jetbrains/kotlinc-js-api"
import path from "path"
import tempy from "tempy"

export default () => ({
	name: "kotlin",
	async resolveId(id, importer) {
		if (!id.endsWith(".kt")) {
			return
		}

		if (!path.isAbsolute(id)) {
			id = path.resolve(path.dirname(importer), id)
		}

		const outputFile = tempy.file({extension: "js"})
		console.log(outputFile)
		await compileKotlin({
			output: outputFile,
			sources: [id],
			sourceMaps: true,
			moduleKind: "commonjs"
		})

		return outputFile
	}
})
```

**Comment by shellscape** [comment]
This might make a great community plugin for the niche that wants this transpilation, but I can't see there being a high enough demand for this to be in this repo.

**Comment by shellscape** [comment]
Given that this hasn't garnered any community interest, we're going to close this one. Please feel completely free to pursue this on your own. Plugins like `sucrase` might be a good starting point. Our [Discord server](https://is.gd/rollup_chat) also has a `#plugin-development` channel that you might find some support in.
