### ISSUE TITLE
Add only option to external 

### ISSUE THREAD

**Issue by NE-SmallTown** [rollup/plugins#74]
- Rollup Plugin Name:  node-resolve
- Rollup Plugin Version: 6.0.0

### Feature Use Case
Transfer from https://github.com/rollup/rollup-plugin-node-resolve/issues/245

### Feature Proposal
Transfer from https://github.com/rollup/rollup-plugin-node-resolve/issues/245

**Comment by shellscape** [comment]
I've begun work on this as part of a larger refactor. The `only` option will be renamed to `resolveOnly` and will mark non-matching dependencies as external as mentioned in https://github.com/rollup/rollup-plugin-node-resolve/issues/245#issuecomment-555889646

**Comment by shellscape** [comment]
@NE-SmallTown I'm going to need a reproduction from you in order to know if I've fixed this successfully. Please choose one of the options for providing a reproduction below:

>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/, or
