### ISSUE TITLE
commonjs: support complex extensions like .js.something

### ISSUE THREAD

**Issue by milahu** [rollup/plugins#740]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 17.0.0

### Feature Use Case

i have input files named `some-name.js.snap` and i want to select them by their full extension `.js.snap`

### Feature Proposal

probably change `packages/commonjs/src/index.js`

```js
      const extName = extname(id);
      if (
        extName !== '.cjs' &&
        id !== DYNAMIC_PACKAGES_ID &&
        !id.startsWith(DYNAMIC_JSON_PREFIX) &&
        (!filter(id) || !extensions.includes(extName))
      ) {
        return null;
      }
```

like

```js
const extMatcher = new RegExp(
  '('+extensions.map(
    e => e.replace(/([.*+?^$()\[\]\\])/g, '\\$1') // escape for regex
  ).join('|')+')$', 'i');
if (extMatcher.test(id)) { .... }
```

**Comment by shellscape** [comment]
In the Node realm, you'd need a custom loader to handle these. In the webpack realm you'd need a custom loader as well. The case is going to be the same here. We've got a bunch of examples of those types of plugins here: https://github.com/rollup/awesome#other-file-imports, and I'd encourage you to attempt a small plugin which enables you to import those files with that extension. Unfortunately this isn't something we'll be adding to the commonjs plugin, as that's outside of its scope.
