### ISSUE TITLE
node-resolve handling of conditional exports with array value

### ISSUE THREAD

**Issue by yyx990803** [rollup/plugins#741]
- Rollup Plugin Name: `@rollup/plugin-node-resolve`
- Rollup Plugin Version: 11.0.1
- Rollup Version: 2.35.1
- Operating System (or Browser): macOS
- Node Version: v15.4.0
- Link to reproduction _(⚠️ read below)_: https://repl.it/@yyx990803/rollup-plugin-repro

### Expected Behavior

Should resolve imports/requires to `terser`

### Actual Behavior

Fails to resolve `terser` (externalized)

### Additional Information

Terser uses a rather complicated conditional `exports` field, with the `.` field having an Array value that has nested objects and strings:

```json
{
  "exports": {
    ".": [
      {
        "import": "./main.js",
        "require": "./dist/bundle.min.js"
      },
      "./dist/bundle.min.js"
    ],
    "./package": "./package.json",
    "./package.json": "./package.json"
  },
}
```

Node proper is able to resolve this format correctly.

**Comment by LarsDenBakker** [comment]
This is fixed on master, bht not yet released :)

**Comment by eemeli** [comment]
I hit this same issue, as `make-plural` uses the same exports form. IIRC, this was required to support Node.js 13.1 and 13.2.
