### ISSUE TITLE
Browser field is not resolved properly for local files

### ISSUE THREAD

**Issue by volkanunsal** [rollup/plugins#744]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 11.0.1
- Rollup Version: 2.34.2
- Operating System (or Browser): Mac
- Node Version: 12.x
- Link to reproduction _(⚠️ read below)_:

https://github.com/volkanunsal/test-case-browser

### Expected Behavior

One of the dependencies of the repo linked to above, i.e. `shortid`, contains a `"browser"` field that looks like the following:

```json
"browser": {
    "./lib/random/random-byte.js": "./lib/random/random-byte-browser.js",
    "./lib/util/cluster-worker-id.js": "./lib/util/cluster-worker-id-browser.js"
},
```

We expect the imports for files on the left to resolve to the files on the right.

### Actual Behavior

The files are not resolved to the correct paths for the browser.

When you install and build the repo above, you will notice that `bundle.js` contains `crypto` library as an external. This library is imported in `random-byte.js`. That's how we can tell that the file resolution is not correct.

**Comment by BlackGlory** [comment]
Why is this issue closed?

**Comment by tuul-wq** [comment]
@volkanunsal did you manage to solve this issue by yourself?

**Comment by volkanunsal** [comment]
I probably used a different id generator like nanoid. The details are hazy right now.
