### ISSUE TITLE
Files with \0 in the name are always rejected from createFilter

### ISSUE THREAD

**Issue by AlexVipond** [rollup/plugins#749]
- Rollup Plugin Name: pluginutils (specifically `createFilter`)
- Rollup Plugin Version: 4.1.0
- Rollup Version: 2.35.1
- Operating System (or Browser): MacOS
- Node Version: 15.x.x
- Link to reproduction _(⚠️ read below)_: https://repl.it/@AlexVipond/createFilter-virtual-rejection

### Expected Behavior

`createFilter` shouldn't care if `\0` is in the file ID, and it shouldn't care if the file is virtual or not (virtual files are conventionally prefixed with `\0virtual:`)

### Actual Behavior

`createFilter` rejects files with `\0` in the ID (e.g. virtual files) outright:
https://github.com/rollup/plugins/blob/0e4f0142a9c44074ae8a5df86f9442b119a9978c/packages/pluginutils/src/createFilter.ts#L48

### Additional Information

The particular use case I have right now is:
1. Taking an SVG icon as an input, construct a virtual file whose code is a single file Vue component wrapping the SVG code.
2. Use rollup-plugin-vue to compile the virtual component file down to a plain JS render function for the browser.

Since rollup-plugin-vue uses `createFilter` under the hood, virtual files are rejected outright, and the component is not properly processed at build time.

**Comment by shellscape** [comment]
There's historical context here, and to get it you have to blame-dive the old repo: https://github.com/rollup/rollup-pluginutils/commit/00a1afb8d7c2c59073ca7e9610e57404786030aa

@Rich-Harris added this with intent 5 years ago, so changing this would definitely be a breaking change. I'm not sure what side effects allowing this to be circumvented would have on the ecosystem. Perhaps Rich can chime in with more context on his change way back when.

**Comment by lukastaegert** [comment]
Why do you want to start your virtual file with `\0`? The intention of the `\0` convention is NOT to mark virtual files, because who cares if a file does not have a disk represents, it is to mark files that should be ignored by all other plugins. If this is a plugin not under your
control that emits that file, then it should probably be an issue for that plugin, but not for the createFilter function.

**Comment by AlexVipond** [comment]
@lukastaegert Thanks, that's helpful! I think I was confused because the official `@rollup/plugin-virtual` always adds the prefix, with no option to disable, so I assumed the intention of `\0` was for all virtual/in-memory code. I can PR an option to disable the prefix in the official plugin if that sounds valuable to you?

Or if anyone else runs into this issue, I updated [my own virtual modules plugin](https://www.npmjs.com/package/@baleada/rollup-plugin-virtual) not to prefix by default, with an option to add the prefix if ignoring the virtual code is desired.

**Comment by lukastaegert** [comment]
I think that makes sense. As a mental model, use the "Babel" test: If the user adds the Babel plugin, do you think the user would expect to process your virtual file with Babel before parsing it? If yes, then do not prefix with `\0`.

**Comment by ericmorand** [comment]
@lukastaegert 

> If yes, then do not prefix with \0.

That's exactly the point: we did not prefix the name with `\0`. The virtual plugin did it without our consent which is the reason this issue was opened.
