### ISSUE TITLE
[alias] Support array of string as replacement value

### ISSUE THREAD

**Issue by akphi** [rollup/plugins#754]
- Rollup Plugin Name:  @rollup/plugin-alias
- Rollup Plugin Version: 3.1.1

### Feature Use Case
Currently, the `alias` plugin only support string value for the replacement, not an array. This behavior is different from how other tools (like [jest](https://github.com/facebook/jest/issues/8461), [typescript](https://www.typescriptlang.org/docs/handbook/module-resolution.html), [webpack](https://github.com/webpack/webpack/issues/6817)) handle aliases.

### Feature Proposal
Could we support something like this:

```js
...
plugins: [
    alias({
      // standard config
      entries: [
        { find: 'utils', replacement: ['../../../utils', '../../../utils2'] },
      ]
     // object format
     entries: {
       utils: ['../../../utils', '../../../utils2'],
     }
   })
]
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Unfortunately I'm not entirely sure what you're asking for, or what case you're trying to make for a new feature. You might consider rephrasing the text of the issue and making a use case explanation. (Note that mirroring how other libs do something is not typically a good use case)

**Comment by akphi** [comment]
@shellscape Thanks for the quick response.

So let's say I'm trying to be able to create an alias for more than 2 code locations.

For example, I have my utilities in 2 folders `utils` and `utils2`. I want it so that when I type

```js
import { getSomething } from 'utils/GeneralUtil';
```

`rollup` knows to look for the `GeneralUtil` file in 2 places `utils` and `utils2`. I'm asking for this because this can be done in Typescript like this:

```js
// tsconfig.json
compilerOptions: {
  paths: {
    "utils/*": ['../../../utils/*', '../../../utils2/*']
  }
}
```

**Comment by shellscape** [comment]
I see. What you're really looking for isn't a simple alias, you're actually looking for a change in module resolution - that's the job of plugins like node-resolve. I'd suggest taking a look at https://github.com/bitshiftza/rollup-plugin-ts-paths that might help, or any of the module resolution third party plugins on the awesome repo https://github.com/rollup/awesome#modules. 

It's probably also worth saying that this is the first time we've seen this request, and with that it's not likely to gain much traction. A custom plugin to suit this need is probably going to be the way to go for you.

**Comment by akphi** [comment]
@shellscape even that plugin mentions this in its limitation, but I get the idea. I'll close this now. Thank you so much!

For folks who struggle with the same issue and could not find a workaround, take a look at [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver) if you're using `babel`.

**Comment by Madd0g** [comment]
hey, I'm sorry to bring this closed issue to life, I'm also interested in the same thing, I'm guessing this is not possible to achieve with the `customResolver` feature?

I want to find the first folder that has a file - is that not something the `customResolver` can do?
