### ISSUE TITLE
(plugin-html) add external files

### ISSUE THREAD

**Issue by asins** [rollup/plugins#755]
- Rollup Plugin Name: plugin-html
- Rollup Plugin Version: 0.2.0

### Feature Use Case

I hope the generated HTML has the ability to reference external files, just like the `externals` function in [rollup-plugin-template-html](https://github.com/byterotate/rollup-plugin-template-html).

### Feature Proposal

```js
function htmlTemplate(externals) {
  return ({ attributes, files, meta, publicPath, title }) => {
    let scripts = [...(files.js || [])];
    let links = [...(files.css || [])];

    // externals = [{ type: 'js', file: '//xxxx1.js', pos: 'before' }, { type: 'css', file: '//xxxx1.css' }]
    if(Array.isArray(externals)) {
      const beforeLinks = [];
      const beforeScripts = [];
      externals.forEach((node) => {
        let fileList;
        const isCssFile = node.type === 'css';
        if (node.pos === 'before') {
          fileList = isCssFile ? beforeLinks : beforeScripts;
        } else {
          fileList = isCssFile ? links : scripts;
        }
        fileList.push({fileName: node.file});
      });
      scripts = beforeScripts.concat(scripts);
      links = beforeLinks.concat(links);
    }

    scripts = scripts.map(({ fileName }) => {
      const attrs = makeHtmlAttributes(attributes.script);
      return `<script src="${publicPath}${fileName}"${attrs}></script>`;
    }).join('\n');

    links = links.map(({ fileName }) => {
      const attrs = makeHtmlAttributes(attributes.link);
      return `<link href="${publicPath}${fileName}" rel="stylesheet"${attrs}>`;
    }).join('\n');

    const metas = meta
      .map((input) => {
        const attrs = makeHtmlAttributes(input);
        return `<meta${attrs}>`;
      })
      .join('\n');

    return `
  <!doctype html>
  <html${makeHtmlAttributes(attributes.html)}>
    <head>
      ${metas}
      <title>${title}</title>
      ${links}
    </head>
    <body>
      ${scripts}
    </body>
  </html>`;
  };
}

function makeHtmlAttributes(attributes) {
  if (!attributes) {
    return '';
  }

  const keys = Object.keys(attributes);
  // eslint-disable-next-line no-param-reassign
  return keys.reduce((result, key) => (result += ` ${key}="${attributes[key]}"`), '');
}
```

when using it:
```js
import html from '@rollup/plugin-html';
import postcss from 'rollup-plugin-postcss';

export default [{
  input: [ 'demo/demo.ts' ],
  output: [ { file: 'dist/demo.js' } ],
  plugins: [
    postcss({
      extract: 'demo.css',
      minimize: false,
      use: ['sass'],
      extensions: ['.scss', '.css'],
    }),
    html({
      title: 'sdk demo page',
      publicPath: './',
      fileName: 'demo.html',
      attributes: { html: {lang: 'zh-cn'} },
      template: htmlTemplate([
        { type: 'js', file: 'sdk.js', pos: 'before' },
        { type: 'css', file: 'sdk.css', pos: 'before' }
      ]),
    }),
  ],
}];
```

The above implementation is based on the `template` construct exposed by the plugin, but I hope that such a functional plugin itself can support it.

**Comment by shellscape** [comment]
Thanks for opening an issue and providing that code for other users. Unfortunately this isn't something that we'll be adding in the near term. Your example code shows our original intent of empowering users with the `template` option to make their output exact what they need, rather than trying to meet the expectations of every user with additional options. Demand isn't there, and there is the third party plugin that you referenced for folks that want different functionality.

What I would suggest is opening a PR and adding a `recipes/external-files` directory to the plugin in `packages/html` with this code and supporting files that show how it's intended to be used. We'd gladly welcome that kind of addition.

**Comment by asins** [comment]
When I wrote this function, I also realized that you probably do not want to expand the function. Sending out this issue is more for friends in need to use it directly.

Let me try the way you mentioned adding external methods to html plugins.

**Comment by pablote** [comment]
This seems like a very basic feature to not be included out of the box, looking at the README, I originally thought the `attributes` prop was meant for this.

`Your example code shows our original intent of empowering users with the template option to make their output exact what they need`

I don't think having a lot of projects with slightly different template functions is the best idea. That's great for very edgy requirements, but this doesn't seem to be it. I'd personally like to keep using the default template, if I "fork" it within my project, I stop getting updates on it, if there's some security fix, or maybe a new feature being added to it.

`Demand isn't there, and there is the third party plugin that you referenced for folks that want different functionality.`

Yea, but this is the one on the curated list of rollup official plugins. The first one users will see, and expect to work. Third party plugins tend to be outdated or not very well maintained.

Just my 2c, thanks.

**Comment by shellscape** [comment]
@pablote appreciate the detailed response. Do note you're the first one in six months to lend support to this. While it may seem an obvious need to you, the community it seems does not support that, evidenced by the low level of interest.

@asins thanks for your original work on this. Going to close this as not enough interest to support the feature, and we've got a good recipe thanks to your work.
