### ISSUE TITLE
typescript plugin still references rollup-pluginutils

### ISSUE THREAD

**Issue by LukasHechenberger** [rollup/plugins#76]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 2.0.0
- Rollup Version: 1.27.8
- Operating System (or Browser): macOS
- Node Version: 12.13.1

### How Do We Reproduce?

- Install the typescript plugin `npm i --save-dev @rollup/plugin-typescript typescript tslib`
- Add it to _rollup.config.js_
- Run  `rollup -c`

### Expected Behavior

It should work ;) 

### Actual Behavior

```
> rollup -cw

[!] Error: Cannot find module 'rollup-pluginutils'
Require stack:
- /Users/lukas/Documents/Bachmann/atscm/transformer-help/node_modules/@rollup/plugin-typescript/dist/index.js
- /Users/lukas/Documents/Bachmann/atscm/transformer-help/rollup.config.js
- /Users/lukas/Documents/Bachmann/atscm/transformer-help/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'rollup-pluginutils'
```

### Reason

The problem is, that [_index.js_ still imports 'rollup-pluginutils' instead of '@rollup/pluginutils'](https://github.com/rollup/plugins/blob/126c4e374b9123ef7dcab57a3b375082e26a3e4e/packages/typescript/src/index.js#L4).

### Workaround 

Install rollup-pluginutils: `npm i --save-dev rollup-pluginutils`

Are you on this one or should I create a PR?

**Comment by shellscape** [comment]
A PR would be fantastic. Otherwise, I can get around to a fix for this later today.

**Comment by LukasHechenberger** [comment]
Okay, on it
