### ISSUE TITLE
Missing type declarations for @rollup/plugin-dynamic-import-vars

### ISSUE THREAD

**Issue by 6XGate** [rollup/plugins#770]
- Rollup Plugin Name:  `@rollup/plugin-dynamic-import-vars`
- Rollup Plugin Version: `1.1.1`
- Rollup Version: `2.36.1`
- Operating System (or Browser): _Ubuntu 20.04_
- Node Version: `12.19.0`
- Link to reproduction _(⚠️ read below)_: [Repl.it example](https://repl.it/@sixxgate/bugs-rollup-plugin-dynamic-import-vars-no-dts#src/rollup.ts}

### Expected Behavior

Using the `@rollup/plugin-dynamic-import-vars` would work 😅.

### Actual Behavior

Attempting to build the a TypeScript module with the rollup API and the `@rollup/plugin-dynamic-import-vars` plug-in fails due to the lack of type declarations for the plug-in.

- In the example repl run `npm run build`, it will result in a TS7016 error.
- Attempting to install type declarations using the method in the error message results in a `E404` from _NPM_.

**Comment by shellscape** [comment]
There's good reason for this - The plugin was not authored in TypeScript. See: https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars/src Some plugins in this repo weren't written in TypeScript and don't have type definitions. It's important to remember that while TypeScript is more widely used every day, it's naive to assume that every portion of an ecosystem you touch will have embraced it. The plugins within our repo are contributed by the community and we respect the choices made by the authors. In these cases, we rely on the community to help produce a good type definition file, or contribute a refactor to TypeScript.
