### ISSUE TITLE
[commonjs] requireReturnsDefault broken in IE 10

### ISSUE THREAD

**Issue by Krinkle** [rollup/plugins#773]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 17.0.0, and 15.0.0
- Rollup Version: 2.37.1, and 2.26.0
- Operating System (or Browser): IE 10
- Node Version: Node.js v10.15.2
- Link to reproduction: **<https://repl.it/@Krinkle/rollup-plugin-repro#output/bundle.js>**

### Expected Behavior

```js
const kleur = require('kleur');
kleur.yellow('abc'); // works
```

### Actual Behavior

```
Died on test #1 undefined: Object doesn't support property or method 'yellow'
```

### Additional Information

Snippet from rollup config:
```js
    nodeResolve({
      preferBuiltins: false
    }),
    commonjs({
      // This makes require() work like in Node.js, instead of wrapped in a {default:…} object.
      requireReturnsDefault: 'auto'
    }),
    babel({
      babelHelpers: 'bundled',
      babelrc: false,
      presets: [
        ['@babel/preset-env', {
          targets: {
            ie: 9
          }
        }]
      ]
    })
  ]
};

```

Snippet from rollup output: 
```js
  var kleur = /*#__PURE__*/Object.freeze({
    __proto__: null,
    'default': $
  });

  function getDefaultExportFromNamespaceIfNotNamed (n) {
  	return n && Object.prototype.hasOwnProperty.call(n, 'default') && Object.keys(n).length === 1 ? n['default'] : n;
  }

  var kleur$1 = /*@__PURE__*/getDefaultExportFromNamespaceIfNotNamed(kleur);
```

Line-by-lie walkthrough of executing parts of this on Internet Explorer 10 (Win 7, BrowserStack) 
```js
var $ = { foo: 42 };
$.foo
//> 42

var kleur = /*#__PURE__*/Object.freeze({ __proto__: null, 'default': $ });
kleur.default.foo
//> 42

Object.prototype.hasOwnProperty.call
//> function call() {  [native code] }

Object.keys
//> function keys() {  [native code] }

Object.keys(kleur);
//> __proto__, default {
//> 0 : "__proto__",
//> 1 : "default"
//> }

Object.keys(kleur).length
//> 2

**Comment by Krinkle** [comment]
In my case I was able to workaround this by using `requireReturnsDefault: preferred` instead of `requireReturnsDefault: auto`. I only use two external dependencies, and I did not actually need the specific "auto" behaviour.

Below in the source code, you can find that these two options are similar (they both seek to return `exports.default`) but the 
`preferred` option is more liberal in its implementation:

https://github.com/rollup/plugins/blob/21c51e0ea4755203baa8385c6a68cf7b1178319a/packages/commonjs/src/proxies.js#L18-L21

https://github.com/rollup/plugins/blob/f75d5a7fff89bff5f3d59cb268926337b709598a/packages/commonjs/src/helpers.js#L27-L33

**Comment by shellscape** [comment]
IE 10 is now end of life. https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-10-end-of-support#:~:text=After%20January%2014%2C%202020%2C%20IE,IE%2011%20to%20remain%20supported.

Thanks for opening the issue and for providing the workaround @Krinkle. With the workaround and information above, we're going to close this one.

**Comment by Krinkle** [comment]
@shellscape I'm aware it's end-of-life, however, it was my understanding from the nearby code that it intends to be compatible with ES3 even (not even ES5). That is why I filed the issue 🙂 .

Is browser support tested for and/or documented for this project?
