### ISSUE TITLE
[babel] Possibility to pass combinedSourcemap into plugins

### ISSUE THREAD

**Issue by KingSora** [rollup/plugins#774]
- Rollup Plugin Name: `@rollup/plugin-babel`
- Rollup Plugin Version: `5.2.2`

### Feature Use Case

My rollup pipeline looks like this:
1. typescript
2. other plugins like `node-resolve` and `commonjs`
3. babel

I'm using the babel plugin [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) to make it possible to generate coverage for my browser tests.

The resulting coverage reports aren't 100% accurate, because the `babel-plugin-istanbul` plugin relies on inline source maps.
My `typescript` build step is doing transformation and because rollup is doing its own sourcemaps management I need to pass the `combinedSourcemap` from rollup into the  `babel-plugin-istanbul` plugin so it knows how to handle the input code.

### Feature Proposal

Make it possible to pass the combinedSourcemap to babel plugins, so that plugins like `babel-plugin-istanbul` can use this information.
I guess it would be enough if the `createBabelInputPluginFactory` would get the rollup context so that you could access rollup internal stuff like the `getCombinedSourcemap()` function.

Or maybe there is a different possibility to handle my case..?

**Comment by shellscape** [comment]
Thanks for the suggestion. This sounds like a reasonable feature to add. Would you be interested in contributing a PR for this feature?

**Comment by KingSora** [comment]
@shellscape great! You can find the PR here: #784 😃
