### ISSUE TITLE
regeneratorRuntime is missed in rollup bundle

### ISSUE THREAD

**Issue by frozer** [rollup/plugins#776]
- Rollup Plugin Name: babel
- Rollup Plugin Version: 5.2.1
- Rollup Version: 2.33.3
- Operating System (or Browser): Ubuntu Linux
- Node Version: 10.16
- Link to reproduction _(⚠️ read below)_: https://github.com/frozer/rollup-typescript-babel

### Expected Behavior
Class should be instantiated without errors

#### On build stage
```
> rollup-typescript-babel@1.0.0 build /home/dim/_work/rollup-typescript-babel
> npm run build:types && npm run build:js


> rollup-typescript-babel@1.0.0 build:types /home/dim/_work/rollup-typescript-babel
> tsc --emitDeclarationOnly


> rollup-typescript-babel@1.0.0 build:js /home/dim/_work/rollup-typescript-babel
> rollup -c


./src/index.ts → dist/rollup-plugin-babel.cjs.js, dist/rollup-plugin-babel.esm.js, dist/rollup-plugin-babel.iife.js...
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
@babel/runtime/regenerator (guessing '_regeneratorRuntime')
@babel/runtime/helpers/asyncToGenerator (guessing '_asyncToGenerator')
@babel/runtime/helpers/classCallCheck (guessing '_classCallCheck')
@babel/runtime/helpers/createClass (guessing '_createClass')
created dist/rollup-plugin-babel.cjs.js, dist/rollup-plugin-babel.esm.js, dist/rollup-plugin-babel.iife.js in 866ms
```
#### Runtime stage
it returns error "ReferenceError: _regeneratorRuntime is not defined"

### Additional Information
There is a simple library class, which has sampe async/await method:
```javascript
export class SampleLibrary {
  async getPromiseLike(): Promise<string> {
    return 'done!';
  }
}
```
when I'm trying to instantiate it inside React/Angular application, I observe the error in browser console.
```javascript
import { SampleLibrary } from 'rollup-typescript-babel';
...
const sampleLibrary = new SampleLibrary();
```

**Comment by shellscape** [comment]
Closing as duplicate. Please search the issues before opening a new one..https://github.com/rollup/plugins/issues?q=is%3Aissue+regeneratorRuntime

**Comment by frozer** [comment]
Why it is duplicating? It addresses to another issue with rollup. I've used "runtime" configuration and can't find "any" working recipe to run it up.

**Comment by yushen7** [comment]
> Why it is duplicating? It addresses to another issue with rollup. I've used "runtime" configuration and can't find "any" working recipe to run it up.

maybe you should include this `regenerator-runtime` package manually in your package.json file
