### ISSUE TITLE
@rollup/plugin-commonjs exclude not work

### ISSUE THREAD

**Issue by wulunyi** [rollup/plugins#778]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version:17.0.0
- Rollup Version:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
After Set options.exclude, The exclude id  not transform with commonjs plugin

### Actual Behavior
Not work 

### Additional Information
The dependencies "@rollup/pluginutils": "^3.1.0" update 4.1.0 may be ok

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
