### ISSUE TITLE
Check types in CI for all plugins written in ts

### ISSUE THREAD

**Issue by fernandopasik** [rollup/plugins#779]
- Rollup Plugin Name: all
- Rollup Plugin Version: any

### Feature Use Case
Have early feedback in every PR that typescript types are not compromised.

### Feature Proposal
Add task `ci:check-types` to every plugin
Run that task on circle ci config

**Comment by fernandopasik** [comment]
Some projects have the task `"test:ts": "tsc types/index.d.ts test/types.ts --noEmit"` so adding it to the ones that don't have it might be a better proposal

**Comment by shellscape** [comment]
Agreed. Some plugins also aren't typescript as yet.

**Comment by fernandopasik** [comment]
Thanks for the comment. I've only added the task to the projects that are typescript.

**Comment by fernandopasik** [comment]
Looking back at the proposal, looks like `"test:ts": "tsc types/index.d.ts --noEmit"` is not doing the necessary check, because the files needed to be checked are directly the ones in `src/**/*.ts`.

I think I'm missing context on why is it necessary to publish the `types/index.d.ts` when the source is already typescript. @shellscape  Do you have more information on this?

**Comment by fernandopasik** [comment]
I managed to resolve it by checking all ts files in the `test:ts` tasks. The PR is ready for @NotWoods and @shellscape to review.
