### ISSUE TITLE
isolatedModules: true does not include imported enum definition

### ISSUE THREAD

**Issue by micmro** [rollup/plugins#790]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.1.1
- Rollup Version: 2.38.4
- Operating System (or Browser): Mac
- Node Version: 4.15.1
- Link to reproduction _(⚠️ read below)_: https://repl.it/@micmro/rollup-plugin-repro  (or [on github](https://github.com/micmro/rollup-plugin-typescript-enum-issue))

### Expected Behavior
The definition of imported enums (`INNER_ENUM` in the reporduction) should be included in the output when using Typescripts `isolatedModules: true` flag.

### Actual Behavior
Code is accessing `INNER_ENUM` [in the output](https://github.com/micmro/rollup-plugin-typescript-enum-issue/blob/main/output/index.js#L6) but it is not defined anywhere:

```js
var OUTER_ENUM;
(function (OUTER_ENUM) {
    OUTER_ENUM[OUTER_ENUM["O1"] = 1] = "O1";
    OUTER_ENUM[OUTER_ENUM["O2"] = 1] = "O2";
})(OUTER_ENUM || (OUTER_ENUM = {}));
var XXX = [INNER_ENUM.A1, INNER_ENUM.A2];

export { OUTER_ENUM, XXX };
```

**Comment by shellscape** [comment]
The TypeScript documentation mentions that exact scenario typescriptlang.org/tsconfig#isolatedModules under `Some examples of code which does not work when isolatedModules is enabled.` here - https://www.typescriptlang.org/tsconfig#references-to-const-enum-members

Unfortunately, this is a limitation of TypeScript and not this plugin.
