### ISSUE TITLE
[node-resolve] No warning about undeclared external dependencies

### ISSUE THREAD

**Issue by tristanlins** [rollup/plugins#792]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 11.1.1
- Rollup Version: 2.38.4
- Operating System (or Browser): Fedora 33
- Node Version: v14.15.3
- Link to reproduction _(⚠️ read below)_: https://repl.it/@tristanlins/rollup-plugin-repro

### Expected Behavior

If the `node-resolve` plugin is used with `resolveOnly: ['...']`, a warning should be issued for all external modules.
Unless, of course, they are [defined as externals](https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency).

### Actual Behavior

No warning is issued, as is typical for rollup.

Build with `node-resolve`:

```
input.js → output/bundle-with-node-resolve.js...
created output/bundle-with-node-resolve.js in 65ms
```

Build without `node-resolve`:

```
input.js → output/bundle.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
rxjs (imported by input.js)
created output/bundle.js in 28ms
```

### Additional Information

I find it a bit confusing that I use the `node-resolve` plugin to implicitly declare all non-resolveOnly modules as externals. Without doing it again explicitly under the [external](https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency) option. Without this explicit declaration of externals, you lose a bit of the overview of external dependencies.

**Comment by shellscape** [comment]
Thanks for the issue. So this is really more of a feature request plus documentation issue. We'd welcome a PR to help resolve this.

**Comment by meyer** [comment]
+1, I was really hoping `resolveOnly` worked this way _if an array of externals was also provided_. It would be a really potent combination imo.
