### ISSUE TITLE
Eslint plugin should work on original files

### ISSUE THREAD

**Issue by danimoh** [rollup/plugins#796]
- Rollup Plugin Name: @rollup/plugin-eslint
- Rollup Plugin Version: ^8.0.1
- Rollup Version: ^2.38.5
- Operating System (or Browser): Linux / all
- Node Version: 12.18.3
- Link to reproduction: https://repl.it/@danimoh/rollup-plugin-eslint-transform

### Expected Behavior

Eslint should lint the original typescript files.

### Actual Behavior

Eslint lints the files after being processed by other plugins.
In the example repl, eslint lints the files after they have already been transformed by the typescript plugin.

### Additional Information

Currently, the linting happens in a `transform` hook, i.e. after `load` hooks of other plugins that convert original files.
This prevents eslint from linting original files that are not javascript, like typescript via plugins like `typescript-eslint`.
Therefore, `@rollup/plugin-eslint` should give the option to already lint in a load hook itself before other load hooks.
This is however not always the desired behavior and should therefore be an option (maybe a filter that can be configured by file type?).
For example you'd want to run `.vue` single file components through the vue loader first before processing the extracted source code.

See here for the issue in the original repository: https://github.com/TrySound/rollup-plugin-eslint/issues/42

By the way there is another, maintained eslint plugin, which already solved this issue and [some others](https://github.com/robinloeffel/rollup-plugin-eslint#why-a-new-plugin): https://github.com/robinloeffel/rollup-plugin-eslint
You should consider asking @robinloeffel,  the dev of that plugin, to become a maintainer of the official plugin (which is unfortunately on a very old, unmaintained plugin).

Also see https://github.com/robinloeffel/rollup-plugin-eslint/pull/4 for the pull request fixing this issue in @robinloeffel's plugin.

**Comment by shellscape** [comment]
@danimoh if you searched open PRs you'd see that @robinloeffel already is maintainer and is recovering from covid at the moment.

**Comment by danimoh** [comment]
Thanks, great to hear that it's being actively maintained!
Hope he recovered or gets better soon.

**Comment by jnath** [comment]
i have the same probleme

**Comment by scottbedard** [comment]
Using @robinloeffel's https://github.com/robinloeffel/rollup-plugin-eslint seems to solve the issue for me. Is this first-party eslint plugin supposed to work on load like the other plugin does? Or is this third-party plugin the recommended setup for typescript projects?

**Comment by shellscape** [comment]
@scottbedard he's also the official maintainer of the plugin here as well. Plan was to migrate the third party plugin functionality to the one here, and then close up the third party plugin. He was hit with a nasty bout of covid and haven't heard much since. I can't make any conclusions, but if his original third party one is working, then I'd say use that for the time being.

Worth noting that just because there's an "official" plugin here, doesn't mean you should or need to use it. Third party plugins are what our ecosystem is based on, and we pulled a few plugins into the official repo just for maintenance purposes.
