### ISSUE TITLE
Missing type declarations for @rollup/plugin-html

### ISSUE THREAD

**Issue by flying-sheep** [rollup/plugins#801]
- Rollup Plugin Name: @rollup/plugin-html
- Rollup Plugin Version: 0.2.2

### Feature Use Case
Using it from TypeScript

### Feature Proposal
You should ship the `index.d.ts` for @rollup/plugin-html

**Comment by shellscape** [comment]
Thanks for the issue. They aren't missing, because they were never developed. If someone would like to contribute them to the project, we'll be happy to have the contribution.

**Comment by flying-sheep** [comment]
They’re right there: https://github.com/rollup/plugins/blob/287e554d57523f939c83ac9cc050e028c1fa43e9/packages/html/types/index.d.ts

**Comment by shellscape** [comment]
So your issue meant to say that they weren't included in the package. 

Wording matters 😄 Please PR an update to `package.json` when you have the opportunity.

**Comment by flying-sheep** [comment]
I don’t know what needs to be change, the path is there:

https://github.com/rollup/plugins/blob/287e554d57523f939c83ac9cc050e028c1fa43e9/packages/html/package.json#L53

**Comment by flying-sheep** [comment]
Ah got it!

**Comment by shellscape** [comment]
Versioning is done automatically when we publish. Thanks for the PR, we'll continue discussion there.
