### ISSUE TITLE
How can I use @rollup/plugin-multi-entry to compile both JS and SCSS?

### ISSUE THREAD

**Issue by andreimoment** [rollup/plugins#807]
- Rollup Plugin Name: @rollup/plugin-multi-entry
- Rollup Plugin Version: 4.0.0

Documentation Is:

- [ ] Missing
- [X] Needed
- [ ] Confusing
- [X] Not Sure?

### Please Explain in Detail...

I am currently using rollup for CSS compilation. I would like to add JS bundling to my config file. It is not clear if this is possible or how to go about it.

Please add documentation which addresses this. Is it possible? If not, what are some avenues to support the development of sass support? Thank you!

```
import scss from '@astappiev/rollup-plugin-scss'
// original is https://github.com/thgh/rollup-plugin-scss but that didn't use dart-sass

export default {
  input: 'source/css/site.scss',
  output: {
    file: 'source/stylesheets/site.js',
    format: 'esm'
  },
  plugins: [

    scss({
          // output: 'source/stylesheets/site.css',
          output: true,
          watch: 'source/css', // watches imported files recursively!!
    }),
  ],
}
```

### Your Proposal for Changes

Provide an example of supporting sass processing along with JS processing.

**Comment by shellscape** [comment]
This is really a support request hiding in a documentation issue. It's not reasonable to expect a project to document every possible use case.

We'll keep this open as a tentative documentation case for compiling two separate kinds of resources, but you should start with posting a reproduction for what you've already tried. Our `Bug` issue templates list several ways to provide reproductions; please choose one of those.

**Comment by andreimoment** [comment]
> This is really a support request hiding in a documentation issue. It's not reasonable to expect a project to document every possible use case.

I agree that it is not possible to document all possibilities.

How to support two separate kinds of resources is not obvious for me - but I need to acknowledge that my experience with configuring compilation pipelines is one of a beginner.

I do believe that SASS and JS compilation could cover a lot of use cases and could be useful for others.

Thank you for considering adding this documentation.
