### ISSUE TITLE
@rollup/plugin-node-resolve: compatibility with pnpm

### ISSUE THREAD

**Issue by mnpenner** [rollup/plugins#808]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 11.2.0
- Rollup Version: 2.39.0
- Operating System (or Browser): WSL Ubuntu 20.04
- Node Version: v14.4.0
- Link to reproduction _(⚠️ read below)_:

Using npm to install the dependencies is precisely the problem. I'd like to use [pnpm](https://pnpm.js.org/)

https://repl.it/@markp2/rollup-plugin-repro#rollup.config.js

### Expected Behavior

`mysql3` depends on `mariadb`, but when installed with `pnpm` you get a directory structure like this:

![image](https://user-images.githubusercontent.com/1112998/108461556-c6d7e880-722f-11eb-9052-d29cdeb73562.png)

i.e., it only has your direct dependencies, instead of like this: 

![image](https://user-images.githubusercontent.com/1112998/108461640-ebcc5b80-722f-11eb-8f64-6521e0b693d0.png)

(it goes on for days)

I believe this is causing node-resolve to not be able to find all the dependencies-of-dependencies:

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
parse5 (imported by parse5?commonjs-external)
mariadb (imported by mariadb?commonjs-external)
highlight.js (imported by highlight.js?commonjs-external)
parse5-htmlparser2-tree-adapter (imported by parse5-htmlparser2-tree-adapter?commonjs-external)
bl (imported by bl?commonjs-external)
log-symbols (imported by log-symbols?commonjs-external)
cli-cursor (imported by cli-cursor?commonjs-external)
cli-spinners (imported by cli-spinners?commonjs-external)
strip-ansi (imported by strip-ansi?commonjs-external)
wcwidth (imported by wcwidth?commonjs-external)
is-interactive (imported by is-interactive?commonjs-external)
fs-constants (imported by fs-constants?commonjs-external)
inherits (imported by inherits?commonjs-external)
readable-stream (imported by readable-stream?commonjs-external)
end-of-stream (imported by end-of-stream?commonjs-external)
supports-color (imported by supports-color?commonjs-external)
ansi-styles (imported by ansi-styles?commonjs-external)
emoji-regex (imported by emoji-regex?commonjs-external)
is-fullwidth-code-point (imported by is-fullwidth-code-point?commonjs-external)
```

I tried adding the custom resolver option shown in the docs:

```
            nodeResolve({
                extensions,
                preferBuiltins: true,
                skipSelf: true,
                custom: {
                    'node-resolve': {
                        isRequire: true,
                    }
                }
            }),
```

but that didn't seem to help.

Would be nice if it worked with pnpm's structure out of the box. Node itself seems to handle it just fine.

They talk about how it works [here](https://pnpm.js.org/blog/2020/05/27/flat-node-modules-is-not-the-only-way).

### Actual Behavior

Can't resolve sub-dependencies.

### Additional Information

https://stackoverflow.com/q/66271792/65387

**Comment by shellscape** [comment]
Thanks for the issue. Since we use pnpm in this repo, we're very familiar with it. We also use rollup to bundle many plugins in the repo. Both with without general issue. You've likely run into an edge case here. While unfortunate, this isn't likely to see resolution without community contribution. We'll welcome PRs if node-resolve can be improved to address this edge case.
