### ISSUE TITLE
@rollup/plugin-replace failing since 2.4.0

### ISSUE THREAD

**Issue by diego-antonelli** [rollup/plugins#811]
- Rollup Plugin Name:@rollup/plugin-replace
- Rollup Plugin Version: 2.4.0
- Rollup Version: 2.39.0
- Operating System (or Browser): Windows & Linux
- Node Version: 14
- Link to reproduction _(⚠️ read below)_: https://github.com/mendix/widgets-resources/pull/469/checks?check_run_id=1952183540

### Expected Behavior
Pass builds without throw error

### Actual Behavior
Throwing the following error: Error: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.

Even adding `preventAssignment` it throws the error and rollup aborts the builds.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
