### ISSUE TITLE
Interop issue with @rollup/plugin-commonjs: module with __esModule marker shouldn't be wrapped up as a default export

### ISSUE THREAD

**Issue by dgoldstein0** [rollup/plugins#817]
- Rollup Plugin Name:  @rollup/plugin-commonjs
- Rollup Plugin Version: 17.1.0
- Rollup Version: 2.38.4
- Operating System (or Browser): Linux
- Node Version: all (repo is in 12.x, but I've also see this in 14.10)
- Link to reproduction: https://repl.it/join/ayalqcmk-dgoldstein0

### Expected Behavior
 reselect @3.0.1 is a dual-format module where the commonjs has been downleveled from the ES code.  There's an __esModule marker so I expect that the exports of the final rolluped module will match those found as `exports.<X>` in the CJS.

### Actual Behavior

For some reason @rollup/plugin-commonjs doesn't recognize the __esModule and bails out to wrap the module in {default: ...} via _commonjsHelpers.createCommonjsModule and _commonjsHelpers.getDefaultExportFromCjs

**Comment by dgoldstein0** [comment]
I'm also seeing a similar issue on react-day-picker@7.4.8

**Comment by lukastaegert** [comment]
This is an issue with your usage of Rollup. You are setting `exports: named` in the output for a module that has a default export. This creates a commonjs module where the exports are an object with the default property. Setting `exports: default` or `exports: auto` fixes the issue. https://rollupjs.org/guide/en/#outputexports

I am currently working on improving the documentation here and also how this option behaves when you are bundling commonjs to commonjs.

**Comment by dgoldstein0** [comment]
Wow, that seems to have explained a lot of the problems!

The docs definitely make it sound like exports: named is the way to go when using @rollup/plugin-commonjs.  I still don't totally understand the differences.  Doesn't help that I get the MIXED_EXPORTS warning with exports: auto which recommends exports: named to shut up the warning, but switching is clearly the wrong answer.

It's also worth noting that these cases worked with an earlier version of @rollup/plugin-commonjs with output.exports: named.  So these felt like regressions from upgrading.  Anyhow I hope better docs can prevent confusion for future users.
