### ISSUE TITLE
deep imports not deduped

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/plugins#82]
- Rollup Plugin Name: `@rollup/plugin-node-resolve`
- Rollup Plugin Version: 6.0.0
- Rollup Version: 1.27.13
- Operating System (or Browser): macOS Sierra
- Node Version: 10.16.0

### How Do We Reproduce?

- Create a package called `foo` with two files:

`shallow.js`:
```js
console.log('shallow.js');
```
`deep/deep.js`:
```js
console.log('deep/deep.js');
```

- Create a package called `bar`, with a dependency on `foo` 1.0.0
- Create a package called `buz`, with a dependency on `foo` 2.0.0
- Create a main export for both `bar` and `buz` with this content:

```js
import * from 'foo/root.js';
import * from 'foo/deep/deep.js';
```

- Create a project which depends on `bar` and `buz`
- Create an `app.js` file:

```js
import 'bar';
import 'buz';
```

- Create a rollup config:

```js
import resolve from '@rollup/plugin-node-resolve';

export default {
  input: 'app.js',
  output: {
    dir: 'output',
  },
  plugins: [resolve({
    dedupe: ['foo']
  })]
};
```

### Expected Behavior
Both `shallow.js` and `foo/deep/deep.js` are deduplicated.

### Actual Behavior
Only `shallow.js` is deduplicated. This is because the `dedupe` option of `rollup-plugin-node-resolve` uses a literal match to find out whether an import should be deduplicated (imported from root): https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/index.js#L168

I don't think this intentional behavior, people would expect deduplication to happen on a package level. 

A fix can be to look at the package name, which is guaranteed to be either the first part of an import path, or the first two is the first part is a scope starting with `@`. I can work on a PR if that's the intended solution.

**Comment by shellscape** [comment]
@LarsDenBakker please fill out the appropriate issue template. This is not optional and something we ask of everyone.

**Comment by LarsDenBakker** [comment]
Although I think the original writeup explained the issue more easily, I've updated the issue with the template now.
