### ISSUE TITLE
[node-resolve] allow disabling "module" export condition

### ISSUE THREAD

**Issue by mildsunrise** [rollup/plugins#821]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 11.2

### Expected Behavior / Situation

There should be a way to make node-resolve behave exactly like Node.js would.

### Actual Behavior / Situation

There's a `"module"` condition that cannot be disabled (because `"exportConditions" only adds to the base conditions). I found the [reason](https://github.com/rollup/plugins/pull/540#discussion_r480309505) for that extra condition, and I understand it's useful to have bundler-specific exports, but there should be a way to opt out.

### Modification Proposal

A `disableModule` option (or similar) that removes "module" from `baseConditions`.

Together with `"exportConditions: ["node"]` and `mainFields: ["main"]` this would load the same file as Node, if I'm correct.

**Comment by mildsunrise** [comment]
Maybe it would be more consistent to let `disableModule` remove `module` from both baseConditions and mainFields.

**Comment by guybedford** [comment]
Agreed this would be useful. `disableModule` as removing both sounds like a good way to allow compatibility to me. `mainFields` can still be overridden so it just changes the mainFields default. Would you be interested in creating a PR?

**Comment by albertodiazdorado** [comment]
Hey, this is a rather big issue, ain't it? Can we please reopen it at least?

**Comment by guybedford** [comment]
@shellscape what about "good first issue" or "seeking contributors" labels?

**Comment by shellscape** [comment]
Great ways for issues to collect dust for years on end. When we moved to the monorepo here, we cleaned up issues that were 3+ years old with those labels. They don't really work. The bot's message is pretty clear and concise, but I'm up for expanding it if you'd like to. And I think the info linked to from the bot's repo itself explains eloquently why we close issues as stale (https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea). If you think that more time is deserved for someone to pick an issue up, I think we're all open to suggestion.
