### ISSUE TITLE
plugin-typescript crashes rollup (while parsing irrelevant files)

### ISSUE THREAD

**Issue by kungfooman** [rollup/plugins#824]
I have a monorepo with lots of different sources/projects and decided to switch from parcel to rollup. However I can't get rollup working without crashing, because it inspects EVERY file in my project before doing anything.

- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.2.0
- Rollup Version: 2.39.1
- Operating System (or Browser): Windows 10
- Node Version: v15.0.1
- Link to reproduction: irrelevant

### Expected Behavior

I created a simple target which includes a `test.ts` which literally just contains one statement for testing/debugging this bug: 

```js
console.log("wow");
```

Either rollup or typescript decides to parse EVERY `*.ts` file in my project and then will crash due a bug in TypeScript itself (see screenshot).

### Actual Behavior

Rollup instructs typescript to parse non-included files and crashes along the way.

### Additional Information

![image](https://user-images.githubusercontent.com/5236548/109633530-7a9e7980-7b48-11eb-8dc3-4d43189f83fa.png)

Is there any way to make rollup NOT crash when a plugin throws an error? Or better, only load extra TypeScript files which are actually relevant based on import statements (to reduce time as well)?

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by kungfooman** [comment]
Thanks for the information @shellscape 

I will just stick to Parcel, because it works 👍

**Comment by shellscape** [comment]
willfully choosing to ignore warning messages in the issue template, and choosing to mark critical information as irrelevant, is unfortunately upon you. following up that willful decision with an unfortunately rude comment is not something that we will come here. in the future if you would like to follow the instructions in our templates, we will be more than happy to help you in any way possible.
