### ISSUE TITLE
[commonjs] Could not resolve some export from aws-sdk - Export is defined with "__esModule"

### ISSUE THREAD

**Issue by knuspertante** [rollup/plugins#827]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: ^17.1.0
- Rollup Version: ^2.40.0
- Operating System (or Browser): MACOS
- Node Version: 14.16.0
- Link to reproduction: https://github.com/knuspertante/open-wc-amplify

### Expected Behavior
Rollup should resolve the named export automatically. 

### Actual Behavior
Rolloup cant resolve some exports in aws-sdk

<img width="413" alt="Bildschirmfoto 2021-03-05 um 10 17 00" src="https://user-images.githubusercontent.com/32802753/110094630-520ebd80-7d9c-11eb-9ab2-e6c82a25b502.png">

<img width="467" alt="Bildschirmfoto 2021-03-05 um 10 17 06" src="https://user-images.githubusercontent.com/32802753/110094635-533fea80-7d9c-11eb-8aed-623a53ae78d8.png">

<img width="930" alt="Bildschirmfoto 2021-03-05 um 10 17 12" src="https://user-images.githubusercontent.com/32802753/110094637-53d88100-7d9c-11eb-9345-568dd223edbb.png">

These exports are necessary:
https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/stencil.config.ts

Probably related to: 
- https://github.com/rollup/plugins/issues/481
- https://github.com/rollup/plugins/pull/816
- https://github.com/rollup/plugins/issues/757
- https://github.com/rollup/plugins/pull/414

**Comment by knuspertante** [comment]
For bot: error still exists...

**Comment by knuspertante** [comment]
Issue still needs to be fixed! #827

**Comment by shellscape** [comment]
@knuspertante if you'd like to open PR, we'll reopen this issue. Otherwise it will remain closed until someone else does.

**Comment by knuspertante** [comment]
@shellscape thanks for this hint.

Unfortunately I'm unable to fix this by myself, otherwise I would open a PR. 

If all issues that have been inactive for the past 60 days are closed, how are they ever fixed?

For me it's ok, because now I use esbuild or webpack for this project. I opened this issue to help all others. 

best regards
