### ISSUE TITLE
node-resolve doesn't import dependencies

### ISSUE THREAD

**Issue by mlbonniec** [rollup/plugins#828]
- Rollup Version: 2.40.0
- Operating System (or Browser): macOS 11.2
- Node Version (if applicable): 14.15.5
- Link to reproduction (IMPORTANT, read below): https://github.com/mlbonniec/MMM-NiceHash/tree/9dcd674b9e3192165bb156b7fa9dc14e6a2587d2

### Expected Behavior

Hi, I'm trying to compile my TypeScript files into JS, but the problem is that nodeResolve doesn't seem to work properly. For example, when I use axios, in my build, axios is not defined, yet at the beginning of my file it says "require('axios')". Yet it is "undefined" in all my file. Do you have an idea of the problem?

### Actual Behavior

The compiled files use dependencies that are "undefined". However, no errors during compilation.

Here's my actual `rollup.config.js` file.

```js
import typescript from '@rollup/plugin-typescript';
import commonJS from '@rollup/plugin-commonjs';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { dependencies } from './package.json';

const deps = Object.keys(dependencies);
export default [
  {
    input: './src/MMM-NiceHash.ts',
    plugins: [
      nodeResolve(),
      typescript(),
      commonJS(),
    ],
    external: [...deps],
    output: {
      file: './MMM-NiceHash.js',
      format: 'umd',
      globals: {
        axios: 'axios',
        uuid: 'uuid',
      },
    },
  },
  {
    input: './src/node_helper.ts',
    plugins: [
      nodeResolve(),
      typescript(),
      commonJS(),
    ],
    external: ['node_helper', 'crypto', ...deps],
    output: {
      file: './node_helper.js',
      format: 'umd',
      globals: {
        axios: 'axios',
        uuid: 'uuid',
        crypto: 'crypto',
      },
    },
  },
];
```

**Comment by shellscape** [comment]
@mlbonniec thanks for the issue. Unfortunately your repository given doesn't match our needs or definition for a _minimal reproduction._

>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/

Please update your reproduction or we'll have to decline to triage your issue.

**Comment by mlbonniec** [comment]
@shellscape thank you for your response, I think it would be too complicated to have to create a repo. You can simply clone my repository, install the dependencies (`npm i`) and do `npm run build`.
Once, we can see in the build file `MMM-NiceHash.js` that the `iife` is required at the last line, the variable `axios`, which is undefined in my browser. How do I get the axios code included in my file?
<img width="278" alt="Capture d’écran 2021-03-05 à 19 16 21" src="https://user-images.githubusercontent.com/29955402/110156592-75128f00-7de7-11eb-86da-09642a51983e.png">

**Comment by shellscape** [comment]
Unfortunately this isn't a forum for support. If you're sure this is a bug and unwilling to provide a valid reproduction, we'll have to close. If you'd like to add a reproduction we consider valid, we'll be happy to reopen your issue.

**Comment by mlbonniec** [comment]
Sorry 😬 
So, here is a reproduction of my bug. [https://repl.it/join/wegwtgdf-mlbonniec](https://repl.it/join/wegwtgdf-mlbonniec)
You can see that in the MMM-NiceHash.js, there is a `require('axios')`, however, `axios` isn't defined in my browser 🤔

**Comment by shellscape** [comment]
Thank you

**Comment by mlbonniec** [comment]
I tried a lot of things, here is my config file. The problem is that there are still 4 `import` left...
I don't know what to do. My repro is still here [repl.it/join/wegwtgdf-mlbonniec](repl.it/join/wegwtgdf-mlbonniec)
```js
// rollup.config.js
import typescript from '@rollup/plugin-typescript';
import common from '@rollup/plugin-commonjs';
import { nodeResolve }  from '@rollup/plugin-node-resolve';
import json from '@rollup/plugin-json';
import polyfills from 'rollup-plugin-node-polyfills';

export default [
  {
    input: './MMM-NiceHash.ts',
    plugins: [
      polyfills(),
      json(),
      common(),
      nodeResolve(),
      typescript(),
    ],
    output: {
      file: './MMM-NiceHash.js',
      format: 'iife',
      globals: {
        axios: 'axios'
      },
    },
  }
];
```

**Comment by prathamVaidya** [comment]
Hey @mlbonniec, I am experiencing a similar issue with Axios. Node.js core libraries, such as util, https, etc. are being imported into the final build. Have you had any luck finding a solution?
