### ISSUE TITLE
Dealing with node_module dependencies that are typescript files. Getting Error: Unexpected token

### ISSUE THREAD

**Issue by mike-hogan** [rollup/plugins#832]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.2.0
- Rollup Version: 2.41.0
- Operating System: Mac OS X 10.15.7
- Node Version: v14.15.
- Link to reproduction _(⚠️ read below)_: https://github.com/mike-hogan/rollup-ts-deps

### Expected Behavior
The `.ts` files in `node_modules/@http4t` are compiled

### Actual Behavior
```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/@http4t/core/requests.ts (5:30)
3: import {Authority, Uri, UriLike} from "./uri";
4: 
5: export function request(method: Method, uri: UriLike, body?: HttpBody, ...headers: Header[]): HttpRequest {
                                 ^
6:   return {
7:     method,
```

### Additional Information

Also posted as this [stackoverflow questions](https://stackoverflow.com/questions/66567284/rollup-dealing-with-dependencies-that-are-typescript-files-getting-error-unex)

**Comment by frederikhors** [comment]
Same here! @mike-hogan did you fix this?

**Comment by mike-hogan** [comment]
No @frederikhors , haven't a scooby how to fix this.

**Comment by pesor** [comment]
I just made a complete reinstall of Windows 10, and a clean install of VSCode, only including PlatformIO, I cannot read mapped networkdrives, which I could a week ago. 

What has changed. 

I hane not rollup installed, so it cannot be that.

**Comment by mike-hogan** [comment]
Comments by @frederikhors on #842 helped me understand how to fix this.  Its not an issue with the plugin, I basically need a tsconfig.json file that includes the src directory in `node_modules`.  Answer detailed more fully in the [stackoverflow question](https://stackoverflow.com/questions/66567284/rollup-dealing-with-dependencies-that-are-typescript-files-getting-error-unex)

**Comment by davidje13** [comment]
I found this issue while trying to get `workspaces` to work (i.e. a monorepo). In this situation, a sibling folder is symlinked into `node_modules`.

For future visitors, the way to make it work is to set an explicit [`filterRoot`](https://github.com/rollup/plugins/tree/master/packages/typescript#filterroot) in the `typescript` plugin options (it defaults to `'.'`):

```js
plugins: [
  nodeResolve(),
  typescript({ filterRoot: '..' }),
]
```

With that, and the requirement noted above of having a `tsconfig.json` file which includes the files (doesn't have to be the same tsconfig), it works fine.
