### ISSUE TITLE
How does @rollup/plugin-typescript generate .d.ts

### ISSUE THREAD

**Issue by zhyafe** [rollup/plugins#833]
How does @rollup/plugin-typescript generate .d.ts

**Comment by zhyafe** [comment]
{"declaration": true  }  did not generate .d.ts file. Did I configure it incorrectly? Or did not support the generation of d.ts?

**Comment by shellscape** [comment]
>   👉🏽 Need help or tech support? Please don't open an issue!
>   Head to https://is.gd/rollup_chat or https://stackoverflow.com/questions/tagged/rollupjs

**Comment by zhyafe** [comment]
Okay, thank you

**Comment by MingweiSamuel** [comment]
Your mistake was that you phrased the title as a question, you should've said "@rollup/plugin-typescript doesn't generate .d.ts"
