### ISSUE TITLE
Why default options of TypeScript plugin does not generate declaration files?

### ISSUE THREAD

**Issue by lyne408** [rollup/plugins#836]
I've add `"declaration": true, "declarationDir": "./types"` to `tsconfig.json`, but no work.

**tsconfig.json**
```json
{
  "compilerOptions": {
    "module": "ES2015",
    "moduleResolution": "Classic",
    "target": "ES2015",
    "resolveJsonModule": false,
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": false,
    "outDir": "./dist",
    "removeComments": true,
    "sourceMap": false,
    "strict": true,
    "declaration": true,
    "declarationDir": "./types"
  },
  "include": [
    "./src/**/*"
  ]
}
```
**rollup.config.js**
```js
import typescript from '@rollup/plugin-typescript'
import pkg from './package.json'

export default {
    input: 'src/index.ts',
    plugins: [typescript()],
    output: [
        {format: 'cjs', file: pkg.main, exports: 'auto'}
    ]
}
```

**Comment by lyne408** [comment]
Like `Spring`, config first.
Not design like `Spring Boot`, not like `webpack + ts-loader`, not `STARTER` first.

**Comment by leepowelldev** [comment]
What did you do to resolve this issue? I can't get declaration files being output like yourself.

**Comment by frederikhors** [comment]
Same here, any news?

**Comment by shellscape** [comment]
@frederikhors if there were updates, you would see them here. please refrain from me too replies for this repo as well as they create unnecessary noise. you'll find that many repositories on GitHub frown upon replies asking for updates.

**Comment by frederikhors** [comment]
@shellscape can you please answer us on this instead of reminding us of the obvious?

Many people have asked the same thing both here and in other issues: there is a reason, right?

My question was for the two before me, in case they could help me solve it.

**Comment by lyne408** [comment]
> 
> 
> Same here, any news?

Need 'dir' and 'entryFileNames', like the following.
```js
import typescript from '@rollup/plugin-typescript'
export default {
    input: 'src/index.ts',
    plugins: [typescript()],
    output: {
        format: 'cjs',
        /*
        [lyne408] 
        "dir" not compatible with "file".
        */ 
        dir:'./',
        entryFileNames: 'dist/index.js'
    }
}
```
