### ISSUE TITLE
Bundling files using require with dynamic paths

### ISSUE THREAD

**Issue by limitlessloop** [rollup/plugins#839]
- Rollup Plugin Name: `@rollup/plugin-commonjs`, `@rollup/plugin-json`, `@rollup/plugin-node-resolve`, `rollup-plugin-polyfill-node`
- Rollup Plugin Version: 17.1.0, 4.1.0, 11.2.0, 0.6.2

Hi, I'm not sure exactly which plugin this relates to as I'm having trouble figuring out which plugin is causing the undesired effect.

### Expected Behavior / Situation

I'm building a module that will be used by Figma Plugin creators. Part of its functionality is that it references a config file and `package.json`. In order for it to a) work in development and production, the path needs to be dynamic, and b) it ideally needs to configurable by the plugin creator.

Below is a simplified demonstration of what I'd like to be supported.

```js
// src/index.ts

const path = process.cwd() + 'package.json'
const pkg = require(path)
console.log(pkg)
```

I would like to use rollup to bundle JSON or even JS files using a dynamic file path into one common js file so it can be used in the browser.

### Actual Behavior / Situation

I've tried to get this working by using the following plugins  `@rollup/plugin-commonjs`, `@rollup/plugin-json`, `@rollup/plugin-node-resolve`, `rollup-plugin-polyfill-node`, but something seems to be canceling each other out.

```js
// dist/index.js
//...
var path = browser$1.cwd() + 'package.json';
var pkg = require(path);
console.log(pkg);
```

I've created a repo to try and [get it working](https://github.com/limitlessloop/testing-rollup-dynamic-require) but with no luck.

### Modification Proposal

Feel free to take a look at the repo. I'm not sure if it's a bug, or a limitation, but I would love your thoughts on how I could cater for this.

**Comment by shellscape** [comment]
Thanks for the issue. This looks more like a "how does one get this working?" to me. We have a discord channel for plugin authors that you can visit here: https://is.gd/rollup_chat

**Comment by limitlessloop** [comment]
Hi @shellscape . Thanks, I appreciate this may not fall under a bug, or proposal for modification. I've already reached out to the discord community. I wanted to create an issue because I found it very difficult to explain in chat. Maybe if a solution is found it will be useful anyway to others, if a solution can't be found then I suppose it can get turned into a bug or proposal for changes.

**Comment by limitlessloop** [comment]
So, just adding an update to this. So from what I can tell, when a dynamic path is used and a `dynamicRequireTarget` is specified `@rollup/plugin-commonjs` still requires the full path to the file which will not work in the browser or similar sandboxed environments.

As you can see in this function, it returns a require.
```js
function commonjsRequire(path, originalModuleDir) {
	const resolvedPath = commonjsResolveImpl(path, originalModuleDir);
	if (resolvedPath !== null) {
		let cachedModule = DYNAMIC_REQUIRE_CACHE[resolvedPath];
		if (cachedModule) return cachedModule.exports;
		const loader = DYNAMIC_REQUIRE_LOADERS[resolvedPath];
		if (loader) {
			DYNAMIC_REQUIRE_CACHE[resolvedPath] = cachedModule = {
				id: resolvedPath,
				filename: resolvedPath,
				path: dirname(resolvedPath),
				exports: {},
				parent: DEFAULT_PARENT_MODULE,
				loaded: false,
				children: [],
				paths: [],
				require: function (path, base) {
					return commonjsRequire(path, (base === undefined || base === null) ? cachedModule.path : base);
				}
			};
			try {
				loader.call(commonjsGlobal, cachedModule, cachedModule.exports);
			} catch (error) {
				delete DYNAMIC_REQUIRE_CACHE[resolvedPath];
				throw error;
			}
			cachedModule.loaded = true;
			return cachedModule.exports;
		}
	}
	return require(path);
}
```
