### ISSUE TITLE
Let plugin-typescript import .ts files from node_modules, why not?

### ISSUE THREAD

**Issue by frederikhors** [rollup/plugins#842]
- Rollup Plugin Name: `typescript`
- Rollup Plugin Version: `8.2.0`

### Feature Use Case

I'm trying to import a `svelte-ts-component` in a `svelte-ts-project`: https://github.com/sveltejs/svelte/issues/6125.

It throws with `Error: The keyword 'interface' is reserved (Note that you need plugins to import files that are not JavaScript)`.

@dummdidumm correctly indicated that Rollup is the problem here and not Svelte.

> Rollup does not compile things inside node_modules

Sounds incredible to me, there must be a way! Even a work-around.

### Feature Proposal

Let people import .ts files from `node_modules` (please).

**Comment by frederikhors** [comment]
I think @mike-hogan had the same problem: https://github.com/rollup/plugins/issues/832, right?

**Comment by mike-hogan** [comment]
I have the same problem @frederikhors, yes.  I gave up trying to figure it out.  I think the argument is something along the lines that node module resolution is separate to ts transpilation, and tsconfig defines src directories, but I am too unskilled with JS and TS tooling to be able to follow any of the discussion.  Like an idiot, I just want it all compiled, regardless of where it is :)

**Comment by frederikhors** [comment]
> Like an idiot

I feel the same.

We are certainly wrong, it is not possible that it cannot be done.

It is not possible that if I move the files from `node_modules` to a higher directory then I can compile them otherwise no.

It is not possible.

**Comment by frederikhors** [comment]
I managed to fix this by using `include` better in my .tsconfig. Specifically put in that array your dir, @mike-hogan.

**Comment by mike-hogan** [comment]
Awesome @frederikhors.  Do you mind please sharing what your tsconfig looks like? Thanks

**Comment by frederikhors** [comment]
```
"include": ["src/**/*", "node_modules/my-component/src/**/*"]
```
