### ISSUE TITLE
Babel Helpers are being bundled mistakenly 

### ISSUE THREAD

**Issue by shoys89** [rollup/plugins#844]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.3.0
- Rollup Version: 2.41.5
- Operating System (or Browser): Chrome
- Node Version: 12.4.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@shoys89/rollup-plugin-repro  

###

### Expected Behavior
_createSuper and _isNativeReflectConstruct Helpers should not be bundled as we have those already in babel-external-helpers.js 

### Actual Behavior
Both _createSuper and _isNativeReflectConstruct are bundled even though babelHelpers is set as "external"

### Aditional Info
See when using external babel helpers some helpers like (_createSuper and _isNativeReflectConstruct) are bundled, which is not expected as we do not want any babel helper to be included.

**Comment by shellscape** [comment]
Have you seen this https://github.com/rollup/plugins/issues/805#issuecomment-779902868?

**Comment by shoys89** [comment]
@shellscape I just looked into, but still not quite sure why `_createSuper` and `_isNativeReflectConstruct` BabelHelpers are bundled, even when `babelHelpers` is set to `external`

**Comment by shoys89** [comment]
this sounds like a babel setup, I could exclude these Helpers by using Babel's `assumptions` opt which is avail since babel 7.13.x 
```       assumptions:{
          superIsCallableConstructor: true
        },
