### ISSUE TITLE
graphql plugin: ability to import fragments like queries and mutations

### ISSUE THREAD

**Issue by LydiaF** [rollup/plugins#847]
- Rollup Plugin Name: graphql
- Rollup Plugin Version: 1.0.0

### Expected Behavior / Situation
We can import queries and mutations like this: `import { BatmanQuery, JokerMutation } from './schema.graphql'`, but we cannot do the same for fragments, e.g., `import { MyFrag } from './myFrag.graphql'.

Situation: I would like to use apollo client's [writeFragment](https://www.apollographql.com/docs/react/caching/cache-interaction/#writefragment) and readFragment methods and this requires the ability to import the fragments in a named way, e.g., 

```js
client.writeFragment({
  id,
  fragment: MyFrag
  data
});
```

### Actual Behavior / Situation

It is not possible to import named fragments to javascript files.

### Modification Proposal

Make it possible to import named fragments like we can import queries and mutations :)

Thank you very much for considering!

**Comment by LydiaF** [comment]
Hello again :)

My apologies...

If we do:

```js
import graphqldoc from './myFrag.graphql'

client.writeFragment({
  id,
  fragment: graqphqldoc,
  fragmentName: 'MyFrag',
  data
});
```

Then it seems to be fine... I will close the issue when I am sure (probably later today)...

**Comment by duckbrain** [comment]
@LydiaF can you reopen this issue? You found a work-around, but the issue is still not resolved.

**Comment by LydiaF** [comment]
@duckbrain

Hey, I don't follow you.. I think the issue is resolved!
