### ISSUE TITLE
@rollup/plugin-image exclude/include options are difficult to work with

### ISSUE THREAD

**Issue by ZachHaber** [rollup/plugins#848]
- Rollup Plugin Name: plugin-image
- Rollup Plugin Version: 2.0.6
- Rollup Version: 1.32.1
- Operating System (or Browser): Windows 10
- Node Version: 14.15.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@ZachHaber/rollup-plugin-repro

Note for the link for reproducing the issue. I'm not too familiar with Rollup and this appears to be the minimal config that I needed to get it to run.

### Expected Behavior

An exclude glob of `'*.svg'` should cause all `.svg` files to be ignored by the plugin

### Actual Behavior

`'*.svg'` is turned into something like `C:/projects/test*.svg` for the glob matching by the `getMatcherString` in `@rollup/pluginutils` due to `@rollup/plugin-image` having an out of date dependency on it. (^3.1.0 vs current version of 4.1.0). The current version has a fix that would fix this behavior and allow simpler globs like `'*.svg'` to work.

In order to exclude all svg files, I have to use `'/**/*.svg'` which took an hour of debugging and working through the code in plugin-image to figure out. The hidden functionality make it very hard to exclude/include files for the image plugin.

### Additional Information

The reason why this is an issue for us is because we are using `svgr` to handle the svg files rather than plugin-image. Since we don't want the svg files to be turned into data urls as those don't work for what we are working with.

**Comment by tomfridental1** [comment]
Had the same issue just now, thank god I found your post!
