### ISSUE TITLE
`Unexpected token` when bundling TypeScript

### ISSUE THREAD

**Issue by dstaley** [rollup/plugins#849]
- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: `8.2.1`
- Rollup Version: `2.44.0`
- Operating System (or Browser): N/A
- Node Version: `12.21.0`
- Link to reproduction: https://replit.com/@dstaley/rollup-plugin-typescript-error

### Expected Behavior

Module builds correctly

### Actual Behavior

```
./test/index.ts → dist/test.js...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
test/index.ts (1:41)
1: export default function testFunction(name: string): string {
                                            ^
2:   return name;
3: }
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/runner/EnchantingHatefulFunctions-1/node_modules/rollup/dist/shared/rollup.js:5305:30)
    at Module.error (/home/runner/EnchantingHatefulFunctions-1/node_modules/rollup/dist/shared/rollup.js:9750:16)
    at Module.tryParse (/home/runner/EnchantingHatefulFunctions-1/node_modules/rollup/dist/shared/rollup.js:10156:25)
    at Module.setSource (/home/runner/EnchantingHatefulFunctions-1/node_modules/rollup/dist/shared/rollup.js:10057:24)
    at ModuleLoader.addModuleSource (/home/runner/EnchantingHatefulFunctions-1/node_modules/rollup/dist/shared/rollup.js:18396:20)
    at async ModuleLoader.fetchModule (/home/runner/EnchantingHatefulFunctions-1/node_modules/rollup/dist/shared/rollup.js:18452:9)
    at async Promise.all (index 0)
```

### Additional Information

I believe this is a continuation of #287, but since that issue was closed and marked as fixed with `8.2.1`, I thought it was appropriate to open a new issue since (at least in this case) the issue hasn't been resolved.

**Comment by ss-xiong** [comment]
Unfortunately got same problem for me, could anyone help us to solve it?

**Comment by jsejcksn** [comment]
@dstaley I continue to encounter this issue as well, and https://github.com/rollup/plugins/issues/287#issuecomment-611368317 is the only solution for my multi-input projects.

In regard to your replit example, if I do the following, it builds successfully:

1. In `rollup.config.js`:
  - Add a `name` property to the UMD bundle output
  - Remove the (unused/unnecessary) `include` property from the options argument when invoking the `typescript` plugin

  So it looks like this:
  ```js
  // Please modify this file to suit your reproduction

  // require plugins here. e.g.
  // const beep = require('@rollup/plugin-beep');

  const typescript = require("@rollup/plugin-typescript");

  module.exports = {
    input: "./src/index.ts",
    output: [
      {
        file: "dist/temp.js",
        format: "umd",
        name: 'temp'
      }
    ],
    plugins: [typescript()]
  };
  ```

2. In the console, run

```
npx rollup -c
```

Result:
```
./src/index.ts → dist/temp.js...
created dist/temp.js in 6.3s
```

**Comment by dstaley** [comment]
@jsejcksn Thanks for the tip! I managed to get some of my builds working again by removing the `include` option from the config, but I'm still getting errors when attempting to build my test files which are located outside of my root `tsconfig.json`'s `include` option. I've updated the REPL link to a new version to demonstrate this issue.

Essentially, it looks like the plugin isn't happy when the file you're importing is outside of the root `include` directory. In this case, I'm using a file from a `test` directory instead of a `src` directory. I know I could probably relocate my `test` folder, or remove the `include` option from my `tsconfig.json`, but those both feel unnecessary considering that they both go against common conventions.

**Comment by jsejcksn** [comment]
@dstaley The `include`, `exclude`, `compilerOptinos.outDir`, etc. properties in `tsconfig.json` (the ones that deal with fs structure) should not be used with the Rollup TS plugin, as they appear to have no useful effects since Rollup simply resolves all input(s) dependencies and outputs the bundle(s) based on the Rollup config values. (Correct me if I'm wrong @shellscape)

You can use multiple tsconfig files and multiple rollup config files if you need different compilation or bundle settings.

_Tip: [`npm` scripts](https://docs.npmjs.com/cli/v7/using-npm/scripts) can help reduce the console typing you need to do._

You can omit the `include` field in your `tsconfig.json` and it will build:

```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es2017",
    "outDir": "./lib/"
  }
}
```

**Comment by dstaley** [comment]
> You can omit the `include` field in your `tsconfig.json` and it will build:

True, but then I'm unable to emit declarations with `tsc -p .` since `tsc` doesn't support specifying `include` via CLI. Furthermore, configuring `include` via `tsconfig.json` is about as standard convention as you can get, and I consider it a bug in the plugin that it's unable to work properly with this value configured. I totally understand that it's not useful for Rollup, but that's even more evidence that it shouldn't outright break the plugin when used.

**Comment by jsejcksn** [comment]
I agree that the plugin should simply ignore invalid/unused fields.

There's clearly a need for better documentation about how tsconfig objects are processed by the plugin.
