### ISSUE TITLE
Circular dependency in Typescript doesn't work

### ISSUE THREAD

**Issue by gamelaster** [rollup/plugins#850]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.2.1
- Rollup Version: 2.30
- Operating System (or Browser): (Replit)
- Node Version: v12.16.2
- Link to reproduction _(⚠️ read below)_: https://replit.com/@gamelaster/rollup-typescript-circular-repro

### Expected Behavior

The decorator should print undefined, and continue (and it later usage, the reference should be correct)

### Actual Behavior

Decorator throws error, since it tries directly to use Class1 before initialization

### Additional Information

This is very simple showcase of circular dependency problem,
although, this have little back story.
I'm trying to use Sapper, together with TypeORM.
The way that TypeORM makes [one-to-one relation](https://typeorm.io/#/one-to-one-relations),
it makes a circular dependency. Although, in this case, it's correct and in app run directly by TypeScript,
it works fine. Although, when using it with rollup, same issue happening as in this REPL.

Please, let me know if this should be assigned directly to rollup (not the plugin), or if it's possible to solve it
through some rollup configuration. I invested several hours of searching for solution, although, after all
I decided to post it as bug here to this plugin.

Thanks

**Comment by shellscape** [comment]
Circular dependencies in Roll-up are generally an issue. There are quite a few issues in rollup/rollup about it.

**Comment by gamelaster** [comment]
@shellscape oh, well, then it should be better to move this issue into the rollup/rollup, or should I keep it here?

Thanks

**Comment by shellscape** [comment]
It's hard to say. if you can pre-build your TypeScript and have roll-up bundle that, then it would not be an issue with rollup. I would check that first

**Comment by lukastaegert** [comment]
It very much depends, but as a matter of fact, most circular dependency issues are rooted in CommonJS. Even though it warns about them, Rollup can handle circular dependencies in ES modules mostly well. For CommonJS, correct circular dependency handling very often also requires correct handling of inline `require` expressions, and that is where the plugin still falls short at the moment. So if you are using `require` in your circular dependencies, then this repo is very likely the right place.

**Comment by lukastaegert** [comment]
Ok, but I see there is no commonjs in your example. Then please try what @shellscape suggested: Bundle the TypeScript output without using the plugin.

**Comment by gamelaster** [comment]
@shellscape @lukastaegert Thank you guys for fast reply.

I'm not sure if I can do this. As I mention in issue upper, I use Sapper + Rollup + TypeORM (REPL script is just for simple reproduce), so TSC would not compile Svelte components (for server-side rendering). Is there another way I can try?

Once again, thank you for your time.

**Comment by gamelaster** [comment]
Also, I tried webpack configuration for Sapper, and it happens in webpack too. So maybe this issue is inside TSC? (I know that webpack have some module importing quirks and module isolation).
