### ISSUE TITLE
[!] Error: The keyword 'interface' is reserved (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by 1512751361** [rollup/plugins#851]
- Rollup Plugin Name:  @rollup/plugin-typescript
- Rollup Plugin Version:  ^8.2.1
- Rollup Version: ^2.6.1
- Operating System (or Browser): mac
- Node Version: v14.15.4
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
正常编译生成ts声明文件

### Actual Behavior
实际在编译时候报错 
![image](https://user-images.githubusercontent.com/24776858/113134129-080de000-9253-11eb-897e-8ec6fe05d09e.png)

### Additional Information
tsconfig.json 配置文件
<pre>
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "DOM",
      "ES5",
      "ES6",
      "ESNext"
    ],
    "allowJs": true,
    "checkJs": true,
    "jsx": "react",
    "noEmit": false,
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "declaration": true, // 是否自动创建类型声明文件
    "outDir": "build/ts"
  },
  "include": [
    "packages/**/*/lib/*.ts+(|x)",
    "packages/**/*/lib/**/*.ts+(|x)"
  ],
  "exclude": [
    "node_modules",
    "*.d.ts",
    "*.spec.ts"
  ]
}
</pre>

**Comment by shellscape** [comment]
Thanks for opening an issue. Unfortunately none of our maintainers can understand Chinese. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by FernandesTeu** [comment]
any solution?
