### ISSUE TITLE
[typescript] Include basic source information for diagnostic warnings

### ISSUE THREAD

**Issue by jsejcksn** [rollup/plugins#852]
- Rollup Plugin Name: `typescript`
- Rollup Plugin Version: `8.2.1`

### Expected Behavior / Situation

[Optionally] richer diagnostic warnings, including a simplified stack trace:
  - source file path
  - row number
  - column number

It seems like the idea of the current implementation is to keep the warning lines brief, but it seems cryptic since there's no way to determine the source of the warnings. This is compounded when using the JS API for many files.

### Actual Behavior / Situation

Just a string with TS error code/name. I think it's being generated here: https://github.com/rollup/plugins/blob/53776ee3fc59587fe5ff0c756216185f48372507/packages/typescript/src/diagnostics/toWarning.ts#L18

### Modification Proposal

Add plugin option to include richer diagnostic warnings.

If there's already a way to do this and I have overlooked it, please feel free to point me to the documented solution and close this issue. Thanks!

**Comment by jsejcksn** [comment]
Why was this closed without a response from a project maintainer?

@shellscape I'm mentioning you because I've seen your username often in recent issue activity. Please cc whoever is responsible for community engagement or manages the stale bot.

**Comment by shellscape** [comment]
Not to be intentionally terse, but the bot's message states exactly why it was closed as stale. There aren't any available maintainers to take up the issue, and there hasn't been any community support. We don't leave issues open indefinitely in this repo, but should an issue regain traction, we're always happen to reopen. You may be used to seeing projects leave large amounts of old issues open, but that's not how issues are managed here.

**Comment by jsejcksn** [comment]
I understand a lack of resources/interest, but when opening an issue in any OSS project, I at least expect a maintainer to respond before the issue is closed for a reason other than being a duplicate/abusive.

**Comment by shellscape** [comment]
You were given a reason other than duplicate/abusive by the bot's message. It just rubbed you the wrong way :)

>  I at least expect a maintainer to respond

This isn't a great mindset to approach OSS with, and I'd suggest a realignment of your expectations with regard to services and things that are gratis. i.e. https://liberamanifesto.com/

**Comment by jsejcksn** [comment]
> It just rubbed you the wrong way

@shellscape I don't feel that way. I think you're projecting your own perspective in that statement.

I'm just confused about why there is the ability to open an issue in this repository if the person opening it is to have no expectation that it will be read and engaged by anyone. If that's what the maintainers (or at least you) want issue openers to think, then what purpose do the issues serve? (I don't expect you to answer that by the way, based on the context of this conversation.)

**Comment by shellscape** [comment]
> I'm just confused about why there is the ability to open an issue in this repository if the person opening it is to have no expectation that it will be read and engaged by anyone.

You have an expectation, and that would indicate you're relatively new to open source.

The crux here is that walking into OSS-anything with any expectation or entitlement isn't healthy. You shouldn't even expect OSS _to work_. Read through that link I shared. It's from the early days of Open Source and it still rings true today. You have the ability to share your experience with the project and the community of folks using the project, but you have no guarantee that anyone will look at it, interact with it, triage it, or solve it. Issues aren't Zendesk, a help desk, or any other flavor of paid support service. There are projects I post issues on that don't get a reply _for years_, and that's just the way it goes. I certainly don't have any expectation that it'll get addressed, and as a good open source citizen, if I don't have time to contribute a fix, I never expect an issue to be resolved. Most of the time, I open issues and follow up on them with workarounds to help others in a community out who may arrive at the issue via Google, etc. If I have time, I open a PR. If that PR goes without any interaction, I fork and use my fork. That's how open source works. Approach it at all times without expectation and without entitlement.

**Comment by jsejcksn** [comment]
> You may be used to seeing projects leave large amounts of old issues open, but that's not how issues are managed here.

How are unresolved issues tracked in this repository?

> but should an issue regain traction, we're always happy to reopen

What is the quantitative definition of "regain traction"?

**Comment by shellscape** [comment]
> How are unresolved issues tracked in this repository?

They aren't. We're not paid for our time and with the size of the userbase generally don't have the resources to do so. That's why we have the stale bot. These bots are extremely common.

> What is the quantitative definition of "regain traction"?

Subjective per maintainer. For me; active triage in the replies or an associated Pull Request.
