### ISSUE TITLE
Must use @babel/plugin-transform-runtime even though I am using it

### ISSUE THREAD

**Issue by puchm** [rollup/plugins#854]
- Rollup Plugin Name: Babel
- Rollup Plugin Version: 5.3.0
- Rollup Version: 2.44.0
- Operating System (or Browser): Win10 18363.1379
- Node Version: 12.18.2
- Link to reproduction _(⚠️ read below)_: https://github.com/puchm/rollup-issue-demo
Sorry, it's not using the Rollup REPL - it's very minimal though since I created it from scratch. I hope this is ok.

### Expected Behavior
When `@babel/plugin-transform-runtime` is in the Babel plugins array inside `.babelrc`, the following error has no reason to appear as far as I'm concerned:
```
Error: You must use the `@babel/plugin-transform-runtime` plugin when `babelHelpers` is "runtime"
```

### Actual Behavior
The above error message appears.

### Additional Information
When making the reproduction repo I noticed that this issue pops up as soon as I add the Node resolve plugin. (`babel.config.js`, lines 17-19). When I remove those lines the error doesn't appear. Instead, it fails to resolve the import from `main.ts` to `test.ts`. 

What is the issue here?

Thanks,
-Moritz

**Comment by solarjoker** [comment]
I got the same error

**Comment by NateScarlet** [comment]
I just use

```typescript
    pluginBabel({
      extensions,
      babelHelpers: 'runtime',
      skipPreflightCheck: true,
    }),
```

then build output seems correct
