### ISSUE TITLE
Not working as an output plugin (warnings printed)

### ISSUE THREAD

**Issue by stevage** [rollup/plugins#858]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version:5.3.0
- Rollup Version:2.45.1
- Operating System (or Browser): MacOS
- Node Version:14.15.4
- Link to reproduction _(⚠️ read below)_: https://replit.com/@stevage/rollup-plugin-repro

### Expected Behavior

Able to specify babel for certain outputs but not all.

### Actual Behavior

Many warnings printed:

```
(!) The "buildStart" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "load" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "moduleParsed" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "resolveId" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "transform" hook used by the output plugin commonjs is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "load" hook used by the output plugin babel is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "options" hook used by the output plugin babel is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "resolveId" hook used by the output plugin babel is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "transform" hook used by the output plugin babel is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
```

### Additional Information

I'm actually pretty new to this stuff, so this could well be user error. However, my understanding was this was supposed to work as of v5: #360

My actual project (from which the minimal repro is derived) is [here](https://github.com/stevage/mapbox-gl-utils/blob/e0670985c0340fec96f1d52b8745c5ecd13708ae/rollup.config.js). My goal (possibly misguided) was to provided a non-babel ES5 version of the library for modern consumers, and a legacy UMD+babel version for use in script tags, and in Node (for testing with Jest).

I did note this advice:

>When using @rollup/plugin-babel with @rollup/plugin-commonjs in the same Rollup configuration, it's important to note that @rollup/plugin-commonjs must be placed before this plugin in the plugins array for the two to work together properly. e.g.

But I didn't know how to make that work in the case where `commonjs` is applied for all inputs, but `babel` is not.

**Comment by shellscape** [comment]
Please see https://www.rollupjs.org/guide/en/#using-output-plugins. Neither plugin is intended to be used as an output plugin.

**Comment by stevage** [comment]
Thank you. [This](https://github.com/rollup/rollup-plugin-babel/issues/360) was the issue I meant to link to above, and the [related PR](https://github.com/rollup/plugins/pull/108). They certainly give the impression it was meant to work.

Are you saying that it's not possible to generate two outputs from the same input, one that runs through Babel and one that doesn't?

**Comment by stevage** [comment]
I see there is a `getBabelOutputPlugin` method, which seems to behave quite differently. 

I guess ideally, the warning in the first place might say something like

```
(!) babel() is not an output plugin. You might be looking for getBabelOutputPlugin() instead. See https://github.com/rollup/plugins/tree/master/packages/babel
```

**Comment by shellscape** [comment]
Thanks for confirming. It might be worth submitting a modification request to the main rollup project (`rollup/rollup`).
