### ISSUE TITLE
dedupe leads to errors in a monorepo with hoisted dependencies

### ISSUE THREAD

**Issue by jpaquim** [rollup/plugins#86]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 6.0.0
- Rollup Version: 1.27.9
- Operating System (or Browser): macOS
- Node Version: 13.2.0

### How Do We Reproduce?

Here is a repo reproducing the issue: https://github.com/jpaquim/rollup-monorepo-issue

Steps:
- Start with a monorepo configuration using package hoisting (the default for yarn workspaces, or using lerna with hoisting enabled)
- Setup rollup and @rollup/plugin-node-resolve in one of the monorepo's packages (let us assume it's in a directory under packages/).
- Configure @rollup/plugin-node-resolve to dedupe a certain package (in my case, I was using sveltejs/template, with `dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')` or more simply `dedupe: ['svelte', 'svelte/internal']`.
- Import the given package in one of the source files
- Bundle using rollup, using as working directory the package directory, and not the monorepo root.

### Expected Behavior
The imported package should be correctly bundled with the rest of the output.

### Actual Behavior
The imported package is not resolved correctly, rollup complains: `(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
svelte/internal (imported by src/App.svelte)`

Consequently, the import statement remains in the output. In my case: `import { SvelteComponent, init, safe_not_equal, element, text, space, attr, insert, append, set_data, noop, detach } from 'svelte/internal';`

### Comments
The issue seems to be related to [this line](https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/index.js#L301), where the importee is overwritten with `join(process.cwd(), 'node_modules', importee)`.

In a monorepo context, `process.cwd()` will typically refer to the package where the rollup command is started from, but with hoisting, the relevant node_modules are actually at the root of the monorepo, thus leading to the conflict.

**Comment by shellscape** [comment]
Thanks for the issue :beer: 

This is going to be a difficult one to remedy in a monorepo. I'm afraid the setup is going to be a bit complex in order to get multiple folks working on triage. Can you provide a repo that has a reproducible setup? One with the setup you're using would be most helpful.

**Comment by jpaquim** [comment]
@shellscape sure thing, here is a repo reproducing the issue: https://github.com/jpaquim/rollup-monorepo-issue

**Comment by jpaquim** [comment]
I don't have enough context on the internals of rollup or this plugin, so this will probably be naïve, but it seems that just replacing `join(process.cwd(), 'node_modules', importee)` with `require.resolve(importee)` seems to work for this specific case, basically letting node itself resolve the importee from the parent folders recursively.

However, I'm not sure if this would actually work inside a nested package, what the behaviour of require.resolve would be in that situation...

**Comment by shellscape** [comment]
#34 is likely to affect this as well.

**Comment by LarsDenBakker** [comment]
I've created a PR for this https://github.com/rollup/plugins/pull/98

**Comment by jpaquim** [comment]
Great, thank you @LarsDenBakker and @shellscape for the great work!

**Comment by shellscape** [comment]
👍  we're still working on getting publishing smoothed out, so please have patience on that getting to NPM
