### ISSUE TITLE
Typescript plugin doesn't emit latest assets on rollup watch mode

### ISSUE THREAD

**Issue by huozhi** [rollup/plugins#860]
- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: 8.2.1
- Rollup Version: 1.32.0
- Operating System (or Browser): macos
- Node Version: 12.20.0
- Link to reproduction _(⚠️ read below)_: https://github.com/beeebox/rollup-ts-watch-issue

### Expected Behavior

expected the emitted file is matched with typescript compiled result when change entry file on rollup watch mode.

### Actual Behavior

the dist file is emitted but the code is not matched input source.

### Additional Information

I debugged a little bit into it, found that `getEmittedFile` always return the same compiled result even it re-run the bundle process. Hope this note could help.

**Comment by shellscape** [comment]
closed by #861
