### ISSUE TITLE
Proposal: support custom extension name in @rollup/plugin-yaml

### ISSUE THREAD

**Issue by yfwz100** [rollup/plugins#868]
- Rollup Plugin Name:  @rollup/plugin-yaml
- Rollup Plugin Version: 3.0.0

### Feature Use Case

In some cases, the file with different extension may be regarded as yaml docs, like custom blocks of vue-i18n, which doesn't emit files with '.y(a)ml' by default. 

### Feature Proposal

Support custom extension name in yaml plugin.

**Comment by shellscape** [comment]
That's a pretty unique edge case. The yaml plugin is pretty small, I'd recommend forking it for your use case.

**Comment by yfwz100** [comment]
Yes... the change may be small, so I propose if it's builtin the core instead of forking another plugin.

**Comment by janosh** [comment]
Considering [GH's chosen methods for making repos citable](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) requires a `citation.cff` file in YAML format, this might not be such an uncommon use case.
