### ISSUE TITLE
commonjs: `requireReturnsDefault: "preferred"` yields unstable results

### ISSUE THREAD

**Issue by thorn0** [rollup/plugins#869]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 18.0.0
- Rollup Version: 2.45.2
- Operating System (or Browser): Linux Ubuntu 20, Windows 10 x64
- Node Version: 16.0.0
- Link to reproduction: https://github.com/thorn0/rollup-commonjs-issue

### Expected Behavior

Calling Rollup multiple times with the same settings should lead to the same output.

### Actual Behavior

Only the first time the output is correct and as expected. Subsequent outputs are incorrect and different from the first one.

### Additional Information

```js
for (let i = 0; i <= 3; i++) {
  const result = await rollup({
    input: "input.js",
    plugins: [commonjs({ requireReturnsDefault: "preferred" })],
  });

  await result.write({ file: `output/result${i}.mjs` });
}
```

**First output:**
```js
var numbers = [1, 2, 3, 4, 5, 6];

console.log(numbers);

var input = {

};

export default input; 
```

**Subsequent output:**
```js
var constants = [1, 2, 3, 4, 5, 6];

var constants$1 = /*#__PURE__*/Object.freeze({
	__proto__: null,
	'default': constants
});

console.log(constants$1);

var input = {

};

export default input; 
```

**This works as expected:**
```js
const plugins = [commonjs({ requireReturnsDefault: "preferred" })];

for (let i = 0; i <= 3; i++) {
  const result = await rollup({
    input: "input.js",
    plugins,
  });

  await result.write({ file: `output/result${i}.mjs` });
}
```

**Comment by thorn0** [comment]
The reason is likely this variable shared between instances:
https://github.com/rollup/plugins/blob/a82166b3640f0e26931eaf17fcec0b9793bfa850/packages/commonjs/src/is-cjs.js#L1

**Comment by guybedford** [comment]
Thanks for spotting this bug. Would you be interested in working on a PR here?

**Comment by thorn0** [comment]
It blocks a release of a package I maintain, so potentially - yes. But it can take some time. If somebody can fix this more quickly, do it, don't wait for me. ;)
