### ISSUE TITLE
feat: error if there are still imports

### ISSUE THREAD

**Issue by appsforartists** [rollup/plugins#87]
Here is my current configuration:

```js
resolve({
  modulesOnly: true,

  // Whitelist imports to assert that we only inline things that we've
  // injected the licenses for.
  only: [
    'indefinite-observable',
    'wobble',
    'symbol-observable',
    'fast-equals',
   ],
}),
```

I'm interested in adding a check that will throw if there are still `import` statements in the resulting bundle (e.g. `exhaustive: true`). The purpose of such a check would be to require a manual intervention before adding any dependencies to a published bundle: in this case, to ensure that the correct licenses have also been included.

Would you be amenable to a patch to support this, or should I make a separate plugin?

_(migrated from https://github.com/rollup/rollup-plugin-node-resolve/issues/188)_

**Comment by appsforartists** [comment]
cc @shellscape @mecurc @larsdenbakker

**Comment by shellscape** [comment]
@appsforartists I think this would make more sense as a separate plugin. That could even allow for adding envars or some such for bypassing the check (similar to using husky/precommit and the `--no-verify` flag). It could also be handy outside of node-resolve as a diagnostics tool.

**Comment by shellscape** [comment]
Closing citing previous reply.
