### ISSUE TITLE
Importing an ES Module doesn't import the default export

### ISSUE THREAD

**Issue by jacques-blom** [rollup/plugins#872]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 18.1.0
- Rollup Version: 2.47.0
- Operating System (or Browser): MacOS 11.3 (Apple Silicon)
- Node Version: 15.10.0
- Link to reproduction: https://replit.com/@jacquesblom/rollup-commonjs-default-import

### Expected Behavior
`react-outside-click-handler` is an ES module package that is built to CJS. It sets the `__esModule` property on its exports ([see here](https://unpkg.com/browse/react-outside-click-handler@1.3.0/build/OutsideClickHandler.js#L3)).

So when I import it (`import OutsideClickHandler from "react-outside-click-handler"`) with the help of `@rollup/plugin-commonjs`, I'd expect `OutsideClickHandler` to be the module's [default export](https://unpkg.com/browse/react-outside-click-handler@1.3.0/build/OutsideClickHandler.js#L228).

My assumption is based on the behaviour mentioned in https://github.com/rollup/plugins/issues/481.

### Actual Behavior
Importing the module returns the whole namespace:

```js
import OutsideClickHandler from "react-outside-click-handler"

/*
OutsideClickHandler is...
{
  default: [Function: OutsideClickHandler] {
    propTypes: {
      children: [Function: bound checkType],
      onOutsideClick: [Function: bound checkType],
      disabled: [Function],
      useCapture: [Function],
      display: [Function],
      'prop-types-exact: ​': [Function]
    },
    defaultProps: { disabled: false, useCapture: true, display: 'block' }
  }
}
*/
```

### Additional Information
I have tried various combinations of the plugin's options but the behaviour is always the same. 

The entry point for `react-outside-click-handler` is [this file](https://unpkg.com/browse/react-outside-click-handler@1.3.0/index.js), which doesn't define `__esModule`. Is that where it's missing?

[Others have experienced this](https://github.com/vitejs/vite/issues/2139#issuecomment-806416318) with ViteJS but the packages mentioned there don't define `__esModule`.

**Comment by ZQ-jhon** [comment]
same here

**Comment by ntkoopman** [comment]
This is the same issue as the one mentioned on the Vite tracker. Because the entry point doesn't contain any hint it's a compiled ES module it gets imported as a normal CommonJS module, which doesn't have a default export. (It does work for some dependencies, like React itself, which also uses this pattern)

**Comment by jwoo0122** [comment]
Same for `react-textarea-autosize`. The package serves esm and cjs bundle, where cjs bundle is exported as `module.exports = require('...')`. So 'default export' is resolved as namespace, not actual default export.
