### ISSUE TITLE
License in README.md

### ISSUE THREAD

**Issue by soimkim** [rollup/plugins#873]
- Rollup Plugin Name: All 
- Rollup Plugin Version: -

Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
README.md says "LICENSE (Mozilla Public License)". 
However, the LICENSE file is written as MIT.

### Your Proposal for Changes
Therefore, it is necessary to modify README.md to "LICENSE (Mozilla Public License)" -> "LICENSE (MIT)".

**Comment by guybedford** [comment]
Thanks for spotting this, I've posted https://github.com/rollup/plugins/pull/874.
