### ISSUE TITLE
CommonJS proxy modules do not have `.js` extension (`preserveModules: true`)

### ISSUE THREAD

**Issue by letmaik** [rollup/plugins#875]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 18.1.0
- Rollup Version: 2.47
- Operating System (or Browser): Ubuntu
- Node Version: 15.14.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@letmaik/rollup-plugin-repro#dist/_virtual/bignumber.mjs_commonjs-proxy

### Expected Behavior

The file extension of all output files should be `.js`.

### Actual Behavior

The file extension of the CommonJS proxies is `.js_commonjs-proxy`.

### Additional Information

Not having `.js` makes life harder and requires to postprocess files or otherwise handle this outlier.

**Comment by htang014** [comment]
Hello, I am running into the same issue here.  Short of creating a hooked plugin that renames these virtual modules and all imports of them, I don't see a real workaround here.

Any reason it cant just be:
```
const PROXY_SUFFIX = '?commonjs-proxy.js';
const REQUIRE_SUFFIX = '?commonjs-require.js';
const EXTERNAL_SUFFIX = '?commonjs-external.js';
const EXPORTS_SUFFIX = '?commonjs-exports.js';
const MODULE_SUFFIX = '?commonjs-module.js';
``` 
?
