### ISSUE TITLE
CommonJS before or after Babel plugin?

### ISSUE THREAD

**Issue by ScottAgirs** [rollup/plugins#880]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [x] Not Sure?

### Please Explain in Detail...

In the plugin Docs [@rollup/plugin-babel](https://github.com/rollup/plugins/tree/master/packages/babel#using-with-rollupplugin-commonjs) it says that `commonjs()` muse be before `babel()`, however, a member @Andarist , suggests the opposite in [this comment](https://github.com/rollup/rollup-plugin-babel/issues/210#issuecomment-399259610), sooo which one is the right correct approach? : )

My personal finding shows, that @Andarist seems to be correct, but would be nice to confirm.

### Your Proposal for Changes

I'd gladly make a small contribution, by submitting a PR for this :)

**Comment by Andarist** [comment]
From what I recall - docs are correct for most use cases but there are some situations in which the opposite has to be done.

**Comment by iDVB** [comment]
Any word on this? We are also not able have `@rollup/plugin-commonjs` before `@rollup/plugin-babel` as it causes errors trying to parse the JSX (React) thats in the code. 

Putting `@rollup/plugin-babel` first seems to fix the issue and all else seems to work as expected.

**Comment by githoniel** [comment]
should we explain about JSX in the docs?
