### ISSUE TITLE
Move `rollup-plugin-postcss` plugin to here and make it official?

### ISSUE THREAD

**Issue by Flcwl** [rollup/plugins#885]
### New Plugin Use Case

https://github.com/egoist/rollup-plugin-postcss/issues/217

### New Plugin Proposal

The plugin has a lot of issues and PRs And I hope the plugin to be updated by rollup official~

**Comment by shellscape** [comment]
We'd need someone to step in here to maintain it. As is it, the current maintainers for this repo are already stretched thin.
