### ISSUE TITLE
@rollup/plugin-node-resolve does not resolve files mapped through `exports` in package.json

### ISSUE THREAD

**Issue by lxg** [rollup/plugins#886]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 9.0.0
- Rollup Version: 2.44.0
- Operating System (or Browser): Linux
- Node Version: v14.4.0
- Link to reproduction _(⚠️ read below)_: https://github.com/lxg/rollup-repro

### Expected Behavior

According to https://nodejs.org/docs/latest-v15.x/api/packages.html#packages_subpath_exports a package can specify a mapping of identifiers to files in order to be resolved as imports. This apparently does not work with `@rollup/plugin-node-resolve`.

This example uses the `@lxg/l10n` library which has such `exports`, see https://github.com/lxg/l10n/blob/master/package.json#L7-L10 one of them is the mapping of `./date` to `dist/date.mjs`. Following that, an import of `@lxg/l10n/date` in a downstream application should make this file available. But instead, the resolution fails and is treated like an external import, see https://github.com/lxg/rollup-repro/blob/master/src/demo.js#L4 and https://github.com/lxg/rollup-repro/blob/master/dist/demo.js#L1

### Actual Behavior

The `@rollup/plugin-node-resolve` plugin does not resolve paths that are specified in the `exports` directive of a `package.json` file. The import is treated as external. A warning about unresolved dependencies is emitted when building:

```
$  npx rollup -c --environment BUILD:production

src/demo.js → dist/demo.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@lxg/l10n/date (imported by src/demo.js)
created dist/demo.js in 41ms
```

**Comment by guybedford** [comment]
Thanks for posting. We do support the "exports" field but given what you describe this does sound like a bug to me. If you are interested in contributing that would be great, otherwise one of us will aim to take a stab at it soon.

**Comment by lxg** [comment]
Happy to have a look, do you have an idea where the code in question might be?

By the way, I just realized that the node-resolve package itself apparently uses the "exports" field in a wrong way:

https://github.com/rollup/plugins/blob/master/packages/node-resolve/package.json#L19-L22

**Comment by lxg** [comment]
Tried it; the weird thing is that now the main (`@lxg/l10n`) dependency is not imported. But that had worked before with v9.0.0!

 This is now the generated output:

```
import L10n from '@lxg/l10n';

class t{constructor(t){this.t=t;}getMonths(){return [this.t.x("_","January"),this.t.x("_","February"),this.t.x("_","March"),this.t.x("_","April"),this.t.x("_","May"),this.t.x("_","June"),this.t.x("_","July"),this.t.x("_","August"),this.t.x("_","September"),this.t.x("_","October"),this.t.x("_","November"),this.t.x("_","December")]}getMonthsShort(){return [this.t.x("_","Jan"),this.t.x("_","Feb"),this.t.x("_","Mar"),this.t.x("_","Apr"),this.t.x("_","May"),this.t.x("_","Jun"),this.t.x("_","Jul"),this.t.x("_","Aug"),this.t.x("_","Sep"),this.t.x("_","Oct"),this.t.x("_","Nov"),this.t.x("_","Dec")]}getWeekdays(){return [this.t.x("_","Sunday"),this.t.x("_","Monday"),this.t.x("_","Tuesday"),this.t.x("_","Wednesday"),this.t.x("_","Thursday"),this.t.x("_","Friday"),this.t.x("_","Saturday")]}getWeekdaysShort(){return [this.t.x("_","Sun"),this.t.x("_","Mon"),this.t.x("_","Tue"),this.t.x("_","Wed"),this.t.x("_","Thu"),this.t.x("_","Fri"),this.t.x("_","Sat")]}getFirstDayOfWeek(){return parseInt(this.t.x("_","1"))}shiftWeekdays(t){const s=this.getFirstDayOfWeek();return t.slice(s).concat(t.slice(0,s))}}

// THIS would technically work, but is not what we want
// import L10nDate from "@lxg/l10n/dist/date"

class Demo
{
    constructor() {
        this._l10n = new L10n({}, this.getAttribute("lang") || "en-GB");
        this.date = new t(this._l10n);
    }
}

console.log(new Demo());
```

**Comment by guybedford** [comment]
@lxg I notice you have an invalid entry in the "exports" field at https://unpkg.com/@lxg/l10n@2.0.2/package.json. It should be `"./dist/l10n" in the main entry point there not `"dist/l10n"`. Ideally we should provide a better error in this case though.

**Comment by lxg** [comment]
@guybedford Yes, you are right! Thanks for pointing it out, and apologies for not spotting it myself.

I can confirm that now everything works as expected, using @rollup/plugin-node-resolve v13.0.0.

Thank you very much for your support!
