### ISSUE TITLE
multi-entry plugin should not treeshake entries

### ISSUE THREAD

**Issue by githoniel** [rollup/plugins#891]
- Rollup Plugin Name: multi-entry
- Rollup Plugin Version:  4.0.0

### Feature Use Case

I use multi-entry to join two entry file together in my webapp.

but if one entry export nothing like below, it will be removed by treeshake 

```js
import React from 'react'
import ReactDOM from 'react-dom'

import { MyButton } from '../src'

ReactDOM.render(React.createElement(MyButton), document.querySelector('#app'))
```

### Feature Proposal

add `moduleSideEffects: 'no-treeshake'` to entry id in `resolveID`

**Comment by shellscape** [comment]
I'm really not sure what you're asking for here. `resolveID` and `moduleSideEffects` aren't options of the `multi-entry` plugin.

**Comment by githoniel** [comment]
> I'm really not sure what you're asking for here. `resolveID` and `moduleSideEffects` aren't options of the `multi-entry` plugin. 

this is a feature request. multi-entry plugin resolveID only resolve a virtual entry that reference all original entry，I think it should also resolve all original entry with moduleSideEffects: 'no-treeshake' to avoid treeshake.

maybe I can pr later
