### ISSUE TITLE
`ignoreDynamicRequires` should not leave `typeof require === 'function'` as-is

### ISSUE THREAD

**Issue by sodatea** [rollup/plugins#893]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 19.0.0
- Rollup Version: 2.50.5
- Operating System (or Browser): macOS
- Node Version: 14.17.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@sodatea/rollup-commonjs-bug-repro-1

### Expected Behavior

`typeof require === 'function'` is not a dynamic require, so it should be either replaced by `typeof commonjsRequire === 'function'` or simply `true`, even when `ignoreDynamicRequires` is enabled.

### Actual Behavior

It is left as-is.

### Additional Information

A typical UMD wrapper use `typeof module === 'object' && module.exports` to check CommonJS environments. But in some very old codebases (in this case, https://github.com/plurals/pluralize), the author might add an additional `typeof require === 'function'` check.

When `ignoreDyanmicRequires` is enabled, rollup not only ignores dynamic requires, but also the `require` in that expression. So the runtime `typeof require === 'fucntion'` check fails. Therefore, other modules can never properly import from this UMD module.

https://github.com/vitejs/vite/issues/3426 is caused by this issue.

**Comment by veikkoeeva** [comment]
Hmm, interesing. Looks similar to
```
if (typeof module === 'object') {
    module.exports = BN;
  } else {
    exports.BN = BN;
  }

``` (in https://github.com/indutny/bn.js/blob/master/lib/bn.js#L42.) I'll add this here since this seem to be a common problem for Ethersjs users (I wrote about it in SO [here](https://stackoverflow.com/questions/67754327/automating-umd-export-to-esm-import-in-rollupjs) too).
