### ISSUE TITLE
(plugin-virtual) Missing typescript definitions

### ISSUE THREAD

**Issue by impy88** [rollup/plugins#894]
(plugin-virtual) Missing typescript definitions

- Rollup Plugin Name: @rollup/plugin-virtual
- Rollup Plugin Version: 2.0.3
- Rollup Version: 2.50.5
- Operating System (or Browser): MacOS
- Node Version: 14.15.4
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior

@rollup/plugin-virtual supports typescript and has typings

### Actual Behavior

The latest version (2.0.3) has no typings

```
Could not find a declaration file for module '@rollup/plugin-virtual'. './node_modules/@rollup/plugin-virtual/dist/index.js' implicitly has an 'any' type.
```

### Additional Information

Hi, Please release a new version of @rollup/plugin-virtual with typescript support as I see migration to typescript was merged 9 months ago but never released.

**2.0.3** https://github.com/rollup/plugins/tree/virtual-v2.0.3/packages/virtual
**master**  https://github.com/rollup/plugins/tree/master/packages/virtual

Cheers,

**Comment by shellscape** [comment]
Fixed by #898

**Comment by nickrum** [comment]
Hi @shellscape, it seems like the latest version of `@rollup/plugin-virtual` is still `2.0.3` which does not include any typings. #898 did not affect the virtual plugin as the package has already been moved to typescript in #578.

**Comment by fjc0k** [comment]
+1 @shellscape 

![image](https://user-images.githubusercontent.com/13151189/133012158-3b659bf5-7c70-4254-8b45-8e039d8beca2.png)

**Comment by Finesse** [comment]
There are types for this plugin [at DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rollup__plugin-virtual), but they are outdated (require Rollup version 1).

P.S. +1 for the issue
