### ISSUE TITLE
commonjs: browser throws "does not provide an export named 'exports'" problem

### ISSUE THREAD

**Issue by BwayCer** [rollup/plugins#908]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 19.0.0
- Rollup Version: 2.52.1
- Operating System (or Browser): Chrome
- Node Version: 15.5.0
- Link to reproduction _(⚠️ read below)_: ---

### Expected Behavior

Everything works when running with @web/dev-server

### Actual Behavior

The browser will throw the following problems:
```
Uncaught (in promise) SyntaxError: The requested module '...?web-dev-server-rollup-null-byte=...%3Fcommonjs-module' 
does not provide an export named "exports"
```

### Additional Information

I don't understand the logic of rullop.
the result of my attempt seems to indicate that 
it will ignore the imported `exports` variable and replace it with `__module.exports` when packaging.

```
// a.js
import { __module as xxx, exports as yyy } from "./b.js?commonjs-module"

// b.js
var xxx = {exports: {}}; 
export {xxx as __module};

// rollup rewrite
var xxx = {exports: {}}; 
(function(module, exports) {
...
})(xxx, xxx.exports);
```

I try to modify the [commonjs/src/index.js#L193](https://github.com/rollup/plugins/blob/5fe760bd931c334fc28d199497dfdb76d888ef67/packages/commonjs/src/index.js#L193) code as follows:

```
code = `var ${name} = {exports: {}}; export {${name} as __module}`;
// to modify
code = `var exports = {}; var ${name} = {exports}; export {${name} as __module, exports}`;
```

then it can work.

@lukastaegert

**Comment by BwayCer** [comment]
Sorry, I must blame myself.
Actually it can't work, the plugin rewrites `module.exports = ...`.
Maybe the rollup method is right.

**Comment by shellscape** [comment]
Sorry, we don't offer support here as mentioned in the issue template. If this is a bug report please provide a valid reproduction.
