### ISSUE TITLE
The 【namedExports】 attribute is not supported

### ISSUE THREAD

**Issue by alanwhy** [rollup/plugins#913]
- Rollup Plugin Name: `@rollup/plugin-node-resolve`、`@rollup/plugin-commonjs`
- Rollup Plugin Version: lastest

Documentation Is:

- [ ] Confusing

### Please Explain in Detail...

Hello, big guys. I encountered this problem when packaging my project, as shown in the figure.
![image](https://user-images.githubusercontent.com/34852024/123504874-6a2d8400-d68e-11eb-968d-665b43b3bc2d.png)

### Your Proposal for Changes

I checked the solution and found that the latest plug-in no longer has this field【namedExports】
[error-name-is-not-exported-by-module](https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module)

And even if I fall back to the old dependency version【rollup-plugin-commonjs】【rollup-plugin-node-resolve】，And to configure this field【namedExports】It's no use

I built a simple demo here to reproduce this problem  [https://github.com/alanwhy/rollup-loaders-cjs](https://github.com/alanwhy/rollup-loaders-cjs)

Although it does not affect my build process, but I still like to solve this problem.

I can only expose methods by `export default`, but not with `export`.As shown
![image](https://user-images.githubusercontent.com/34852024/123505054-7cf48880-d68f-11eb-9775-e74a395d75a3.png)
![image](https://user-images.githubusercontent.com/34852024/123505091-aad9cd00-d68f-11eb-9092-f6f541076ee4.png)
There will be no problem if you package it in the way shown in the figure, but I can’t modify the third-party dependencies

In addition, my configuration【browser】must be 【true】,When it is false, there is no problem with packaging.

Finally, I hope to get your help, thank you!!!

**Comment by shellscape** [comment]
This was an intentional change. Please see the changelog for more details https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#breaking-changes-5, and view the associated Pull Request with the changes for more information on why, and any possible changes needed to your code to accommodate the newer version.

**Comment by alanwhy** [comment]
> 这是有意的改变。有关更多详细信息，请参阅变更日志[https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#break-changes-5](https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#breaking-changes-5)，并查看相关的拉取请求与更改以获取更多信息为什么，以及为适应较新版本而需要对代码进行的任何可能更改。

Hello, shellscape, I read the link you sent me, and I understand that the problem may be caused by my low dependency version. I tried to upgrade the dependency to the latest version, but the problem still exists...

I have uploaded the code to https://github.com/alanwhy/rollup-loaders-cjs. Looking forward to your reply again!
