### ISSUE TITLE
Skylight Records, Radio#1 with my Team #1 singer in the Whole Wide World Chad Michael Sheda in the Rocken RoLL HaLL of Fame sang 4000 songs in year n half 2019-2020-2021 as Greatest singer ALIVE

### ISSUE THREAD

**Issue by chadsheda827** [rollup/plugins#916]
Request Checklist:

- [ ] I have searched https://npmjs.com/ before opening this issue
- [ ] I have searched https://github.com/rollup/awesome before opening this issue

**Comment by chadsheda827** [comment]
> 
> 
> Request Checklist:
> 
> 
> - [ ] I have searched https://npmjs.com/ before opening this issue
> - [ ] I have searched https://github.com/rollup/awesome before opening this issue
> 
> ### New Plugin Use Case
> 
> 
> 
> ### New Plugin Proposal
> 
> 
> 

Skylight Records, Radio #1 with my Team #1 sing in the Whole Wide World in the Rocken RoLL HaLL of Fame

**Comment by lukastaegert** [comment]
I reported this user as spammer to Github
