### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by CWSites** [rollup/plugins#917]
- Rollup Plugin Name: `@rollup/plugin-url`
- Rollup Plugin Version: `5.0.1` and `6.0.0`
- Rollup Version: 
- Operating System (or Browser): Mac OS X, Chrome
- Node Version: `15.11.0`
- Link to reproduction _(⚠️ read below)_: https://replit.com/join/oleoxyoaec-cwsites

### Expected Behavior

There should be no warnings during install

### Actual Behavior

I receive a warning during install

```sh
@rollup/plugin-url@6.0.0" has unmet peer dependency "rollup@^1.20.0||^2.0.0
```

### Additional Information

Able to reproduce anywhere by running `yarn add @rollup/plugin-url`

**Comment by shellscape** [comment]
This looks like you're not familiar with how node package management works. I'd recommend reading up on that:

- https://nodejs.org/es/blog/npm/peer-dependencies/
- https://classic.yarnpkg.com/en/docs/dependency-types/#toc-peerdependencies

This isn't a bug or misconfiguration in the rollup plugin you're attempting to install - you don't have a valid version of rollup installed (there isn't _any_ version installed) and so the warning is displayed to alert you to that fact. I don't even see the plugin being used in your reproduction (and worth mentioning that the facetious reproduction name is not appreciated). Please attempt to understand the base technology you're using better before raising bugs in projects.

**Comment by CWSites** [comment]
> (and worth mentioning that the facetious reproduction name is not appreciated

Sorry for the aggression in naming, I was frustrated with having to create another issue and reproduce when I felt like I had already explained my issue thoroughly. Either way I shouldn't have gone about it that way.
