### ISSUE TITLE
TS declaration file for image plugin

### ISSUE THREAD

**Issue by wdfinch** [rollup/plugins#918]
- Rollup Plugin Name: @rollup/plugin-image
- Rollup Plugin Version: 2.0.6

### Feature Use Case
Hi all, I was wondering if there was any way we could add a typescript declaration file to the image plugin. I do my rollup config in typescript which means I need to create my own declaration file in order to import the package. Would be great if this was included with the package. 

### Feature Proposal
Add a TS declaration file.

**Comment by shellscape** [comment]
We'd be happy to review a Pull Request to add that.

**Comment by NotWoods** [comment]
Will be fixed by #898

**Comment by shellscape** [comment]
Closed by #898
