### ISSUE TITLE
[node-resolve] package.json "browser" paths are incorrectly resolved for sub-paths

### ISSUE THREAD

**Issue by eemeli** [rollup/plugins#919]
- Rollup Plugin Name: @rollup/node-resolve
- Rollup Plugin Version: 13.0.0
- Rollup Version: 2.52.6
- Operating System (or Browser): MacOS
- Node Version: 15.11.0
- Link to reproduction: https://replit.com/@eemeli1/rollup-plugin-repro

### Expected Behavior

Build should succeed.

### Actual Behavior

Build fails with a circular dependency:
```
node_modules/yaml/browser/index.js -> node_modules/yaml/browser/index.js
```

This is due to the browser import path for `"./dist/index.js"` being incorrectly applied when used in the `browser/` sub-path of the `yaml` package.

### Additional Information

Originally reported by @jdesrosiers as eemeli/yaml#291, see there for some initial debugging.

I'll work on a PR potentially fixing this.

**Comment by guybedford** [comment]
Fixed in https://github.com/rollup/plugins/pull/920.
