### ISSUE TITLE
Documentation on rollupjs says otherwise for Babel & Commonjs plugins

### ISSUE THREAD

**Issue by shotamakino** [rollup/plugins#931]
- Rollup Plugin Name: babel & commonjs
- Rollup Plugin Version: 5.3.0 & 19.0.0 respectively

Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
[link](https://rollupjs.org/guide/en/#rollupplugin-commonjs) says that babel plugin needs to come before commonjs plugin, however on the github README for babel-plugin, [link](https://rollupjs.org/guide/en/#rollupplugin-commonjs) it says otherwise. So which is it?

**Comment by shellscape** [comment]
The plugin's documentation here should be taken as a source of truth, _in most situations_. It's possible that the docs on the main rollup site are out of date with recently updates to the babel plugin.
