### ISSUE TITLE
typescript: declaration files emitted to wrong path when output is file

### ISSUE THREAD

**Issue by MingweiSamuel** [rollup/plugins#934]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.2.1
- Rollup Version: 2.53.1
- Operating System: Windows 10
- Node Version: v15.5.1
- Link to reproduction _(⚠️ read below)_: https://github.com/MingweiSamuel/rpts

### Expected Behavior
When specifying a file output, `@rollup/plugin-typescript` should output the declaration files in `lib/index.d.ts`.

### Actual Behavior
`@rollup/plugin-typescript` ouputs the declaration file to `lib/lib/index.d.ts`

The outer `lib` is from rollup's output filename. The inner `lib` is from `tsconfig.json`'s `outDir`.

### Additional Information

Relevant code is here https://github.com/rollup/plugins/blob/6867290ec8b983950ce20e58a34eaaee5e371517/packages/typescript/src/index.ts#L137-L139 from #687

Correct behavior can be obtained by specifying the output as a `dir: './lib'` and ensure that `tsconfig.json`'s `"outDir": "./lib"` matches.

Trying to set `declarationDir: './'` as a hack (in either tsconfig or rollup config) doesn't work since typescript will then exclude the `./` folder and fail to find any source ts files. Trying to set an absolute path `declarationDir: require('path').resolve('lib')` does not do anything different.  
EDIT: seems someone got this to work: https://github.com/microsoft/bistring/commit/7e57116c812ae2c01f383c234f3b447f733b5d0c

**Comment by MingweiSamuel** [comment]
Replacing
https://github.com/rollup/plugins/blob/6867290ec8b983950ce20e58a34eaaee5e371517/packages/typescript/src/index.ts#L137-L139
with
```js
if (!baseDir) {
    baseDir = parsedOptions.options.declarationDir || parsedOptions.options.outDir;
}
if (!baseDir && tsconfig) {
    baseDir = tsconfig.substring(0, tsconfig.lastIndexOf('/'));
}
```
Fixes the issue.  I'm not sure what exactly the _intented_ behavior of rollup is, but this certainly seems more sensible than the current.

**Comment by MingweiSamuel** [comment]
I've solved my original issue using the rollup-plugin-rename to avoid using `file` output
```js
import typescript from '@rollup/plugin-typescript';
import resolve from '@rollup/plugin-node-resolve';
import rename from 'rollup-plugin-rename';

export default {
    input: 'src/board-utils.ts',
    output: [
        {
            dir: 'lib',
            sourcemap: true,
            format: 'es',
            plugins: [
                rename({
                    map: name => name.replace('.js', '.mjs'),
                }),
            ],
        },
        {
            dir: 'lib',
            sourcemap: true,
            format: 'cjs',
        }
    ],
    plugins: [
        typescript({ tsconfig: './tsconfig.json' }),
        resolve(),
    ],
};
```

**Comment by shellscape** [comment]
Given the workaround linked to, I think this can be chalked up to a documentation issue for this specific use case.

**Comment by MingweiSamuel** [comment]
Thanks @shellscape
