### ISSUE TITLE
Sucrase plugin dependencies out of date

### ISSUE THREAD

**Issue by curran** [rollup/plugins#936]
Greetings, I noticed that the Sucrase plugin dependencies are a bit stale.

**Comment by shellscape** [comment]
Greetings. In this repository we require using one of our issue templates. The information we request may seem unnecessary to you, but it's useful to us. Please feel free to submit a PR to the sucrase plugin.

**Comment by curran** [comment]
Thanks! Created a new issue: https://github.com/rollup/plugins/issues/937
