### ISSUE TITLE
CommonJS plugin doesn't recognize the `__esModule` field in `module.exports = { __esModule: true, ... }`

### ISSUE THREAD

**Issue by sodatea** [rollup/plugins#939]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 19.0.0
- Rollup Version: 2.53.1
- Operating System (or Browser): macOS 11.4
- Node Version: 16.4.2
- Link to reproduction _(⚠️ read below)_: https://replit.com/@sodatea/rollup-esm-import-compiled-cjs

### Expected Behavior

Both imports from `symbol` and `symbol2` return the `.default` field because they are both compiled from an ES module and contain the `__esModule` field.

### Actual Behavior

The CommonJS plugin only recognizes the one with `exports.__esModule`. The one with `module.exports = { __esModule: true, default: ... }` is treated as a normal CJS module.

### Additional Information

The `module.exports = { __esModule: true, default: ... }` pattern is found in `babel-runtime` v6 https://unpkg.com/browse/babel-runtime@6.26.0/core-js/symbol.js

It is used in some old codebases. So this issue causes incompatibility with them.

See also https://github.com/vitejs/vite/issues/4090

**Comment by guybedford** [comment]
Fixed in https://github.com/rollup/plugins/pull/942.
