### ISSUE TITLE
plugin-replace v3.0.0 changelog empty

### ISSUE THREAD

**Issue by peterpeterparker** [rollup/plugins#945]
Documentation Is:

- [X] Missing

### Please Explain in Detail...

The [CHANGELOG](https://github.com/rollup/plugins/blob/master/packages/replace/CHANGELOG.md) of `plugin-replace` contains no entries for the v3.0.0 list of breaking changes.

**Comment by shellscape** [comment]
Casualty of a new auto release process we were rolling out. Follow the commit log until that's remedied.

**Comment by jnordberg** [comment]
Why was this closed? Changelog has not been fixed.

If you like me came here to find out what the breaking change is, it can be found here: https://github.com/rollup/plugins/pull/903
