### ISSUE TITLE
can't do `export ` in ts file through @rollup/typescript plugin

### ISSUE THREAD

**Issue by HomyeeKing** [rollup/plugins#946]
- Rollup Plugin Name:   @rollup/plugin-typescript
- Rollup Plugin Version:
- Rollup Version:
- Operating System (or Browser): chrome
- Node Version:
- Link to reproduction _(⚠️ read below)_:

if I `export` something in .ts file, the bundle will not right,

### Expected Behavior

bundle normally
### Actual Behavior
bundle wrong

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
