### ISSUE TITLE
[@rollup/plugin-typescript] missing bundle while bundle the .ts file

### ISSUE THREAD

**Issue by HomyeeKing** [rollup/plugins#947]
- Rollup Plugin Name: 
- Rollup Plugin Version:
- Rollup Version:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_: https://replit.com/@HomyeeKing/rollup-plugin-repro#output/test.js

### Actual Behavior

here is the `rollup.config.js`

```js
import typescript from '@rollup/plugin-typescript'
{
input:{
// ... 

a:"a.ts"
},
plugin:[
typescript({

}),
output:'cjs'
]

}

```

```ts
// a.ts

import ....

// .... 

export const a = 'a'

//. ...


```

```ts
// b.ts

import  {a} from 'a.ts'
```

```js
// bundle a.js

// !ONLY and dep requirements
exports.a = a
//  don't have other codes 

// so the CI always fail


```

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed portions of the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request template sections. They're in the template because they're useful to the maintainers of this project.
