### ISSUE TITLE
React CommonJS

### ISSUE THREAD

**Issue by pmorim** [rollup/plugins#949]
- Rollup Plugin Name:  [commonjs](https://github.com/rollup/plugins/tree/master/packages/commonjs)
- Rollup Plugin Version: 11.1.0
- Rollup Version: 1.32.1
- Operating System (or Browser): Windows WSL (Brave Browser)
- Node Version: 10.19.0
- Link to reproduction _(⚠️ read below)_: https://github.com/pmorim/react-draw-circuits/tree/basic-logic

### Expected Behavior
It's expected to normally build the library.

### Actual Behavior
I get the error (`Error: 'useRef' is not exported by node_modules/react/index.js`) anyway.

### Additional Information
I'm trying to build a React library with Storybook. When I just do `npm run storybook` it works fine. But when I try to host the Storybook on Netlify I get that error.

Here is my `rollup.config.js`:
```js
import commonjs from '@rollup/plugin-commonjs';
import react from 'react';
import reactDom from 'react-dom';

export default {
  input: 'src/index.js',
  output: {
    dir: 'storybook-static',
    format: 'cjs',
  },
  plugins: [
    commonjs({
      include: 'node_modules/**',
      namedExports: {
        react: Object.keys(react),
        'react-dom': Object.keys(reactDom),
      },
    }),
  ],
};
```

**Comment by pmorim** [comment]
I fixed the issue, it wasn't a problem with Rollup but with my `package.json` file.

**Comment by JaffParker** [comment]
@pmorim what was the issue in your package.json?
