### ISSUE TITLE
entry-point [!] Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Rick-Rick-Rick** [rollup/plugins#95]
- Rollup Plugin Name: @rollup/plugin-multi-entry
- Rollup Plugin Version: 3.0.0
- Rollup Version: 1.27.10
- Operating System (or Browser): windows
- Node Version: 10.15.3

![image](https://user-images.githubusercontent.com/9975520/71165699-4a90f080-228c-11ea-9708-24d00e09e2ec.png)
![image](https://user-images.githubusercontent.com/9975520/71165815-77dd9e80-228c-11ea-9929-e232cd2f33f0.png)

![image](https://user-images.githubusercontent.com/9975520/71165766-67c5bf00-228c-11ea-9506-6c809d78827e.png)

is anyone who could tell me  how to fix it ?

**Comment by shellscape** [comment]
Hey thanks for opening an issue. Unfortunately this isn't the right place to ask for support. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).

**Comment by xinaesthete** [comment]
I believe this is indeed a bug.  Taking a working configuration and invoking this plugin causes the above error to appear, even before any configuration that would cause it to become effective is introduced.

My config:
```
import ts from '@rollup/plugin-typescript';
import resolve from '@rollup/plugin-node-resolve';
import multi from '@rollup/plugin-multi-entry';

export default {
    input: ['TS/mod/test.ts'],
    //input: 'TS/mod/**/*.ts', //if the plugin was working, I'd use something like this.
    plugins: [
        //multi(), //uncommenting this line will cause an error
        ts(), resolve()
    ],
    output: {
        dir: 'dist',
        //entryFileNames: '[name]--r.js',
        format: 'esm',
        sourcemap: true
    }
}
```

I don't think interactions with other plugins are to blame, but I haven't tried a more minimalistic configuration as yet.  I am on a slightly more recent rollup version than the OP (1.29.0).

**Comment by shellscape** [comment]
@xinaesthete if you can put together a minimal reproduction, we'll reopen this as a bug to triage. Good repros are: 

>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/, or

**Comment by xinaesthete** [comment]
@shellscape  ok, but literally all that seems required to repro is to install and invoke the plugin...

**Comment by xinaesthete** [comment]
hmm, first attempt at minimal repro in repl.it did not repro, will keep you posted.

**Comment by shellscape** [comment]
That's why we ask for them :smile: 

I would say next step is to create a new repo to try and reproduce the problem. If that doesn't show a reproduction, then we can try taking a look at a repo that _does_. A lot of the time these types of things boil down to a specific environment issue. Sometimes we can spot what it is, other times it takes a ground-up rebuild of a repo to identify the culprit (typically a last resort).

**Comment by xinaesthete** [comment]
It appears to be a Windows issue.  I've now tried with my mac this morning and the same project is ok there.  I'll set up a quick minimal repo and try it in a couple of different environments now.

**Comment by xinaesthete** [comment]
I only just noticed, it does behave differently on macos, but still doesn't work properly.  On mac, no error is reported, but a file is written with a name like `'_rollup:plugin-multi-entry:entry-point.js'`

**Comment by xinaesthete** [comment]
Not sure why this is still "closed".

**Comment by noBlubb** [comment]
I ran into the same issue today, maybe this works as repro for you:

We build a few small apps and try to export them as single file components. On windows this fails with the identical expection as given above while the pipeline running in a node container prints the expected output, but creates only a _rollup:plugin-multi-entry:entry-point.js file. Is this related to the integration with other plugins?

```js
import svelte from 'rollup-plugin-svelte';
import multi from '@rollup/plugin-multi-entry';
import resolve from '@rollup/plugin-node-resolve';
import { terser } from 'rollup-plugin-terser';

const production = !process.env.ROLLUP_WATCH;

export default {
    input: ['resources/fms.js', 'resources/server-browser.js'],
    output: {
        dir: 'static',
    },
    plugins: [
        multi(),
        svelte({
            css: false,
            dev: !production,
        }),
        resolve({
            browser: true,
            dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
        }),
        production && terser()
    ]
}
```
Repository for repro, run with `yarn run rollup -c`: https://gitlab.com/emergencyx/emergencyx.gitlab.io/tree/d7c9f78d8700da7a6a04999472f116491ae13c67
Pipeline run that generated the entry-point.js file: https://gitlab.com/emergencyx/emergencyx.gitlab.io/-/jobs/417936316

**Comment by shellscape** [comment]
> Not sure why this is still "closed".

We definitely appreciate the interest you have in solving this problem on your systems. However, we really , really need everyone to abide by the requirements for reporting an issue. In the issue template we include a link to instructions for creating a _minimal reproduction_. For convenience, that link is https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff#how-to-create-a-minimal-reproduction. We all volunteer our time to keep the entire plugin ecosystem up and running for Rollup - something that was very difficult in years prior. We've made a lot of progress and are more efficient, but we simply don't have the time necessary to parse or triage repos with a lot of moving parts.

If you can't put together a minimal reproduction and can't triage the problem on your end, then submitting a PR with a failing test is an option to at least highlight the problem. That will at least give the maintainers a focused path for solving. And of course we always welcome PRs with fixes.

**Comment by noBlubb** [comment]
I was able to boil down my case to this repro - please tell me if I can improve this in any way to make debugging easier for you: https://repl.it/repls/StaidRegularBlogware

**Comment by noBlubb** [comment]
After reviewing https://github.com/rollup/rollup/issues/1435 I realized that I may be misusing the multi-entry plugin, as I want to export multiple files in the end: 
```js
import svelte from 'rollup-plugin-svelte';
import resolve from '@rollup/plugin-node-resolve';
import { terser } from 'rollup-plugin-terser';

const production = !process.env.ROLLUP_WATCH;

const COMMON = {
    output: {
        dir: 'static'
    },
    plugins: [
        svelte({
            css: false,
            dev: !production,
        }),
        resolve({
            browser: true,
            dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
        }),
        production && terser()
    ]
};

const FMS = {
    input: 'resources/fms.js'
};

const BROWSER = {
    input: 'resources/server-browser.js'
};

export default [
    Object.assign({}, COMMON, FMS),
    Object.assign({}, COMMON, BROWSER)
];
```

**Comment by unlight** [comment]
Encountered with same issue. To fix this you need explicitly set `output.file` (e.g. `dist/bundle.spec.js`)
This plugin has entry `const entry = '\0rollup:plugin-multi-entry:entry-point';` which contains incorrect colon and \0 symbols for file names in windows.

And looks like rollup tries to write to `dist\\0rollup:plugin-multi-entry:entry-point.js`

**Comment by shellscape** [comment]
Hey folks, this one has gone quite stale. We're going to close for housekeeping but we'd happily review any PRs that pop up to resolve this issue.
