### ISSUE TITLE
@rollup/plugin-replace Changelog not accurate enough

### ISSUE THREAD

**Issue by akauppi** [rollup/plugins#950]
- Rollup Plugin Name: `plugin-replace`
- Rollup Plugin Version: 3.0.0

Documentation Is:

- [x] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The Changelog [here](https://github.com/rollup/plugins/blob/master/packages/replace/CHANGELOG.md) is not enough, to judge whether I should update; what the breaking changes are.

>![image](https://user-images.githubusercontent.com/1297734/126161731-0d624d58-6b41-44de-9a3d-81d7c780fd46.png)

### Your Proposal for Changes

@shellscape could add information to that file?

**Comment by shellscape** [comment]
Please search issues. This was already reported. In the meantime, use the release tag to inspect the commits for a version.
