### ISSUE TITLE
@rollup/plugin-replace 3.0.0 changelog

### ISSUE THREAD

**Issue by jnordberg** [rollup/plugins#951]
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: 3.0.0

Documentation Is:

- [x] Missing
- [x] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Semver major release only has breaking change listed as `fix`.

https://github.com/rollup/plugins/commit/bc15173dcb23d01e5fa2cab3dfa15c9bd262f42d#diff-a244598ce33c10650f0bc9a5f1b9a58dc1293b17addb92b21b422a81aa8cf341R9

### Your Proposal for Changes

Document what the made the 3.0.0 release incompatible with the 2.x.x release

**Comment by shellscape** [comment]
Please search issues before opening new ones.This has already been reported.

**Comment by jnordberg** [comment]
I did but didn't find anything, please link the original when closing as duplicate.

**Comment by shellscape** [comment]
There's no need. The issue closed right before yours was the same. I'd suggest beefing up your searching skills.
