### ISSUE TITLE
ERR_CHILD_PROCESS_STDIO_MAXBUFFER occurred on version > 2.1.0 

### ISSUE THREAD

**Issue by imstand** [rollup/plugins#952]
- Rollup Plugin Name: plugin-typescript
- Rollup Plugin Version:3.1
- Rollup Version:1.2.0
- Operating System (or Browser):OSX
- Node Version:12
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
rollup success

### Actual Behavior
Message:
    stderr maxBuffer length exceeded
Details:
    code: ERR_CHILD_PROCESS_STDIO_MAXBUFFER
    cmd: node node_modules/.bin/rollup -c

### Additional Information
The bug occurred when upgrade rollup and plugins, the old version working well.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.
