### ISSUE TITLE
Node Resolve 13.0.2 Release Notes Description Lacking

### ISSUE THREAD

**Issue by aedryan** [rollup/plugins#953]
- Rollup Plugin Name: `node-resolve`
- Rollup Plugin Version: 13.0.2

Documentation Is:

- [x] Missing
- [x] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
13.0.2 claims to just be a `"fix"`: https://github.com/rollup/plugins/blob/node-resolve-v13.0.2/packages/node-resolve/CHANGELOG.md#v1302

I believe this is the PR: https://github.com/rollup/plugins/pull/927

### Your Proposal for Changes
The `access` package seems to be no longer used but is still included for some reason and is replaced with an asynchronous call to `stat`.  I'm unsure of what issues existed with `access` except that it's permission focused where is stat is more general.  

The bits that seem to fulfill the goal of the PR are here though and maybe unrelated to the stat/access swap: https://github.com/rollup/plugins/pull/927/files#diff-feca43bd4cf6b266d3fdd0ac000bac597028a1c87b78ea6f41fe5c5006d2c191R31-R123

This commit seems to best illustrate the intent of the PR: https://github.com/rollup/plugins/pull/927/commits/0eed03774f7d7c42ffd6e49afa370d5bd0182027

I would update the change log from `"fix"` to `"fix: handle 'package.json' being in path"`

**Comment by shellscape** [comment]
we're aware. PLEASE search issues first. look at the commit log for now.
