### ISSUE TITLE
`@rollup/plugin-replace` breaks import statement

### ISSUE THREAD

**Issue by loynoir** [rollup/plugins#964]
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: "^3.0.0"
- Rollup Version: "^2.55.1"
- Operating System (or Browser): linux
- Node Version: v14.17.4
- Link to reproduction _(⚠️ read below)_: https://gist.github.com/loynoir/250ed27119fb429c0b9695b9145c0780

### Brief
`@rollup/plugin-replace` breaks import statement 
```js
import { isNode, isBrowser, isWorker } from "browser-or-node"
if (isNode) {}
```
This scenario should add to `preventAssignment`.

### Expected Behavior
```js
function main() {
    {
        console.log('Node');
    }
}

export { main as default };
```

### Actual Behavior
```js
[!] Error: Unexpected keyword 'true'
index.js (1:9)
1: import { isNode, isBrowser, isWorker } from "browser-or-node"
```

**Comment by mtone** [comment]
By evaluating isNode in your rollup.config.js you are hard-coding text replacements at build-time:

```js
plugins: [
        replace({
            preventAssignment: true,
            values: { isNode: true, isBrowser: false, isWorker: false }
        })
    ]
```

This probably results in this invalid code: `import { true, false, false} from "browser-or-node"`

If you want to evaluate isNode at run-time, use @rollup/plugin-node-resolve - see https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency

I don't see a problem with Rollup itself but a question better suited for [StackOverflow](https://stackoverflow.com/questions/tagged/rollupjs).

**Comment by loynoir** [comment]
Oh, I forgot to close this issue. After that, I checked the source code.
Both replacement and `preventAssignment` are done by pure text replacement, but not replace read value at AST level and exclude write value.

Solution is provide a pre-evaluated module for each situation
```
    rollupVirtual({
      "@loynoir/browser-or-node": `export const isNode = false ...`
   })
```

**Comment by loynoir** [comment]
Closed. Using `rollupVirtual` to fake at ast level instead of `rollupReplace` at text level.
