### ISSUE TITLE
plugin-typescript supports `tsconfigDefaults` and `tsconfigOverride`

### ISSUE THREAD

**Issue by aladdin-add** [rollup/plugins#965]
- Rollup Plugin Name:  @rollup/plugin-typescript
- Rollup Plugin Version: n/w

### Feature Use Case
I am trying to move from `rollup-plugin-typescript2` to `@rollup/plugin-typescript` in tsdx (https://github.com/weiran-zsd/tsdx/issues/2).  it used the (`tsconfigDefaults` and `tsconfigOverride`](https://github.com/ezolenko/rollup-plugin-typescript2#plugin-options), while seems the official plugin does not support it.

### Feature Proposal
support the two options as rollup-plugin-typescript2. :)

**Comment by ericmorand** [comment]
Why are you moving from a plugin that provides what you need to a plugin that doesn't?

**Comment by shellscape** [comment]
I'd recommend learning how to extend `tsconfig.json` based on need and for different build conditions. That will accomplish what those options accomplish for the other plugin. Given that this is built into TypeScript (https://www.typescriptlang.org/tsconfig#extends) we're going to decline adding these two options to the plugin.

**Comment by shellscape** [comment]
We don't compare plugins here with others from the ecosystem. Plugins here may have different philosophies to those elsewhere in the greater Rollup community, and that's what makes our community solid. We're all on the same team, and comments that purport to pit one project against another, or compare negatively, are not welcome here. 

As always, we encourage and welcome forks of the projects in this repo to accomplish things beyond what the maintainers here accept into the plugins in this repo. We're even happy to promote them by means of https://github.com/rollup/awesome.
