### ISSUE TITLE
Annoying navigation to individual plugins

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#966]
- Rollup Plugin Name: all
- Rollup Plugin Version: all

Documentation Is:

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

If I search Google for a Rollup plugin, I'm always taken to an old version like https://github.com/rollup/rollup-plugin-commonjs. The link in the righthand side bar always takes me to https://github.com/rollup/plugins, which is frustrating because it always takes me two more clicks to get where I'm trying to go.

### Your Proposal for Changes

Update the links on the old plugins to point directly to the new plugin locations. E.g. https://github.com/rollup/plugins/tree/master/packages/commonjs

**Comment by shellscape** [comment]
> The link in the righthand side bar

The what where?

**Comment by benmccann** [comment]
Here's the section I'm talking about:

![Screenshot from 2021-08-04 08-05-15](https://user-images.githubusercontent.com/322311/128205284-27925db8-5b9e-434e-9c06-4f6492d8c2d6.png)

**Comment by shellscape** [comment]
Ah gotcha. Want access to those repos to update that?

**Comment by benmccann** [comment]
Sure, I'd be happy to do it

**Comment by shellscape** [comment]
OK cool you should have access. Let me know if there are any you don't have permissions on.

**Comment by benmccann** [comment]
Done. Thanks!

It was kind of a pain because I had to unarchive and then rearchive them all. Hope that didn't kill your notifications

Feel free to reset my permissions now
