### ISSUE TITLE
eslint fails with "Unable to resolve path to module '@rollup/plugin-json'"

### ISSUE THREAD

**Issue by ddinchev** [rollup/plugins#97]
- Rollup Plugin Name: rollup-json
- Rollup Plugin Version: 4.0.0
- Rollup Version: 1.27.13
- Operating System (or Browser): macOS 10.13
- Node Version: v12.13.1

### How Do We Reproduce?

In my `rollup.config.js` I changed `import json from 'rollup-plugin-json'` to `import json from '@rollup/plugin-json';` and of course, installed `@rollup/plugin-json`.

### Expected Behavior

No eslint errors

### Actual Behavior

  7:18  error  Unable to resolve path to module '@rollup/plugin-json'  import/no-unresolved
✖ 1 problem (1 error, 0 warnings)

Suppressing the error seems to do the trick so it is actually correctly resolved.

**Comment by shellscape** [comment]
Thanks for opening an issue. I can't reproduce this locally, so we're going to have to request that you follow the issue template a d provide a minimal reproduction.
