### ISSUE TITLE
[@rollup/plugin-html] Async imported chunk should have an option be excluded from the final html src tags.

### ISSUE THREAD

**Issue by amit-gshe** [rollup/plugins#976]
- Rollup Plugin Name: html
- Rollup Plugin Version: 0.2.3

### Expected Behavior / Situation
Async import module should have an option be excluded from the final html src tags.

### Actual Behavior / Situation
Async import modules are included in the final html and downloaded at the initial requests.

### Modification Proposal
```js
const getFiles = (bundle) => {
    // file.isDynamicEntry === false to filter out the dynamic entry
    const files = Object.values(bundle).filter((file) => (file.type === 'chunk' && file.isDynamicEntry === false) ||
        (typeof file.type === 'string' ? file.type === 'asset' : file.isAsset));
    const result = {};
    for (const file of files) {
        const { fileName } = file;
        const extension = path.extname(fileName).substring(1);
        result[extension] = (result[extension] || []).concat(file);
    }
    return result;
};
```

**Comment by shellscape** [comment]
Thanks for the suggestion. We don't assume how users will leverage the plugin, which is why the template option is available and powerful. Please use that to your needs.
