### ISSUE TITLE
typescript plugin forces a single tslib version causing a mismatch

### ISSUE THREAD

**Issue by danielgindi** [rollup/plugins#979]
- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: 8.2.5
- Rollup Version: 2.56.2
- Operating System (or Browser): macOS
- Node Version: 16.5.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@danielcgindi/rollup-plugin-repro-3

### Reproduction
It's hard to reproduce intentionally, as npm will choose whatever version it wants to be in the root `node_modules`, sometimes v1 and sometimes v2. Probably depending on the order of packages in the package tree.

### Expected Behavior
Each module should use its own `tslib` version, or at least disallow using an older version than specified in `package.json`.

### Actual Behavior
All modules are forced to be compiled with a single `tslib` version from the root `node_modules`, causing missing exports.

### Additional Information
It's this damn line here: https://github.com/rollup/plugins/blob/master/packages/typescript/src/index.ts#L93

### Workaround
Add `tslib` dependency directly to your project, with the latest version. This will be the root `tslib` and will *probably* be compatible with v1, but that's not guaranteed.

**Comment by alshdavid** [comment]
On a brand new rollup + typescript project I am getting:
```
[!] (plugin typescript) Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
```

**Comment by danny007in** [comment]
also https://github.com/ColorlibHQ/AdminLTE/runs/4355451248?check_suite_focus=true
