### ISSUE TITLE
TypeScript plugin won't exit

### ISSUE THREAD

**Issue by xeptore** [rollup/plugins#993]
- Rollup Plugin Name: typescript
- Rollup Plugin Version:  ^8.2.5
- Rollup Version: ^2.56.3
- Operating System (or Browser): Linux  5.13.12
- Node Version: v16.8.0
- Link to reproduction _(⚠️ read below)_: https://github.com/xeptore/rollup-plugin-typescript-bug (run build script)

### Expected Behavior

Exit after successful or failed build.

### Actual Behavior

Does not exit after build, and waits for ever.

### Additional Information

It seems after build a callback or a file watcher still remains in the Node event loop which causes it waits for nothing. I tried debugging using <https://www.npmjs.com/package/wtfnode>, and <https://github.com/mafintosh/why-is-node-running>, and as the result, there are some file watchers watching for file changes from typescript package. After a brief look into the code, my guess is that the [createWatchProgram](https://github.com/rollup/plugins/blob/e0761538ae8f230a5f46ccf2104ab06e29a6c9cb/packages/typescript/src/index.ts#L55-L69) creates those watchers, but [program?.close();](https://github.com/rollup/plugins/blob/e0761538ae8f230a5f46ccf2104ab06e29a6c9cb/packages/typescript/src/index.ts#L83) does not close the watchers (?).

My question is that when it is possible to [check whether the plugin is being run in watch mode or not](https://github.com/rollup/plugins/blob/e0761538ae8f230a5f46ccf2104ab06e29a6c9cb/packages/typescript/src/index.ts#L50), why even creating a _watch_ program in non-watch builds?

**Comment by shellscape** [comment]
Please search issues before opening a new one. This is an upstream TypeScript issue that's already been reported twice.
