### ISSUE TITLE
@rollup/plugin-typescript hangs indefinitely

### ISSUE THREAD

**Issue by kevmo314** [rollup/plugins#994]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.2.5
- Rollup Version: 2.56.3
- Operating System (or Browser): Windows
- Node Version: 14.17.1
- Link to reproduction _(⚠️ read below)_: https://github.com/kevmo314/rollup-demo

### Expected Behavior

Rollup exits successfully.

### Actual Behavior

Rollup hangs after building bundle.

### Additional Information

So I'm really not sure what's going on here... but... cloning the repro repo into an empty dir and then running `npm run build` hangs indefinitely. I tried this on WSL too, same thing...

```
PS E:\rollup-demo> npm install

added 13 packages, and audited 14 packages in 1s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS E:\rollup-demo> npm run build

> rollup-demo@1.0.0 build
> rollup -c


src/index.ts → lib/bundle.js...
(!) Generated an empty chunk
index
created lib/bundle.js in 557ms
```

Removing the `typescript()` plugin (and changing the file to not be ts) lets rollup finish successfully.

**Comment by kevmo314** [comment]
It seems that this is related to the version of the `typescript` plugin used. Downgrading to `4.2.4` "fixes" the issue.

**Comment by kevmo314** [comment]
Linking to `typescript` against the HEAD of https://github.com/microsoft/typescript also seems to fix the issue, so I suppose this might go away automatically after a while.

**Comment by shellscape** [comment]
Duplicate. This has been reported a few times now. Please search issues before opening new ones.
