### ISSUE TITLE
Typescript plugin causes rollup to never terminate

### ISSUE THREAD

**Issue by calebmchenry** [rollup/plugins#995]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 8.2.5
- Rollup Version: 2.56.3
- Operating System (or Browser): OSX 10.15.7
- Node Version: 14.17.1
- Link to reproduction _(⚠️ read below)_: https://github.com/calebmchenry/indefinite-rollup

### Expected Behavior
rollup to terminate after producing bundle

### Actual Behavior
rollup command never terminates

### Additional Information

When running rollup with the typescript plugin the bundle is produced but the command never exists. When the typescript plugin is removed and entry point is changed to a .js file then the command terminates appropriately.

Edit: Created a [REPL](https://replit.com/@calebmchenry/indefinite-rollup-with-typescript#.replit) in case that is easier for you

**Comment by shellscape** [comment]
OK. I just closed the same exact issue three hours ago (#994), and there are a number of other issues (#993
#991) that are duplicates of the original reported, which has a resolution - #983

### Please start searching issues before opening new issues.

**Comment by calebmchenry** [comment]
Appreciate it. Thanks for the quit response
